CODE = 'electronics'; ROOT = 'Electronics'; STORE_NAME = 'Voltline'; ATTRIBUTE_SET = 'Electronics'; WEIGHT = 1
ATTRIBUTE_COLUMNS = ['color', 'brand', 'connectivity', 'storage']
ATTRIBUTES = [
    dict(code='brand', label='Brand', input='select', scope='global', filterable=1, filterable_in_search=1, searchable=1, visible_on_front=1, comparable=1, used_in_product_listing=1, sets='Electronics', group='General', sort_order=50),
    dict(code='connectivity', label='Connectivity', input='multiselect', scope='global', filterable=1, visible_on_front=1, comparable=1, sets='Electronics', group='General', sort_order=60),
    dict(code='storage', label='Storage', input='select', scope='global', filterable=1, visible_on_front=1, comparable=1, is_configurable=1, sets='Electronics', group='General', sort_order=70),
]
OPTIONS = {'brand': ['Voltline', 'Kestrel Audio', 'Nimbus', 'Orbit Labs', 'Halide', 'Tessera'], 'connectivity': ['Bluetooth', 'Wi-Fi', 'USB-C', 'Thunderbolt', 'HDMI', 'Wired'], 'storage': ['128 GB', '256 GB', '512 GB', '1 TB', '2 TB']}
ROOT_DESCRIPTION = 'Audio, computing, cameras and smart home gear, tested by people who use it.'
META_DESCRIPTION = 'Voltline: headphones, laptops, cameras, smart home and accessories, with honest specs and a two-year warranty.'
PRODUCT_STYLE = 'Studio product photograph of a single electronic device on a plain white seamless background, soft even light, no reflections of people, no screen content, no text, no lettering, no logos, no watermark, centered with margin around it.'
SCENE_STYLE = 'Clean editorial technology photograph, dark oak and matte black surfaces, cool daylight, shallow depth of field, no screen content, no text, no lettering, no logos, no watermark.'
SCENES = {
    'hero-main': 'A minimalist desk with a slim laptop, over-ear headphones and a mechanical keyboard, a single window light, dark wood.',
    'hero-side': 'Close up of black wireless earbuds in an open charging case on a slate surface.',
    'editorial': 'A technician at a bench testing headphones with an audio analyser, seen from the side, warm lamp light.',
    'about': 'A small electronics workshop with shelves of labelled boxes, a soldering station and a window.',
}
CATEGORIES = [
    dict(path='audio', name='Audio', description='Headphones, earbuds and speakers with honest sound.', landing_title='Sound you can measure', landing_text='We publish the frequency response of every headphone we sell. If it is not flat, we say where it bends.', scene='Over-ear headphones resting on a walnut stand beside a small bookshelf speaker.'),
    dict(path='computing', name='Computing', description='Laptops, keyboards and displays for long days.', landing_title='Built for the long session', landing_text='Laptops with real keyboards, monitors that do not flicker, and keyboards that click the way you like.', scene='A slim laptop open on a desk next to a large monitor and a mechanical keyboard, cool light.'),
    dict(path='cameras', name='Cameras', description='Mirrorless bodies, lenses and the bits in between.', landing_title='Glass first', landing_text='Bodies come and go. Lenses stay. We stock the ones that earn their place in the bag.', scene='A mirrorless camera with a prime lens on a leather strap, laid on a wooden table with two extra lenses.'),
    dict(path='smart-home', name='Smart Home', description='Lights, plugs, speakers and cameras that work without an account.', landing_title='Local first', landing_text='Everything here works on your own network. No cloud account required, no subscription ever.', scene='A smart speaker and a smart bulb glowing warm on a bedside table.'),
    dict(path='wearables', name='Wearables', description='Watches and trackers that last a week on a charge.', landing_title='A week between charges', landing_text='We only list wearables that go seven days. Anything less is a phone on your wrist.', scene='A smart watch with a black strap on a slate surface beside a fitness band.'),
    dict(path='accessories', name='Accessories', description='Cables, chargers, stands and cases that outlast the device.', landing_title='The boring stuff, done right', landing_text='Braided cables, chargers that do not get hot, and stands that do not wobble.', scene='A tidy flat lay of a braided cable, a compact charger and a laptop stand on dark wood.'),
]
HERO = dict(badge='New in', title='Gear that earns its place', text='Tested, measured and returned when it fails. Everything here passed.')
FEATURES = [('shield-check', 'Two-year warranty', 'On everything, no small print'), ('truck', 'Next-day delivery', 'Order by 6 pm on weekdays'), ('arrow-back-up', '30-day returns', 'Even if you opened it'), ('headset', 'Real support', 'Engineers, not scripts')]
STORY = dict(title='We test before we sell', text1='Voltline started on a workbench. Every product still crosses one before it goes on the shelf: measured, torn down, used for a week.', text2='If something fails our tests, it is not listed. If it fails yours, send it back.')
PROMO = dict(badge='Refurbished', title='Certified refurbished', text='Returned units, fully tested and re-boxed, with the same two-year warranty at a lower price.', path='accessories', button='See the deals', list_title='Tested and ready')
TESTIMONIALS = [('The headphones came with a measurement chart. Nobody else does that.', 'Elena R.', 'Berlin'), ('Ordered a laptop at 5 pm, it was on my desk at 9 the next morning.', 'Marcus T.', 'Leeds'), ('Support fixed my camera issue in one call. An actual engineer.', 'Priya S.', 'Toronto')]
NEWSLETTER = dict(title='Bench notes', text='One email a month: what we tested, what passed, and what did not.')
ABOUT = dict(title='From a workbench', paragraphs=['Voltline began as a repair bench in a shared workshop. Customers asked what we would buy. We told them, then we started selling it.', 'Every product on the shelf is measured on our bench. Headphones get a frequency response. Chargers get a thermal test. Laptops get a week of real work.', 'The bench is still here. If a product fails our tests, it does not go on the shelf. If it fails yours, we take it back.'])
REVIEWS = [
    ('Does what the chart says', 'The measurements matched what I heard. Rare honesty.', 5),
    ('Solid, a bit pricey', 'Great build. You pay for the testing, and it shows.', 4),
    ('Fast delivery, no fuss', 'Arrived next day, double boxed. Works perfectly.', 5),
    ('Replaced under warranty', 'A port failed after a year. New unit in three days.', 5),
    ('Battery lasts all week', 'Charged on Sunday, still going Friday night.', 5),
    ('Firmware update fixed it', 'Dropouts at first. One update later, rock solid.', 4),
    ('Cable is too short', 'Great device, but the included cable is a metre. Buy a longer one.', 4),
    ('Clear mids', 'Vocals sit where they should. Bass is honest, not boosted.', 5),
    ('No app needed', 'Everything works with a button. My parents could use it.', 5),
    ('Runs warm', 'Works fine but gets warm under load. Give it some air.', 3),
    ('Quiet fan', 'I forgot it was on. That is the highest praise for a fan.', 5),
    ('Case is metal', 'Real aluminium, not painted plastic. Feels like it will last.', 5),
    ('Pairing was instant', 'Open the lid, tap once, done.', 5),
    ('Wish it had USB-C', 'Everything else is right. The port is from another decade.', 3),
    ('Great for calls', 'Colleagues stopped asking me to repeat myself.', 5),
    ('Speaker fills the room', 'Small box, big sound. Party volume without distortion.', 5),
    ('Manual is thin', 'Works well, but I had to search online for the settings.', 4),
    ('Lens is sharp corner to corner', 'Tested on a brick wall like a nerd. It passes.', 5),
    ('Returned, wrong size', 'My fault, the spec sheet was clear. Return was painless.', 4),
    ('Charges the laptop too', 'One cable for everything on the desk now.', 5),
    ('Slight hiss at idle', 'Only with sensitive earphones and at full gain. Fine otherwise.', 4),
    ('Bought two', 'One for the office, one for home. No regrets.', 5),
    ('Buttons feel cheap', 'Sound is great, the plastic buttons are not.', 3),
    ('Setup took five minutes', 'Plugged in, updated, done before the coffee was ready.', 5),
]
def P(sku, name, cats, price, desc, prompt, **kw):
    d = dict(sku=sku, name=name, categories=cats, price=price, description=desc, prompt=prompt); d.update(kw); return d
PRODUCTS = [
    P('E-HEADPHONE-ANC', 'Kestrel K2 noise-cancelling headphones', ['audio'], 299, 'Over-ear headphones with adaptive noise cancelling, forty hours of battery and a flat tuning.', 'a pair of {value} over-ear wireless headphones', axis='color', values=['Black', 'Silver', 'Green'], picture_per_value=True, attributes=dict(brand='Kestrel Audio', connectivity='Bluetooth|USB-C')),
    P('E-EARBUDS', 'Kestrel Buds', ['audio'], 149, 'True wireless earbuds with a six-hour charge and a case that adds three more.', 'a pair of {value} wireless earbuds in an open charging case', axis='color', values=['Black', 'White'], picture_per_value=True, attributes=dict(brand='Kestrel Audio', connectivity='Bluetooth|USB-C')),
    P('E-WIRED-IEM', 'Kestrel Studio in-ear monitors', ['audio'], 189, 'Wired in-ear monitors with a single dynamic driver and a detachable cable.', 'a pair of wired in-ear monitors with a braided cable, coiled on white', attributes=dict(brand='Kestrel Audio', connectivity='Wired', color='Black')),
    P('E-SPEAKER-BT', 'Nimbus Go speaker', ['audio'], 119, 'A pocket speaker with a real passive radiator, twelve hours of play and an IP67 rating.', 'a small {value} fabric-covered portable bluetooth speaker', axis='color', values=['Charcoal', 'Blue', 'Orange'], picture_per_value=True, attributes=dict(brand='Nimbus', connectivity='Bluetooth|USB-C')),
    P('E-BOOKSHELF', 'Nimbus Shelf active speakers', ['audio'], 449, 'A pair of powered bookshelf speakers with a built-in DAC and Bluetooth.', 'a pair of walnut veneer bookshelf speakers with black fabric grilles', attributes=dict(brand='Nimbus', connectivity='Bluetooth|Wired', color='Brown')),
    P('E-TURNTABLE', 'Nimbus Spin turntable', ['audio'], 329, 'A belt-drive turntable with a carbon tonearm and a built-in phono stage.', 'a modern black belt-drive turntable with a walnut plinth', attributes=dict(brand='Nimbus', connectivity='Wired|Bluetooth', color='Black')),
    P('E-DAC', 'Kestrel Pocket DAC', ['audio', 'accessories'], 79, 'A USB-C headphone amplifier the size of a lighter, with a balanced output.', 'a tiny aluminium USB-C headphone amplifier dongle', attributes=dict(brand='Kestrel Audio', connectivity='USB-C', color='Silver')),
    P('E-SOUNDBAR', 'Nimbus Bar soundbar', ['audio', 'smart-home'], 279, 'A compact soundbar with a wireless subwoofer and HDMI eARC.', 'a slim black soundbar with a small subwoofer beside it', attributes=dict(brand='Nimbus', connectivity='HDMI|Bluetooth|Wi-Fi', color='Black')),
    P('E-LAPTOP-14', 'Voltline Air 14 laptop', ['computing'], 1199, 'A fourteen-inch laptop with a matte display, eighteen hours of battery and a keyboard people write on.', 'a slim silver 14 inch laptop open at an angle with a dark blank screen', axis='storage', values=['256 GB', '512 GB', '1 TB'], attributes=dict(brand='Voltline', connectivity='Wi-Fi|USB-C|Thunderbolt', color='Silver')),
    P('E-LAPTOP-16', 'Voltline Pro 16 laptop', ['computing'], 2199, 'A sixteen-inch workstation with a 120 Hz display and quiet fans.', 'a dark grey 16 inch laptop open at an angle with a dark blank screen', axis='storage', values=['512 GB', '1 TB', '2 TB'], attributes=dict(brand='Voltline', connectivity='Wi-Fi|USB-C|Thunderbolt|HDMI', color='Charcoal')),
    P('E-MONITOR-27', 'Tessera 27 inch 4K monitor', ['computing'], 549, 'A 27-inch 4K IPS display with USB-C power delivery and a matte coating.', 'a 27 inch monitor with thin bezels and a dark blank screen on a metal stand', attributes=dict(brand='Tessera', connectivity='USB-C|HDMI', color='Black')),
    P('E-MONITOR-34', 'Tessera 34 inch ultrawide monitor', ['computing'], 749, 'A curved ultrawide with a 144 Hz panel and a KVM switch.', 'a curved 34 inch ultrawide monitor with a dark blank screen', attributes=dict(brand='Tessera', connectivity='USB-C|HDMI', color='Black')),
    P('E-KEYBOARD', 'Orbit Labs 75 mechanical keyboard', ['computing'], 159, 'A 75 percent mechanical keyboard with hot-swap switches and a gasket mount.', 'a compact {value} mechanical keyboard with keycaps, top down view', axis='color', values=['Black', 'White', 'Blue'], picture_per_value=True, attributes=dict(brand='Orbit Labs', connectivity='Bluetooth|USB-C')),
    P('E-MOUSE', 'Orbit Labs Glide mouse', ['computing'], 89, 'A lightweight wireless mouse with a 4000 Hz polling rate and PTFE feet.', 'a {value} lightweight wireless gaming mouse', axis='color', values=['Black', 'White'], picture_per_value=True, attributes=dict(brand='Orbit Labs', connectivity='Bluetooth|USB-C')),
    P('E-DOCK', 'Voltline Thunderbolt dock', ['computing', 'accessories'], 249, 'A Thunderbolt dock with two displays, ten ports and 96 W of charging.', 'a flat aluminium thunderbolt docking station with many ports', attributes=dict(brand='Voltline', connectivity='Thunderbolt|USB-C|HDMI', color='Silver')),
    P('E-SSD', 'Voltline portable SSD', ['computing', 'accessories'], 129, 'A rugged USB-C SSD with 2000 MB/s reads, in a rubber sleeve.', 'a small rugged portable SSD drive with a rubber sleeve', axis='storage', values=['1 TB', '2 TB'], attributes=dict(brand='Voltline', connectivity='USB-C', color='Charcoal')),
    P('E-WEBCAM', 'Tessera 4K webcam', ['computing'], 119, 'A 4K webcam with a large sensor and a privacy shutter.', 'a small black 4K webcam with a privacy shutter on a monitor clip', attributes=dict(brand='Tessera', connectivity='USB-C', color='Black')),
    P('E-CAMERA-BODY', 'Halide M1 mirrorless camera', ['cameras'], 1499, 'A full-frame mirrorless body with in-body stabilisation and a quiet shutter.', 'a black full frame mirrorless camera body without a lens', attributes=dict(brand='Halide', connectivity='Wi-Fi|USB-C|Bluetooth', color='Black')),
    P('E-LENS-35', 'Halide 35 mm f/1.8 lens', ['cameras'], 549, 'A compact 35 mm prime with fast, silent focus. The one-lens travel kit.', 'a compact black 35mm prime camera lens standing upright', attributes=dict(brand='Halide', connectivity='Wired', color='Black')),
    P('E-LENS-85', 'Halide 85 mm f/1.4 lens', ['cameras'], 999, 'A portrait prime with creamy bokeh and weather sealing.', 'a large black 85mm portrait camera lens standing upright', attributes=dict(brand='Halide', color='Black')),
    P('E-LENS-2470', 'Halide 24-70 mm f/2.8 lens', ['cameras'], 1299, 'The standard zoom, sharp at every stop.', 'a black 24-70mm zoom camera lens standing upright', attributes=dict(brand='Halide', color='Black')),
    P('E-COMPACT-CAM', 'Halide Pocket compact camera', ['cameras'], 799, 'A pocket camera with a one-inch sensor and a fast lens. Better than your phone, fits the same pocket.', 'a small silver and black compact camera', attributes=dict(brand='Halide', connectivity='Wi-Fi|USB-C', color='Silver')),
    P('E-ACTION-CAM', 'Halide Go action camera', ['cameras'], 349, 'A waterproof action camera with 5K video and horizon lock.', 'a small black waterproof action camera', attributes=dict(brand='Halide', connectivity='Wi-Fi|Bluetooth|USB-C', color='Black')),
    P('E-TRIPOD', 'Halide carbon travel tripod', ['cameras', 'accessories'], 229, 'A carbon fibre tripod that folds to 40 cm and holds 10 kg.', 'a folded carbon fibre travel tripod with a ball head', attributes=dict(brand='Halide', color='Black')),
    P('E-CAM-BAG', 'Halide sling bag', ['cameras', 'accessories'], 89, 'A six-litre sling for a body and two lenses, with a weather flap.', 'a small {value} camera sling bag', axis='color', values=['Charcoal', 'Khaki'], picture_per_value=True, attributes=dict(brand='Halide')),
    P('E-SD-CARD', 'Voltline SD card', ['cameras', 'accessories'], 49, 'A V90 SD card for 8K video and fast bursts.', 'a single SD memory card standing upright', axis='storage', values=['128 GB', '256 GB', '512 GB'], attributes=dict(brand='Voltline', color='Black')),
    P('E-SMART-BULB', 'Orbit Labs smart bulb', ['smart-home'], 24, 'A colour smart bulb that works over your local network. No account.', 'a single white smart LED bulb', attributes=dict(brand='Orbit Labs', connectivity='Wi-Fi', color='White')),
    P('E-SMART-PLUG', 'Orbit Labs smart plug', ['smart-home'], 19, 'A compact plug with energy metering and a physical button.', 'a small white smart plug adapter', attributes=dict(brand='Orbit Labs', connectivity='Wi-Fi', color='White')),
    P('E-SMART-SPEAKER', 'Nimbus Home speaker', ['smart-home', 'audio'], 129, 'A room-filling speaker with local voice control and a mute switch that cuts power to the mics.', 'a round {value} fabric smart speaker', axis='color', values=['Grey', 'Charcoal'], picture_per_value=True, attributes=dict(brand='Nimbus', connectivity='Wi-Fi|Bluetooth')),
    P('E-DOORBELL', 'Orbit Labs video doorbell', ['smart-home'], 149, 'A wired doorbell camera that records to a card in your home, not a cloud.', 'a slim black video doorbell', attributes=dict(brand='Orbit Labs', connectivity='Wi-Fi', color='Black')),
    P('E-THERMOSTAT', 'Orbit Labs thermostat', ['smart-home'], 179, 'A learning thermostat with a rotary dial and an e-paper display.', 'a round white smart thermostat with a dial', attributes=dict(brand='Orbit Labs', connectivity='Wi-Fi', color='White')),
    P('E-SENSOR-KIT', 'Orbit Labs sensor kit', ['smart-home'], 69, 'Four door sensors and two motion sensors, batteries included.', 'a set of small white door sensors and motion sensors laid out', attributes=dict(brand='Orbit Labs', connectivity='Wi-Fi', color='White')),
    P('E-HUB', 'Orbit Labs home hub', ['smart-home'], 99, 'The hub that runs your home on your own network, with Zigbee and Thread.', 'a small white square smart home hub', attributes=dict(brand='Orbit Labs', connectivity='Wi-Fi|USB-C', color='White')),
    P('E-WATCH', 'Voltline Watch', ['wearables'], 299, 'A smart watch with a sapphire glass face, a week of battery and offline maps.', 'a {value} smart watch with a round face and a sport strap', axis='color', values=['Black', 'Silver'], picture_per_value=True, attributes=dict(brand='Voltline', connectivity='Bluetooth|Wi-Fi')),
    P('E-BAND', 'Voltline Band', ['wearables'], 79, 'A slim tracker with sleep, heart rate and two weeks of battery.', 'a slim {value} fitness tracker band', axis='color', values=['Black', 'Blue', 'Pink'], picture_per_value=True, attributes=dict(brand='Voltline', connectivity='Bluetooth')),
    P('E-RING', 'Voltline Ring', ['wearables'], 249, 'A titanium sleep ring that lasts a week, no subscription.', 'a {value} titanium smart ring', axis='color', values=['Silver', 'Black'], picture_per_value=True, attributes=dict(brand='Voltline', connectivity='Bluetooth')),
    P('E-WATCH-STRAP', 'Voltline leather watch strap', ['wearables', 'accessories'], 39, 'A vegetable-tanned leather strap with a quick-release pin.', 'a {value} leather smart watch strap', axis='color', values=['Brown', 'Black'], picture_per_value=True, attributes=dict(brand='Voltline')),
    P('E-CHARGER-65', 'Voltline 65 W charger', ['accessories'], 49, 'A GaN charger with two USB-C ports, small enough to lose.', 'a compact white USB-C wall charger', attributes=dict(brand='Voltline', connectivity='USB-C', color='White')),
    P('E-CABLE-C', 'Voltline braided USB-C cable', ['accessories'], 19, 'A 2 m braided cable for 240 W charging and 40 Gbps data.', 'a coiled {value} braided USB-C cable', axis='color', values=['Black', 'Grey'], picture_per_value=True, attributes=dict(brand='Voltline', connectivity='USB-C')),
    P('E-POWERBANK', 'Voltline 20000 power bank', ['accessories'], 69, 'A 20000 mAh power bank with 65 W output and a display.', 'a slim dark grey power bank with a small display', attributes=dict(brand='Voltline', connectivity='USB-C', color='Charcoal')),
    P('E-LAPTOP-STAND', 'Tessera laptop stand', ['accessories', 'computing'], 59, 'An aluminium stand that raises the screen to eye height and folds flat.', 'a silver aluminium folding laptop stand', attributes=dict(brand='Tessera', color='Silver')),
    P('E-DESK-MAT', 'Orbit Labs desk mat', ['accessories'], 29, 'A felt and cork desk mat, 90 by 40 cm.', 'a {value} felt desk mat rolled at one corner', axis='color', values=['Grey', 'Green'], picture_per_value=True, attributes=dict(brand='Orbit Labs')),
    P('E-PHONE-CASE', 'Tessera phone case', ['accessories'], 34, 'A slim case in recycled polymer with a microfibre lining.', 'a slim {value} phone case seen from the back', axis='color', values=['Black', 'Blue', 'Green'], picture_per_value=True, attributes=dict(brand='Tessera')),
    P('E-SCREEN-CLEAN', 'Tessera screen cleaning kit', ['accessories'], 15, 'A spray, two cloths and a brush, for screens and lenses.', 'a small screen cleaning kit with a spray bottle and microfibre cloths', attributes=dict(brand='Tessera', color='Grey')),
    P('E-DESK-KIT', 'Home office kit', ['accessories', 'computing'], 449, 'Keyboard, mouse, laptop stand and desk mat in one order.', 'a mechanical keyboard, a wireless mouse, a laptop stand and a felt desk mat arranged together', grouped=['E-KEYBOARD-BLACK', 'E-MOUSE-BLACK', 'E-LAPTOP-STAND', 'E-DESK-MAT-GREY'], attributes=dict(brand='Orbit Labs')),
    P('E-TRAVEL-KIT', 'Travel charging kit', ['accessories'], 129, 'Charger, cable and power bank, packed in a zip pouch.', 'a compact charger, a braided cable and a power bank in an open zip pouch', grouped=['E-CHARGER-65', 'E-CABLE-C-BLACK', 'E-POWERBANK'], attributes=dict(brand='Voltline')),
]
POSTS = [
    ('How we measure headphones', '<p>Every headphone goes on a measurement rig before it goes on the shelf. We record the frequency response from 20 Hz to 20 kHz and compare it to a target that most listeners describe as neutral.</p><p>The chart is published on the product page. A bump at 100 Hz means warm bass. A dip at 3 kHz means voices sit back. You choose, with the chart in front of you.</p>', 'Over-ear headphones on a measurement rig in a lab, with an analyser screen out of focus behind.'),
    ('Why local-first smart home', '<p>A smart bulb that needs a cloud account stops working when the company changes its mind. Everything in our smart home range talks to a hub in your house, over your own network.</p><p>No account, no subscription, and it keeps working when the internet does not.</p>', 'A smart home hub on a shelf with a bulb glowing warm beside it.'),
    ('One lens to travel with', '<p>If you take one lens, take a 35 mm. Wide enough for a street, tight enough for a face, and small enough that you bring the camera.</p><p>Shoot at f/2.8 in the day, open up at night, and stop worrying about the rest of the bag.</p>', 'A mirrorless camera with a small prime lens on a cafe table beside a coffee cup.'),
]
MORE = {
    'E-HEADPHONE-ANC': 'Fold flat into a hard case, charge by USB-C, and the cancelling adapts to a plane or a train. The tuning is flat, so what you hear is the recording.',
    'E-EARBUDS': 'The buds seal well and the microphones handle a windy call. The case charges wirelessly or by USB-C.',
    'E-WIRED-IEM': 'A single driver keeps the sound coherent from bass to treble. The cable unclips, so a broken cable is not a broken pair.',
    'E-SPEAKER-BT': 'It survives a pool and a beach, and pairs with a second unit for stereo. Twelve hours at normal volume.',
    'E-BOOKSHELF': 'Plug in the turntable, the television or a laptop, or stream from a phone. No separate amplifier needed.',
    'E-TURNTABLE': 'The phono stage switches off for people who own one already. Set up in ten minutes with the included gauge.',
    'E-DAC': 'It powers demanding headphones from a phone or a laptop and adds no noise of its own. The case is machined aluminium.',
    'E-SOUNDBAR': 'One cable to the television and the subwoofer finds the bar by itself. Dialogue mode makes voices clear at low volume.',
    'E-LAPTOP-14': 'Sixteen gigabytes of memory, a fast SSD and a case that opens with one hand. It charges from any USB-C charger.',
    'E-LAPTOP-16': 'Built for people who compile, render and edit. The fans stay quiet until the work gets heavy.',
    'E-MONITOR-27': 'One USB-C cable carries video, data and 90 W of power to a laptop. The stand tilts, swivels and rises.',
    'E-MONITOR-34': 'Two computers, one keyboard and mouse, switched with a button. The curve keeps the corners at the same distance as the centre.',
    'E-KEYBOARD': 'The switches pull out without soldering, and the gasket mount softens every keystroke. Wired or Bluetooth.',
    'E-MOUSE': 'Fifty-eight grams, a week of battery, and feet that glide on any mat. The receiver lives inside the mouse when not in use.',
    'E-DOCK': 'One cable from the laptop to the dock, and the desk is ready. Two 4K displays at 60 Hz.',
    'E-SSD': 'Two terabytes in a case that survives a drop from two metres. The USB-C cable is in the box.',
    'E-WEBCAM': 'The sensor handles a dark room without grain. Slide the shutter shut and it is a lens cap, not a promise.',
    'E-CAMERA-BODY': 'Twenty-four megapixels, dual card slots and a viewfinder that does not lag. The body is sealed against rain.',
    'E-LENS-35': 'Sharp wide open, close focusing to 25 cm, and small enough for a jacket pocket. Weather sealed at the mount.',
    'E-LENS-85': 'Wide open it separates a face from a busy background. Focus is fast enough for children and dogs.',
    'E-LENS-2470': 'Weddings, landscapes and everything between. Weather sealed, with a lock switch for the zoom ring.',
    'E-COMPACT-CAM': 'A real zoom, a real flash and a battery that lasts a day out. Raw files, if you want them.',
    'E-ACTION-CAM': 'Waterproof to ten metres without a case. Horizon lock keeps the video level on a bike or a board.',
    'E-TRIPOD': 'The legs fold back over the head to fit a daypack. The centre column reverses for low shots.',
    'E-CAM-BAG': 'The camera comes out with one hand, and the flap keeps rain out. The strap swaps sides for left-handers.',
    'E-SD-CARD': 'Two hundred and fifty-six gigabytes with sustained writes for 8K video. Rated for ten thousand insertions.',
    'E-SMART-BULB': 'Set the colour and the schedule from the hub, with no cloud and no account. Works with a normal switch too.',
    'E-SMART-PLUG': 'It reports watts and kilowatt hours, and the button works when the network is down. Rated for a heater.',
    'E-SMART-SPEAKER': 'Voice commands are processed in the room, not on a server. The mute switch is a physical cut, not a request.',
    'E-DOORBELL': 'Wired to the existing chime, recording to a card behind the unit. Notifications come from your own hub.',
    'E-THERMOSTAT': 'Turn the dial to set the temperature and it learns the rest. Runs on the hub, no cloud.',
    'E-SENSOR-KIT': 'Stick the sensors on doors and shelves, pair them with the hub, and the batteries last two years.',
    'E-HUB': 'It speaks Zigbee, Thread and Wi-Fi, stores its data on the device, and updates when you say so.',
    'E-WATCH': 'Heart rate, sleep, GPS routes and offline maps, on a battery that lasts seven days. The face is sapphire.',
    'E-BAND': 'It weighs fourteen grams and tracks sleep, steps and heart rate for two weeks between charges. The strap comes in three colours.',
    'E-RING': 'Sleep stages, resting heart rate and temperature from a ring you forget. Charge once a week.',
    'E-WATCH-STRAP': 'Full-grain leather that softens in a week. The quick-release pin swaps it in seconds.',
    'E-CHARGER-65': 'Charges a laptop and a phone at once, from a plug the size of a matchbox. Foldable prongs.',
    'E-CABLE-C': 'Two metres of braided nylon, rated for the fastest laptops and displays. The connectors are aluminium.',
    'E-POWERBANK': 'Enough for a laptop and two phone charges. The display shows the percentage, not a row of dots.',
    'E-LAPTOP-STAND': 'It lifts the screen to eye height for a straight neck and folds flat for a bag. Fits laptops up to 16 inches.',
    'E-DESK-MAT': 'Wool felt on top, cork underneath, no slipping. The keyboard and the mouse both fit with room to spare.',
    'E-PHONE-CASE': 'Slim enough to keep the phone slim, grippy enough to survive a wet hand. Buttons stay clicky.',
    'E-SCREEN-CLEAN': 'Alcohol free, safe for coatings and lenses. One bottle cleans a year of screens.',
    'E-DESK-KIT': 'Everything for a clean desk in one box, at a saving. Keyboard, mouse, stand and mat.',
    'E-TRAVEL-KIT': 'Charger, cable and power bank in a pouch that fits a jacket pocket. Enough for a week away.',
}
