"""The French, German and Italian text of the Fashion pack.

The Fashion pack is the one pack that is not generated: packs/fashion holds hand written CSV files,
so this file carries no catalog, only the text of that pack in the three other languages. Every
other store keeps its translations inside its own spec, next to the English string they translate.

tools/build-store-pack.py reads the English text of the pack from the CSV files and looks it up
here, so the 'en' value must match the CSV character for character. A string with no entry stays in
English on the French, German and Italian store views.
"""
TEXTS = [
    # Categories
    {'en': 'Fashion', 'fr': 'Mode', 'de': 'Mode', 'it': 'Moda'},
    {'en': 'Travel-wear and lifestyle pieces for the journey.',
     'fr': 'Des vêtements de voyage et des pièces du quotidien, pour la route.',
     'de': 'Reisekleidung und Lieblingsstücke für unterwegs.',
     'it': 'Capi da viaggio e pezzi di tutti i giorni, per la strada.'},
    {'en': 'Women', 'fr': 'Femme', 'de': 'Damen', 'it': 'Donna'},
    {'en': 'New Arrivals', 'fr': 'Nouveautés', 'de': 'Neuheiten', 'it': 'Novità'},
    {'en': 'Tops & Blouses', 'fr': 'Hauts et chemisiers', 'de': 'Tops und Blusen', 'it': 'Top e camicette'},
    {'en': 'Pants & Denim', 'fr': 'Pantalons et jeans', 'de': 'Hosen und Jeans', 'it': 'Pantaloni e jeans'},
    {'en': 'Dresses & Skirts', 'fr': 'Robes et jupes', 'de': 'Kleider und Röcke', 'it': 'Abiti e gonne'},
    {'en': 'Men', 'fr': 'Homme', 'de': 'Herren', 'it': 'Uomo'},
    {'en': 'Shirts', 'fr': 'Chemises', 'de': 'Hemden', 'it': 'Camicie'},
    {'en': 'Tees, Knits and Polos', 'fr': 'T-shirts, mailles et polos', 'de': 'Shirts, Strick und Polos', 'it': 'T-shirt, maglieria e polo'},
    {'en': 'Blazers', 'fr': 'Vestes', 'de': 'Sakkos', 'it': 'Giacche'},
    {'en': 'Eyewear', 'fr': 'Lunettes', 'de': 'Brillen', 'it': 'Occhiali'},
    {'en': 'Shoes', 'fr': 'Chaussures', 'de': 'Schuhe', 'it': 'Scarpe'},
    {'en': 'Bags & Luggage', 'fr': 'Sacs et bagages', 'de': 'Taschen und Gepäck', 'it': 'Borse e valigie'},
    {'en': 'Sale', 'fr': 'Soldes', 'de': 'Sale', 'it': 'Saldi'},

    # Reviews
    {'en': 'Exactly as pictured', 'fr': 'Exactement comme sur la photo', 'de': 'Genau wie abgebildet', 'it': 'Esattamente come in foto'},
    {'en': 'Fits true to size and the fabric feels expensive. Washed twice, no change.',
     'fr': 'Taille juste et le tissu fait cher. Lavé deux fois, aucun changement.',
     'de': 'Fällt normal aus und der Stoff fühlt sich teuer an. Zweimal gewaschen, keine Veränderung.',
     'it': 'Veste come da taglia e il tessuto sembra costoso. Lavato due volte, nessun cambiamento.'},
    {'en': 'Ties stay put', 'fr': 'Les liens tiennent', 'de': 'Die Bänder halten', 'it': 'I lacci tengono'},
    {'en': 'The wrap does not come loose during the day. Shipping was quick.',
     'fr': 'Le cache-cœur ne se défait pas dans la journée. Livraison rapide.',
     'de': 'Das Wickelteil geht tagsüber nicht auf. Schneller Versand.',
     'it': "L'incrocio non si apre durante il giorno. Spedizione veloce."},
    {'en': 'My new favourite', 'fr': 'Mon nouveau préféré', 'de': 'Mein neuer Liebling', 'it': 'Il mio nuovo preferito'},
    {'en': 'Comfortable, light and it goes with everything I own.',
     'fr': "Confortable, léger et il va avec tout ce que j'ai.",
     'de': 'Bequem, leicht und es passt zu allem, was ich habe.',
     'it': 'Comodo, leggero e sta bene con tutto quello che ho.'},
    {'en': 'Good, not perfect', 'fr': 'Bien, sans être parfait', 'de': 'Gut, nicht perfekt', 'it': 'Buono, non perfetto'},
    {'en': 'Nice cut and colour. The sizing runs a little large, so size down.',
     'fr': 'Belle coupe et belle couleur. La taille est un peu grande, prenez en dessous.',
     'de': 'Schöner Schnitt und schöne Farbe. Fällt etwas groß aus, also eine Nummer kleiner wählen.',
     'it': "Bel taglio e bel colore. La taglia è un po' grande, prendine una in meno."},
    {'en': 'Bought it for a wedding', 'fr': 'Acheté pour un mariage', 'de': 'Für eine Hochzeit gekauft', 'it': 'Comprato per un matrimonio'},
    {'en': 'Wore it to a summer wedding and got asked about it four times.',
     'fr': "Porté à un mariage d'été, on m'a demandé quatre fois où je l'avais trouvé.",
     'de': 'Bei einer Sommerhochzeit getragen und vier Mal darauf angesprochen worden.',
     'it': "Indossato a un matrimonio d'estate e me lo hanno chiesto quattro volte."},
    {'en': 'Creases, but that is linen', 'fr': "Il froisse, mais c'est du lin", 'de': 'Es knittert, aber das ist Leinen', 'it': 'Si stropiccia, ma è lino'},
    {'en': 'Looks best a little crumpled. Cool on a hot day and dries in an hour.',
     'fr': 'Il est plus beau un peu froissé. Frais quand il fait chaud et sec en une heure.',
     'de': 'Es sieht leicht zerknittert am besten aus. Kühl an heißen Tagen und in einer Stunde trocken.',
     'it': "Sta meglio un po' spiegazzato. Fresco quando fa caldo e asciuga in un'ora."},
    {'en': 'Packed it for three weeks', 'fr': 'Emporté pendant trois semaines', 'de': 'Drei Wochen im Koffer', 'it': 'In valigia per tre settimane'},
    {'en': 'Came out of the bag ready to wear every time. Would buy again.',
     'fr': 'Il sortait du sac prêt à porter à chaque fois. Je rachèterai.',
     'de': 'Kam jedes Mal tragefertig aus der Tasche. Ich kaufe es wieder.',
     'it': 'Usciva dalla borsa pronto da indossare ogni volta. Lo ricomprerei.'},
    {'en': 'Collar holds its shape', 'fr': 'Le col garde sa forme', 'de': 'Der Kragen hält die Form', 'it': 'Il colletto tiene la forma'},
    {'en': 'Buttoned down, no curling after a dozen washes. Proper oxford cloth.',
     'fr': 'Col boutonné, aucun rebord après une douzaine de lavages. Du vrai tissu oxford.',
     'de': 'Button-down, keine Wellen nach einem Dutzend Wäschen. Echter Oxford-Stoff.',
     'it': 'Button-down, nessuna arricciatura dopo una dozzina di lavaggi. Vero tessuto oxford.'},
    {'en': 'Sleeves a touch long', 'fr': 'Manches un peu longues', 'de': 'Ärmel etwas zu lang', 'it': "Maniche un po' lunghe"},
    {'en': 'Good shirt, but the sleeves are long on me. A cuff roll fixes it.',
     'fr': 'Bonne chemise, mais les manches sont longues pour moi. Un revers règle le problème.',
     'de': 'Gutes Hemd, aber die Ärmel sind mir zu lang. Einmal umschlagen löst das.',
     'it': 'Bella camicia, ma le maniche sono lunghe per me. Un risvolto risolve.'},
    {'en': 'Solid basics', 'fr': 'Des basiques solides', 'de': 'Solide Basics', 'it': 'Capi base che durano'},
    {'en': 'Heavy cotton, no see-through, neck has not stretched. Bought three.',
     'fr': "Coton épais, pas transparent, le col n'a pas bougé. J'en ai acheté trois.",
     'de': 'Schwere Baumwolle, nicht durchsichtig, der Ausschnitt ist nicht ausgeleiert. Drei gekauft.',
     'it': 'Cotone pesante, non trasparente, il collo non si è allargato. Ne ho presi tre.'},
    {'en': 'Warm without bulk', 'fr': 'Chaud sans volume', 'de': 'Warm ohne aufzutragen', 'it': 'Caldo senza volume'},
    {'en': 'Merino at its best. Fits under a jacket and over a shirt.',
     'fr': 'Du mérinos au meilleur niveau. Il passe sous une veste et sur une chemise.',
     'de': 'Merino von seiner besten Seite. Passt unter eine Jacke und über ein Hemd.',
     'it': 'Merino al meglio. Sta sotto una giacca e sopra una camicia.'},
    {'en': 'Buttons are horn', 'fr': 'Des boutons en corne', 'de': 'Knöpfe aus Horn', 'it': 'Bottoni in corno'},
    {'en': 'Real horn buttons and a proper placket. Small things, done right.',
     'fr': 'De vrais boutons en corne et une patte de boutonnage soignée. Les détails, bien faits.',
     'de': 'Echte Hornknöpfe und eine ordentliche Knopfleiste. Kleine Dinge, richtig gemacht.',
     'it': 'Bottoni in vero corno e un bel cannoncino. Piccole cose, fatte bene.'},
    {'en': 'Stiff at first', 'fr': 'Rigide au début', 'de': 'Anfangs steif', 'it': "Rigidi all'inizio"},
    {'en': 'Two weeks of wear and they gave in. Now they fit like a glove.',
     'fr': 'Deux semaines de port et ils se sont assouplis. Maintenant ils vont comme un gant.',
     'de': 'Zwei Wochen getragen und sie haben nachgegeben. Jetzt sitzen sie wie angegossen.',
     'it': 'Due settimane di uso e si sono ammorbiditi. Ora calzano a pennello.'},
    {'en': 'Travel blazer', 'fr': 'La veste de voyage', 'de': 'Der Reiseblazer', 'it': 'La giacca da viaggio'},
    {'en': 'Rolled it in a suitcase, shook it out, wore it to dinner.',
     'fr': 'Roulée dans une valise, secouée, portée au dîner.',
     'de': 'Im Koffer gerollt, ausgeschüttelt, zum Abendessen getragen.',
     'it': 'Arrotolata in valigia, scossa, indossata a cena.'},
    {'en': 'Lining is light', 'fr': 'Doublure légère', 'de': 'Leichtes Futter', 'it': 'Fodera leggera'},
    {'en': 'Half lined, so it breathes. Perfect for a warm office.',
     'fr': 'Demi-doublée, donc elle respire. Parfaite pour un bureau chaud.',
     'de': 'Halb gefüttert, also atmet er. Perfekt für ein warmes Büro.',
     'it': 'Mezza foderata, quindi respira. Perfetta per un ufficio caldo.'},
    {'en': 'Lenses are dark enough', 'fr': 'Des verres assez foncés', 'de': 'Die Gläser sind dunkel genug', 'it': 'Lenti abbastanza scure'},
    {'en': 'Proper category three lenses and no distortion at the edges.',
     'fr': 'De vrais verres de catégorie trois, sans déformation sur les bords.',
     'de': 'Echte Gläser der Kategorie drei und keine Verzerrung am Rand.',
     'it': 'Vere lenti di categoria tre e nessuna distorsione ai bordi.'},
    {'en': 'Cheap and cheerful', 'fr': 'Simple et efficace', 'de': 'Günstig und gut', 'it': 'Economico e fa il suo'},
    {'en': 'Clear lenses, light frame, a spare pair for the car.',
     'fr': 'Verres clairs, monture légère, une paire de secours pour la voiture.',
     'de': 'Klare Gläser, leichter Rahmen, ein Ersatzpaar fürs Auto.',
     'it': "Lenti chiare, montatura leggera, un paio di scorta per l'auto."},
    {'en': 'Case is included', 'fr': "L'étui est inclus", 'de': 'Etui ist dabei', 'it': 'La custodia è inclusa'},
    {'en': 'Hard case in the box. Did not expect that at this price.',
     'fr': "Un étui rigide dans la boîte. Je ne m'y attendais pas à ce prix.",
     'de': 'Hartschalenetui in der Box. Damit hatte ich zu dem Preis nicht gerechnet.',
     'it': "Custodia rigida nella scatola. Non me l'aspettavo a questo prezzo."},
    {'en': 'Light on the ear', 'fr': "Légères à l'oreille", 'de': 'Leicht am Ohr', 'it': "Leggeri all'orecchio"},
    {'en': 'Hollow hoops, so no drag after a full day.',
     'fr': 'Des créoles creuses, donc aucune tension après une journée entière.',
     'de': 'Hohle Creolen, also kein Ziehen nach einem ganzen Tag.',
     'it': 'Cerchi cavi, quindi nessun peso dopo un giorno intero.'},
    {'en': 'Broke in fast', 'fr': 'Vite assouplies', 'de': 'Schnell eingelaufen', 'it': 'Si sono ammorbidite subito'},
    {'en': 'Two days and no rubbing. The rubber sole grips well in the rain.',
     'fr': 'Deux jours et plus aucun frottement. La semelle en caoutchouc accroche bien sous la pluie.',
     'de': 'Zwei Tage und kein Scheuern mehr. Die Gummisohle greift auch im Regen.',
     'it': 'Due giorni e niente sfregamento. La suola di gomma tiene bene sotto la pioggia.'},
    {'en': 'Runs half a size big', 'fr': 'Taille une demi-pointure au-dessus', 'de': 'Fällt eine halbe Nummer größer aus', 'it': 'Veste mezza taglia in più'},
    {'en': 'Great shoe, order half a size down. The white stays white with a wipe.',
     'fr': 'Très bonne chaussure, prenez une demi-pointure en dessous. Le blanc reste blanc avec un coup de chiffon.',
     'de': 'Toller Schuh, eine halbe Nummer kleiner bestellen. Das Weiß bleibt weiß, ein Wischen reicht.',
     'it': 'Ottima scarpa, ordina mezza taglia in meno. Il bianco resta bianco con una passata.'},
    {'en': 'Elastic is strong', 'fr': "L'élastique tient bien", 'de': 'Das Gummi hält', 'it': "L'elastico tiene"},
    {'en': 'Slip on, slip off, and the elastic has not sagged after a winter.',
     'fr': "On les enfile, on les enlève, et l'élastique n'a pas cédé après un hiver.",
     'de': 'Reinschlüpfen, rausschlüpfen, und das Gummi ist nach einem Winter nicht ausgeleiert.',
     'it': "Si infilano, si sfilano, e l'elastico non ha ceduto dopo un inverno."},
    {'en': 'Carries a laptop', 'fr': 'Il porte un ordinateur portable', 'de': 'Trägt einen Laptop', 'it': 'Porta un portatile'},
    {'en': 'Fifteen inch laptop, a book and lunch. The straps do not dig in.',
     'fr': 'Un portable de quinze pouces, un livre et le déjeuner. Les bretelles ne rentrent pas dans les épaules.',
     'de': 'Fünfzehn-Zoll-Laptop, ein Buch und das Mittagessen. Die Gurte schneiden nicht ein.',
     'it': 'Portatile da quindici pollici, un libro e il pranzo. Gli spallacci non segnano.'},
    {'en': 'Canvas is thick', 'fr': 'La toile est épaisse', 'de': 'Das Segeltuch ist dick', 'it': 'La tela è spessa'},
    {'en': 'Stands up on its own. Wish it had an inside pocket.',
     'fr': 'Il tient debout tout seul. Il manque juste une poche intérieure.',
     'de': 'Steht von allein. Eine Innentasche fehlt mir.',
     'it': 'Sta in piedi da sola. Le manca una tasca interna.'},

    # Products
    {'en': 'Ashford linen shirt', 'fr': 'Chemise en lin Ashford', 'de': 'Ashford Leinenhemd', 'it': 'Camicia di lino Ashford'},
    {'en': 'A relaxed linen shirt with a soft collar and mother-of-pearl buttons. Packs flat, dries fast, gets better with every wash. Cut from midweight European linen with a curved hem that works tucked or out. Wash cold and hang to dry.',
     'fr': "Une chemise en lin décontractée, col souple et boutons de nacre. Elle se plie à plat, sèche vite et s'améliore à chaque lavage. Coupée dans un lin européen de poids moyen, avec un bas arrondi qui se porte rentré ou sorti. Lavage à froid, séchage sur cintre.",
     'de': 'Ein lockeres Leinenhemd mit weichem Kragen und Perlmuttknöpfen. Es packt flach, trocknet schnell und wird mit jeder Wäsche besser. Aus mittelschwerem europäischem Leinen, mit rundem Saum zum Reinstecken oder Offentragen. Kalt waschen und hängend trocknen.',
     'it': 'Una camicia di lino dal taglio morbido, con collo soft e bottoni in madreperla. Si piega piatta, asciuga in fretta e migliora a ogni lavaggio. Tagliata in lino europeo di peso medio, con fondo arrotondato che sta bene dentro o fuori. Lavare a freddo e asciugare appesa.'},
    {'en': 'Meridian silk blouse', 'fr': 'Blouse en soie Meridian', 'de': 'Meridian Seidenbluse', 'it': 'Blusa di seta Meridian'},
    {'en': 'A fluid silk blouse with a concealed placket and a slightly dropped shoulder. Wear it tucked or loose. Sandwashed mulberry silk that falls close without clinging. Dry clean, or hand wash cold and lay flat.',
     'fr': 'Une blouse en soie fluide, patte de boutonnage cachée et épaule légèrement tombante. À porter rentrée ou libre. Soie de mûrier sablée qui tombe près du corps sans coller. Nettoyage à sec, ou lavage à la main à froid et séchage à plat.',
     'de': 'Eine fließende Seidenbluse mit verdeckter Knopfleiste und leicht abfallender Schulter. Ob eingesteckt oder locker getragen. Sandgewaschene Maulbeerseide, die nah fällt, ohne zu kleben. Chemisch reinigen oder kalt von Hand waschen und liegend trocknen.',
     'it': 'Una blusa di seta fluida, con cannoncino nascosto e spalla leggermente scesa. Da portare dentro o fuori. Seta di gelso lavata alla sabbia che cade vicino al corpo senza appiccicarsi. Lavaggio a secco, oppure a mano in acqua fredda e ad asciugare in piano.'},
    {'en': 'Nordlys ribbed tank', 'fr': 'Débardeur côtelé Nordlys', 'de': 'Nordlys Ripptop', 'it': 'Canotta a coste Nordlys'},
    {'en': 'A ribbed cotton tank with a square neck. The layering piece that works alone on warm days. A dense rib in organic cotton that holds its shape all day. Machine wash, no tumble.',
     'fr': 'Un débardeur en coton côtelé à encolure carrée. La pièce à superposer qui se suffit aussi quand il fait chaud. Une côte dense en coton biologique qui garde sa forme toute la journée. Lavage en machine, pas de sèche-linge.',
     'de': 'Ein geripptes Baumwolltop mit eckigem Ausschnitt. Das Lagen-Teil, das an warmen Tagen auch allein funktioniert. Ein dichter Rippstrick aus Biobaumwolle, der den ganzen Tag in Form bleibt. Maschinenwäsche, nicht in den Trockner.',
     'it': 'Una canotta di cotone a coste con scollo quadrato. Il capo da sovrapporre che nei giorni caldi sta bene anche da solo. Una costa fitta in cotone biologico che tiene la forma tutto il giorno. Lavaggio in lavatrice, no asciugatrice.'},
    {'en': 'Bruma Sol wrap top', 'fr': 'Top portefeuille Bruma Sol', 'de': 'Bruma Sol Wickeltop', 'it': 'Top a portafoglio Bruma Sol'},
    {'en': 'A wrap top in crinkled cotton that ties at the side. No ironing, ever. The crinkle is set in the fabric, so it comes out of the suitcase ready. Machine wash cold.',
     'fr': 'Un top portefeuille en coton froissé qui se noue sur le côté. Jamais de repassage. Le froissé est fixé dans le tissu, il sort donc de la valise prêt à porter. Lavage en machine à froid.',
     'de': 'Ein Wickeltop aus Krinkelbaumwolle, das an der Seite gebunden wird. Nie wieder bügeln. Der Krinkel steckt im Stoff, also kommt es tragefertig aus dem Koffer. Kalt in der Maschine waschen.',
     'it': 'Un top a portafoglio in cotone crinkle che si annoda sul fianco. Mai più ferro da stiro. Il crinkle è fissato nel tessuto, quindi esce dalla valigia già pronto. Lavaggio in lavatrice a freddo.'},
    {'en': 'Harbour stripe tee', 'fr': 'T-shirt rayé Harbour', 'de': 'Harbour Streifenshirt', 'it': 'T-shirt a righe Harbour'},
    {'en': 'A heavyweight striped tee with a boat neck, cut from organic cotton. A 220 g jersey with a wide neck and a straight hem. It shrinks a touch on the first wash, then stays put.',
     'fr': 'Un t-shirt rayé épais à encolure bateau, en coton biologique. Un jersey de 220 g avec une large encolure et un bas droit. Il rétrécit un peu au premier lavage, puis ne bouge plus.',
     'de': 'Ein schweres Streifenshirt mit U-Boot-Ausschnitt aus Biobaumwolle. Ein 220-g-Jersey mit weitem Ausschnitt und geradem Saum. Es geht bei der ersten Wäsche etwas ein und bleibt danach so.',
     'it': 'Una t-shirt a righe pesante con scollo a barca, in cotone biologico. Una jersey da 220 g con scollo largo e fondo dritto. Si ritira un poco al primo lavaggio, poi resta così.'},
    {'en': 'Sand wide-leg trousers', 'fr': 'Pantalon large Sand', 'de': 'Sand Marlenehose', 'it': 'Pantaloni a gamba larga Sand'},
    {'en': 'High-waisted wide-leg trousers in a linen and viscose blend that falls straight and cool. A fitted waist, a flat front and a leg that ends at the ankle. Machine wash cold and hang to dry.',
     'fr': "Un pantalon large taille haute, en mélange lin et viscose, qui tombe droit et reste frais. Une taille ajustée, un devant plat et une jambe qui s'arrête à la cheville. Lavage en machine à froid, séchage sur cintre.",
     'de': 'Eine weite Hose mit hohem Bund aus Leinen-Viskose-Mix, die gerade fällt und kühl bleibt. Ein anliegender Bund, eine flache Front und ein Bein, das am Knöchel endet. Kalt waschen und hängend trocknen.',
     'it': 'Pantaloni a gamba larga a vita alta, in misto lino e viscosa, che cadono dritti e restano freschi. Vita aderente, davanti liscio e gamba che finisce alla caviglia. Lavaggio a freddo e asciugatura appesi.'},
    {'en': 'Fjordline straight jeans', 'fr': 'Jean droit Fjordline', 'de': 'Fjordline Straight Jeans', 'it': 'Jeans dritti Fjordline'},
    {'en': 'A straight-leg jean in rigid organic denim with a high rise. Breaks in to fit you. Rigid 13 oz denim from an Italian mill, with a button fly. Wash rarely and cold.',
     'fr': "Un jean droit en denim brut biologique, taille haute. Il se façonne à votre silhouette. Un denim rigide de 13 oz d'une filature italienne, braguette à boutons. Lavez-le rarement et à froid.",
     'de': 'Eine gerade Jeans aus festem Bio-Denim mit hoher Leibhöhe. Sie arbeitet sich in deine Form ein. Fester 13-oz-Denim aus einer italienischen Weberei, mit Knopfleiste. Selten und kalt waschen.',
     'it': "Un jeans dritto in denim rigido biologico a vita alta. Si adatta a te con l'uso. Denim rigido da 13 oz di una filatura italiana, con patta a bottoni. Lavare di rado e a freddo."},
    {'en': 'Coast cropped chinos', 'fr': 'Chino court Coast', 'de': 'Coast Chino, verkürzt', 'it': 'Chino corti Coast'},
    {'en': 'Cropped chinos in garment-dyed cotton twill, with a clean front and a slim ankle. Garment dyed, so the colour is soft and a little uneven. A touch of stretch in the twill.',
     'fr': "Un chino court en sergé de coton teint en pièce, devant net et cheville fine. Teint après confection, la couleur est douce et un peu irrégulière. Le sergé contient une pointe d'élasthanne.",
     'de': 'Ein verkürzter Chino aus stückgefärbtem Baumwolltwill, mit glatter Front und schmalem Knöchel. Stückgefärbt, daher ist die Farbe weich und leicht ungleichmäßig. Etwas Stretch im Twill.',
     'it': "Chino corti in twill di cotone tinto in capo, con davanti pulito e caviglia stretta. Tinti in capo, quindi il colore è morbido e un po' irregolare. Un pizzico di elastico nel twill."},
    {'en': 'Salt denim shorts', 'fr': 'Short en jean Salt', 'de': 'Salt Jeansshorts', 'it': 'Shorts di jeans Salt'},
    {'en': 'Relaxed denim shorts with a raw hem and a high waist, in a light wash. Cut from 12 oz denim with a four-inch inseam. The hem frays a little more with every wash.',
     'fr': "Un short en jean décontracté, bas brut et taille haute, dans un lavage clair. Coupé dans un denim de 12 oz avec une entrejambe de dix centimètres. Le bas s'effiloche un peu plus à chaque lavage.",
     'de': 'Lockere Jeansshorts mit offenem Saum und hohem Bund, in heller Waschung. Aus 12-oz-Denim mit zehn Zentimetern Innenbeinlänge. Der Saum franst mit jeder Wäsche ein wenig mehr aus.',
     'it': 'Shorts di jeans dal taglio morbido, con fondo vivo e vita alta, in lavaggio chiaro. Tagliati in denim da 12 oz con cavallo di dieci centimetri. Il fondo si sfrangia un poco a ogni lavaggio.'},
    {'en': 'Ashford linen midi dress', 'fr': 'Robe midi en lin Ashford', 'de': 'Ashford Midikleid aus Leinen', 'it': 'Abito midi di lino Ashford'},
    {'en': 'A sleeveless linen midi dress with a square neck and pockets. The one you pack first. The skirt falls to mid calf with a slit at the back. Wash cold and hang to dry.',
     'fr': 'Une robe midi en lin sans manches, encolure carrée et poches. Celle que vous mettez en premier dans la valise. La jupe tombe à mi-mollet avec une fente au dos. Lavage à froid, séchage sur cintre.',
     'de': 'Ein ärmelloses Midikleid aus Leinen mit eckigem Ausschnitt und Taschen. Das Kleid, das zuerst in den Koffer kommt. Der Rock fällt bis zur halben Wade, mit Schlitz hinten. Kalt waschen und hängend trocknen.',
     'it': 'Un abito midi di lino senza maniche, con scollo quadrato e tasche. Quello che metti in valigia per primo. La gonna arriva a metà polpaccio con uno spacco dietro. Lavare a freddo e asciugare appeso.'},
    {'en': 'Meridian slip dress', 'fr': 'Robe nuisette Meridian', 'de': 'Meridian Slipdress', 'it': 'Abito sottoveste Meridian'},
    {'en': 'A bias-cut silk slip dress that skims rather than clings. Dinner, then dancing. Adjustable straps, a low back and a hem below the knee. Dry clean, or hand wash cold.',
     'fr': 'Une robe nuisette en soie coupée dans le biais, qui effleure sans coller. Le dîner, puis la piste. Bretelles réglables, dos échancré et ourlet sous le genou. Nettoyage à sec, ou lavage à la main à froid.',
     'de': 'Ein schräg geschnittenes Seiden-Slipdress, das streift statt zu kleben. Erst Essen, dann Tanzen. Verstellbare Träger, tiefer Rücken und ein Saum unter dem Knie. Chemisch reinigen oder kalt von Hand waschen.',
     'it': 'Un abito sottoveste di seta tagliato in sbieco, che sfiora invece di fasciare. Prima la cena, poi il ballo. Spalline regolabili, schiena scoperta e orlo sotto il ginocchio. Lavaggio a secco o a mano in acqua fredda.'},
    {'en': 'Harbour shirt dress', 'fr': 'Robe chemise Harbour', 'de': 'Harbour Hemdblusenkleid', 'it': 'Abito camicia Harbour'},
    {'en': 'A cotton poplin shirt dress with a belted waist and a full skirt. Crisp poplin with a self belt and side pockets. Machine wash cold.',
     'fr': 'Une robe chemise en popeline de coton, ceinture à la taille et jupe ample. Une popeline nette, avec une ceinture assortie et des poches sur les côtés. Lavage en machine à froid.',
     'de': 'Ein Hemdblusenkleid aus Baumwollpopeline mit Gürtel und weitem Rock. Knackige Popeline mit Stoffgürtel und Seitentaschen. Kalt in der Maschine waschen.',
     'it': 'Un abito camicia in popeline di cotone, con cintura in vita e gonna ampia. Popeline compatto, cintura in tinta e tasche laterali. Lavaggio in lavatrice a freddo.'},
    {'en': 'Sable pleated skirt', 'fr': 'Jupe plissée Sable', 'de': 'Sable Plisseerock', 'it': 'Gonna plissé Sable'},
    {'en': 'A knife-pleated midi skirt in recycled satin, with an elastic waistband. The pleats are heat set and survive the wash. The hem sits below the knee.',
     'fr': "Une jupe midi à plis couchés en satin recyclé, avec une taille élastique. Les plis sont thermofixés et résistent au lavage. L'ourlet tombe sous le genou.",
     'de': 'Ein Midirock mit Kellerfalten aus recyceltem Satin, mit Gummibund. Die Falten sind thermofixiert und überstehen die Wäsche. Der Saum sitzt unter dem Knie.',
     'it': "Una gonna midi a pieghe piatte in raso riciclato, con elastico in vita. Le pieghe sono fissate a caldo e resistono al lavaggio. L'orlo cade sotto il ginocchio."},
    {'en': 'Salt denim skirt', 'fr': 'Jupe en jean Salt', 'de': 'Salt Jeansrock', 'it': 'Gonna di jeans Salt'},
    {'en': 'An A-line denim mini skirt with patch pockets, in a mid wash. Rigid denim with a front button fly and a raw hem. It sits at the natural waist.',
     'fr': 'Une mini-jupe en jean trapèze avec des poches plaquées, dans un lavage moyen. Un denim rigide avec une braguette à boutons et un bas brut. Elle se porte à la taille naturelle.',
     'de': 'Ein Jeans-Minirock in A-Linie mit aufgesetzten Taschen, in mittlerer Waschung. Fester Denim mit Knopfleiste vorn und offenem Saum. Er sitzt in der natürlichen Taille.',
     'it': 'Una minigonna di jeans a trapezio con tasche applicate, in lavaggio medio. Denim rigido con patta a bottoni davanti e fondo vivo. Sta in vita naturale.'},
    {'en': 'Ashford linen camp shirt', 'fr': 'Chemise camp en lin Ashford', 'de': 'Ashford Leinen-Campshirt', 'it': 'Camicia camp di lino Ashford'},
    {'en': 'A washed linen shirt with a one-piece collar. Roll the sleeves, forget the iron. Garment washed for softness, with a chest pocket and a straight hem. Machine wash cold.',
     'fr': 'Une chemise en lin lavé, col une pièce. Remontez les manches, oubliez le fer. Lavée après confection pour la souplesse, avec une poche poitrine et un bas droit. Lavage en machine à froid.',
     'de': 'Ein gewaschenes Leinenhemd mit einteiligem Kragen. Ärmel hochkrempeln, Bügeleisen vergessen. Stückgewaschen für Weichheit, mit Brusttasche und geradem Saum. Kalt in der Maschine waschen.',
     'it': 'Una camicia di lino lavato, con collo in un pezzo. Arrotola le maniche e dimentica il ferro. Lavata in capo per la morbidezza, con taschino e fondo dritto. Lavaggio in lavatrice a freddo.'},
    {'en': 'Halden oxford shirt', 'fr': 'Chemise oxford Halden', 'de': 'Halden Oxfordhemd', 'it': 'Camicia oxford Halden'},
    {'en': 'A button-down oxford in brushed organic cotton, cut slim through the body. A 150 g oxford cloth with a soft roll collar and a locker loop. Machine wash warm.',
     'fr': 'Une chemise oxford à col boutonné, en coton biologique gratté, ajustée au corps. Un tissu oxford de 150 g avec un col souple qui roule et une patte au dos. Lavage en machine à chaud.',
     'de': 'Ein Button-down-Oxford aus gebürsteter Biobaumwolle, schmal geschnitten. Ein 150-g-Oxfordstoff mit weichem Rollkragen und Aufhängeschlaufe. Warm in der Maschine waschen.',
     'it': 'Una camicia oxford con collo button-down, in cotone biologico spazzolato, tagliata aderente. Un tessuto oxford da 150 g con collo morbido che si arrotola e asola sul retro. Lavaggio in lavatrice a caldo.'},
    {'en': 'Bruma Sol camp shirt', 'fr': 'Chemise camp Bruma Sol', 'de': 'Bruma Sol Campshirt', 'it': 'Camicia camp Bruma Sol'},
    {'en': 'A short-sleeved camp collar shirt in a woven cotton, with a straight hem. A loose fit in a light woven cotton with a single chest pocket. Machine wash cold.',
     'fr': 'Une chemise à col camp et manches courtes, en coton tissé, avec un bas droit. Une coupe ample dans un coton tissé léger, avec une seule poche poitrine. Lavage en machine à froid.',
     'de': 'Ein kurzärmeliges Hemd mit Campkragen aus gewebter Baumwolle und geradem Saum. Eine lockere Passform in leichter Webbaumwolle mit einer Brusttasche. Kalt in der Maschine waschen.',
     'it': 'Una camicia a maniche corte con collo camp, in cotone tessuto e fondo dritto. Vestibilità ampia in un cotone leggero, con un solo taschino. Lavaggio in lavatrice a freddo.'},
    {'en': 'Fjordline flannel shirt', 'fr': 'Chemise en flanelle Fjordline', 'de': 'Fjordline Flanellhemd', 'it': 'Camicia di flanella Fjordline'},
    {'en': 'A brushed flannel overshirt in a muted check, with two chest pockets. Heavy brushed cotton with a rounded hem, cut to wear open over a tee. Machine wash cold.',
     'fr': 'Une surchemise en flanelle grattée à carreaux discrets, avec deux poches poitrine. Un coton gratté épais au bas arrondi, coupé pour se porter ouvert sur un t-shirt. Lavage en machine à froid.',
     'de': 'Ein Overshirt aus gebürstetem Flanell in gedecktem Karo, mit zwei Brusttaschen. Schwere gebürstete Baumwolle mit rundem Saum, zum offenen Tragen über einem Shirt. Kalt in der Maschine waschen.',
     'it': 'Una sovracamicia di flanella spazzolata a quadri discreti, con due taschini. Cotone spazzolato pesante con fondo arrotondato, pensata per stare aperta su una t-shirt. Lavaggio in lavatrice a freddo.'},
    {'en': 'Harbour crew tee', 'fr': 'T-shirt col rond Harbour', 'de': 'Harbour Rundhalsshirt', 'it': 'T-shirt girocollo Harbour'},
    {'en': 'A heavyweight organic cotton tee with a ribbed crew neck. Buy two. A 220 g jersey with a rib neck that keeps its shape. It shrinks a touch on the first wash, then stays put.',
     'fr': "Un t-shirt épais en coton biologique, col rond côtelé. Prenez-en deux. Un jersey de 220 g dont l'encolure côtelée garde sa forme. Il rétrécit un peu au premier lavage, puis ne bouge plus.",
     'de': 'Ein schweres Shirt aus Biobaumwolle mit geripptem Rundhals. Kauf zwei davon. Ein 220-g-Jersey, dessen Rippkragen die Form hält. Es geht bei der ersten Wäsche etwas ein und bleibt danach so.',
     'it': 'Una t-shirt pesante in cotone biologico con girocollo a coste. Prendine due. Una jersey da 220 g con collo a coste che tiene la forma. Si ritira un poco al primo lavaggio, poi resta così.'},
    {'en': 'Meridian pique polo', 'fr': 'Polo piqué Meridian', 'de': 'Meridian Piqué-Polo', 'it': 'Polo in piqué Meridian'},
    {'en': 'A pique polo with a two-button placket, cut from long-staple cotton. A fine pique that breathes, with a rib collar and a straight hem. Machine wash cold.',
     'fr': 'Un polo en piqué à patte deux boutons, coupé dans un coton à fibres longues. Un piqué fin qui respire, avec un col côtelé et un bas droit. Lavage en machine à froid.',
     'de': 'Ein Piqué-Polo mit Zweiknopfleiste aus langstapeliger Baumwolle. Ein feines Piqué, das atmet, mit Rippkragen und geradem Saum. Kalt in der Maschine waschen.',
     'it': 'Una polo in piqué con cannoncino a due bottoni, in cotone a fibra lunga. Un piqué fine che respira, con collo a coste e fondo dritto. Lavaggio in lavatrice a freddo.'},
    {'en': 'Nordlys merino crew', 'fr': 'Pull col rond mérinos Nordlys', 'de': 'Nordlys Merino-Rundhals', 'it': 'Maglia girocollo in merino Nordlys'},
    {'en': 'A fine-gauge merino crew neck that layers under a jacket without bulk. Extra fine merino at 19 microns, so it does not itch. Hand wash or wool cycle.',
     'fr': 'Un pull col rond en mérinos fin qui se porte sous une veste sans épaisseur. Un mérinos extra-fin de 19 microns, qui ne gratte pas. Lavage à la main ou cycle laine.',
     'de': 'Ein feiner Merino-Rundhalspullover, der unter der Jacke nicht aufträgt. Extrafeines Merino mit 19 Mikron, das nicht kratzt. Handwäsche oder Wollprogramm.',
     'it': 'Una maglia girocollo in merino fine che sta sotto una giacca senza fare volume. Merino extrafine da 19 micron, quindi non punge. Lavaggio a mano o programma lana.'},
    {'en': 'Nordlys shawl cardigan', 'fr': 'Cardigan col châle Nordlys', 'de': 'Nordlys Schalkragenjacke', 'it': 'Cardigan con collo a scialle Nordlys'},
    {'en': 'A chunky shawl-collar cardigan in a wool and alpaca blend, with horn buttons. A heavy five-gauge knit with a shawl collar and two patch pockets. Hand wash or wool cycle.',
     'fr': 'Un gros cardigan à col châle en mélange laine et alpaga, avec des boutons en corne. Une maille lourde de jauge cinq, col châle et deux poches plaquées. Lavage à la main ou cycle laine.',
     'de': 'Eine dicke Strickjacke mit Schalkragen aus Wolle und Alpaka, mit Hornknöpfen. Ein schwerer Strick in Feinheit fünf, mit Schalkragen und zwei aufgesetzten Taschen. Handwäsche oder Wollprogramm.',
     'it': 'Un cardigan pesante con collo a scialle in misto lana e alpaca, con bottoni in corno. Una maglia grossa di finezza cinque, collo a scialle e due tasche applicate. Lavaggio a mano o programma lana.'},
    {'en': 'Coast waffle henley', 'fr': "Henley nid-d'abeille Coast", 'de': 'Coast Waffel-Henley', 'it': "Henley a nido d'ape Coast"},
    {'en': 'A long-sleeved waffle knit henley with a three-button placket. Thermal waffle cotton that traps warmth without weight. Machine wash warm.',
     'fr': "Un henley à manches longues en maille nid-d'abeille, patte à trois boutons. Un coton gaufré thermique qui retient la chaleur sans peser. Lavage en machine à chaud.",
     'de': 'Ein langärmeliger Henley aus Waffelstrick mit Dreiknopfleiste. Thermische Waffelbaumwolle, die Wärme hält, ohne aufzutragen. Warm in der Maschine waschen.',
     'it': "Una henley a maniche lunghe in maglia a nido d'ape, con cannoncino a tre bottoni. Cotone waffle termico che trattiene il calore senza pesare. Lavaggio in lavatrice a caldo."},
    {'en': 'Coast chinos', 'fr': 'Chino Coast', 'de': 'Coast Chino', 'it': 'Chino Coast'},
    {'en': 'Garment-dyed cotton twill chinos with a tapered leg and a touch of stretch. A 280 g twill, garment dyed and washed for a soft hand. Machine wash cold.',
     'fr': "Un chino en sergé de coton teint en pièce, jambe fuselée et une pointe d'élasthanne. Un sergé de 280 g, teint et lavé après confection pour un toucher doux. Lavage en machine à froid.",
     'de': 'Ein Chino aus stückgefärbtem Baumwolltwill mit schmal zulaufendem Bein und etwas Stretch. Ein 280-g-Twill, stückgefärbt und gewaschen für einen weichen Griff. Kalt in der Maschine waschen.',
     'it': 'Un chino in twill di cotone tinto in capo, con gamba affusolata e un pizzico di elastico. Un twill da 280 g, tinto e lavato in capo per una mano morbida. Lavaggio in lavatrice a freddo.'},
    {'en': 'Fjordline selvedge jeans', 'fr': 'Jean selvedge Fjordline', 'de': 'Fjordline Selvedge Jeans', 'it': 'Jeans selvedge Fjordline'},
    {'en': 'Raw selvedge denim with a regular fit and a straight leg. Wear them in. A 14 oz Japanese selvedge with a button fly and a red line on the outseam. Wash rarely and cold.',
     'fr': 'Un denim selvedge brut, coupe droite et jambe droite. À vous de le façonner. Un selvedge japonais de 14 oz, braguette à boutons et liseré rouge sur la couture extérieure. Lavez-le rarement et à froid.',
     'de': 'Roher Selvedge-Denim in normaler Passform mit geradem Bein. Trag ihn ein. Ein japanischer 14-oz-Selvedge mit Knopfleiste und roter Linie an der Außennaht. Selten und kalt waschen.',
     'it': "Denim selvedge grezzo, vestibilità regolare e gamba dritta. Falli tuoi con l'uso. Un selvedge giapponese da 14 oz con patta a bottoni e cimosa rossa sulla cucitura esterna. Lavare di rado e a freddo."},
    {'en': 'Sand linen trousers', 'fr': 'Pantalon en lin Sand', 'de': 'Sand Leinenhose', 'it': 'Pantaloni di lino Sand'},
    {'en': 'Drawstring linen trousers with a relaxed leg. Airport to beach without a change. An elastic and drawstring waist with a relaxed leg and a cropped hem. Machine wash cold.',
     'fr': "Un pantalon en lin à cordon de serrage, jambe décontractée. De l'aéroport à la plage sans se changer. Une taille élastique à cordon, une jambe ample et un bas raccourci. Lavage en machine à froid.",
     'de': 'Eine Leinenhose mit Kordelzug und lockerem Bein. Vom Flughafen an den Strand ohne Umziehen. Ein Gummibund mit Kordel, ein lockeres Bein und ein verkürzter Saum. Kalt in der Maschine waschen.',
     'it': "Pantaloni di lino con coulisse e gamba morbida. Dall'aeroporto alla spiaggia senza cambiarsi. Vita elastica con coulisse, gamba comoda e fondo accorciato. Lavaggio in lavatrice a freddo."},
    {'en': 'Harbour cargo shorts', 'fr': 'Short cargo Harbour', 'de': 'Harbour Cargoshorts', 'it': 'Shorts cargo Harbour'},
    {'en': 'Ripstop cotton cargo shorts with bellows pockets and a nine-inch inseam. A 200 g ripstop with two front pockets, two bellows pockets and a rear pocket. Machine wash cold.',
     'fr': 'Un short cargo en coton ripstop, poches à soufflet et entrejambe de vingt-trois centimètres. Un ripstop de 200 g avec deux poches devant, deux poches à soufflet et une poche arrière. Lavage en machine à froid.',
     'de': 'Cargoshorts aus Ripstop-Baumwolle mit Balgtaschen und 23 Zentimetern Innenbeinlänge. Ein 200-g-Ripstop mit zwei Vordertaschen, zwei Balgtaschen und einer Gesäßtasche. Kalt in der Maschine waschen.',
     'it': 'Shorts cargo in cotone ripstop, con tasche a soffietto e cavallo di ventitré centimetri. Un ripstop da 200 g con due tasche davanti, due a soffietto e una dietro. Lavaggio in lavatrice a freddo.'},
    {'en': 'Ashford linen blazer', 'fr': 'Veste en lin Ashford', 'de': 'Ashford Leinenblazer', 'it': 'Giacca di lino Ashford'},
    {'en': 'An unstructured linen blazer with patch pockets and a half lining. Creases are part of the look. No shoulder pads, a single vent and a half lining in cotton. Dry clean or steam.',
     'fr': 'Une veste en lin déstructurée, poches plaquées et demi-doublure. Les plis font partie du style. Sans épaulettes, une fente au dos et une demi-doublure en coton. Nettoyage à sec ou vapeur.',
     'de': 'Ein unkonstruierter Leinenblazer mit aufgesetzten Taschen und Halbfutter. Knitter gehören dazu. Ohne Schulterpolster, mit einem Rückenschlitz und Halbfutter aus Baumwolle. Chemisch reinigen oder dämpfen.',
     'it': 'Una giacca di lino destrutturata, con tasche applicate e mezza fodera. Le pieghe fanno parte del look. Senza spalline, con uno spacco dietro e mezza fodera in cotone. Lavaggio a secco o vapore.'},
    {'en': 'Nordlys knit blazer', 'fr': 'Veste en maille Nordlys', 'de': 'Nordlys Strickblazer', 'it': 'Giacca in maglia Nordlys'},
    {'en': 'A jersey knit blazer in merino wool that moves like a cardigan and looks like a jacket. A milano-stitch merino with patch pockets and no lining. Hand wash or wool cycle.',
     'fr': 'Une veste en maille de mérinos qui bouge comme un cardigan et se porte comme une veste. Un mérinos point milano, poches plaquées et sans doublure. Lavage à la main ou cycle laine.',
     'de': 'Ein Strickblazer aus Merinowolle, der sich wie eine Strickjacke bewegt und wie ein Sakko aussieht. Ein Merino im Milanostich mit aufgesetzten Taschen und ohne Futter. Handwäsche oder Wollprogramm.',
     'it': 'Una giacca in maglia di merino che si muove come un cardigan e sembra una giacca. Un merino a punto milano con tasche applicate e senza fodera. Lavaggio a mano o programma lana.'},
    {'en': 'Halden field jacket', 'fr': 'Veste de terrain Halden', 'de': 'Halden Fieldjacket', 'it': 'Giacca field Halden'},
    {'en': 'A four-pocket field jacket in waxed cotton with a corduroy collar. Waxed cotton that sheds rain and darkens with age. Re-wax it once a year and it lasts decades.',
     'fr': 'Une veste de terrain à quatre poches en coton huilé, col en velours côtelé. Un coton huilé qui repousse la pluie et fonce avec le temps. Réhuilez-la une fois par an et elle dure des décennies.',
     'de': 'Eine Fieldjacket mit vier Taschen aus gewachster Baumwolle und Cordkragen. Gewachste Baumwolle, die Regen abweist und mit den Jahren nachdunkelt. Einmal im Jahr nachwachsen und sie hält Jahrzehnte.',
     'it': "Una giacca field a quattro tasche in cotone cerato, con collo in velluto a coste. Cotone cerato che respinge la pioggia e si scurisce con gli anni. Ricera una volta l'anno e dura decenni."},
    {'en': 'Ottavia round sunglasses', 'fr': 'Lunettes de soleil rondes Ottavia', 'de': 'Ottavia Sonnenbrille, rund', 'it': 'Occhiali da sole tondi Ottavia'},
    {'en': 'Round acetate sunglasses with polarised lenses and a keyhole bridge. Hand-polished acetate with five-barrel hinges and category three lenses. A hard case and a cloth are included.',
     'fr': 'Des lunettes de soleil rondes en acétate, verres polarisés et pont en trou de serrure. Un acétate poli à la main, charnières à cinq tenons et verres de catégorie trois. Un étui rigide et un chiffon sont inclus.',
     'de': 'Eine runde Sonnenbrille aus Acetat mit polarisierten Gläsern und Keyhole-Steg. Handpoliertes Acetat mit Fünfnietscharnieren und Gläsern der Kategorie drei. Hartschalenetui und Tuch liegen bei.',
     'it': 'Occhiali da sole tondi in acetato, con lenti polarizzate e ponte a goccia. Acetato lucidato a mano, cerniere a cinque perni e lenti di categoria tre. Custodia rigida e panno inclusi.'},
    {'en': 'Ottavia aviator sunglasses', 'fr': 'Lunettes de soleil aviateur Ottavia', 'de': 'Ottavia Pilotenbrille', 'it': 'Occhiali da sole aviator Ottavia'},
    {'en': 'Slim steel aviators with green glass lenses and a double bridge. Steel frames with adjustable nose pads and mineral glass lenses. A hard case and a cloth are included.',
     'fr': 'Des lunettes aviateur fines en acier, verres minéraux verts et double pont. Une monture en acier avec plaquettes réglables et verres en verre minéral. Un étui rigide et un chiffon sont inclus.',
     'de': 'Eine schmale Pilotenbrille aus Stahl mit grünen Glasgläsern und Doppelsteg. Stahlfassung mit verstellbaren Nasenpads und mineralischen Gläsern. Hartschalenetui und Tuch liegen bei.',
     'it': 'Occhiali aviator sottili in acciaio, con lenti in vetro verde e doppio ponte. Montatura in acciaio con naselli regolabili e lenti minerali. Custodia rigida e panno inclusi.'},
    {'en': 'Ottavia square sunglasses', 'fr': 'Lunettes de soleil carrées Ottavia', 'de': 'Ottavia Sonnenbrille, eckig', 'it': 'Occhiali da sole quadrati Ottavia'},
    {'en': 'Bold square sunglasses in polished acetate with grey gradient lenses. Thick acetate frames with a keyhole bridge and category three lenses. A hard case and a cloth are included.',
     'fr': 'Des lunettes de soleil carrées affirmées en acétate poli, verres gris dégradés. Une monture épaisse en acétate avec un pont en trou de serrure et des verres de catégorie trois. Un étui rigide et un chiffon sont inclus.',
     'de': 'Eine markante eckige Sonnenbrille aus poliertem Acetat mit grauen Verlaufsgläsern. Dicke Acetatfassung mit Keyhole-Steg und Gläsern der Kategorie drei. Hartschalenetui und Tuch liegen bei.',
     'it': 'Occhiali da sole quadrati e decisi in acetato lucido, con lenti grigie sfumate. Montatura spessa in acetato con ponte a goccia e lenti di categoria tre. Custodia rigida e panno inclusi.'},
    {'en': 'Ottavia reading glasses', 'fr': 'Lunettes de lecture Ottavia', 'de': 'Ottavia Lesebrille', 'it': 'Occhiali da lettura Ottavia'},
    {'en': 'Lightweight reading glasses in a panto shape, with a cloth case. Available from +1.0 to +3.0 in half steps. The lenses are scratch coated.',
     'fr': 'Des lunettes de lecture légères de forme panto, avec un étui en tissu. Disponibles de +1,0 à +3,0 par demi-degrés. Les verres reçoivent un traitement anti-rayures.',
     'de': 'Eine leichte Lesebrille in Panto-Form, mit Stoffetui. Erhältlich von +1,0 bis +3,0 in halben Schritten. Die Gläser sind kratzfest beschichtet.',
     'it': 'Occhiali da lettura leggeri di forma panto, con custodia in tessuto. Disponibili da +1,0 a +3,0 a mezzi passi. Le lenti hanno un trattamento antigraffio.'},
    {'en': 'Meridian curb chain', 'fr': 'Chaîne gourmette Meridian', 'de': 'Meridian Panzerkette', 'it': 'Catena grumette Meridian'},
    {'en': 'A slim curb chain in gold-plated sterling silver, 45 cm. A 3 mm curb link with a lobster clasp, plated in 18 karat gold. Wear it alone or under a shirt.',
     'fr': 'Une fine chaîne gourmette en argent massif plaqué or, 45 cm. Une maille gourmette de 3 mm avec un fermoir mousqueton, plaquée or 18 carats. À porter seule ou sous une chemise.',
     'de': 'Eine schmale Panzerkette aus vergoldetem Sterlingsilber, 45 cm. Ein 3-mm-Panzerglied mit Karabinerverschluss, vergoldet mit 18 Karat. Allein oder unter dem Hemd zu tragen.',
     'it': 'Una catena grumette sottile in argento sterling dorato, 45 cm. Maglia grumette da 3 mm con chiusura a moschettone, placcata in oro 18 carati. Da portare da sola o sotto la camicia.'},
    {'en': 'Halden signet ring', 'fr': 'Chevalière Halden', 'de': 'Halden Siegelring', 'it': 'Anello chevalier Halden'},
    {'en': 'A square signet ring in solid sterling silver, plain face for engraving. A 12 mm square face, polished, on a solid band. Engraving is free and takes three days.',
     'fr': 'Une chevalière carrée en argent massif, plateau lisse à graver. Un plateau carré de 12 mm, poli, sur un anneau plein. La gravure est offerte et prend trois jours.',
     'de': 'Ein eckiger Siegelring aus massivem Sterlingsilber, mit glatter Platte zum Gravieren. Eine 12-mm-Quadratplatte, poliert, auf einem massiven Ring. Die Gravur ist kostenlos und dauert drei Tage.',
     'it': "Un anello chevalier quadrato in argento sterling massiccio, con piano liscio da incidere. Piano quadrato da 12 mm, lucido, su una fascia piena. L'incisione è gratuita e richiede tre giorni."},
    {'en': 'Bruma Sol hoops', 'fr': 'Créoles Bruma Sol', 'de': 'Bruma Sol Creolen', 'it': 'Cerchi Bruma Sol'},
    {'en': 'Medium hammered hoop earrings in gold-plated brass. Thirty millimetre hoops with a hinged closure, plated in 18 karat gold. Sold as a pair.',
     'fr': 'Des créoles moyennes martelées en laiton plaqué or. Des anneaux de trente millimètres à fermeture à charnière, plaqués or 18 carats. Vendues par paire.',
     'de': 'Mittelgroße gehämmerte Creolen aus vergoldetem Messing. Dreißig Millimeter Durchmesser, mit Scharnierverschluss, vergoldet mit 18 Karat. Als Paar verkauft.',
     'it': 'Cerchi medi martellati in ottone dorato. Cerchi da trenta millimetri con chiusura a cerniera, placcati in oro 18 carati. Venduti in coppia.'},
    {'en': 'Coast rope bracelet', 'fr': 'Bracelet corde Coast', 'de': 'Coast Segeltau-Armband', 'it': 'Bracciale in corda Coast'},
    {'en': 'A braided nylon rope bracelet with a stainless steel shackle clasp. Nylon rope from a sailmaker, with a shackle that opens with a coin. One size, adjusts with the knot.',
     'fr': "Un bracelet en corde de nylon tressée avec une manille en acier inoxydable. Une corde de nylon de voilier, avec une manille qui s'ouvre avec une pièce. Taille unique, réglable par le nœud.",
     'de': 'Ein Armband aus geflochtenem Nylonseil mit Schäkelverschluss aus Edelstahl. Nylonseil vom Segelmacher, mit einem Schäkel, der sich mit einer Münze öffnet. Eine Größe, über den Knoten verstellbar.',
     'it': 'Un bracciale in corda di nylon intrecciata con grillo in acciaio inossidabile. Corda di nylon da velaio, con un grillo che si apre con una moneta. Taglia unica, si regola con il nodo.'},
    {'en': 'Halden leather sandals', 'fr': 'Sandales en cuir Halden', 'de': 'Halden Ledersandalen', 'it': 'Sandali di pelle Halden'},
    {'en': 'Flat leather sandals with two straps and a moulded footbed. Vegetable-tanned leather uppers on a cork footbed with a rubber sole. They mould to the foot in a week.',
     'fr': 'Des sandales plates en cuir à deux brides, avec une semelle moulée. Une tige en cuir à tannage végétal sur un lit de liège et une semelle en caoutchouc. Elles épousent le pied en une semaine.',
     'de': 'Flache Ledersandalen mit zwei Riemen und geformtem Fußbett. Pflanzlich gegerbtes Obermaterial auf einem Korkfußbett mit Gummisohle. Sie passen sich in einer Woche dem Fuß an.',
     'it': 'Sandali bassi in pelle a due fasce, con plantare sagomato. Tomaia in pelle conciata al vegetale su plantare di sughero e suola in gomma. Si adattano al piede in una settimana.'},
    {'en': 'Harbour canvas sneakers', 'fr': 'Baskets en toile Harbour', 'de': 'Harbour Canvas-Sneaker', 'it': 'Sneaker di tela Harbour'},
    {'en': 'Low canvas sneakers with a natural rubber sole and cotton laces. Heavy cotton canvas on a vulcanised natural rubber sole. Wipe clean, or machine wash cold in a bag.',
     'fr': 'Des baskets basses en toile, semelle en caoutchouc naturel et lacets en coton. Une toile de coton épaisse sur une semelle vulcanisée en caoutchouc naturel. Un coup de chiffon, ou lavage en machine à froid dans un filet.',
     'de': 'Niedrige Canvas-Sneaker mit Naturkautschuksohle und Baumwollschnürsenkeln. Schweres Baumwollcanvas auf einer vulkanisierten Naturkautschuksohle. Abwischen oder kalt im Beutel in der Maschine waschen.',
     'it': 'Sneaker basse di tela, con suola in caucciù naturale e lacci di cotone. Tela di cotone pesante su una suola vulcanizzata in caucciù naturale. Si puliscono con un panno, oppure in lavatrice a freddo dentro un sacchetto.'},
    {'en': 'Halden penny loafers', 'fr': 'Mocassins Halden', 'de': 'Halden Pennyloafer', 'it': 'Mocassini Halden'},
    {'en': 'Penny loafers in full-grain leather with a stacked heel. Full-grain leather, a leather sole with a rubber insert and a stacked leather heel. Made in Portugal.',
     'fr': 'Des mocassins en cuir pleine fleur avec un talon empilé. Cuir pleine fleur, semelle en cuir avec insert en caoutchouc et talon en cuir empilé. Fabriqués au Portugal.',
     'de': 'Pennyloafer aus Vollnarbenleder mit gestapeltem Absatz. Vollnarbenleder, eine Ledersohle mit Gummieinsatz und ein gestapelter Lederabsatz. In Portugal gefertigt.',
     'it': 'Mocassini in pelle pieno fiore con tacco accatastato. Pelle pieno fiore, suola in cuoio con inserto in gomma e tacco in cuoio accatastato. Prodotti in Portogallo.'},
    {'en': 'Bruma Sol espadrilles', 'fr': 'Espadrilles Bruma Sol', 'de': 'Bruma Sol Espadrilles', 'it': 'Espadrillas Bruma Sol'},
    {'en': 'Canvas espadrilles with a jute sole, made in Spain. Cotton canvas stitched by hand to a jute sole with a thin rubber tread. Buy them snug, they stretch.',
     'fr': 'Des espadrilles en toile à semelle de jute, fabriquées en Espagne. Une toile de coton cousue à la main sur une semelle de jute avec une fine bande de caoutchouc. Prenez-les serrées, elles se détendent.',
     'de': 'Espadrilles aus Canvas mit Jutesohle, in Spanien gefertigt. Baumwollcanvas, von Hand auf eine Jutesohle mit dünner Gummilaufsohle genäht. Eng kaufen, sie weiten sich.',
     'it': 'Espadrillas di tela con suola in juta, prodotte in Spagna. Tela di cotone cucita a mano su una suola di juta con sottile battistrada in gomma. Prendile strette, si allargano.'},
    {'en': 'Fjordline chelsea boots', 'fr': 'Bottines chelsea Fjordline', 'de': 'Fjordline Chelsea Boots', 'it': 'Stivaletti chelsea Fjordline'},
    {'en': 'Suede chelsea boots with a crepe sole and elastic side panels. Suede uppers on a crepe sole that softens every step. Spray them before the first wear.',
     'fr': 'Des bottines chelsea en daim, semelle en crêpe et soufflets élastiques. Une tige en daim sur une semelle de crêpe qui adoucit chaque pas. Imperméabilisez-les avant le premier port.',
     'de': 'Chelsea Boots aus Veloursleder mit Kreppsohle und elastischen Seiteneinsätzen. Velours-Obermaterial auf einer Kreppsohle, die jeden Schritt weicher macht. Vor dem ersten Tragen imprägnieren.',
     'it': 'Stivaletti chelsea in camoscio, con suola in crepe ed elastici laterali. Tomaia in camoscio su una suola in crepe che ammorbidisce ogni passo. Trattali con lo spray prima di indossarli.'},
    {'en': 'Halden leather weekender', 'fr': 'Sac week-end en cuir Halden', 'de': 'Halden Leder-Reisetasche', 'it': 'Borsone di pelle Halden'},
    {'en': 'A full-grain leather weekender with a brass zip and a detachable strap. Fits under the seat. Fifty centimetres wide with a cotton lining and an inside zip pocket. The leather scuffs and darkens with age.',
     'fr': 'Un sac week-end en cuir pleine fleur, fermeture en laiton et bandoulière amovible. Il passe sous le siège. Cinquante centimètres de large, doublure en coton et poche zippée intérieure. Le cuir se patine et fonce avec le temps.',
     'de': 'Eine Reisetasche aus Vollnarbenleder mit Messingreißverschluss und abnehmbarem Gurt. Passt unter den Sitz. Fünfzig Zentimeter breit, mit Baumwollfutter und Innenreißverschlusstasche. Das Leder bekommt Spuren und dunkelt nach.',
     'it': 'Un borsone in pelle pieno fiore, con zip in ottone e tracolla staccabile. Entra sotto il sedile. Cinquanta centimetri di larghezza, fodera in cotone e tasca interna con zip. La pelle si segna e si scurisce con gli anni.'},
    {'en': 'Meridian crossbody bag', 'fr': 'Sac bandoulière Meridian', 'de': 'Meridian Umhängetasche', 'it': 'Borsa a tracolla Meridian'},
    {'en': 'A compact leather crossbody bag with a flap and an adjustable strap. Full-grain leather with a magnetic flap and a card slot inside. The strap adjusts from 100 to 130 cm.',
     'fr': "Un petit sac bandoulière en cuir avec un rabat et une sangle réglable. Cuir pleine fleur, rabat aimanté et un porte-carte à l'intérieur. La sangle se règle de 100 à 130 cm.",
     'de': 'Eine kompakte Umhängetasche aus Leder mit Überschlag und verstellbarem Gurt. Vollnarbenleder mit Magnetlasche und einem Kartenfach innen. Der Gurt lässt sich von 100 auf 130 cm einstellen.',
     'it': "Una piccola borsa a tracolla in pelle, con patta e tracolla regolabile. Pelle pieno fiore, patta magnetica e uno scomparto per le carte all'interno. La tracolla si regola da 100 a 130 cm."},
    {'en': 'Harbour canvas tote', 'fr': 'Tote bag en toile Harbour', 'de': 'Harbour Canvas-Shopper', 'it': 'Shopper di tela Harbour'},
    {'en': 'A heavy canvas tote with leather handles and an inside pocket. A 20 oz canvas that stands on its own, with a magnetic closure. Machine wash cold, the leather handles included.',
     'fr': 'Un tote bag en toile épaisse avec des anses en cuir et une poche intérieure. Une toile de 20 oz qui tient debout toute seule, avec une fermeture aimantée. Lavage en machine à froid, anses en cuir comprises.',
     'de': 'Ein schwerer Canvas-Shopper mit Ledergriffen und Innentasche. Ein 20-oz-Canvas, das von allein steht, mit Magnetverschluss. Kalt in der Maschine waschen, samt Ledergriffen.',
     'it': 'Uno shopper in tela pesante con manici di pelle e tasca interna. Una tela da 20 oz che sta in piedi da sola, con chiusura magnetica. Lavaggio in lavatrice a freddo, manici di pelle compresi.'},
    {'en': 'Fjordline cabin case', 'fr': 'Valise cabine Fjordline', 'de': 'Fjordline Kabinenkoffer', 'it': 'Trolley da cabina Fjordline'},
    {'en': 'A hard-shell cabin case in recycled polycarbonate with silent wheels and a TSA lock. Fifty-five by thirty-five by twenty centimetres, 2.8 kg, with four double wheels. The shell dents and pops back.',
     'fr': 'Une valise cabine rigide en polycarbonate recyclé, roues silencieuses et serrure TSA. Cinquante-cinq sur trente-cinq sur vingt centimètres, 2,8 kg, avec quatre roues doubles. La coque se creuse puis reprend sa forme.',
     'de': 'Ein Hartschalen-Kabinenkoffer aus recyceltem Polycarbonat mit leisen Rollen und TSA-Schloss. Fünfundfünfzig mal fünfunddreißig mal zwanzig Zentimeter, 2,8 kg, mit vier Doppelrollen. Die Schale gibt nach und springt zurück.',
     'it': 'Un trolley da cabina rigido in policarbonato riciclato, con ruote silenziose e serratura TSA. Cinquantacinque per trentacinque per venti centimetri, 2,8 kg, con quattro ruote doppie. Il guscio si ammacca e torna come prima.'},
    {'en': 'Coast daypack', 'fr': 'Sac à dos Coast', 'de': 'Coast Tagesrucksack', 'it': 'Zaino da giorno Coast'},
    {'en': 'A 20-litre daypack in recycled nylon with a padded laptop sleeve. A padded back, a fifteen-inch laptop sleeve and a water bottle pocket. The fabric is made from recycled bottles.',
     'fr': 'Un sac à dos de 20 litres en nylon recyclé, avec un compartiment matelassé pour ordinateur. Un dos matelassé, une housse pour portable de quinze pouces et une poche pour gourde. Le tissu est fait de bouteilles recyclées.',
     'de': 'Ein 20-Liter-Tagesrucksack aus recyceltem Nylon mit gepolstertem Laptopfach. Ein gepolsterter Rücken, ein Fach für fünfzehn Zoll und eine Flaschentasche. Der Stoff besteht aus recycelten Flaschen.',
     'it': 'Uno zaino da 20 litri in nylon riciclato, con scomparto imbottito per il portatile. Schienale imbottito, tasca per portatili da quindici pollici e porta borraccia. Il tessuto è fatto di bottiglie riciclate.'},
]
