CODE = 'garden'; ROOT = 'Garden'; STORE_NAME = 'Greenhaven'; ATTRIBUTE_SET = 'Garden'; WEIGHT = 2
ATTRIBUTE_COLUMNS = ['light', 'hardiness', 'pot_size', 'material', 'dimensions']
ATTRIBUTES = [
    dict(code='light', label='Light', input='select', scope='global', filterable=1, filterable_in_search=1, visible_on_front=1, used_in_product_listing=1, sets='Garden', group='General', sort_order=50),
    dict(code='hardiness', label='Hardiness', input='select', scope='global', filterable=1, visible_on_front=1, comparable=1, sets='Garden', group='General', sort_order=60),
    dict(code='pot_size', label='Pot size', input='select', scope='global', filterable=1, visible_on_front=1, is_configurable=1, sets='Garden', group='General', sort_order=70),
]
OPTIONS = {'light': ['Full sun', 'Part shade', 'Shade', 'Indoor bright', 'Indoor low'], 'hardiness': ['Hardy', 'Half hardy', 'Tender', 'Indoor'], 'pot_size': ['9 cm', '12 cm', '17 cm', '21 cm', '30 cm']}
ROOT_DESCRIPTION = 'Plants, seeds, pots and tools from a nursery that grows what it sells.'
META_DESCRIPTION = 'Greenhaven: houseplants, outdoor plants, seeds, pots, tools and garden furniture from our own nursery.'
PRODUCT_STYLE = 'Studio product photograph of a single plant or garden product on a plain white seamless background, natural daylight, no people, no text, no lettering, no logos, no watermark, centered with margin around it.'
SCENE_STYLE = 'Lush editorial garden photograph, greenhouse glass, terracotta, morning dew, warm sunlight through leaves, no people, no readable text, no lettering, no logos, no watermark.'
SCENES = {
    'hero-main': 'A sunlit greenhouse full of potted plants on wooden benches, terracotta pots and a watering can, morning light through the glass.',
    'hero-side': 'A close up of hands potting a fern into a terracotta pot with dark compost.',
    'editorial': 'Rows of young plants in a nursery polytunnel with a gardener watering, seen from the side.',
    'about': 'A small plant nursery with a glasshouse, potting benches and stacks of terracotta pots.',
}
CATEGORIES = [
    dict(path='houseplants', name='Houseplants', description='Grown in our glasshouse, shipped with roots intact.', landing_title='Grown here, not shipped through', landing_text='Every houseplant spends a month in our glasshouse before it leaves. We say which window it wants.', scene='A group of houseplants in terracotta pots on a windowsill in morning light.'),
    dict(path='outdoor-plants', name='Outdoor Plants', description='Perennials, shrubs and trees for beds and pots.', landing_title='For beds, borders and balconies', landing_text='Hardy perennials, small trees and shrubs, sold in the season they should be planted.', scene='A border of lavender and grasses in a sunny garden with a gravel path.'),
    dict(path='seeds', name='Seeds & Bulbs', description='Open-pollinated seed and bulbs by the dozen.', landing_title='Sow, wait, eat', landing_text='Open-pollinated vegetable and flower seed, saved on our own beds, and bulbs sold by the dozen.', scene='Seed packets, a wooden dibber and a tray of seedlings on a potting bench.'),
    dict(path='pots', name='Pots & Planters', description='Terracotta, stoneware and zinc.', landing_title='Something to grow in', landing_text='Frost-proof terracotta, glazed stoneware and zinc planters, with the drainage holes already there.', scene='A stack of terracotta pots of different sizes on a stone floor in sunlight.'),
    dict(path='tools', name='Tools', description='Forged tools with ash handles, sharpened before shipping.', landing_title='Sharp on arrival', landing_text='Forged steel heads on ash handles. Every tool is sharpened before it ships.', scene='A row of garden tools with wooden handles hanging on a shed wall.'),
    dict(path='furniture', name='Outdoor Furniture', description='Benches, tables and chairs in oak and steel.', landing_title='Sit in the garden', landing_text='Oak benches, folding steel chairs and a table that stays out all winter.', scene='An oak garden bench under a tree with dappled sunlight and a cup of tea on the arm.'),
]
HERO = dict(badge='Spring stock', title='Grown here, shipped with care', text='Plants from our own glasshouse, seed from our own beds, and tools sharpened before they leave.')
FEATURES = [('truck', 'Plant-safe delivery', 'Boxed upright, two days'), ('plant', 'Grown by us', 'A month in the glasshouse'), ('arrow-back-up', 'Plant guarantee', 'Thirty days, replaced'), ('headset', 'Ask a grower', 'Real answers, weekdays')]
STORY = dict(title='A nursery, not a warehouse', text1='Greenhaven is a working nursery with a glasshouse, three polytunnels and a seed bed. What we sell, we grow, and the rest comes from growers we visit.', text2='Every plant page says which light it wants and what it does in winter. If it dies in thirty days, we replace it.')
PROMO = dict(badge='Season', title='Plant now', text='What to plant this month, chosen by the growers: perennials for the border and bulbs for spring.', path='outdoor-plants', button='See what to plant', list_title='In season now')
TESTIMONIALS = [('The fern arrived upright, moist and bigger than the photo. First plant that has survived my flat.', 'Elena R.', 'Manchester'), ('The spade came sharp. I did not know that was a thing.', 'Marcus T.', 'Leeds'), ('Asked which side of the balcony for the olive. They told me. It is thriving.', 'Priya S.', 'Toronto')]
NEWSLETTER = dict(title='From the glasshouse', text='A note every two weeks: what to sow, what to plant, and what came into stock.')
ABOUT = dict(title='Three polytunnels and a seed bed', paragraphs=['Greenhaven started as a market stall selling seedlings from a back garden. The back garden became a field, then a glasshouse.', 'We grow most of what we sell. The rest comes from growers within a day of the nursery, and we visit them.', 'The nursery is open on weekends. Bring a coffee and ask the growers anything.'])
REVIEWS = [
    ('Healthy and well packed', 'Arrived upright with damp compost and no broken leaves.', 5),
    ('Smaller than expected', 'Healthy plant but a smaller pot than I thought. Check the pot size.', 4),
    ('Sharp and solid', 'The tool is heavy in a good way and came sharp.', 5),
    ('Replaced without fuss', 'One plant failed. Photo sent, new one in three days.', 5),
    ('Flowered in three weeks', 'Planted it on a Sunday, first bud by month end.', 5),
    ('Terracotta is thick', 'Proper fired clay, not the thin stuff. Survived a frost.', 5),
    ('Seeds all came up', 'Twenty sown, nineteen seedlings. Cannot ask for more.', 5),
    ('Soil was dry on arrival', 'Plant bounced back after a soak, but the box sat somewhere warm.', 3),
    ('Handle fits the hand', 'Ash handle, no blisters after an afternoon of digging.', 5),
    ('Bees love it', 'Covered in bees within a week of planting.', 5),
    ('Wrong colour', 'Ordered white, got pink. Beautiful, but not what I ordered. Refund given.', 3),
    ('Hardy as promised', 'Left out all winter in a pot and it came back.', 5),
    ('Good starter set', 'Everything a first garden needs and nothing it does not.', 5),
    ('Watering can pours well', 'Long spout, fine rose, no dribble down the side.', 5),
    ('Delivery was gentle', 'The courier carried it upright. The driver deserves the credit.', 5),
    ('Herbs on the sill', 'Six pots on the kitchen sill and I have not bought parsley since.', 5),
    ('Compost smells right', 'Dark and crumbly. My tomatoes doubled in a month.', 5),
    ('Pot has no drainage hole', 'Lovely glaze but no hole. Drill it or use it indoors with gravel.', 3),
    ('Pruners cut clean', 'Bypass blades, no crushing. Roses thanked me.', 5),
    ('Bigger than the photo', 'A three year old plant, not a plug. Delighted.', 5),
    ('Label was helpful', 'Planting depth, spacing and sun on the tag. Saved a search.', 4),
    ('Gloves are tough', 'Thorns did not get through. Fit is snug.', 5),
    ('Slow to establish', 'Took a full season to settle. Now it is the best thing in the border.', 4),
    ('Bulbs came in paper', 'No plastic in the box at all. Every bulb sprouted.', 5),
    ('Trellis went up in an hour', 'Cedar, pre-drilled, and the screws were in the box.', 5),
]
def P(sku, name, cats, price, desc, prompt, **kw):
    d = dict(sku=sku, name=name, categories=cats, price=price, description=desc, prompt=prompt); d.update(kw); return d
PRODUCTS = [
    P('N-MONSTERA', 'Monstera deliciosa', ['houseplants'], 32, 'The split-leaf climber. Bright indirect light, water when the top is dry.', 'a monstera plant with split leaves in a plain terracotta pot', axis='pot_size', values=['17 cm', '21 cm', '30 cm'], attributes=dict(light='Indoor bright', hardiness='Indoor', material='Terracotta')),
    P('N-FERN', 'Boston fern', ['houseplants'], 22, 'A full fern for a bathroom or a north window. Keep it moist.', 'a lush boston fern in a terracotta pot', axis='pot_size', values=['12 cm', '17 cm'], attributes=dict(light='Indoor low', hardiness='Indoor', material='Terracotta')),
    P('N-PILEA', 'Pilea', ['houseplants'], 16, 'The pancake plant. Easy, and it makes babies to give away.', 'a pilea plant with round leaves in a small terracotta pot', attributes=dict(light='Indoor bright', hardiness='Indoor', pot_size='12 cm', material='Terracotta')),
    P('N-SNAKE-PLANT', 'Snake plant', ['houseplants'], 24, 'Survives neglect and low light. Water once a month.', 'a tall snake plant with upright striped leaves in a pot', axis='pot_size', values=['12 cm', '17 cm', '21 cm'], attributes=dict(light='Indoor low', hardiness='Indoor', material='Terracotta')),
    P('N-FICUS', 'Fiddle leaf fig', ['houseplants'], 48, 'A statement tree for a bright corner. Do not move it once it is happy.', 'a fiddle leaf fig tree with large leaves in a pot', axis='pot_size', values=['21 cm', '30 cm'], attributes=dict(light='Indoor bright', hardiness='Indoor', material='Terracotta')),
    P('N-POTHOS', 'Golden pothos', ['houseplants'], 14, 'A trailing vine for a shelf. Nearly impossible to kill.', 'a trailing golden pothos plant in a hanging pot', attributes=dict(light='Indoor low', hardiness='Indoor', pot_size='12 cm', material='Terracotta')),
    P('N-CALATHEA', 'Calathea', ['houseplants'], 26, 'Patterned leaves that fold at night. Likes humidity and soft water.', 'a calathea plant with patterned leaves in a pot', attributes=dict(light='Indoor low', hardiness='Indoor', pot_size='17 cm', material='Terracotta')),
    P('N-OLIVE-INDOOR', 'Olive tree', ['houseplants', 'outdoor-plants'], 45, 'A young olive for a sunny window or a sheltered balcony.', 'a small olive tree with silver leaves in a terracotta pot', axis='pot_size', values=['17 cm', '21 cm'], attributes=dict(light='Full sun', hardiness='Half hardy', material='Terracotta')),
    P('N-CACTUS-SET', 'Cactus trio', ['houseplants'], 20, 'Three small cacti in 6 cm pots.', 'three small cacti in tiny terracotta pots', attributes=dict(light='Indoor bright', hardiness='Indoor', pot_size='9 cm', material='Terracotta')),
    P('N-LAVENDER', 'Lavender', ['outdoor-plants'], 9, 'English lavender for sun and poor soil. Bees will find it.', 'a lavender plant in bloom in a small pot', axis='pot_size', values=['9 cm', '17 cm'], attributes=dict(light='Full sun', hardiness='Hardy', material='Terracotta')),
    P('N-ROSEMARY', 'Rosemary', ['outdoor-plants', 'seeds'], 8, 'Upright rosemary for a pot by the kitchen door.', 'a rosemary plant in a small pot', attributes=dict(light='Full sun', hardiness='Hardy', pot_size='12 cm', material='Terracotta')),
    P('N-HYDRANGEA', 'Hydrangea', ['outdoor-plants'], 24, 'A mophead hydrangea that flowers blue in acid soil and pink in lime.', 'a hydrangea shrub with blue flowers in a pot', axis='pot_size', values=['17 cm', '30 cm'], attributes=dict(light='Part shade', hardiness='Hardy', material='Terracotta')),
    P('N-JAPANESE-MAPLE', 'Japanese maple', ['outdoor-plants'], 55, 'A slow red maple for a pot or a sheltered corner.', 'a small japanese maple tree with red leaves in a pot', attributes=dict(light='Part shade', hardiness='Hardy', pot_size='30 cm', material='Terracotta')),
    P('N-GRASS', 'Fountain grass', ['outdoor-plants'], 12, 'A soft grass that moves in wind and holds its seed heads into winter.', 'a clump of ornamental fountain grass in a pot', attributes=dict(light='Full sun', hardiness='Hardy', pot_size='17 cm', material='Terracotta')),
    P('N-FERN-OUTDOOR', 'Hardy fern', ['outdoor-plants'], 14, 'A shield fern for dry shade under trees.', 'a hardy green fern in a plastic nursery pot', attributes=dict(light='Shade', hardiness='Hardy', pot_size='17 cm', material='Terracotta')),
    P('N-HOSTA', 'Hosta', ['outdoor-plants'], 11, 'Big blue-green leaves for shade. Watch for slugs.', 'a hosta plant with large blue green leaves in a pot', attributes=dict(light='Shade', hardiness='Hardy', pot_size='17 cm', material='Terracotta')),
    P('N-CLEMATIS', 'Clematis', ['outdoor-plants'], 16, 'A late-flowering purple clematis for a fence or an obelisk.', 'a clematis vine with purple flowers on a small cane', attributes=dict(light='Full sun', hardiness='Hardy', pot_size='17 cm', material='Terracotta')),
    P('N-TOMATO-SEED', 'Tomato seed, Costoluto', ['seeds'], 3.5, 'A ribbed beefsteak from our own seed bed. Forty seeds.', 'a small paper seed packet with an illustration of a ribbed red tomato', attributes=dict(light='Full sun', hardiness='Tender', pot_size='', material='')),
    P('N-BEAN-SEED', 'Climbing bean seed', ['seeds'], 3, 'A purple-podded climbing bean that turns green when cooked. Fifty seeds.', 'a small paper seed packet with an illustration of purple beans', attributes=dict(light='Full sun', hardiness='Half hardy', pot_size='', material='')),
    P('N-LETTUCE-SEED', 'Lettuce mix seed', ['seeds'], 2.5, 'Six cut-and-come-again lettuces in one packet.', 'a small paper seed packet with an illustration of lettuce leaves', attributes=dict(light='Part shade', hardiness='Hardy', pot_size='', material='')),
    P('N-SWEET-PEA', 'Sweet pea seed', ['seeds'], 3, 'A scented old mix in every colour. Soak overnight.', 'a small paper seed packet with an illustration of sweet pea flowers', attributes=dict(light='Full sun', hardiness='Hardy', pot_size='', material='')),
    P('N-WILDFLOWER', 'Wildflower mix', ['seeds'], 6, 'Twenty native wildflowers for a square metre of bees.', 'a paper seed packet with an illustration of mixed wildflowers', attributes=dict(light='Full sun', hardiness='Hardy', pot_size='', material='')),
    P('N-TULIP-BULBS', 'Tulip bulbs, 12', ['seeds'], 9, 'A dozen dark tulips for pots and borders. Plant in November.', 'a dozen tulip bulbs in a paper bag', axis='pot_size', values=['9 cm'], attributes=dict(light='Full sun', hardiness='Hardy', material='')),
    P('N-DAFFODIL-BULBS', 'Daffodil bulbs, 25', ['seeds'], 12, 'Small early daffodils that come back every year.', 'a pile of daffodil bulbs in a paper bag', attributes=dict(light='Part shade', hardiness='Hardy', pot_size='', material='')),
    P('N-GARLIC', 'Seed garlic, 3 bulbs', ['seeds'], 7, 'Hardneck garlic to plant in autumn and lift in July.', 'three bulbs of seed garlic in a paper bag', attributes=dict(light='Full sun', hardiness='Hardy', pot_size='', material='')),
    P('N-TERRACOTTA', 'Terracotta pot', ['pots'], 8, 'A frost-proof terracotta pot with a drainage hole and a saucer.', 'a plain terracotta pot with a saucer', axis='pot_size', values=['12 cm', '17 cm', '21 cm', '30 cm'], attributes=dict(light='', hardiness='', material='Terracotta')),
    P('N-GLAZED-POT', 'Glazed stoneware pot', ['pots'], 24, 'A reactive-glazed pot for indoors, with a hole.', 'a {value} glazed stoneware plant pot', axis='color', values=['Green', 'White', 'Blue'], picture_per_value=True, attributes=dict(light='', hardiness='', pot_size='17 cm', material='Ceramic')),
    P('N-ZINC-PLANTER', 'Zinc trough', ['pots'], 45, 'A 60 cm zinc trough for herbs on a windowsill.', 'a long zinc metal planter trough', attributes=dict(light='', hardiness='', pot_size='30 cm', material='Stainless steel', dimensions='60 x 20 x 20 cm')),
    P('N-HANGING-POT', 'Hanging pot', ['pots'], 22, 'A stoneware pot on a jute hanger.', 'a stoneware hanging plant pot on a jute macrame hanger', attributes=dict(light='', hardiness='', pot_size='17 cm', material='Ceramic')),
    P('N-SEED-TRAY', 'Seed trays, set of 3', ['pots', 'seeds'], 12, 'Three rigid recycled trays with lids.', 'three black seed trays with clear lids stacked', attributes=dict(light='', hardiness='', pot_size='', material='Recycled polyester')),
    P('N-RAISED-BED', 'Oak raised bed', ['pots', 'furniture'], 190, 'A 120 by 80 cm raised bed in oak sleepers, no tools needed.', 'a rectangular oak raised garden bed', attributes=dict(light='', hardiness='', pot_size='', material='Oak', dimensions='120 x 80 x 40 cm')),
    P('N-COMPOST', 'Peat-free compost, 40 l', ['pots'], 9, 'Our own mix for pots and beds.', 'a plain kraft paper bag of compost', attributes=dict(light='', hardiness='', pot_size='', material='')),
    P('N-SPADE', 'Forged spade', ['tools'], 75, 'A forged steel spade with an ash handle, sharpened before it ships.', 'a garden spade with a steel blade and an ash wood handle', attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel')),
    P('N-FORK', 'Forged fork', ['tools'], 75, 'A four-tine fork that does not bend.', 'a garden fork with steel tines and an ash handle', attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel')),
    P('N-TROWEL', 'Hand trowel', ['tools'], 22, 'A stainless trowel with an ash handle.', 'a stainless steel hand trowel with a wooden handle', attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel')),
    P('N-SECATEURS', 'Bypass secateurs', ['tools'], 48, 'Forged bypass secateurs with a replaceable blade.', 'a pair of red handled bypass secateurs', attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel')),
    P('N-WATERING-CAN', 'Watering can', ['tools'], 38, 'A 5 litre galvanised can with a brass rose.', 'a {value} galvanised metal watering can', axis='color', values=['Silver', 'Green'], picture_per_value=True, attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel')),
    P('N-GLOVES', 'Leather gloves', ['tools'], 18, 'Goatskin gloves that let you feel a seedling.', 'a pair of tan leather gardening gloves', axis='size', values=['S', 'M', 'L'], attributes=dict(light='', hardiness='', pot_size='', material='Leather')),
    P('N-HOE', 'Dutch hoe', ['tools'], 42, 'A push hoe for weeds between rows.', 'a long handled dutch hoe', attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel')),
    P('N-KNEELER', 'Kneeling pad', ['tools'], 14, 'A thick foam pad for beds and borders.', 'a green foam garden kneeling pad', attributes=dict(light='', hardiness='', pot_size='', material='Rubber')),
    P('N-TOOL-SET', 'Hand tool set', ['tools'], 55, 'Trowel, fork and dibber in a canvas roll.', 'a hand trowel, a hand fork and a dibber in a canvas roll', attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel')),
    P('N-BENCH', 'Oak garden bench', ['furniture'], 390, 'A 150 cm oak bench that greys outside and lasts decades.', 'a solid oak garden bench', attributes=dict(light='', hardiness='', pot_size='', material='Oak', dimensions='150 x 55 x 85 cm')),
    P('N-BISTRO-SET', 'Bistro set', ['furniture'], 220, 'A folding steel table and two chairs for a balcony.', 'a {value} folding steel bistro table with two chairs', axis='color', values=['Green', 'Black', 'White'], picture_per_value=True, attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel', dimensions='60 cm table')),
    P('N-DECK-CHAIR', 'Deck chair', ['furniture'], 85, 'A beech deck chair with a striped canvas seat.', 'a wooden deck chair with a striped canvas seat', attributes=dict(light='', hardiness='', pot_size='', material='Oak')),
    P('N-PARASOL', 'Parasol', ['furniture'], 140, 'A 2.5 m parasol with an ash pole and a canvas cover.', 'a large canvas garden parasol with a wooden pole', axis='color', values=['Oatmeal', 'Green'], picture_per_value=True, attributes=dict(light='', hardiness='', pot_size='', material='Cotton')),
    P('N-FIRE-BOWL', 'Steel fire bowl', ['furniture'], 160, 'A 70 cm steel fire bowl that rusts to a warm brown.', 'a round rusted steel fire bowl', attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel', dimensions='70 cm')),
    P('N-POTTING-BENCH', 'Potting bench', ['furniture', 'tools'], 240, 'A pine potting bench with a zinc top and a shelf.', 'a wooden potting bench with a zinc top', attributes=dict(light='', hardiness='', pot_size='', material='Oak', dimensions='120 x 50 x 90 cm')),
    P('N-STARTER-KIT', 'Kitchen garden kit', ['seeds', 'tools'], 45, 'Tomato, bean and lettuce seed, three trays and a trowel.', 'seed packets, seed trays and a trowel arranged together', grouped=['N-TOMATO-SEED', 'N-BEAN-SEED', 'N-LETTUCE-SEED', 'N-SEED-TRAY', 'N-TROWEL'], attributes=dict(light='', hardiness='', pot_size='', material='')),
    P('N-SHADE-SET', 'Shady corner set', ['outdoor-plants'], 34, 'A hardy fern, a hosta and a bag of compost.', 'a fern and a hosta in pots beside a bag of compost', grouped=['N-FERN-OUTDOOR', 'N-HOSTA', 'N-COMPOST'], attributes=dict(light='Shade', hardiness='Hardy', pot_size='', material='')),
    P('N-GIFT-CARD', 'Greenhaven gift card', ['pots'], 40, 'A gift card by email, for the plant they choose.', 'a green gift card with a leaf illustration', type='virtual', attributes=dict(light='', hardiness='', pot_size='', material='')),
]
POSTS = [
    ('Which window', '<p>South windows are bright and hot: cacti, olives, pilea. East windows are gentle: ferns, calathea, pothos. North windows are for the tough ones: snake plants and the fern that forgives you.</p><p>Most plants die of kindness. Water when the top two centimetres are dry, not on a schedule.</p>', 'Houseplants on a bright windowsill with morning sun through the glass.'),
    ('Sowing in March', '<p>Tomatoes and chillies indoors on a warm windowsill now. Peas and broad beans straight into the ground. Lettuce in a tray under cover, then out in April.</p><p>Label everything. You will not remember.</p>', 'Seed trays with small seedlings and wooden labels on a sunny potting bench.'),
    ('Sharpen your tools', '<p>A sharp spade cuts roots instead of tearing them, and a sharp hoe skims weeds without effort. Ten strokes with a file along the bevel, once a month, is all it takes.</p><p>Wipe the steel with an oily rag before winter. Ash handles want a little linseed.</p>', 'A hand sharpening a spade blade with a file on a workbench in a shed.'),
]
MORE = {
    'N-MONSTERA': 'Delivered in a 19 cm pot at about 70 cm tall, with a moss pole. It grows a leaf a month in summer.',
    'N-FERN': 'A 17 cm pot with a full, arching crown. Mist it in a dry room and it stays green.',
    'N-PILEA': 'A 12 cm pot with a healthy young plant. Turn it weekly so it grows straight.',
    'N-SNAKE-PLANT': 'A 14 cm pot at about 50 cm tall. It tolerates a dark hallway and forgets you were away.',
    'N-FICUS': 'A 24 cm pot at about 120 cm tall. It needs a bright spot and a steady routine.',
    'N-POTHOS': 'A 12 cm pot with trails of about 40 cm. It roots in water, so one plant becomes many.',
    'N-CALATHEA': 'A 14 cm pot with fresh growth. Rainwater or filtered water keeps the leaf edges brown-free.',
    'N-OLIVE-INDOOR': 'A 19 cm pot at about 80 cm tall, with a woody trunk. Water when the top half of the compost is dry.',
    'N-CACTUS-SET': 'Three different shapes, sold as a set. A sunny sill and a drink once a month is all they ask.',
    'N-LAVENDER': 'A 2 litre pot, ready to plant. Cut it back after flowering to keep it compact.',
    'N-ROSEMARY': 'A 2 litre pot with a plant of about 40 cm. Snip what you need all year round.',
    'N-HYDRANGEA': 'A 3 litre pot, flowering from July. The colour depends on your soil, and the label explains how.',
    'N-JAPANESE-MAPLE': 'A 5 litre pot at about 80 cm tall. It wants shelter from wind and afternoon sun.',
    'N-GRASS': 'A 2 litre pot, about 60 cm tall in flower. Cut it down in February and it comes back.',
    'N-FERN-OUTDOOR': 'A 2 litre pot with fronds of about 40 cm. It is evergreen and needs nothing once settled.',
    'N-HOSTA': 'A 2 litre pot with three to five leaves. It dies down in winter and returns bigger each spring.',
    'N-CLEMATIS': 'A 2 litre pot with a cane. Plant it deep and cut it to 30 cm each February.',
    'N-TOMATO-SEED': 'Sow indoors in March and plant out after the last frost. Big, ribbed fruit from August.',
    'N-BEAN-SEED': 'Sow in May, straight in the ground, beside a cane wigwam. Pick young for the best pods.',
    'N-LETTUCE-SEED': 'Sow a short row every fortnight from March. Cut the outer leaves and the plant keeps growing.',
    'N-SWEET-PEA': 'Sow in autumn or early spring and give them something to climb. Pick daily to keep them flowering.',
    'N-WILDFLOWER': 'Sow on bare soil in spring or autumn and do not feed it. Flowers from the second month.',
    'N-TULIP-BULBS': 'Twelve large bulbs of one dark variety. Plant them 15 cm deep in November.',
    'N-DAFFODIL-BULBS': 'Twenty-five bulbs of a small early variety for pots and grass. They multiply each year.',
    'N-GARLIC': 'Three hardneck bulbs, about thirty cloves. Plant the cloves in October, 15 cm apart.',
    'N-TERRACOTTA': 'Fired at a high temperature, so it survives winter outside. Available in three sizes.',
    'N-GLAZED-POT': 'Each pot comes out of the kiln slightly different. The drainage hole and a saucer are included.',
    'N-ZINC-PLANTER': 'Galvanised steel with drainage holes and a tray. It holds four herb pots in a row.',
    'N-HANGING-POT': 'A stoneware pot with a drainage plug and a jute hanger of 90 cm. Good for a trailing plant.',
    'N-SEED-TRAY': 'Rigid trays that last years, with clear lids for the first weeks. They stack when empty.',
    'N-RAISED-BED': 'Oak sleepers that slot together without screws. Fill it with about 200 litres of compost.',
    'N-COMPOST': 'Bark, coir and green compost, with slow-release feed for six weeks. A 40 litre bag fills four large pots.',
    'N-SPADE': 'A narrow blade with a tread, forged from one piece of steel. It comes with a twenty-year guarantee.',
    'N-FORK': 'Forged tines and an ash handle with a wide grip. It lifts potatoes and turns compost without bending.',
    'N-TROWEL': 'A narrow blade for planting and a wide one for potting, both stainless. The handle is oiled ash.',
    'N-SECATEURS': 'Forged from steel, with a blade that unscrews for sharpening or replacing. They cut branches up to 20 mm.',
    'N-WATERING-CAN': 'Galvanised steel with a long spout and a fine brass rose that unscrews. Balanced to pour with one hand.',
    'N-GLOVES': 'Soft goatskin with a cotton back, in three sizes. Thorns do not get through.',
    'N-HOE': 'A sharp blade on a 150 cm ash handle. Walk backwards and the weeds are gone.',
    'N-KNEELER': 'Thick closed-cell foam that does not soak up water. It hangs on a hook by a loop.',
    'N-TOOL-SET': 'Three stainless tools with ash handles in a canvas roll. A good first set or a good gift.',
    'N-BENCH': 'Solid oak, joined with oak pegs and stainless screws. Leave it to silver or oil it once a year.',
    'N-BISTRO-SET': 'Powder-coated steel that folds flat against a wall. The table is 60 cm across.',
    'N-DECK-CHAIR': 'Oiled beech with a canvas seat that unclips for washing. It folds flat for winter.',
    'N-PARASOL': 'A 2.5 m canopy on an ash pole with a brass tilt joint. The base is sold separately.',
    'N-FIRE-BOWL': 'Three millimetre steel on a tripod stand. It arrives grey and turns brown in a month outside.',
    'N-POTTING-BENCH': 'A zinc top that wipes clean and a shelf for pots. Assembly takes twenty minutes.',
    'N-STARTER-KIT': 'Everything for a first season of vegetables in one box. The instructions fit on one card.',
    'N-SHADE-SET': 'Two plants that thrive where nothing else will, with the compost to plant them. For a north-facing corner.',
    'N-GIFT-CARD': 'Delivered by email within the hour, with a message of your own. Valid for a year in the store.',
}
