CODE = 'garden'; ROOT = {'en': 'Garden', 'fr': 'Jardin', 'de': 'Garten', 'it': 'Giardino'}; STORE_NAME = 'Greenhaven'; ATTRIBUTE_SET = 'Garden'; WEIGHT = 2
ATTRIBUTE_COLUMNS = ['light', 'hardiness', 'pot_size', 'material', 'dimensions']
ATTRIBUTES = [
    dict(code='light', label='Light', input='select', scope='global', filterable=1, filterable_in_search=1, visible_on_front=1, used_in_product_listing=1, sets='Garden', group='General', sort_order=50),
    dict(code='hardiness', label='Hardiness', input='select', scope='global', filterable=1, visible_on_front=1, comparable=1, sets='Garden', group='General', sort_order=60),
    dict(code='pot_size', label='Pot size', input='select', scope='global', filterable=1, visible_on_front=1, is_configurable=1, sets='Garden', group='General', sort_order=70),
]
OPTIONS = {'light': ['Full sun', 'Part shade', 'Shade', 'Indoor bright', 'Indoor low'], 'hardiness': ['Hardy', 'Half hardy', 'Tender', 'Indoor'], 'pot_size': ['9 cm', '12 cm', '17 cm', '21 cm', '30 cm']}
ROOT_DESCRIPTION = {'en': 'Plants, seeds, pots and tools from a nursery that grows what it sells.',
                    'fr': "Plantes, graines, pots et outils d'une pépinière qui cultive ce qu'elle vend.",
                    'de': 'Pflanzen, Samen, Töpfe und Werkzeug aus einer Gärtnerei, die anbaut, was sie verkauft.',
                    'it': 'Piante, semi, vasi e attrezzi da un vivaio che coltiva quello che vende.'}
META_DESCRIPTION = 'Greenhaven: houseplants, outdoor plants, seeds, pots, tools and garden furniture from our own nursery.'
PRODUCT_STYLE = 'Studio product photograph of a single plant or garden product on a plain white seamless background, natural daylight, no people, no text, no lettering, no logos, no watermark, centered with margin around it.'
SCENE_STYLE = 'Lush editorial garden photograph, greenhouse glass, terracotta, morning dew, warm sunlight through leaves, no people, no readable text, no lettering, no logos, no watermark.'
SCENES = {
    'hero-main': 'A sunlit greenhouse full of potted plants on wooden benches, terracotta pots and a watering can, morning light through the glass.',
    'hero-side': 'A close up of hands potting a fern into a terracotta pot with dark compost.',
    'editorial': 'Rows of young plants in a nursery polytunnel with a gardener watering, seen from the side.',
    'about': 'A small plant nursery with a glasshouse, potting benches and stacks of terracotta pots.',
}
CATEGORIES = [
    dict(path='houseplants', name={'en': 'Houseplants', 'fr': "Plantes d'intérieur", 'de': 'Zimmerpflanzen', 'it': 'Piante da interno'}, description='Grown in our glasshouse, shipped with roots intact.', landing_title='Grown here, not shipped through', landing_text='Every houseplant spends a month in our glasshouse before it leaves. We say which window it wants.', scene='A group of houseplants in terracotta pots on a windowsill in morning light.'),
    dict(path='outdoor-plants', name={'en': 'Outdoor Plants', 'fr': "Plantes d'extérieur", 'de': 'Gartenpflanzen', 'it': 'Piante da esterno'}, description='Perennials, shrubs and trees for beds and pots.', landing_title='For beds, borders and balconies', landing_text='Hardy perennials, small trees and shrubs, sold in the season they should be planted.', scene='A border of lavender and grasses in a sunny garden with a gravel path.'),
    dict(path='seeds', name={'en': 'Seeds & Bulbs', 'fr': 'Graines et bulbes', 'de': 'Samen und Zwiebeln', 'it': 'Semi e bulbi'}, description='Open-pollinated seed and bulbs by the dozen.', landing_title='Sow, wait, eat', landing_text='Open-pollinated vegetable and flower seed, saved on our own beds, and bulbs sold by the dozen.', scene='Seed packets, a wooden dibber and a tray of seedlings on a potting bench.'),
    dict(path='pots', name={'en': 'Pots & Planters', 'fr': 'Pots et jardinières', 'de': 'Töpfe und Kübel', 'it': 'Vasi e fioriere'}, description='Terracotta, stoneware and zinc.', landing_title='Something to grow in', landing_text='Frost-proof terracotta, glazed stoneware and zinc planters, with the drainage holes already there.', scene='A stack of terracotta pots of different sizes on a stone floor in sunlight.'),
    dict(path='tools', name={'en': 'Tools', 'fr': 'Outils', 'de': 'Werkzeug', 'it': 'Attrezzi'}, description='Forged tools with ash handles, sharpened before shipping.', landing_title='Sharp on arrival', landing_text='Forged steel heads on ash handles. Every tool is sharpened before it ships.', scene='A row of garden tools with wooden handles hanging on a shed wall.'),
    dict(path='furniture', name={'en': 'Outdoor Furniture', 'fr': 'Mobilier de jardin', 'de': 'Gartenmöbel', 'it': 'Mobili da giardino'}, description='Benches, tables and chairs in oak and steel.', landing_title='Sit in the garden', landing_text='Oak benches, folding steel chairs and a table that stays out all winter.', scene='An oak garden bench under a tree with dappled sunlight and a cup of tea on the arm.'),
]
HERO = dict(badge='Spring stock', title='Grown here, shipped with care', text='Plants from our own glasshouse, seed from our own beds, and tools sharpened before they leave.')
FEATURES = [('truck', 'Plant-safe delivery', 'Boxed upright, two days'), ('plant', 'Grown by us', 'A month in the glasshouse'), ('arrow-back-up', 'Plant guarantee', 'Thirty days, replaced'), ('headset', 'Ask a grower', 'Real answers, weekdays')]
STORY = dict(title='A nursery, not a warehouse', text1='Greenhaven is a working nursery with a glasshouse, three polytunnels and a seed bed. What we sell, we grow, and the rest comes from growers we visit.', text2='Every plant page says which light it wants and what it does in winter. If it dies in thirty days, we replace it.')
PROMO = dict(badge='Season', title='Plant now', text='What to plant this month, chosen by the growers: perennials for the border and bulbs for spring.', path='outdoor-plants', button='See what to plant', list_title='In season now')
TESTIMONIALS = [('The fern arrived upright, moist and bigger than the photo. First plant that has survived my flat.', 'Elena R.', 'Manchester'), ('The spade came sharp. I did not know that was a thing.', 'Marcus T.', 'Leeds'), ('Asked which side of the balcony for the olive. They told me. It is thriving.', 'Priya S.', 'Toronto')]
NEWSLETTER = dict(title='From the glasshouse', text='A note every two weeks: what to sow, what to plant, and what came into stock.')
ABOUT = dict(title='Three polytunnels and a seed bed', paragraphs=['Greenhaven started as a market stall selling seedlings from a back garden. The back garden became a field, then a glasshouse.', 'We grow most of what we sell. The rest comes from growers within a day of the nursery, and we visit them.', 'The nursery is open on weekends. Bring a coffee and ask the growers anything.'])
REVIEWS = [
    ({'en': 'Healthy and well packed', 'fr': 'Sain et bien emballé', 'de': 'Gesund und gut verpackt', 'it': 'Sana e ben imballata'}, {'en': 'Arrived upright with damp compost and no broken leaves.',
                                 'fr': 'Arrivé droit avec du terreau humide et aucune feuille cassée.',
                                 'de': 'Kam aufrecht an, mit feuchter Erde und ohne gebrochene Blätter.',
                                 'it': 'Arrivata dritta con terriccio umido e nessuna foglia rotta.'}, 5),
    ({'en': 'Smaller than expected', 'fr': 'Plus petit que prévu', 'de': 'Kleiner als erwartet', 'it': 'Più piccola del previsto'}, {'en': 'Healthy plant but a smaller pot than I thought. Check the pot size.',
                               'fr': 'Plante saine mais un pot plus petit que je ne pensais. Vérifiez la taille du pot.',
                               'de': 'Gesunde Pflanze, aber ein kleinerer Topf als gedacht. Prüfen Sie die Topfgröße.',
                               'it': 'Pianta sana ma un vaso più piccolo di quanto pensassi. Controlla la misura del vaso.'}, 4),
    ({'en': 'Sharp and solid', 'fr': 'Affûté et solide', 'de': 'Scharf und solide', 'it': 'Affilato e robusto'}, {'en': 'The tool is heavy in a good way and came sharp.',
                         'fr': "L'outil est lourd dans le bon sens et est arrivé affûté.",
                         'de': 'Das Werkzeug ist angenehm schwer und kam scharf an.',
                         'it': "L'attrezzo è pesante nel senso buono ed è arrivato affilato."}, 5),
    ({'en': 'Replaced without fuss', 'fr': 'Remplacé sans histoires', 'de': 'Ohne Umstände ersetzt', 'it': 'Sostituita senza problemi'}, {'en': 'One plant failed. Photo sent, new one in three days.',
                               'fr': "Une plante n'a pas pris. Photo envoyée, une nouvelle en trois jours.",
                               'de': 'Eine Pflanze ging ein. Foto geschickt, eine neue in drei Tagen.',
                               'it': 'Una pianta non ha attecchito. Foto inviata, una nuova in tre giorni.'}, 5),
    ({'en': 'Flowered in three weeks', 'fr': 'Fleuri en trois semaines', 'de': 'Blühte nach drei Wochen', 'it': 'Ha fiorito in tre settimane'}, {'en': 'Planted it on a Sunday, first bud by month end.',
                                 'fr': 'Planté un dimanche, premier bouton à la fin du mois.',
                                 'de': 'An einem Sonntag gepflanzt, erste Knospe zum Monatsende.',
                                 'it': 'Piantata di domenica, primo bocciolo a fine mese.'}, 5),
    ({'en': 'Terracotta is thick', 'fr': 'La terre cuite est épaisse', 'de': 'Die Terrakotta ist dick', 'it': 'La terracotta è spessa'}, {'en': 'Proper fired clay, not the thin stuff. Survived a frost.',
                             'fr': 'De la vraie argile cuite, pas la version fine. Elle a passé une gelée.',
                             'de': 'Echter gebrannter Ton, nicht die dünne Ware. Hat einen Frost überstanden.',
                             'it': 'Vera argilla cotta, non quella sottile. Ha superato una gelata.'}, 5),
    ({'en': 'Seeds all came up', 'fr': 'Toutes les graines ont levé', 'de': 'Alle Samen sind aufgegangen', 'it': 'Tutti i semi sono nati'}, {'en': 'Twenty sown, nineteen seedlings. Cannot ask for more.',
                           'fr': 'Vingt semées, dix-neuf plants. On ne peut pas demander mieux.',
                           'de': 'Zwanzig gesät, neunzehn Sämlinge. Mehr kann man nicht verlangen.',
                           'it': 'Venti seminati, diciannove piantine. Non si può chiedere di più.'}, 5),
    ({'en': 'Soil was dry on arrival', 'fr': "La terre était sèche à l'arrivée", 'de': 'Die Erde war bei Ankunft trocken', 'it': "La terra era secca all'arrivo"}, {'en': 'Plant bounced back after a soak, but the box sat somewhere warm.',
                                 'fr': 'La plante est repartie après un bon arrosage, mais le colis est resté au chaud.',
                                 'de': 'Die Pflanze erholte sich nach einem Tauchbad, aber der Karton stand irgendwo warm.',
                                 'it': 'La pianta si è ripresa dopo una bella bagnata, ma la scatola è rimasta al caldo.'}, 3),
    ({'en': 'Handle fits the hand', 'fr': 'Le manche tient bien en main', 'de': 'Der Griff liegt gut in der Hand', 'it': 'Il manico sta bene in mano'}, {'en': 'Ash handle, no blisters after an afternoon of digging.',
                              'fr': 'Manche en frêne, aucune ampoule après un après-midi à bêcher.',
                              'de': 'Eschengriff, keine Blasen nach einem Nachmittag Graben.',
                              'it': 'Manico in frassino, nessuna vescica dopo un pomeriggio a scavare.'}, 5),
    ({'en': 'Bees love it', 'fr': "Les abeilles l'adorent", 'de': 'Die Bienen lieben sie', 'it': 'Le api la adorano'}, {'en': 'Covered in bees within a week of planting.',
                      'fr': "Couverte d'abeilles une semaine après la plantation.",
                      'de': 'Eine Woche nach dem Pflanzen voller Bienen.',
                      'it': 'Coperta di api una settimana dopo la messa a dimora.'}, 5),
    ({'en': 'Wrong colour', 'fr': 'Mauvaise couleur', 'de': 'Falsche Farbe', 'it': 'Colore sbagliato'}, {'en': 'Ordered white, got pink. Beautiful, but not what I ordered. Refund given.',
                      'fr': "J'ai commandé du blanc, j'ai reçu du rose. C'est beau, mais ce n'est pas ma commande. Remboursement accordé.",
                      'de': 'Weiß bestellt, Rosa bekommen. Schön, aber nicht das Bestellte. Erstattung erhalten.',
                      'it': 'Ordinato bianco, arrivato rosa. Bello, ma non quello che avevo ordinato. Rimborso concesso.'}, 3),
    ({'en': 'Hardy as promised', 'fr': 'Rustique comme promis', 'de': 'Winterhart wie versprochen', 'it': 'Rustica come promesso'}, {'en': 'Left out all winter in a pot and it came back.',
                           'fr': "Laissée dehors tout l'hiver en pot et elle est repartie.",
                           'de': 'Den ganzen Winter im Topf draußen gelassen und sie kam zurück.',
                           'it': "Lasciata fuori tutto l'inverno in vaso ed è ripartita."}, 5),
    ({'en': 'Good starter set', 'fr': 'Un bon kit pour débuter', 'de': 'Gutes Einsteigerset', 'it': 'Buon kit per iniziare'}, {'en': 'Everything a first garden needs and nothing it does not.',
                          'fr': "Tout ce qu'un premier jardin demande et rien de plus.",
                          'de': 'Alles, was ein erster Garten braucht, und nichts darüber hinaus.',
                          'it': 'Tutto quello che serve a un primo giardino e niente di più.'}, 5),
    ({'en': 'Watering can pours well', 'fr': "L'arrosoir verse bien", 'de': 'Die Gießkanne gießt gut', 'it': "L'annaffiatoio versa bene"}, {'en': 'Long spout, fine rose, no dribble down the side.',
                                 'fr': 'Long bec, pomme fine, aucune coulure sur le côté.',
                                 'de': 'Langer Auslauf, feine Brause, kein Tropfen an der Seite.',
                                 'it': 'Becco lungo, cipolla fine, nessuna goccia sul lato.'}, 5),
    ({'en': 'Delivery was gentle', 'fr': 'Une livraison en douceur', 'de': 'Die Lieferung war behutsam', 'it': 'La consegna è stata delicata'}, {'en': 'The courier carried it upright. The driver deserves the credit.',
                             'fr': "Le livreur l'a porté droit. Le mérite lui revient.",
                             'de': 'Der Kurier hat sie aufrecht getragen. Das Lob gebührt dem Fahrer.',
                             'it': "Il corriere l'ha portata dritta. Il merito è dell'autista."}, 5),
    ({'en': 'Herbs on the sill', 'fr': 'Des herbes sur le rebord', 'de': 'Kräuter auf der Fensterbank', 'it': 'Erbe sul davanzale'}, {'en': 'Six pots on the kitchen sill and I have not bought parsley since.',
                           'fr': "Six pots sur le rebord de la cuisine et je n'ai plus acheté de persil.",
                           'de': 'Sechs Töpfe auf der Küchenfensterbank und ich habe seitdem keine Petersilie mehr gekauft.',
                           'it': 'Sei vasi sul davanzale della cucina e non compro più prezzemolo.'}, 5),
    ({'en': 'Compost smells right', 'fr': 'Le terreau sent bon', 'de': 'Der Kompost riecht richtig', 'it': 'Il compost ha il profumo giusto'}, {'en': 'Dark and crumbly. My tomatoes doubled in a month.',
                              'fr': 'Foncé et friable. Mes tomates ont doublé en un mois.',
                              'de': 'Dunkel und krümelig. Meine Tomaten haben sich in einem Monat verdoppelt.',
                              'it': 'Scuro e friabile. I miei pomodori sono raddoppiati in un mese.'}, 5),
    ({'en': 'Pot has no drainage hole', 'fr': "Le pot n'a pas de trou de drainage", 'de': 'Der Topf hat kein Abzugsloch', 'it': 'Il vaso non ha il foro di drenaggio'}, {'en': 'Lovely glaze but no hole. Drill it or use it indoors with gravel.',
                                  'fr': "Un bel émail mais pas de trou. Percez-le ou utilisez-le à l'intérieur avec des graviers.",
                                  'de': 'Schöne Glasur, aber kein Loch. Bohren Sie es oder nutzen Sie ihn drinnen mit Kies.',
                                  'it': 'Bello smalto ma niente foro. Fallo tu o usalo in casa con la ghiaia.'}, 3),
    ({'en': 'Pruners cut clean', 'fr': 'Le sécateur coupe net', 'de': 'Die Schere schneidet sauber', 'it': 'Le cesoie tagliano netto'}, {'en': 'Bypass blades, no crushing. Roses thanked me.',
                           'fr': "Lames franches, aucun écrasement. Les rosiers m'ont remercié.",
                           'de': 'Bypass-Klingen, kein Quetschen. Die Rosen haben es mir gedankt.',
                           'it': 'Lame bypass, nessuno schiacciamento. Le rose mi hanno ringraziato.'}, 5),
    ({'en': 'Bigger than the photo', 'fr': 'Plus grande que sur la photo', 'de': 'Größer als auf dem Foto', 'it': 'Più grande della foto'}, {'en': 'A three year old plant, not a plug. Delighted.',
                               'fr': 'Une plante de trois ans, pas un godet. Ravi.',
                               'de': 'Eine dreijährige Pflanze, kein Steckling. Begeistert.',
                               'it': 'Una pianta di tre anni, non una piantina. Felicissimo.'}, 5),
    ({'en': 'Label was helpful', 'fr': "L'étiquette a été utile", 'de': 'Das Etikett war hilfreich', 'it': "L'etichetta è stata utile"}, {'en': 'Planting depth, spacing and sun on the tag. Saved a search.',
                           'fr': "Profondeur de plantation, espacement et exposition sur l'étiquette. Cela m'a évité une recherche.",
                           'de': 'Pflanztiefe, Abstand und Sonne auf dem Schild. Hat mir eine Suche erspart.',
                           'it': 'Profondità, distanza e sole sul cartellino. Mi ha risparmiato una ricerca.'}, 4),
    ({'en': 'Gloves are tough', 'fr': 'Les gants sont résistants', 'de': 'Die Handschuhe sind robust', 'it': 'I guanti sono resistenti'}, {'en': 'Thorns did not get through. Fit is snug.',
                          'fr': 'Les épines ne sont pas passées. La coupe est ajustée.',
                          'de': 'Dornen kamen nicht durch. Die Passform ist eng.',
                          'it': 'Le spine non sono passate. La vestibilità è aderente.'}, 5),
    ({'en': 'Slow to establish', 'fr': "Longue à s'installer", 'de': 'Braucht lange zum Anwachsen', 'it': 'Lenta ad attecchire'}, {'en': 'Took a full season to settle. Now it is the best thing in the border.',
                           'fr': "Il a fallu une saison entière pour qu'elle s'installe. C'est maintenant la plus belle du massif.",
                           'de': 'Sie brauchte eine ganze Saison. Jetzt ist sie das Beste im Beet.',
                           'it': "Ci è voluta una stagione intera. Ora è la cosa più bella dell'aiuola."}, 4),
    ({'en': 'Bulbs came in paper', 'fr': 'Les bulbes sont livrés dans du papier', 'de': 'Die Zwiebeln kamen in Papier', 'it': 'I bulbi sono arrivati nella carta'}, {'en': 'No plastic in the box at all. Every bulb sprouted.',
                             'fr': 'Aucun plastique dans le colis. Chaque bulbe a germé.',
                             'de': 'Überhaupt kein Plastik im Karton. Jede Zwiebel ist ausgetrieben.',
                             'it': 'Nessuna plastica nella scatola. Ogni bulbo è germogliato.'}, 5),
    ({'en': 'Trellis went up in an hour', 'fr': 'Le treillis a été posé en une heure', 'de': 'Das Spalier stand in einer Stunde', 'it': "Il traliccio è salito in un'ora"}, {'en': 'Cedar, pre-drilled, and the screws were in the box.',
                                    'fr': 'Cèdre, pré-percé, et les vis étaient dans la boîte.',
                                    'de': 'Zeder, vorgebohrt, und die Schrauben lagen in der Box.',
                                    'it': 'Cedro, pre-forato, e le viti erano nella scatola.'}, 5),
]
def P(sku, name, cats, price, desc, prompt, **kw):
    d = dict(sku=sku, name=name, categories=cats, price=price, description=desc, prompt=prompt); d.update(kw); return d
PRODUCTS = [
    P('N-MONSTERA', 'Monstera deliciosa', ['houseplants'], 32, 'The split-leaf climber. Bright indirect light, water when the top is dry. Delivered in a 19 cm pot at about 70 cm tall, with a moss pole. It grows a leaf a month in summer.', 'a monstera plant with split leaves in a plain terracotta pot', axis='pot_size', values=['17 cm', '21 cm', '30 cm'], attributes=dict(light='Indoor bright', hardiness='Indoor', material='Terracotta')),
    P('N-FERN', 'Boston fern', ['houseplants'], 22, 'A full fern for a bathroom or a north window. Keep it moist. A 17 cm pot with a full, arching crown. Mist it in a dry room and it stays green.', 'a lush boston fern in a terracotta pot', axis='pot_size', values=['12 cm', '17 cm'], attributes=dict(light='Indoor low', hardiness='Indoor', material='Terracotta')),
    P('N-PILEA', 'Pilea', ['houseplants'], 16, 'The pancake plant. Easy, and it makes babies to give away. A 12 cm pot with a healthy young plant. Turn it weekly so it grows straight.', 'a pilea plant with round leaves in a small terracotta pot', attributes=dict(light='Indoor bright', hardiness='Indoor', pot_size='12 cm', material='Terracotta')),
    P('N-SNAKE-PLANT', 'Snake plant', ['houseplants'], 24, 'Survives neglect and low light. Water once a month. A 14 cm pot at about 50 cm tall. It tolerates a dark hallway and forgets you were away.', 'a tall snake plant with upright striped leaves in a pot', axis='pot_size', values=['12 cm', '17 cm', '21 cm'], attributes=dict(light='Indoor low', hardiness='Indoor', material='Terracotta')),
    P('N-FICUS', 'Fiddle leaf fig', ['houseplants'], 48, 'A statement tree for a bright corner. Do not move it once it is happy. A 24 cm pot at about 120 cm tall. It needs a bright spot and a steady routine.', 'a fiddle leaf fig tree with large leaves in a pot', axis='pot_size', values=['21 cm', '30 cm'], attributes=dict(light='Indoor bright', hardiness='Indoor', material='Terracotta')),
    P('N-POTHOS', 'Golden pothos', ['houseplants'], 14, 'A trailing vine for a shelf. Nearly impossible to kill. A 12 cm pot with trails of about 40 cm. It roots in water, so one plant becomes many.', 'a trailing golden pothos plant in a hanging pot', attributes=dict(light='Indoor low', hardiness='Indoor', pot_size='12 cm', material='Terracotta')),
    P('N-CALATHEA', 'Calathea', ['houseplants'], 26, 'Patterned leaves that fold at night. Likes humidity and soft water. A 14 cm pot with fresh growth. Rainwater or filtered water keeps the leaf edges brown-free.', 'a calathea plant with patterned leaves in a pot', attributes=dict(light='Indoor low', hardiness='Indoor', pot_size='17 cm', material='Terracotta')),
    P('N-OLIVE-INDOOR', 'Olive tree', ['houseplants', 'outdoor-plants'], 45, 'A young olive for a sunny window or a sheltered balcony. A 19 cm pot at about 80 cm tall, with a woody trunk. Water when the top half of the compost is dry.', 'a small olive tree with silver leaves in a terracotta pot', axis='pot_size', values=['17 cm', '21 cm'], attributes=dict(light='Full sun', hardiness='Half hardy', material='Terracotta')),
    P('N-CACTUS-SET', 'Cactus trio', ['houseplants'], 20, 'Three small cacti in 6 cm pots. Three different shapes, sold as a set. A sunny sill and a drink once a month is all they ask.', 'three small cacti in tiny terracotta pots', attributes=dict(light='Indoor bright', hardiness='Indoor', pot_size='9 cm', material='Terracotta')),
    P('N-LAVENDER', 'Lavender', ['outdoor-plants'], 9, 'English lavender for sun and poor soil. Bees will find it. A 2 litre pot, ready to plant. Cut it back after flowering to keep it compact.', 'a lavender plant in bloom in a small pot', axis='pot_size', values=['9 cm', '17 cm'], attributes=dict(light='Full sun', hardiness='Hardy', material='Terracotta')),
    P('N-ROSEMARY', 'Rosemary', ['outdoor-plants', 'seeds'], 8, 'Upright rosemary for a pot by the kitchen door. A 2 litre pot with a plant of about 40 cm. Snip what you need all year round.', 'a rosemary plant in a small pot', attributes=dict(light='Full sun', hardiness='Hardy', pot_size='12 cm', material='Terracotta')),
    P('N-HYDRANGEA', 'Hydrangea', ['outdoor-plants'], 24, 'A mophead hydrangea that flowers blue in acid soil and pink in lime. A 3 litre pot, flowering from July. The colour depends on your soil, and the label explains how.', 'a hydrangea shrub with blue flowers in a pot', axis='pot_size', values=['17 cm', '30 cm'], attributes=dict(light='Part shade', hardiness='Hardy', material='Terracotta')),
    P('N-JAPANESE-MAPLE', 'Japanese maple', ['outdoor-plants'], 55, 'A slow red maple for a pot or a sheltered corner. A 5 litre pot at about 80 cm tall. It wants shelter from wind and afternoon sun.', 'a small japanese maple tree with red leaves in a pot', attributes=dict(light='Part shade', hardiness='Hardy', pot_size='30 cm', material='Terracotta')),
    P('N-GRASS', 'Fountain grass', ['outdoor-plants'], 12, 'A soft grass that moves in wind and holds its seed heads into winter. A 2 litre pot, about 60 cm tall in flower. Cut it down in February and it comes back.', 'a clump of ornamental fountain grass in a pot', attributes=dict(light='Full sun', hardiness='Hardy', pot_size='17 cm', material='Terracotta')),
    P('N-FERN-OUTDOOR', 'Hardy fern', ['outdoor-plants'], 14, 'A shield fern for dry shade under trees. A 2 litre pot with fronds of about 40 cm. It is evergreen and needs nothing once settled.', 'a hardy green fern in a plastic nursery pot', attributes=dict(light='Shade', hardiness='Hardy', pot_size='17 cm', material='Terracotta')),
    P('N-HOSTA', 'Hosta', ['outdoor-plants'], 11, 'Big blue-green leaves for shade. Watch for slugs. A 2 litre pot with three to five leaves. It dies down in winter and returns bigger each spring.', 'a hosta plant with large blue green leaves in a pot', attributes=dict(light='Shade', hardiness='Hardy', pot_size='17 cm', material='Terracotta')),
    P('N-CLEMATIS', 'Clematis', ['outdoor-plants'], 16, 'A late-flowering purple clematis for a fence or an obelisk. A 2 litre pot with a cane. Plant it deep and cut it to 30 cm each February.', 'a clematis vine with purple flowers on a small cane', attributes=dict(light='Full sun', hardiness='Hardy', pot_size='17 cm', material='Terracotta')),
    P('N-TOMATO-SEED', 'Tomato seed, Costoluto', ['seeds'], 3.5, 'A ribbed beefsteak from our own seed bed. Forty seeds. Sow indoors in March and plant out after the last frost. Big, ribbed fruit from August.', 'a small paper seed packet with an illustration of a ribbed red tomato', attributes=dict(light='Full sun', hardiness='Tender', pot_size='', material='')),
    P('N-BEAN-SEED', 'Climbing bean seed', ['seeds'], 3, 'A purple-podded climbing bean that turns green when cooked. Fifty seeds. Sow in May, straight in the ground, beside a cane wigwam. Pick young for the best pods.', 'a small paper seed packet with an illustration of purple beans', attributes=dict(light='Full sun', hardiness='Half hardy', pot_size='', material='')),
    P('N-LETTUCE-SEED', 'Lettuce mix seed', ['seeds'], 2.5, 'Six cut-and-come-again lettuces in one packet. Sow a short row every fortnight from March. Cut the outer leaves and the plant keeps growing.', 'a small paper seed packet with an illustration of lettuce leaves', attributes=dict(light='Part shade', hardiness='Hardy', pot_size='', material='')),
    P('N-SWEET-PEA', 'Sweet pea seed', ['seeds'], 3, 'A scented old mix in every colour. Soak overnight. Sow in autumn or early spring and give them something to climb. Pick daily to keep them flowering.', 'a small paper seed packet with an illustration of sweet pea flowers', attributes=dict(light='Full sun', hardiness='Hardy', pot_size='', material='')),
    P('N-WILDFLOWER', 'Wildflower mix', ['seeds'], 6, 'Twenty native wildflowers for a square metre of bees. Sow on bare soil in spring or autumn and do not feed it. Flowers from the second month.', 'a paper seed packet with an illustration of mixed wildflowers', attributes=dict(light='Full sun', hardiness='Hardy', pot_size='', material='')),
    P('N-TULIP-BULBS', 'Tulip bulbs, 12', ['seeds'], 9, 'A dozen dark tulips for pots and borders. Plant in November. Twelve large bulbs of one dark variety. Plant them 15 cm deep in November.', 'a dozen tulip bulbs in a paper bag', axis='pot_size', values=['9 cm'], attributes=dict(light='Full sun', hardiness='Hardy', material='')),
    P('N-DAFFODIL-BULBS', 'Daffodil bulbs, 25', ['seeds'], 12, 'Small early daffodils that come back every year. Twenty-five bulbs of a small early variety for pots and grass. They multiply each year.', 'a pile of daffodil bulbs in a paper bag', attributes=dict(light='Part shade', hardiness='Hardy', pot_size='', material='')),
    P('N-GARLIC', 'Seed garlic, 3 bulbs', ['seeds'], 7, 'Hardneck garlic to plant in autumn and lift in July. Three hardneck bulbs, about thirty cloves. Plant the cloves in October, 15 cm apart.', 'three bulbs of seed garlic in a paper bag', attributes=dict(light='Full sun', hardiness='Hardy', pot_size='', material='')),
    P('N-TERRACOTTA', 'Terracotta pot', ['pots'], 8, 'A frost-proof terracotta pot with a drainage hole and a saucer. Fired at a high temperature, so it survives winter outside. Available in three sizes.', 'a plain terracotta pot with a saucer', axis='pot_size', values=['12 cm', '17 cm', '21 cm', '30 cm'], attributes=dict(light='', hardiness='', material='Terracotta')),
    P('N-GLAZED-POT', 'Glazed stoneware pot', ['pots'], 24, 'A reactive-glazed pot for indoors, with a hole. Each pot comes out of the kiln slightly different. The drainage hole and a saucer are included.', 'a {value} glazed stoneware plant pot', axis='color', values=['Green', 'White', 'Blue'], picture_per_value=True, attributes=dict(light='', hardiness='', pot_size='17 cm', material='Ceramic')),
    P('N-ZINC-PLANTER', 'Zinc trough', ['pots'], 45, 'A 60 cm zinc trough for herbs on a windowsill. Galvanised steel with drainage holes and a tray. It holds four herb pots in a row.', 'a long zinc metal planter trough', attributes=dict(light='', hardiness='', pot_size='30 cm', material='Stainless steel', dimensions='60 x 20 x 20 cm')),
    P('N-HANGING-POT', 'Hanging pot', ['pots'], 22, 'A stoneware pot on a jute hanger. A stoneware pot with a drainage plug and a jute hanger of 90 cm. Good for a trailing plant.', 'a stoneware hanging plant pot on a jute macrame hanger', attributes=dict(light='', hardiness='', pot_size='17 cm', material='Ceramic')),
    P('N-SEED-TRAY', 'Seed trays, set of 3', ['pots', 'seeds'], 12, 'Three rigid recycled trays with lids. Rigid trays that last years, with clear lids for the first weeks. They stack when empty.', 'three black seed trays with clear lids stacked', attributes=dict(light='', hardiness='', pot_size='', material='Recycled polyester')),
    P('N-RAISED-BED', 'Oak raised bed', ['pots', 'furniture'], 190, 'A 120 by 80 cm raised bed in oak sleepers, no tools needed. Oak sleepers that slot together without screws. Fill it with about 200 litres of compost.', 'a rectangular oak raised garden bed', attributes=dict(light='', hardiness='', pot_size='', material='Oak', dimensions='120 x 80 x 40 cm')),
    P('N-COMPOST', 'Peat-free compost, 40 l', ['pots'], 9, 'Our own mix for pots and beds. Bark, coir and green compost, with slow-release feed for six weeks. A 40 litre bag fills four large pots.', 'a plain kraft paper bag of compost', attributes=dict(light='', hardiness='', pot_size='', material='')),
    P('N-SPADE', 'Forged spade', ['tools'], 75, 'A forged steel spade with an ash handle, sharpened before it ships. A narrow blade with a tread, forged from one piece of steel. It comes with a twenty-year guarantee.', 'a garden spade with a steel blade and an ash wood handle', attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel')),
    P('N-FORK', 'Forged fork', ['tools'], 75, 'A four-tine fork that does not bend. Forged tines and an ash handle with a wide grip. It lifts potatoes and turns compost without bending.', 'a garden fork with steel tines and an ash handle', attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel')),
    P('N-TROWEL', 'Hand trowel', ['tools'], 22, 'A stainless trowel with an ash handle. A narrow blade for planting and a wide one for potting, both stainless. The handle is oiled ash.', 'a stainless steel hand trowel with a wooden handle', attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel')),
    P('N-SECATEURS', 'Bypass secateurs', ['tools'], 48, 'Forged bypass secateurs with a replaceable blade. Forged from steel, with a blade that unscrews for sharpening or replacing. They cut branches up to 20 mm.', 'a pair of red handled bypass secateurs', attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel')),
    P('N-WATERING-CAN', 'Watering can', ['tools'], 38, 'A 5 litre galvanised can with a brass rose. Galvanised steel with a long spout and a fine brass rose that unscrews. Balanced to pour with one hand.', 'a {value} galvanised metal watering can', axis='color', values=['Silver', 'Green'], picture_per_value=True, attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel')),
    P('N-GLOVES', 'Leather gloves', ['tools'], 18, 'Goatskin gloves that let you feel a seedling. Soft goatskin with a cotton back, in three sizes. Thorns do not get through.', 'a pair of tan leather gardening gloves', axis='size', values=['S', 'M', 'L'], attributes=dict(light='', hardiness='', pot_size='', material='Leather')),
    P('N-HOE', 'Dutch hoe', ['tools'], 42, 'A push hoe for weeds between rows. A sharp blade on a 150 cm ash handle. Walk backwards and the weeds are gone.', 'a long handled dutch hoe', attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel')),
    P('N-KNEELER', 'Kneeling pad', ['tools'], 14, 'A thick foam pad for beds and borders. Thick closed-cell foam that does not soak up water. It hangs on a hook by a loop.', 'a green foam garden kneeling pad', attributes=dict(light='', hardiness='', pot_size='', material='Rubber')),
    P('N-TOOL-SET', 'Hand tool set', ['tools'], 55, 'Trowel, fork and dibber in a canvas roll. Three stainless tools with ash handles in a canvas roll. A good first set or a good gift.', 'a hand trowel, a hand fork and a dibber in a canvas roll', attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel')),
    P('N-BENCH', 'Oak garden bench', ['furniture'], 390, 'A 150 cm oak bench that greys outside and lasts decades. Solid oak, joined with oak pegs and stainless screws. Leave it to silver or oil it once a year.', 'a solid oak garden bench', attributes=dict(light='', hardiness='', pot_size='', material='Oak', dimensions='150 x 55 x 85 cm')),
    P('N-BISTRO-SET', 'Bistro set', ['furniture'], 220, 'A folding steel table and two chairs for a balcony. Powder-coated steel that folds flat against a wall. The table is 60 cm across.', 'a {value} folding steel bistro table with two chairs', axis='color', values=['Green', 'Black', 'White'], picture_per_value=True, attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel', dimensions='60 cm table')),
    P('N-DECK-CHAIR', 'Deck chair', ['furniture'], 85, 'A beech deck chair with a striped canvas seat. Oiled beech with a canvas seat that unclips for washing. It folds flat for winter.', 'a wooden deck chair with a striped canvas seat', attributes=dict(light='', hardiness='', pot_size='', material='Oak')),
    P('N-PARASOL', 'Parasol', ['furniture'], 140, 'A 2.5 m parasol with an ash pole and a canvas cover. A 2.5 m canopy on an ash pole with a brass tilt joint. The base is sold separately.', 'a large canvas garden parasol with a wooden pole', axis='color', values=['Oatmeal', 'Green'], picture_per_value=True, attributes=dict(light='', hardiness='', pot_size='', material='Cotton')),
    P('N-FIRE-BOWL', 'Steel fire bowl', ['furniture'], 160, 'A 70 cm steel fire bowl that rusts to a warm brown. Three millimetre steel on a tripod stand. It arrives grey and turns brown in a month outside.', 'a round rusted steel fire bowl', attributes=dict(light='', hardiness='', pot_size='', material='Stainless steel', dimensions='70 cm')),
    P('N-POTTING-BENCH', 'Potting bench', ['furniture', 'tools'], 240, 'A pine potting bench with a zinc top and a shelf. A zinc top that wipes clean and a shelf for pots. Assembly takes twenty minutes.', 'a wooden potting bench with a zinc top', attributes=dict(light='', hardiness='', pot_size='', material='Oak', dimensions='120 x 50 x 90 cm')),
    P('N-STARTER-KIT', 'Kitchen garden kit', ['seeds', 'tools'], 45, 'Tomato, bean and lettuce seed, three trays and a trowel. Everything for a first season of vegetables in one box. The instructions fit on one card.', 'seed packets, seed trays and a trowel arranged together', grouped=['N-TOMATO-SEED', 'N-BEAN-SEED', 'N-LETTUCE-SEED', 'N-SEED-TRAY', 'N-TROWEL'], attributes=dict(light='', hardiness='', pot_size='', material='')),
    P('N-SHADE-SET', 'Shady corner set', ['outdoor-plants'], 34, 'A hardy fern, a hosta and a bag of compost. Two plants that thrive where nothing else will, with the compost to plant them. For a north-facing corner.', 'a fern and a hosta in pots beside a bag of compost', grouped=['N-FERN-OUTDOOR', 'N-HOSTA', 'N-COMPOST'], attributes=dict(light='Shade', hardiness='Hardy', pot_size='', material='')),
    P('N-GIFT-CARD', 'Greenhaven gift card', ['pots'], 40, 'A gift card by email, for the plant they choose. Delivered by email within the hour, with a message of your own. Valid for a year in the store.', 'a green gift card with a leaf illustration', type='virtual', attributes=dict(light='', hardiness='', pot_size='', material='')),
]
POSTS = [
    ('Which window', '<p>South windows are bright and hot: cacti, olives, pilea. East windows are gentle: ferns, calathea, pothos. North windows are for the tough ones: snake plants and the fern that forgives you.</p><p>Most plants die of kindness. Water when the top two centimetres are dry, not on a schedule.</p>', 'Houseplants on a bright windowsill with morning sun through the glass.'),
    ('Sowing in March', '<p>Tomatoes and chillies indoors on a warm windowsill now. Peas and broad beans straight into the ground. Lettuce in a tray under cover, then out in April.</p><p>Label everything. You will not remember.</p>', 'Seed trays with small seedlings and wooden labels on a sunny potting bench.'),
    ('Sharpen your tools', '<p>A sharp spade cuts roots instead of tearing them, and a sharp hoe skims weeds without effort. Ten strokes with a file along the bevel, once a month, is all it takes.</p><p>Wipe the steel with an oily rag before winter. Ash handles want a little linseed.</p>', 'A hand sharpening a spade blade with a file on a workbench in a shed.'),
]
GALLERY = [('A potting bench in a greenhouse with terracotta pots, seedlings and a trowel, sun through glass', 'houseplants'), ('Close-up of hands planting a seedling in dark soil', 'seeds'), ('A tall shot of a climbing rose on a brick wall beside a wooden door', 'outdoor-plants'), ('A row of terracotta pots with herbs on a sunny windowsill', 'pots'), ('A wooden garden chair and table on a lawn under a tree with dappled light', 'furniture')]
BRANDS = [('Greenhaven', 'NURSERY'), ('Loam', 'SOIL'), ('Terra', 'POTS'), ('Sprout', 'SEEDS'), ('Hollis', 'TOOLS'), ('Fern', 'HOUSEPLANTS'), ('Arbor', 'FURNITURE'), ('Bloom', 'BULBS'), ('Wren', 'WATERING'), ('Heath', 'GLOVES')]
GALLERY_TITLE = 'In the greenhouse'
