CODE = 'home'; ROOT = 'Home'; STORE_NAME = 'Hearthstone'; ATTRIBUTE_SET = 'Home'; WEIGHT = 3
ATTRIBUTE_COLUMNS = ['room', 'material', 'color', 'dimensions']
ATTRIBUTES = [
    dict(code='room', label='Room', input='multiselect', scope='global', filterable=1, filterable_in_search=1, visible_on_front=1, sets='Home', group='General', sort_order=50),
    dict(code='dimensions', label='Dimensions', input='text', scope='global', visible_on_front=1, comparable=1, sets='Home|Garden', group='General', sort_order=60),
]
OPTIONS = {'room': ['Living room', 'Bedroom', 'Kitchen', 'Bathroom', 'Hallway', 'Office'], 'material': ['Oak', 'Walnut', 'Ash', 'Linen', 'Wool', 'Ceramic', 'Glass', 'Stoneware', 'Brass', 'Rattan']}
ROOT_DESCRIPTION = 'Furniture, textiles and objects for a calm home, made by workshops we visit.'
META_DESCRIPTION = 'Hearthstone: sofas, tables, bedding, ceramics and lighting from small workshops, made from solid wood and natural fibres.'
PRODUCT_STYLE = 'Studio product photograph of a single piece of furniture or home object on a plain white seamless background, soft daylight, slight shadow, no people, no text, no logos, no watermark, centered with margin around it.'
SCENE_STYLE = 'Calm editorial interior photograph, oak floors, white walls, linen and wool textures, soft daylight from a large window, no people, no text, no lettering, no logos, no watermark.'
SCENES = {
    'hero-main': 'A bright living room with a linen sofa, an oak coffee table, a wool throw and a ceramic vase of dried grass, morning light.',
    'hero-side': 'A close up of a stoneware mug and a folded linen napkin on an oak table.',
    'editorial': 'A woodworker sanding an oak table top in a workshop full of daylight and sawdust.',
    'about': 'A small furniture workshop with hand tools on a pegboard and stacked planks of oak.',
}
CATEGORIES = [
    dict(path='furniture', name='Furniture', description='Solid wood tables, chairs and storage, built to be repaired.', landing_title='Built once', landing_text='Solid oak, ash and walnut, joined without screws where we can, and finished with oil you can renew at home.', scene='An oak dining table with four ash chairs in a bright room with a large window.'),
    dict(path='seating', name='Seating', description='Sofas and armchairs with replaceable covers.', landing_title='Sit for twenty years', landing_text='Feather and foam cushions on hardwood frames, with covers that zip off for washing or replacing.', scene='A linen sofa with wool cushions beside a floor lamp in a calm living room.'),
    dict(path='bedding', name='Bedding', description='Linen sheets, wool blankets and pillows that last.', landing_title='Sleep in linen', landing_text='Stonewashed linen sheets, merino blankets and pillows with a ten-year promise.', scene='An unmade bed with rumpled white linen sheets and a grey wool blanket in morning light.'),
    dict(path='kitchen', name='Kitchen & Dining', description='Stoneware, glass and wood for the table.', landing_title='For the everyday table', landing_text='Stoneware plates, hand-blown glasses and oak boards, all dishwasher safe except the boards.', scene='A wooden table set with stoneware plates, linen napkins and hand blown glasses.'),
    dict(path='lighting', name='Lighting', description='Lamps and pendants with warm bulbs included.', landing_title='Warm light only', landing_text='Every lamp ships with a 2700 K bulb. Dimmable where the design allows.', scene='A paper pendant lamp glowing warm above a wooden side table in the evening.'),
    dict(path='decor', name='Decor', description='Vases, mirrors, baskets and rugs.', landing_title='The last five percent', landing_text='Ceramics, mirrors, baskets and rugs. The pieces that make a room yours.', scene='A stoneware vase with dried grass, a round brass mirror and a rattan basket on an oak console.'),
]
HERO = dict(badge='New collection', title='A calm home, made slowly', text='Solid wood, natural fibres and workshops we visit. Furniture that gets repaired, not replaced.')
FEATURES = [('truck', 'Room-of-choice delivery', 'Two people, assembled'), ('tool', 'Repair service', 'Ten years, parts and labour'), ('arrow-back-up', '100-day trial', 'On sofas and mattresses'), ('tree', 'Certified timber', 'Every board traced')]
STORY = dict(title='We visit every workshop', text1='Hearthstone works with fourteen workshops, from a chair maker in the hills to a weaving mill by the coast. We visit each one every year.', text2='Every piece is designed to be repaired: oiled finishes, zipped covers, joints that come apart.')
PROMO = dict(badge='Outlet', title='Showroom pieces', text='Ex-display furniture with small marks and a large discount, delivered the same way.', path='furniture', button='See the outlet', list_title='From the showroom')
TESTIMONIALS = [('The oak table arrived assembled, carried to the room, and the box taken away. Perfect.', 'Elena R.', 'Munich'), ('Replaced a sofa cushion cover after four years. Same fabric, one week.', 'Marcus T.', 'Leeds'), ('The linen sheets get softer every wash. Third winter.', 'Priya S.', 'Toronto')]
NEWSLETTER = dict(title='From the workshops', text='One letter a month: new pieces, workshop visits and the outlet before it goes public.')
ABOUT = dict(title='Fourteen workshops, one shop', paragraphs=['Hearthstone began as a search for a table that would last. We found a workshop, then another, and opened a shop to sell what they made.', 'Today there are fourteen workshops. We visit every one each year, and every piece carries the name of the place it was made.', 'Everything is built to be repaired. Oiled wood, zipped covers, joints that come apart. Ten years of parts and labour.'])
REVIEWS = [
    ('Solid and beautiful', 'Heavier and better made than expected. The oil finish is lovely.', 5),
    ('Good, delivery slow', 'Great piece, but it took six weeks. Worth the wait, just plan ahead.', 4),
    ('Room of choice delivery', 'Two people carried it upstairs and took the packaging. Excellent.', 5),
    ('Cover replaced for free', 'A stain that would not come out. New cover, no charge.', 5),
    ('Linen softens fast', 'Crisp on day one, soft after three washes. Sleeping better.', 5),
    ('Colour is true', 'The oatmeal is the oatmeal in the photo. No surprises.', 5),
    ('Wobbles a little', 'One leg needed a shim on my old floor. Fine after that.', 3),
    ('Guests ask where it is from', 'Every time. The answer is always this shop.', 5),
    ('Candle burns even', 'No tunnelling, no soot, forty hours as promised.', 5),
    ('Too firm for me', 'Well made sofa, but the seat is firmer than the showroom feel I wanted.', 3),
    ('Assembled in ten minutes', 'Four bolts and a key. Instructions with actual words.', 5),
    ('Mug keeps coffee hot', 'Thick stoneware. My coffee stays warm through a whole call.', 5),
    ('Rug sheds at first', 'Wool fluff for two weeks, then it settled. Vacuum often at first.', 4),
    ('Fits the alcove exactly', 'I measured twice and it fits to the centimetre.', 5),
    ('Throw is generous', 'Big enough for two on the sofa. Fringe has not shed.', 5),
    ('Paint chipped on the edge', 'Small chip on the frame from transit. Touch-up pot sent free.', 3),
    ('Table takes a beating', 'Kids, homework, dinner. The oak just gets better.', 5),
    ('Lamp gives a warm pool', 'Perfect reading light. The switch on the cord is handy.', 5),
    ('Smells of wood', 'Opened the box and the workshop came with it.', 5),
    ('Cushion lost its shape', 'Feather filling flattens. Plump it daily or choose foam.', 3),
    ('Vase is heavy', 'Stoneware with real weight. Tulips do not tip it.', 5),
    ('Worth the wait', 'Eight weeks, made to order, and it shows in every joint.', 5),
    ('Storage inside the bench', 'I did not notice the lid lifts. Winter blankets live there now.', 5),
    ('Sheets fit a deep mattress', 'Finally a fitted sheet that stays on the corners.', 5),
]
def P(sku, name, cats, price, desc, prompt, **kw):
    d = dict(sku=sku, name=name, categories=cats, price=price, description=desc, prompt=prompt); d.update(kw); return d
PRODUCTS = [
    P('H-DINING-TABLE', 'Solid oak dining table', ['furniture', 'kitchen'], 1290, 'A 40 mm oak top on tapered legs, oiled. Seats six, eight at a squeeze.', 'a solid oak dining table with tapered legs', axis='material', values=['Oak', 'Walnut'], picture_per_value=True, attributes=dict(room='Kitchen', color='Brown', dimensions='200 x 90 x 75 cm')),
    P('H-COFFEE-TABLE', 'Round coffee table', ['furniture'], 490, 'A 90 cm round top on three turned legs, in oak or ash.', 'a round {value} wood coffee table with three legs', axis='material', values=['Oak', 'Ash'], picture_per_value=True, attributes=dict(room='Living room', color='Brown', dimensions='90 x 45 cm')),
    P('H-SIDE-TABLE', 'Side table', ['furniture'], 220, 'A small oak side table with a single drawer.', 'a small oak side table with one drawer', attributes=dict(room='Living room|Bedroom', material='Oak', color='Brown', dimensions='45 x 40 x 55 cm')),
    P('H-BOOKCASE', 'Ash bookcase', ['furniture', 'decor'], 890, 'A five-shelf bookcase in ash with an adjustable middle shelf.', 'a tall pale ash wood bookcase with five shelves', attributes=dict(room='Living room|Office', material='Ash', color='Oatmeal', dimensions='90 x 35 x 200 cm')),
    P('H-DESK', 'Oak desk', ['furniture'], 690, 'A 140 cm oak desk with a cable tray and one drawer.', 'an oak desk with a single drawer', attributes=dict(room='Office', material='Oak', color='Brown', dimensions='140 x 70 x 75 cm')),
    P('H-DINING-CHAIR', 'Ash dining chair', ['furniture', 'seating'], 210, 'A steam-bent ash chair with a woven paper cord seat.', 'an ash wood dining chair with a woven paper cord seat', axis='color', values=['Oatmeal', 'Black'], picture_per_value=True, attributes=dict(room='Kitchen', material='Ash', dimensions='50 x 48 x 80 cm')),
    P('H-BENCH', 'Oak bench', ['furniture'], 390, 'A 160 cm bench for the table or the hallway.', 'a long solid oak bench', attributes=dict(room='Kitchen|Hallway', material='Oak', color='Brown', dimensions='160 x 35 x 45 cm')),
    P('H-WARDROBE', 'Two-door wardrobe', ['furniture'], 1490, 'A solid ash wardrobe with a rail, a shelf and brass handles.', 'a two door pale ash wardrobe with brass handles', attributes=dict(room='Bedroom', material='Ash', color='Oatmeal', dimensions='120 x 60 x 200 cm')),
    P('H-BED-FRAME', 'Oak bed frame', ['furniture', 'bedding'], 990, 'A low oak platform bed with a slatted base.', 'a low oak platform bed frame with a slatted base', axis='size', values=['One size'], attributes=dict(room='Bedroom', material='Oak', color='Brown', dimensions='160 x 200 cm')),
    P('H-SOFA-3', 'Linen three-seat sofa', ['seating'], 1890, 'A three-seat sofa on a beech frame with feather-wrapped cushions and zip-off linen covers.', 'a {value} linen three seat sofa with deep cushions', axis='color', values=['Oatmeal', 'Grey', 'Green'], picture_per_value=True, attributes=dict(room='Living room', material='Linen', dimensions='220 x 95 x 85 cm')),
    P('H-SOFA-2', 'Linen two-seat sofa', ['seating'], 1490, 'The two-seat version, same frame, same covers.', 'a {value} linen two seat sofa', axis='color', values=['Oatmeal', 'Grey'], picture_per_value=True, attributes=dict(room='Living room', material='Linen', dimensions='170 x 95 x 85 cm')),
    P('H-ARMCHAIR', 'Wool armchair', ['seating'], 790, 'A deep armchair in boucle wool on oak legs.', 'a {value} boucle wool armchair on oak legs', axis='color', values=['Ivory', 'Charcoal'], picture_per_value=True, attributes=dict(room='Living room|Bedroom', material='Wool', dimensions='85 x 90 x 80 cm')),
    P('H-STOOL', 'Oak stool', ['seating', 'furniture'], 140, 'A three-legged oak stool, 45 cm high.', 'a three legged oak stool', attributes=dict(room='Kitchen|Hallway', material='Oak', color='Brown', dimensions='35 x 45 cm')),
    P('H-FLOOR-CUSHION', 'Floor cushion', ['seating', 'decor'], 90, 'A 70 cm linen floor cushion with a feather fill.', 'a large {value} linen floor cushion', axis='color', values=['Oatmeal', 'Green', 'Blue Dark'], picture_per_value=True, attributes=dict(room='Living room', material='Linen', dimensions='70 x 70 x 15 cm')),
    P('H-OTTOMAN', 'Linen ottoman', ['seating'], 390, 'A footstool that matches the sofa, with storage inside.', 'an oatmeal linen ottoman footstool', attributes=dict(room='Living room', material='Linen', color='Oatmeal', dimensions='70 x 50 x 42 cm')),
    P('H-LINEN-SHEETS', 'Linen sheet set', ['bedding'], 260, 'A fitted sheet, a flat sheet and two pillowcases in stonewashed linen.', 'a folded stack of {value} stonewashed linen sheets', axis='color', values=['White', 'Oatmeal', 'Grey', 'Blue Dark'], picture_per_value=True, attributes=dict(room='Bedroom', material='Linen', dimensions='160 x 200 cm')),
    P('H-DUVET-COVER', 'Linen duvet cover', ['bedding'], 190, 'A stonewashed linen duvet cover with coconut buttons.', 'a folded {value} linen duvet cover', axis='color', values=['White', 'Oatmeal', 'Green'], picture_per_value=True, attributes=dict(room='Bedroom', material='Linen', dimensions='200 x 200 cm')),
    P('H-WOOL-BLANKET', 'Merino blanket', ['bedding', 'decor'], 220, 'A 400 g merino blanket woven at a mill by the coast.', 'a folded {value} merino wool blanket with fringed edges', axis='color', values=['Grey', 'Oatmeal', 'Green'], picture_per_value=True, attributes=dict(room='Bedroom|Living room', material='Wool', dimensions='140 x 200 cm')),
    P('H-PILLOW', 'Feather and down pillow', ['bedding'], 70, 'A medium pillow with a cotton cover and a ten-year promise.', 'a plump white pillow', attributes=dict(room='Bedroom', material='Linen', color='White', dimensions='50 x 75 cm')),
    P('H-DUVET', 'Wool duvet', ['bedding'], 240, 'A washable wool duvet, warm in winter and cool in summer.', 'a folded white wool duvet', attributes=dict(room='Bedroom', material='Wool', color='White', dimensions='200 x 200 cm')),
    P('H-MATTRESS-TOPPER', 'Wool mattress topper', ['bedding'], 190, 'A 5 cm wool topper that softens a firm bed.', 'a folded white wool mattress topper', attributes=dict(room='Bedroom', material='Wool', color='White', dimensions='160 x 200 cm')),
    P('H-PLATES', 'Stoneware dinner plates, set of 4', ['kitchen'], 96, 'Four 27 cm plates in reactive-glazed stoneware.', 'a stack of four {value} stoneware dinner plates', axis='color', values=['White', 'Grey', 'Green'], picture_per_value=True, attributes=dict(room='Kitchen', material='Stoneware', dimensions='27 cm')),
    P('H-BOWLS', 'Stoneware bowls, set of 4', ['kitchen'], 76, 'Four 18 cm bowls for soup, pasta and cereal.', 'a stack of four {value} stoneware bowls', axis='color', values=['White', 'Grey'], picture_per_value=True, attributes=dict(room='Kitchen', material='Stoneware', dimensions='18 cm')),
    P('H-MUGS', 'Stoneware mugs, set of 2', ['kitchen'], 38, 'Two 350 ml mugs with a comfortable handle.', 'two stoneware mugs with a speckled glaze', attributes=dict(room='Kitchen', material='Stoneware', color='White', dimensions='350 ml')),
    P('H-GLASSES', 'Hand-blown tumblers, set of 6', ['kitchen'], 72, 'Six tumblers with a slight lean and tiny bubbles.', 'six clear hand blown glass tumblers', attributes=dict(room='Kitchen', material='Glass', color='White', dimensions='300 ml')),
    P('H-CARAFE', 'Glass carafe', ['kitchen'], 34, 'A one-litre carafe with an oak stopper.', 'a clear glass carafe with an oak stopper', attributes=dict(room='Kitchen', material='Glass', color='White', dimensions='1 l')),
    P('H-BOARD', 'Oak serving board', ['kitchen'], 58, 'A 50 cm oak board with a leather loop.', 'a long oak serving board with a leather loop', attributes=dict(room='Kitchen', material='Oak', color='Brown', dimensions='50 x 20 cm')),
    P('H-NAPKINS', 'Linen napkins, set of 4', ['kitchen'], 42, 'Four 45 cm linen napkins that only get better.', 'four folded {value} linen napkins', axis='color', values=['Oatmeal', 'White', 'Green'], picture_per_value=True, attributes=dict(room='Kitchen', material='Linen', dimensions='45 x 45 cm')),
    P('H-CUTLERY', 'Brushed cutlery, 16 pieces', ['kitchen'], 110, 'Four place settings in brushed stainless steel.', 'a brushed stainless steel cutlery set laid out', attributes=dict(room='Kitchen', material='Brass', color='Silver', dimensions='4 settings')),
    P('H-PENDANT', 'Paper pendant lamp', ['lighting'], 120, 'A 45 cm washi paper pendant with a bamboo ring, bulb included.', 'a round white paper pendant lamp', axis='size', values=['One size'], attributes=dict(room='Living room|Bedroom', material='Rattan', color='White', dimensions='45 cm')),
    P('H-TABLE-LAMP', 'Ceramic table lamp', ['lighting'], 160, 'A stoneware base with a linen shade and a dimmable bulb.', 'a {value} ceramic table lamp with a linen shade', axis='color', values=['White', 'Green', 'Charcoal'], picture_per_value=True, attributes=dict(room='Living room|Bedroom', material='Ceramic', dimensions='30 x 48 cm')),
    P('H-FLOOR-LAMP', 'Oak floor lamp', ['lighting'], 290, 'A tripod oak floor lamp with a linen drum shade.', 'an oak tripod floor lamp with a linen drum shade', attributes=dict(room='Living room', material='Oak', color='Brown', dimensions='55 x 150 cm')),
    P('H-WALL-LIGHT', 'Brass wall light', ['lighting'], 140, 'An adjustable brass reading light for the bedside.', 'a small brass adjustable wall reading light', attributes=dict(room='Bedroom', material='Brass', color='Yellow', dimensions='15 x 30 cm')),
    P('H-RATTAN-PENDANT', 'Rattan pendant', ['lighting'], 180, 'A hand-woven rattan pendant, 50 cm, bulb included.', 'a hand woven rattan pendant lamp shade', attributes=dict(room='Kitchen|Living room', material='Rattan', color='Tan', dimensions='50 cm')),
    P('H-CANDLE-HOLDER', 'Brass candle holders, set of 3', ['lighting', 'decor'], 48, 'Three heights in solid brass, for dinner candles.', 'three brass candle holders of different heights', attributes=dict(room='Kitchen|Living room', material='Brass', color='Yellow', dimensions='8, 12, 16 cm')),
    P('H-VASE', 'Stoneware vase', ['decor'], 68, 'A 30 cm vase with a matte glaze, for branches.', 'a tall {value} matte stoneware vase', axis='color', values=['White', 'Charcoal', 'Green'], picture_per_value=True, attributes=dict(room='Living room', material='Stoneware', dimensions='30 cm')),
    P('H-MIRROR', 'Round oak mirror', ['decor', 'seating'], 190, 'A 70 cm mirror in a slim oak frame.', 'a round mirror in a thin oak frame', attributes=dict(room='Hallway|Bedroom', material='Oak', color='Brown', dimensions='70 cm')),
    P('H-BASKET', 'Rattan basket', ['decor'], 54, 'A woven basket for logs, blankets or laundry.', 'a large woven rattan basket with handles', attributes=dict(room='Living room|Bathroom', material='Rattan', color='Tan', dimensions='45 x 40 cm')),
    P('H-RUG', 'Wool rug', ['decor'], 420, 'A flat-woven wool rug in undyed yarn.', 'a flat woven {value} wool rug rolled at one end', axis='color', values=['Oatmeal', 'Grey'], picture_per_value=True, attributes=dict(room='Living room|Bedroom', material='Wool', dimensions='170 x 240 cm')),
    P('H-CUSHION', 'Linen cushion', ['decor', 'seating'], 48, 'A 50 cm linen cushion with a feather pad.', 'a {value} linen cushion', axis='color', values=['Oatmeal', 'Green', 'Blue Dark', 'Salmon'], picture_per_value=True, attributes=dict(room='Living room|Bedroom', material='Linen', dimensions='50 x 50 cm')),
    P('H-THROW', 'Cotton throw', ['decor', 'bedding'], 90, 'A waffle-weave cotton throw for the sofa.', 'a folded {value} waffle weave cotton throw', axis='color', values=['White', 'Grey', 'Green'], picture_per_value=True, attributes=dict(room='Living room', material='Linen', dimensions='130 x 180 cm')),
    P('H-HOOKS', 'Oak wall hooks, set of 3', ['decor'], 36, 'Three turned oak hooks with brass screws.', 'three round oak wall hooks', attributes=dict(room='Hallway|Bathroom', material='Oak', color='Brown', dimensions='5 cm')),
    P('H-BATH-MAT', 'Cotton bath mat', ['decor'], 40, 'A thick cotton mat that dries by lunchtime.', 'a folded white cotton bath mat', attributes=dict(room='Bathroom', material='Linen', color='White', dimensions='50 x 80 cm')),
    P('H-TABLE-SET', 'The dining set', ['furniture', 'kitchen'], 2100, 'The oak table and four ash chairs, together.', 'an oak dining table with four ash chairs', grouped=['H-DINING-TABLE-OAK', 'H-DINING-CHAIR-OATMEAL'], attributes=dict(room='Kitchen', material='Oak', color='Brown', dimensions='')),
    P('H-BED-SET', 'The bed set', ['bedding'], 640, 'Sheets, duvet cover and two pillows in one order.', 'a made bed with white linen sheets and two pillows', grouped=['H-LINEN-SHEETS-WHITE', 'H-DUVET-COVER-WHITE', 'H-PILLOW'], attributes=dict(room='Bedroom', material='Linen', color='White', dimensions='')),
    P('H-GIFT-CARD', 'Hearthstone gift card', ['decor'], 100, 'A gift card by email, for a piece they choose.', 'a cream gift card on an oak surface', type='virtual', attributes=dict(room='', material='', color='', dimensions='')),
]
POSTS = [
    ('Caring for oiled wood', '<p>Wipe spills within the hour, use a damp cloth for the rest, and re-oil once a year: a thin coat, ten minutes, wipe off the excess. Scratches sand out with fine paper, then oil again.</p><p>Never varnish. Oil can be renewed for fifty years. Varnish has to be stripped.</p>', 'A hand rubbing oil into an oak table top with a cloth, in a sunlit workshop.'),
    ('Why linen wrinkles', '<p>Linen fibres are long and stiff, so they crease and they last. Stonewashing softens them before you do, and every wash after that does the rest.</p><p>Tumble low, take it out damp, and never iron. The wrinkles are the point.</p>', 'Rumpled white linen sheets on a bed in soft morning light, close up.'),
    ('Room of choice, explained', '<p>Two people bring the piece into the room you name, assemble it, and take the packaging away. It costs more than a doorstep drop, and we think it is the only way to deliver furniture.</p><p>Book a slot at checkout. We call the day before.</p>', 'Two delivery people carrying a wrapped sofa through a bright doorway.'),
]
MORE = {
    'H-DINING-TABLE': 'Made to order in six weeks, delivered to the room of your choice. The oil finish wipes clean and repairs with a cloth.',
    'H-COFFEE-TABLE': 'The top is 25 mm solid wood on turned legs. It arrives assembled.',
    'H-SIDE-TABLE': 'Forty centimetres square and 55 cm high, with a drawer on wooden runners. A bedside table or a lamp table.',
    'H-BOOKCASE': 'Solid ash, 90 cm wide and 200 cm tall, with a fixing kit for the wall. Each shelf holds 40 kg of books.',
    'H-DESK': 'The cable tray hides a power strip and the drawer holds a laptop. Delivered assembled.',
    'H-DINING-CHAIR': 'The cord seat is woven by hand and lasts decades. Sold singly.',
    'H-BENCH': 'Solid oak, 40 mm thick, on tapered legs. Seats three at the table.',
    'H-WARDROBE': 'Made to order in six weeks and delivered assembled. The doors close on soft hinges.',
    'H-BED-FRAME': 'Solid oak, 30 cm high, with a slatted base included. Assembly takes two people and thirty minutes.',
    'H-SOFA-3': 'The covers zip off and wash at forty degrees. Choose the linen colour from six, and the legs in oak or black.',
    'H-SOFA-2': 'A 170 cm sofa for smaller rooms. The cushions are feather-wrapped foam that keeps its shape.',
    'H-ARMCHAIR': 'Deep enough to curl up in, with a seat that holds you. The boucle comes in cream, moss and rust.',
    'H-STOOL': 'Turned legs wedged into a thick seat. A stool, a side table, a step.',
    'H-FLOOR-CUSHION': 'A washable linen cover over a feather pad. Two make a reading corner.',
    'H-OTTOMAN': 'The lid lifts on a hinge and the box inside holds blankets. The cover matches the sofa linens.',
    'H-LINEN-SHEETS': 'Stonewashed European flax that softens with every wash. The fitted sheet suits mattresses up to 35 cm deep.',
    'H-DUVET-COVER': 'Made from the same linen as the sheets, with a wide envelope closure. Available in single to super king.',
    'H-WOOL-BLANKET': 'Woven from merino yarn and finished with a blanket stitch. Light, warm and 140 by 200 cm.',
    'H-PILLOW': 'Duck feather with a down core, in a cotton cover you can wash. If it flattens within ten years, we replace it.',
    'H-DUVET': 'Wool regulates heat, so one duvet does the whole year. It washes at forty degrees.',
    'H-MATTRESS-TOPPER': 'Wool fibre on a cotton cover with elastic corners. It adds softness without heat.',
    'H-PLATES': 'Each plate is glazed by hand, so no two match. Dishwasher and oven safe.',
    'H-BOWLS': 'The same glaze as the plates, deep enough for noodles. Dishwasher safe.',
    'H-MUGS': 'Thick walls keep tea warm and hands cool. Dishwasher safe.',
    'H-GLASSES': 'Mouth-blown, so each one is a little different. Dishwasher safe on a gentle cycle.',
    'H-CARAFE': 'Thin glass with a wide base and an oak stopper. It fits a fridge door.',
    'H-BOARD': 'Cut from one plank, oiled, with a leather loop for hanging. Wash it by hand and oil it twice a year.',
    'H-NAPKINS': 'Stonewashed linen that absorbs and dries fast. Wash them with the sheets.',
    'H-CUTLERY': 'Balanced, heavy and brushed so scratches do not show. Dishwasher safe.',
    'H-PENDANT': 'Washi paper on a bamboo frame, with a two metre cord and a warm LED bulb. It hangs from a hook or a rose.',
    'H-TABLE-LAMP': 'A stoneware base in a reactive glaze with a linen shade. The dimmer is on the cord.',
    'H-FLOOR-LAMP': 'Solid oak legs and a linen shade of 45 cm. The switch is on the cord.',
    'H-WALL-LIGHT': 'Solid brass that darkens with age, with a switch on the arm. Wired for a wall box.',
    'H-RATTAN-PENDANT': 'Hand woven in a workshop we visit, with a two metre cord. The shadows on the ceiling are half the point.',
    'H-CANDLE-HOLDER': 'Solid brass that develops a patina. They hold standard dinner candles.',
    'H-VASE': 'Hand thrown, with a matte glaze and a wide neck. It holds a bundle of eucalyptus or one big branch.',
    'H-MIRROR': 'A 20 mm oak frame with a hanging plate. It arrives with the screws and the plugs.',
    'H-BASKET': 'Hand woven rattan with two handles, 50 cm wide. Good beside the fire or the sofa.',
    'H-RUG': 'Undyed wool in two natural shades, woven flat. Available in 140 by 200 and 200 by 300 cm.',
    'H-CUSHION': 'A linen cover with a hidden zip over a feather pad. Six colours to match the sofa.',
    'H-THROW': 'Waffle-weave cotton that gets softer with every wash. 130 by 180 cm.',
    'H-HOOKS': 'Turned from a single piece of oak, with brass screws and plugs. They hold a heavy coat.',
    'H-BATH-MAT': 'Thick combed cotton, 50 by 80 cm. Washes at sixty degrees.',
    'H-TABLE-SET': 'The table and four chairs together, at a saving. Delivered to the room of your choice.',
    'H-BED-SET': 'A sheet set, a duvet cover and two pillows in one order. Choose the size and the linen colour.',
    'H-GIFT-CARD': 'Delivered by email within the hour, with a message of your own. Valid for a year in the store.',
}
