CODE = 'jewelry'; ROOT = {'en': 'Jewelry', 'fr': 'Bijoux', 'de': 'Schmuck', 'it': 'Gioielli'}; STORE_NAME = 'Aurelie'; ATTRIBUTE_SET = 'Jewelry'; WEIGHT = 0.1
ATTRIBUTE_COLUMNS = ['material', 'stone', 'size', 'color']
ATTRIBUTES = [
    dict(code='stone', label='Stone', input='select', scope='global', filterable=1, filterable_in_search=1, visible_on_front=1, comparable=1, sets='Jewelry', group='General', sort_order=50),
]
OPTIONS = {'stone': ['None', 'Diamond', 'Pearl', 'Sapphire', 'Emerald', 'Moonstone', 'Onyx', 'Topaz'], 'material': ['Gold plated', 'Sterling silver', '14k gold', 'Rose gold', 'Stainless steel']}
ROOT_DESCRIPTION = {'en': 'Fine and everyday jewelry, made in a small workshop from recycled metals.',
                    'fr': 'Des bijoux fins et de tous les jours, faits dans un petit atelier avec des métaux recyclés.',
                    'de': 'Feiner und alltäglicher Schmuck, in einer kleinen Werkstatt aus recycelten Metallen gefertigt.',
                    'it': 'Gioielli fini e di tutti i giorni, fatti in un piccolo laboratorio con metalli riciclati.'}
META_DESCRIPTION = 'Aurelie: rings, necklaces, earrings and bracelets in recycled gold and silver, made to order in our workshop.'
PRODUCT_STYLE = 'Macro studio product photograph of a single piece of jewelry on a plain white seamless background, soft diffused light, subtle reflection, no hands, no text, no logos, no watermark, centered with margin around it.'
SCENE_STYLE = 'Luxurious editorial jewelry photograph, dark velvet and marble surfaces, warm low light with soft highlights, shallow depth of field, no text, no lettering, no logos, no watermark.'
SCENES = {
    'hero-main': 'A womans hand resting on dark green velvet wearing a thin gold ring and a pearl bracelet, warm side light.',
    'hero-side': 'A close up of a gold chain necklace with a small pearl pendant on black marble.',
    'editorial': 'A goldsmith at a bench polishing a ring under a lamp, tools laid out, seen from the side.',
    'about': 'A small jewelry workshop with a bench, a magnifier lamp and trays of loose stones.',
}
CATEGORIES = [
    dict(path='rings', name={'en': 'Rings', 'fr': 'Bagues', 'de': 'Ringe', 'it': 'Anelli'}, description='Bands, stacking rings and stones set by hand.', landing_title='Worn every day', landing_text='Bands and stacking rings in recycled gold and silver, sized to you and made to be worn, not kept.', scene='Three thin gold rings stacked on a dark velvet ring cushion.'),
    dict(path='necklaces', name={'en': 'Necklaces', 'fr': 'Colliers', 'de': 'Ketten', 'it': 'Collane'}, description='Chains, pendants and pearls for every neckline.', landing_title='The one you never take off', landing_text='Fine chains, small pendants and a strand of pearls. Layer them or wear one for a year.', scene='A thin gold chain with a small pendant laid on black marble beside a pearl strand.'),
    dict(path='earrings', name={'en': 'Earrings', 'fr': "Boucles d'oreilles", 'de': 'Ohrringe', 'it': 'Orecchini'}, description='Hoops, studs and drops, light enough for all day.', landing_title='Light enough to forget', landing_text='Small hoops, tiny studs and a few drops for evenings. All under three grams.', scene='A pair of gold hoop earrings and pearl studs on a dark velvet tray.'),
    dict(path='bracelets', name={'en': 'Bracelets', 'fr': 'Bracelets', 'de': 'Armbänder', 'it': 'Bracciali'}, description='Chains, cuffs and cords for one wrist or a stack.', landing_title='For the wrist', landing_text='Slim chains, a hammered cuff and silk cords with a single stone.', scene='A gold cuff and a thin chain bracelet on a marble surface with soft shadows.'),
    dict(path='engagement', name={'en': 'Engagement', 'fr': 'Fiançailles', 'de': 'Verlobung', 'it': 'Fidanzamento'}, description='Solitaires and vintage-style settings, made to order.', landing_title='Made for one person', landing_text='Solitaires, halos and vintage settings, made to order in six weeks with stones you choose.', scene='A solitaire diamond ring in an open dark green ring box on marble.'),
    dict(path='gifts', name={'en': 'Gifts', 'fr': 'Cadeaux', 'de': 'Geschenke', 'it': 'Regali'}, description='Sets and small pieces, boxed and ready.', landing_title='Small and boxed', landing_text='Matching sets and small pieces under a hundred, in a linen box with a handwritten card.', scene='A small linen gift box with a gold necklace inside, tied with a silk ribbon on marble.'),
]
HERO = dict(badge='Made to order', title='Small pieces, made slowly', text='Recycled gold and silver, stones we can trace, and a workshop where every piece is finished by hand.')
FEATURES = [('recycle', 'Recycled metals', 'Every piece, every time'), ('ruler', 'Free resizing', 'Within a year of purchase'), ('gift', 'Gift boxed', 'Linen box, handwritten card'), ('shield-check', 'Lifetime repair', 'Bring it back, we fix it')]
STORY = dict(title='A bench, not a factory', text1='Aurelie is three goldsmiths and a bench. Every piece is cast from recycled metal, set and polished by hand, and signed on the inside.', text2='If it breaks, we fix it. If it no longer fits, we resize it. Jewelry should last longer than a season.')
PROMO = dict(badge='New', title='The pearl edit', text='Freshwater pearls on gold chain, in five pieces that work together.', path='necklaces', button='See the edit', list_title='From the pearl edit')
TESTIMONIALS = [('The ring came in a linen box with a note from the goldsmith who made it. It fits perfectly.', 'Elena R.', 'Lyon'), ('Resized my grandmothers ring for free, a year after I bought mine from them.', 'Marcus T.', 'Leeds'), ('Small hoops I have not taken off in six months. Still bright.', 'Priya S.', 'Toronto')]
NEWSLETTER = dict(title='From the bench', text='A note every month: new pieces, workshop days and the occasional sample sale.')
ABOUT = dict(title='Three goldsmiths and a bench', paragraphs=['Aurelie began at a shared bench in a jewelry quarter. Three of us, one polishing motor, and a promise to use only recycled metal.', 'Every piece is cast, set and finished by hand. The stones come from two cutters we know, and every one can be traced.', 'The workshop is open on Fridays. Come and watch your ring being made.'])
REVIEWS = [
    ({'en': 'Delicate and well made', 'fr': 'Délicat et bien fait', 'de': 'Zart und gut gemacht', 'it': 'Delicato e ben fatto'}, {'en': 'Finer than the photos suggest, in a good way. The finish is flawless.',
                                'fr': 'Plus fin que sur les photos, dans le bon sens. La finition est impeccable.',
                                'de': 'Feiner als die Fotos vermuten lassen, im positiven Sinn. Die Verarbeitung ist makellos.',
                                'it': 'Più fine di quanto suggeriscano le foto, in senso buono. La finitura è impeccabile.'}, 5),
    ({'en': 'Lovely, a little small', 'fr': 'Joli, un peu petit', 'de': 'Schön, etwas klein', 'it': "Bello, un po' piccolo"}, {'en': 'Beautiful piece. The pendant is smaller than I expected, so check the size.',
                                'fr': 'Belle pièce. Le pendentif est plus petit que prévu, vérifiez la taille.',
                                'de': 'Schönes Stück. Der Anhänger ist kleiner als erwartet, prüfen Sie die Größe.',
                                'it': 'Bel pezzo. Il pendente è più piccolo del previsto, controlla la misura.'}, 4),
    ({'en': 'Worn every day', 'fr': 'Porté tous les jours', 'de': 'Jeden Tag getragen', 'it': 'Portato ogni giorno'}, {'en': 'Six months in, no tarnish, no loose stone.',
                        'fr': 'Six mois plus tard, aucun ternissement, aucune pierre qui bouge.',
                        'de': 'Nach sechs Monaten kein Anlaufen, kein loser Stein.',
                        'it': 'Dopo sei mesi nessuna opacità, nessuna pietra allentata.'}, 5),
    ({'en': 'Perfect gift', 'fr': 'Le cadeau parfait', 'de': 'Perfektes Geschenk', 'it': 'Regalo perfetto'}, {'en': 'The box and the handwritten card made it. She cried.',
                      'fr': 'La boîte et la carte écrite à la main ont tout fait. Elle a pleuré.',
                      'de': 'Die Schachtel und die handgeschriebene Karte haben es ausgemacht. Sie hat geweint.',
                      'it': 'La scatola e il biglietto scritto a mano hanno fatto tutto. Ha pianto.'}, 5),
    ({'en': 'Clasp is secure', 'fr': 'Le fermoir tient bien', 'de': 'Der Verschluss hält sicher', 'it': 'La chiusura tiene'}, {'en': 'Lobster clasp with a proper spring. Never opened by itself.',
                         'fr': "Fermoir mousqueton avec un vrai ressort. Il ne s'est jamais ouvert seul.",
                         'de': 'Karabinerverschluss mit richtiger Feder. Er hat sich nie von selbst geöffnet.',
                         'it': 'Chiusura a moschettone con una vera molla. Non si è mai aperta da sola.'}, 5),
    ({'en': 'Resized for free', 'fr': 'Mis à la taille gratuitement', 'de': 'Kostenlos geweitet', 'it': 'Ridimensionato gratis'}, {'en': 'Half a size out. Sent back, resized, returned within a week.',
                          'fr': 'Une demi-taille de trop. Renvoyé, ajusté, revenu en une semaine.',
                          'de': 'Eine halbe Größe daneben. Zurückgeschickt, angepasst, in einer Woche wieder da.',
                          'it': 'Mezza misura di troppo. Rispedito, ridimensionato, tornato in una settimana.'}, 5),
    ({'en': 'Catches the light', 'fr': 'Il accroche la lumière', 'de': 'Fängt das Licht ein', 'it': 'Prende la luce'}, {'en': 'The stone sparkles under office lights. Colleagues noticed.',
                           'fr': "La pierre brille sous les néons du bureau. Mes collègues l'ont remarqué.",
                           'de': 'Der Stein funkelt im Bürolicht. Die Kollegen haben es bemerkt.',
                           'it': "La pietra brilla sotto le luci dell'ufficio. I colleghi lo hanno notato."}, 5),
    ({'en': 'Chain is fine', 'fr': 'La chaîne est fine', 'de': 'Die Kette ist fein', 'it': 'La catena è sottile'}, {'en': 'Beautiful but very fine. I take it off for the gym.',
                       'fr': "Belle mais très fine. Je l'enlève pour la salle.",
                       'de': 'Schön, aber sehr fein. Fürs Studio nehme ich sie ab.',
                       'it': 'Bella ma molto sottile. La tolgo per la palestra.'}, 4),
    ({'en': 'Stacks well', 'fr': "Elles s'empilent bien", 'de': 'Lässt sich gut stapeln', 'it': 'Si abbinano bene'}, {'en': 'Three thin rings, worn together. That was the plan and it works.',
                     'fr': "Trois anneaux fins, portés ensemble. C'était le plan et cela marche.",
                     'de': 'Drei schmale Ringe, zusammen getragen. Das war der Plan und er geht auf.',
                     'it': 'Tre anelli sottili, portati insieme. Era il piano e funziona.'}, 5),
    ({'en': 'Earring back is tiny', 'fr': 'Le poussoir est minuscule', 'de': 'Der Verschluss ist winzig', 'it': 'Il fermaglio è minuscolo'}, {'en': 'Lovely hoops but the backs are small and easy to drop.',
                              'fr': 'De jolies créoles mais les poussoirs sont petits et faciles à perdre.',
                              'de': 'Schöne Creolen, aber die Verschlüsse sind klein und fallen leicht herunter.',
                              'it': 'Bei cerchi ma i fermagli sono piccoli e cadono facilmente.'}, 3),
    ({'en': 'Solid gold, not plated', 'fr': "De l'or massif, pas du plaqué", 'de': 'Massives Gold, nicht vergoldet', 'it': 'Oro massiccio, non placcato'}, {'en': 'You can feel the weight. Worth every penny.',
                                'fr': 'On sent le poids. Cela vaut chaque centime.',
                                'de': 'Man spürt das Gewicht. Jeden Cent wert.',
                                'it': 'Si sente il peso. Vale ogni centesimo.'}, 5),
    ({'en': 'Slight scratch on the band', 'fr': "Une légère rayure sur l'anneau", 'de': 'Leichter Kratzer am Ring', 'it': 'Un leggero graffio sulla fascia'}, {'en': 'Hairline mark out of the box. Polished it out myself.',
                                    'fr': "Une marque fine à la sortie de la boîte. Je l'ai polie moi-même.",
                                    'de': 'Haarfeiner Kratzer direkt aus der Schachtel. Ich habe ihn selbst herauspoliert.',
                                    'it': "Un segno sottilissimo appena tolto dalla scatola. L'ho lucidato da solo."}, 4),
    ({'en': 'Pearls are matched', 'fr': 'Des perles assorties', 'de': 'Die Perlen sind abgestimmt', 'it': 'Perle abbinate'}, {'en': 'Same size, same lustre, well knotted between each.',
                            'fr': 'Même taille, même éclat, bien nouées entre elles.',
                            'de': 'Gleiche Größe, gleicher Glanz, sauber zwischen jeder geknotet.',
                            'it': 'Stessa misura, stessa lucentezza, ben annodate una a una.'}, 5),
    ({'en': 'Fits the wrist', 'fr': 'Il va bien au poignet', 'de': 'Passt ans Handgelenk', 'it': 'Sta bene al polso'}, {'en': 'Cuff opens just enough. Stays put all day.',
                        'fr': "Le jonc s'ouvre juste ce qu'il faut. Il tient toute la journée.",
                        'de': 'Der Armreif öffnet sich gerade genug. Sitzt den ganzen Tag.',
                        'it': 'Il bracciale si apre quanto basta. Resta al suo posto tutto il giorno.'}, 5),
    ({'en': 'Ring box is lovely', 'fr': "L'écrin est très beau", 'de': 'Die Ringschachtel ist schön', 'it': "La scatola dell'anello è bella"}, {'en': 'The linen box is a keepsake on its own.',
                            'fr': 'La boîte en lin est un souvenir à elle seule.',
                            'de': 'Die Leinenschachtel ist für sich schon ein Andenken.',
                            'it': 'La scatola di lino è già di per sé un ricordo.'}, 5),
    ({'en': 'Wanted it bigger', 'fr': "Je l'aurais voulu plus grand", 'de': 'Hätte es größer gewollt', 'it': 'Lo volevo più grande'}, {'en': 'Beautiful stone, smaller than the photo led me to expect.',
                          'fr': 'Belle pierre, plus petite que ce que la photo laissait croire.',
                          'de': 'Schöner Stein, kleiner als das Foto erwarten ließ.',
                          'it': 'Bella pietra, più piccola di quanto lasciasse pensare la foto.'}, 4),
    ({'en': 'No green finger', 'fr': 'Pas de doigt vert', 'de': 'Kein grüner Finger', 'it': 'Nessun alone verde'}, {'en': 'A month of daily wear, no mark on the skin.',
                         'fr': 'Un mois de port quotidien, aucune marque sur la peau.',
                         'de': 'Einen Monat täglich getragen, keine Spur auf der Haut.',
                         'it': 'Un mese di uso quotidiano, nessun segno sulla pelle.'}, 5),
    ({'en': 'Engraving is crisp', 'fr': 'La gravure est nette', 'de': 'Die Gravur ist sauber', 'it': "L'incisione è netta"}, {'en': 'Two initials and a date, clean and even.',
                            'fr': 'Deux initiales et une date, propres et régulières.',
                            'de': 'Zwei Initialen und ein Datum, sauber und gleichmäßig.',
                            'it': 'Due iniziali e una data, pulite e regolari.'}, 5),
    ({'en': 'Bought a second for my sister', 'fr': "J'en ai acheté un deuxième pour ma sœur", 'de': 'Ein zweites für meine Schwester gekauft', 'it': 'Ne ho preso un secondo per mia sorella'}, {'en': 'She saw mine and now we match.',
                                       'fr': 'Elle a vu le mien et maintenant nous sommes assorties.',
                                       'de': 'Sie hat meins gesehen und jetzt tragen wir dasselbe.',
                                       'it': 'Ha visto il mio e ora siamo uguali.'}, 5),
    ({'en': 'Post is short', 'fr': 'La tige est courte', 'de': 'Der Stift ist kurz', 'it': 'Il perno è corto'}, {'en': 'Stud sits close to the ear, which I like. Bigger lobes may want longer posts.',
                       'fr': "La puce est près de l'oreille, ce que j'aime. Les lobes plus épais voudront des tiges plus longues.",
                       'de': 'Der Stecker sitzt nah am Ohr, was mir gefällt. Größere Ohrläppchen brauchen längere Stifte.',
                       'it': "Il punto luce sta vicino all'orecchio, cosa che mi piace. Lobi più grandi vorranno perni più lunghi."}, 4),
    ({'en': 'Came with a cloth', 'fr': 'Livré avec un chiffon', 'de': 'Kam mit einem Tuch', 'it': 'Arrivato con un panno'}, {'en': 'Polishing cloth and care notes in the box. Thoughtful.',
                           'fr': "Un chiffon de polissage et des conseils d'entretien dans la boîte. Bien pensé.",
                           'de': 'Poliertuch und Pflegehinweise in der Schachtel. Aufmerksam.',
                           'it': 'Panno per lucidare e istruzioni di cura nella scatola. Premuroso.'}, 5),
    ('Priced fairly', 'Compared four shops. This was the best value for the weight.', 5),
    ('Took three weeks', 'Made to order. The wait was stated, and it was worth it.', 4),
    ('Stone is set low', 'Does not catch on jumpers. A ring you can wear every day.', 5),
]
def P(sku, name, cats, price, desc, prompt, **kw):
    d = dict(sku=sku, name=name, categories=cats, price=price, description=desc, prompt=prompt); d.update(kw); return d
RING = ['48', '50', '52', '54', '56', '58']
PRODUCTS = [
    P('J-BAND-THIN', {'en': 'Thin band', 'fr': 'Anneau fin', 'de': 'Schmaler Ring', 'it': 'Fedina sottile'}, ['rings'], 120, {'en': 'A 1.5 mm round band in recycled gold, the one you stack or wear alone. Made from recycled 14 karat gold and polished by hand. Available in sizes from 46 to 62.',
        'fr': "Un anneau rond de 1,5 mm en or recyclé, celui qu'on empile ou qu'on porte seul. Fait d'or recyclé 14 carats et poli à la main. Disponible des tailles 46 à 62.",
        'de': 'Ein runder 1,5-mm-Ring aus recyceltem Gold, zum Stapeln oder allein. Aus recyceltem 14-Karat-Gold, von Hand poliert. In den Größen 46 bis 62.',
        'it': 'Una fedina tonda da 1,5 mm in oro riciclato, da abbinare o da portare da sola. Fatta in oro riciclato 14 carati e lucidata a mano. Nelle misure dalla 46 alla 62.'}, 'a thin polished gold band ring', axis='size', values=RING, attributes=dict(material='14k gold', stone='None', color='Yellow')),
    P('J-BAND-HAMMER', {'en': 'Hammered band', 'fr': 'Anneau martelé', 'de': 'Gehämmerter Ring', 'it': 'Fedina martellata'}, ['rings'], 95, {'en': 'A 3 mm band with a hand-hammered face in sterling silver. Each band is hammered by hand, so the pattern is never the same twice. Sterling silver, sizes 48 to 64.',
        'fr': "Un anneau de 3 mm à la face martelée à la main, en argent massif. Chaque anneau est martelé à la main, le motif n'est donc jamais deux fois le même. Argent massif, tailles 48 à 64.",
        'de': 'Ein 3-mm-Ring mit von Hand gehämmerter Fläche, aus Sterlingsilber. Jeder Ring wird von Hand gehämmert, das Muster ist nie zweimal gleich. Sterlingsilber, Größen 48 bis 64.',
        'it': 'Una fedina da 3 mm con superficie martellata a mano, in argento sterling. Ogni fedina è martellata a mano, quindi il motivo non è mai lo stesso. Argento sterling, misure dalla 48 alla 64.'}, 'a hammered sterling silver band ring', axis='size', values=RING, attributes=dict(material='Sterling silver', stone='None', color='Silver')),
    P('J-SIGNET', {'en': 'Oval signet ring', 'fr': 'Chevalière ovale', 'de': 'Ovaler Siegelring', 'it': 'Anello chevalier ovale'}, ['rings'], 180, {'en': 'A small oval signet in recycled gold, plain for engraving. The oval face is 9 by 7 mm, ready for one or two initials. Engraving is free and takes three days.',
        'fr': 'Une petite chevalière ovale en or recyclé, lisse pour la gravure. Le plateau ovale fait 9 sur 7 mm, prêt pour une ou deux initiales. La gravure est offerte et prend trois jours.',
        'de': 'Ein kleiner ovaler Siegelring aus recyceltem Gold, glatt zum Gravieren. Die ovale Platte misst 9 mal 7 mm, bereit für ein oder zwei Initialen. Die Gravur ist kostenlos und dauert drei Tage.',
        'it': "Un piccolo chevalier ovale in oro riciclato, liscio per l'incisione. Il piano ovale è di 9 per 7 mm, pronto per una o due iniziali. L'incisione è gratuita e richiede tre giorni."}, 'a small oval gold signet ring', axis='size', values=RING, attributes=dict(material='14k gold', stone='None', color='Yellow')),
    P('J-MOONSTONE-RING', {'en': 'Moonstone ring', 'fr': 'Bague pierre de lune', 'de': 'Mondsteinring', 'it': 'Anello con pietra di luna'}, ['rings'], 140, {'en': 'A rainbow moonstone in a low bezel on a thin gold band. The stone shows a blue flash in daylight. Set in 14 karat recycled gold.',
        'fr': "Une pierre de lune arc-en-ciel sertie clos bas sur un anneau d'or fin. La pierre lance un éclat bleu à la lumière du jour. Sertie en or recyclé 14 carats.",
        'de': 'Ein Regenbogen-Mondstein in flacher Zargenfassung auf einem schmalen Goldring. Der Stein zeigt bei Tageslicht ein blaues Aufleuchten. Gefasst in recyceltem 14-Karat-Gold.',
        'it': 'Una pietra di luna arcobaleno in castone basso su una fedina sottile di oro. La pietra manda un lampo blu alla luce del giorno. Montata in oro riciclato 14 carati.'}, 'a thin gold ring with a round white moonstone in a bezel setting', axis='size', values=RING, attributes=dict(material='14k gold', stone='Moonstone', color='Yellow')),
    P('J-SAPPHIRE-RING', {'en': 'Sapphire stacking ring', 'fr': 'Bague à empiler saphir', 'de': 'Saphir-Stapelring', 'it': 'Anello da abbinare con zaffiri'}, ['rings'], 220, {'en': 'Three tiny blue sapphires set flush in a slim gold band. The stones sit flush with the band, so nothing catches. 14 karat recycled gold.',
        'fr': "Trois minuscules saphirs bleus sertis à fleur dans un anneau d'or fin. Les pierres affleurent l'anneau, rien n'accroche. Or recyclé 14 carats.",
        'de': 'Drei winzige blaue Saphire, bündig in einen schmalen Goldring gefasst. Die Steine liegen bündig mit dem Ring, nichts bleibt hängen. Recyceltes 14-Karat-Gold.',
        'it': 'Tre piccolissimi zaffiri blu incassati a filo in una fedina sottile di oro. Le pietre stanno a filo con la fedina, quindi niente si impiglia. Oro riciclato 14 carati.'}, 'a slim gold ring with three tiny blue sapphires', axis='size', values=RING, attributes=dict(material='14k gold', stone='Sapphire', color='Yellow')),
    P('J-ONYX-RING', {'en': 'Onyx dome ring', 'fr': 'Bague dôme onyx', 'de': 'Onyx-Kuppelring', 'it': 'Anello a cupola con onice'}, ['rings'], 110, {'en': 'A black onyx cabochon in a silver dome setting. The cabochon is 10 mm across and the dome sits low on the finger. Sterling silver.',
        'fr': "Un cabochon d'onyx noir dans une monture dôme en argent. Le cabochon fait 10 mm et le dôme reste bas sur le doigt. Argent massif.",
        'de': 'Ein schwarzer Onyx-Cabochon in einer silbernen Kuppelfassung. Der Cabochon misst 10 mm und die Kuppel sitzt flach auf dem Finger. Sterlingsilber.',
        'it': 'Un cabochon di onice nera in una montatura a cupola di argento. Il cabochon è da 10 mm e la cupola resta bassa sul dito. Argento sterling.'}, 'a sterling silver ring with a black onyx cabochon', axis='size', values=RING, attributes=dict(material='Sterling silver', stone='Onyx', color='Silver')),
    P('J-TWIST-RING', {'en': 'Twist ring', 'fr': 'Bague torsadée', 'de': 'Zwirbelring', 'it': 'Anello attorcigliato'}, ['rings'], 130, {'en': 'Two thin bands twisted into one, in rose gold. Two 1.2 mm bands in 14 karat rose gold, soldered at the twist. Comfortable on its own or in a stack.',
        'fr': 'Deux anneaux fins torsadés en un seul, en or rose. Deux anneaux de 1,2 mm en or rose 14 carats, soudés à la torsade. Confortable seule ou empilée.',
        'de': 'Zwei schmale Ringe zu einem verdreht, in Roségold. Zwei 1,2-mm-Ringe aus 14-Karat-Roségold, an der Drehung verlötet. Bequem allein oder im Stapel.',
        'it': 'Due fedine sottili attorcigliate in una, in oro rosa. Due fedine da 1,2 mm in oro rosa 14 carati, saldate nel punto di torsione. Comodo da solo o abbinato.'}, 'a twisted rose gold ring', axis='size', values=RING, attributes=dict(material='Rose gold', stone='None', color='Pink')),
    P('J-CHAIN-FINE', {'en': 'Fine cable chain', 'fr': 'Chaîne forçat fine', 'de': 'Feine Ankerkette', 'it': 'Catena forzatina'}, ['necklaces'], 150, {'en': 'A 45 cm fine cable chain in recycled gold, the base for every pendant. A 1 mm cable chain with a spring clasp, in 14 karat recycled gold. Strong enough for a small pendant.',
        'fr': 'Une chaîne forçat fine de 45 cm en or recyclé, la base de tous les pendentifs. Une maille forçat de 1 mm avec un fermoir à ressort, en or recyclé 14 carats. Assez solide pour un petit pendentif.',
        'de': 'Eine feine 45-cm-Ankerkette aus recyceltem Gold, die Basis für jeden Anhänger. Ein 1-mm-Ankerglied mit Federring, aus recyceltem 14-Karat-Gold. Stark genug für einen kleinen Anhänger.',
        'it': 'Una catena forzatina fine da 45 cm in oro riciclato, la base per ogni pendente. Maglia forzatina da 1 mm con chiusura a molla, in oro riciclato 14 carati. Abbastanza robusta per un piccolo pendente.'}, 'a fine gold cable chain necklace coiled on white', attributes=dict(material='14k gold', stone='None', color='Yellow')),
    P('J-PEARL-PENDANT', {'en': 'Single pearl pendant', 'fr': 'Pendentif perle unique', 'de': 'Anhänger mit einer Perle', 'it': 'Pendente con una perla'}, ['necklaces', 'gifts'], 130, {'en': 'One freshwater pearl on a fine gold chain. A 7 mm round freshwater pearl on a 45 cm chain. Gold filled, so the colour lasts.',
        'fr': "Une perle d'eau douce sur une fine chaîne d'or. Une perle ronde d'eau douce de 7 mm sur une chaîne de 45 cm. En or laminé, la couleur tient donc.",
        'de': 'Eine Süßwasserperle an einer feinen Goldkette. Eine runde 7-mm-Süßwasserperle an einer 45-cm-Kette. Goldfilled, deshalb hält die Farbe.',
        'it': "Una perla d'acqua dolce su una catenina d'oro. Una perla tonda d'acqua dolce da 7 mm su una catena di 45 cm. In oro laminato, quindi il colore dura."}, 'a fine gold chain with a single white pearl pendant', attributes=dict(material='Gold plated', stone='Pearl', color='Yellow')),
    P('J-PEARL-STRAND', {'en': 'Freshwater pearl strand', 'fr': "Rang de perles d'eau douce", 'de': 'Süßwasserperlenkette', 'it': "Filo di perle d'acqua dolce"}, ['necklaces'], 260, {'en': 'A 42 cm strand of baroque freshwater pearls, knotted by hand. Each pearl is knotted on silk, so a break loses one pearl, not the strand. The clasp is a gold filled hook.',
        'fr': "Un rang de 42 cm de perles baroques d'eau douce, nouées à la main. Chaque perle est nouée sur soie, une casse ne coûte donc qu'une perle, pas le rang. Le fermoir est un crochet en or laminé.",
        'de': 'Eine 42-cm-Kette aus barocken Süßwasserperlen, von Hand geknotet. Jede Perle ist auf Seide geknotet, ein Riss kostet eine Perle, nicht die Kette. Der Verschluss ist ein Goldfilled-Haken.',
        'it': "Un filo di 42 cm di perle barocche d'acqua dolce, annodate a mano. Ogni perla è annodata su seta, quindi una rottura costa una perla, non il filo. La chiusura è un gancio in oro laminato."}, 'a strand of baroque freshwater pearls with a gold clasp', attributes=dict(material='Gold plated', stone='Pearl', color='White')),
    P('J-DISC-PENDANT', {'en': 'Disc pendant', 'fr': 'Pendentif disque', 'de': 'Scheibenanhänger', 'it': 'Pendente a disco'}, ['necklaces'], 140, {'en': 'A hammered 12 mm disc on a fine chain, plain for an initial. The disc is 14 karat gold on a 45 cm chain. One initial is engraved free.',
        'fr': 'Un disque martelé de 12 mm sur une chaîne fine, lisse pour une initiale. Le disque est en or 14 carats, sur une chaîne de 45 cm. Une initiale est gravée gratuitement.',
        'de': 'Eine gehämmerte 12-mm-Scheibe an einer feinen Kette, glatt für eine Initiale. Die Scheibe ist 14-Karat-Gold an einer 45-cm-Kette. Eine Initiale wird kostenlos graviert.',
        'it': "Un disco martellato da 12 mm su una catenina, liscio per un'iniziale. Il disco è in oro 14 carati su una catena di 45 cm. Un'iniziale è incisa gratis."}, 'a fine gold chain with a small hammered gold disc pendant', attributes=dict(material='14k gold', stone='None', color='Yellow')),
    P('J-BAR-NECK', {'en': 'Bar necklace', 'fr': 'Collier barrette', 'de': 'Stabkette', 'it': 'Collana con barretta'}, ['necklaces'], 120, {'en': 'A slim horizontal bar in sterling silver on a 45 cm chain. The bar is 30 mm long and 2 mm wide, polished on the front. Engraving is free.',
        'fr': 'Une fine barrette horizontale en argent massif sur une chaîne de 45 cm. La barrette fait 30 mm de long et 2 mm de large, polie sur le devant. La gravure est offerte.',
        'de': 'Ein schmaler waagerechter Stab aus Sterlingsilber an einer 45-cm-Kette. Der Stab ist 30 mm lang und 2 mm breit, vorn poliert. Die Gravur ist kostenlos.',
        'it': "Una barretta orizzontale sottile in argento sterling su una catena di 45 cm. La barretta è lunga 30 mm e larga 2 mm, lucida sul davanti. L'incisione è gratuita."}, 'a silver chain necklace with a slim horizontal bar pendant', attributes=dict(material='Sterling silver', stone='None', color='Silver')),
    P('J-EMERALD-PENDANT', {'en': 'Emerald drop pendant', 'fr': 'Pendentif goutte émeraude', 'de': 'Smaragd-Tropfenanhänger', 'it': 'Pendente a goccia con smeraldo'}, ['necklaces'], 340, {'en': 'A small pear-cut emerald in a gold bezel on a fine chain. The emerald is about 0.3 carat, set in 14 karat gold on a 42 cm chain. Each stone is a little different.',
        'fr': "Une petite émeraude taille poire sertie clos dans l'or, sur une chaîne fine. L'émeraude fait environ 0,3 carat, sertie en or 14 carats sur une chaîne de 42 cm. Chaque pierre est un peu différente.",
        'de': 'Ein kleiner Smaragd im Tropfenschliff in Goldzarge an einer feinen Kette. Der Smaragd hat etwa 0,3 Karat, gefasst in 14-Karat-Gold an einer 42-cm-Kette. Jeder Stein ist ein wenig anders.',
        'it': 'Un piccolo smeraldo taglio goccia in castone di oro su una catenina. Lo smeraldo è di circa 0,3 carati, montato in oro 14 carati su una catena di 42 cm. Ogni pietra è un po diversa.'}, 'a fine gold chain with a small green emerald drop pendant', attributes=dict(material='14k gold', stone='Emerald', color='Green')),
    P('J-CURB-CHAIN', {'en': 'Curb chain', 'fr': 'Chaîne gourmette', 'de': 'Panzerkette', 'it': 'Catena grumetta'}, ['necklaces'], 190, {'en': 'A 50 cm curb chain in sterling silver with a lobster clasp. A 4 mm curb link, solid sterling silver, with a substantial lobster clasp. Wear it alone.',
        'fr': 'Une chaîne gourmette de 50 cm en argent massif avec un fermoir mousqueton. Une maille gourmette de 4 mm, argent massif plein, avec un mousqueton solide. À porter seule.',
        'de': 'Eine 50-cm-Panzerkette aus Sterlingsilber mit Karabinerverschluss. Ein 4-mm-Panzerglied, massives Sterlingsilber, mit kräftigem Karabiner. Allein tragen.',
        'it': 'Una catena grumetta da 50 cm in argento sterling con chiusura a moschettone. Maglia grumetta da 4 mm, argento sterling pieno, con moschettone robusto. Da portare da sola.'}, 'a sterling silver curb chain necklace', attributes=dict(material='Sterling silver', stone='None', color='Silver')),
    P('J-LAYER-SET', {'en': 'Layering set', 'fr': 'Ensemble à superposer', 'de': 'Layering-Set', 'it': 'Set da sovrapporre'}, ['necklaces', 'gifts'], 250, {'en': 'The fine chain, the disc pendant and the pearl pendant, at three lengths. Three necklaces at 40, 45 and 50 cm so they sit apart. Cheaper than the three bought separately.',
        'fr': "La chaîne fine, le pendentif disque et le pendentif perle, en trois longueurs. Trois colliers de 40, 45 et 50 cm pour qu'ils ne se touchent pas. Moins cher que les trois achetés séparément.",
        'de': 'Die feine Kette, der Scheibenanhänger und der Perlenanhänger, in drei Längen. Drei Ketten mit 40, 45 und 50 cm, damit sie auseinanderliegen. Günstiger als die drei einzeln.',
        'it': 'La catenina, il pendente a disco e il pendente con perla, in tre lunghezze. Tre collane da 40, 45 e 50 cm così restano distanziate. Costa meno delle tre comprate separate.'}, 'three layered fine gold necklaces with a disc and a pearl pendant', grouped=['J-CHAIN-FINE', 'J-DISC-PENDANT', 'J-PEARL-PENDANT'], attributes=dict(material='14k gold', stone='Pearl', color='Yellow')),
    P('J-HOOP-SMALL', {'en': 'Small hoops', 'fr': 'Petites créoles', 'de': 'Kleine Creolen', 'it': 'Cerchi piccoli'}, ['earrings'], 90, {'en': 'A 12 mm hoop in recycled gold with a hinged closure. A 1.5 mm wire with a hinge that clicks shut. 14 karat recycled gold, sold as a pair.',
        'fr': 'Une créole de 12 mm en or recyclé à fermeture à charnière. Un fil de 1,5 mm avec une charnière qui claque en se fermant. Or recyclé 14 carats, vendues par paire.',
        'de': 'Eine 12-mm-Creole aus recyceltem Gold mit Scharnierverschluss. Ein 1,5-mm-Draht mit einem Scharnier, das einrastet. Recyceltes 14-Karat-Gold, als Paar verkauft.',
        'it': 'Un cerchio da 12 mm in oro riciclato con chiusura a cerniera. Filo da 1,5 mm con una cerniera che scatta. Oro riciclato 14 carati, venduti in coppia.'}, 'a pair of small polished {value} hoop earrings', axis='color', values=['Yellow', 'Silver', 'Pink'], picture_per_value=True, attributes=dict(material='14k gold', stone='None')),
    P('J-HOOP-LARGE', {'en': 'Large hoops', 'fr': 'Grandes créoles', 'de': 'Große Creolen', 'it': 'Cerchi grandi'}, ['earrings'], 140, {'en': 'A 30 mm hollow hoop, light enough for all day. A 3 mm hollow tube, so each hoop weighs under two grams. 14 karat gold, sold as a pair.',
        'fr': 'Une créole creuse de 30 mm, assez légère pour la journée entière. Un tube creux de 3 mm, chaque créole pèse donc moins de deux grammes. Or 14 carats, vendues par paire.',
        'de': 'Eine 30-mm-Hohlcreole, leicht genug für den ganzen Tag. Ein 3-mm-Hohlrohr, deshalb wiegt jede Creole unter zwei Gramm. 14-Karat-Gold, als Paar verkauft.',
        'it': 'Un cerchio cavo da 30 mm, leggero abbastanza per tutto il giorno. Tubo cavo da 3 mm, quindi ogni cerchio pesa meno di due grammi. Oro 14 carati, venduti in coppia.'}, 'a pair of large thin gold hoop earrings', attributes=dict(material='Gold plated', stone='None', color='Yellow')),
    P('J-PEARL-STUD', {'en': 'Pearl studs', 'fr': 'Puces perle', 'de': 'Perlenstecker', 'it': 'Punti luce con perla'}, ['earrings', 'gifts'], 80, {'en': 'Six millimetre freshwater pearls on gold posts. Round, white, matched pearls on 14 karat gold posts with butterfly backs. Sold as a pair.',
        'fr': "Des perles d'eau douce de six millimètres sur des tiges d'or. Des perles rondes, blanches et assorties sur des tiges en or 14 carats, avec poussoirs papillon. Vendues par paire.",
        'de': 'Sechs Millimeter Süßwasserperlen auf Goldstiften. Runde, weiße, abgestimmte Perlen auf 14-Karat-Goldstiften mit Schmetterlingsverschluss. Als Paar verkauft.',
        'it': "Perle d'acqua dolce da sei millimetri su perni d'oro. Perle tonde, bianche e abbinate su perni in oro 14 carati, con farfalline. Venduti in coppia."}, 'a pair of white pearl stud earrings on gold posts', attributes=dict(material='Gold plated', stone='Pearl', color='White')),
    P('J-DOT-STUD', {'en': 'Dot studs', 'fr': 'Puces point', 'de': 'Punkt-Stecker', 'it': 'Punti luce a sfera'}, ['earrings'], 60, {'en': 'A 3 mm polished dot, the smallest stud we make. A polished sphere on a post, in 14 karat gold. For a second piercing or a first.',
        'fr': 'Un point poli de 3 mm, la plus petite puce que nous faisons. Une sphère polie sur une tige, en or 14 carats. Pour un deuxième trou, ou un premier.',
        'de': 'Ein polierter 3-mm-Punkt, der kleinste Stecker, den wir machen. Eine polierte Kugel auf einem Stift, aus 14-Karat-Gold. Für ein zweites Loch, oder ein erstes.',
        'it': 'Una sfera lucida da 3 mm, il punto luce più piccolo che facciamo. Una sfera lucida su un perno, in oro 14 carati. Per un secondo foro, o per il primo.'}, 'a pair of tiny polished gold dot stud earrings', attributes=dict(material='14k gold', stone='None', color='Yellow')),
    P('J-DIAMOND-STUD', {'en': 'Diamond studs', 'fr': 'Puces diamant', 'de': 'Diamantstecker', 'it': 'Punti luce con diamante'}, ['earrings', 'engagement'], 420, {'en': 'Two 0.15 carat diamonds in a four-claw setting. Round brilliant diamonds, G colour, VS clarity, in 14 karat gold. Sold as a pair with a certificate.',
        'fr': 'Deux diamants de 0,15 carat sertis quatre griffes. Des diamants taille brillant, couleur G, pureté VS, en or 14 carats. Vendues par paire avec un certificat.',
        'de': 'Zwei Diamanten mit je 0,15 Karat in Vierkrappenfassung. Diamanten im Brillantschliff, Farbe G, Reinheit VS, in 14-Karat-Gold. Als Paar mit Zertifikat verkauft.',
        'it': 'Due diamanti da 0,15 carati in montatura a quattro griffe. Diamanti taglio brillante, colore G, purezza VS, in oro 14 carati. Venduti in coppia con certificato.'}, 'a pair of small diamond stud earrings in gold claw settings', attributes=dict(material='14k gold', stone='Diamond', color='Yellow')),
    P('J-DROP-TOPAZ', {'en': 'Topaz drops', 'fr': 'Pendants topaze', 'de': 'Topas-Ohrhänger', 'it': 'Orecchini pendenti con topazio'}, ['earrings'], 160, {'en': 'Pear-cut blue topaz on short gold hooks. Eight millimetre pear cuts on 14 karat gold hooks. They swing when you turn your head.',
        'fr': "Des topazes bleues taille poire sur de courts crochets d'or. Des tailles poire de huit millimètres sur des crochets en or 14 carats. Elles balancent quand on tourne la tête.",
        'de': 'Blaue Topase im Tropfenschliff an kurzen Goldhaken. Acht Millimeter Tropfenschliff an 14-Karat-Goldhaken. Sie schwingen, wenn du den Kopf drehst.',
        'it': 'Topazi blu taglio goccia su corti ganci di oro. Gocce da otto millimetri su ganci in oro 14 carati. Oscillano quando giri la testa.'}, 'a pair of blue topaz drop earrings on gold hooks', attributes=dict(material='14k gold', stone='Topaz', color='Blue')),
    P('J-THREADER', {'en': 'Chain threaders', 'fr': 'Chaînes traversantes', 'de': 'Durchzieh-Ketten', 'it': 'Orecchini a catena passante'}, ['earrings'], 110, {'en': 'A 7 cm chain that threads through the ear and hangs free. A fine cable chain with a short bar that passes through the ear. 14 karat gold, sold as a pair.',
        'fr': "Une chaîne de 7 cm qui traverse l'oreille et pend librement. Une fine chaîne forçat avec une courte barrette qui passe dans l'oreille. Or 14 carats, vendues par paire.",
        'de': 'Eine 7-cm-Kette, die durch das Ohr gezogen wird und frei hängt. Eine feine Ankerkette mit einem kurzen Stab, der durch das Ohr geht. 14-Karat-Gold, als Paar verkauft.',
        'it': "Una catenina da 7 cm che passa attraverso l'orecchio e resta libera. Una forzatina fine con una barretta corta che attraversa il lobo. Oro 14 carati, venduti in coppia."}, 'a pair of thin gold chain threader earrings', attributes=dict(material='14k gold', stone='None', color='Yellow')),
    P('J-CUFF-HAMMER', {'en': 'Hammered cuff', 'fr': 'Jonc martelé', 'de': 'Gehämmerter Armreif', 'it': 'Bracciale rigido martellato'}, ['bracelets'], 170, {'en': 'An open cuff with a hammered face in sterling silver. A 10 mm wide cuff that bends gently to fit. Sterling silver, one size.',
        'fr': "Un jonc ouvert à la face martelée, en argent massif. Un jonc de 10 mm de large qui se plie doucement pour s'ajuster. Argent massif, taille unique.",
        'de': 'Ein offener Armreif mit gehämmerter Fläche, aus Sterlingsilber. Ein 10 mm breiter Reif, der sich sanft anpassen lässt. Sterlingsilber, eine Größe.',
        'it': 'Un bracciale rigido aperto con superficie martellata, in argento sterling. Largo 10 mm, si piega con delicatezza per adattarsi. Argento sterling, taglia unica.'}, 'a hammered sterling silver open cuff bracelet', attributes=dict(material='Sterling silver', stone='None', color='Silver')),
    P('J-CHAIN-BRACELET', {'en': 'Fine chain bracelet', 'fr': 'Bracelet chaîne fine', 'de': 'Feines Kettenarmband', 'it': 'Bracciale a catenina'}, ['bracelets', 'gifts'], 95, {'en': 'A 17 cm fine chain with a 2 cm extender. A 1 mm cable chain in 14 karat gold with a spring clasp. Fits wrists from 15 to 19 cm.',
        'fr': 'Une chaîne fine de 17 cm avec une rallonge de 2 cm. Une maille forçat de 1 mm en or 14 carats avec un fermoir à ressort. Convient aux poignets de 15 à 19 cm.',
        'de': 'Eine feine 17-cm-Kette mit 2-cm-Verlängerung. Ein 1-mm-Ankerglied aus 14-Karat-Gold mit Federring. Passt an Handgelenke von 15 bis 19 cm.',
        'it': 'Una catenina da 17 cm con prolunga di 2 cm. Maglia forzatina da 1 mm in oro 14 carati con chiusura a molla. Adatta a polsi da 15 a 19 cm.'}, 'a fine gold chain bracelet', attributes=dict(material='14k gold', stone='None', color='Yellow')),
    P('J-PEARL-BRACELET', {'en': 'Pearl bracelet', 'fr': 'Bracelet de perles', 'de': 'Perlenarmband', 'it': 'Bracciale di perle'}, ['bracelets'], 140, {'en': 'Small freshwater pearls on gold wire, with a toggle clasp. Five millimetre pearls on 14 karat gold wire, with a toggle you can close with one hand. 18 cm.',
        'fr': "De petites perles d'eau douce sur un fil d'or, avec un fermoir bâtonnet. Des perles de cinq millimètres sur un fil d'or 14 carats, avec un fermoir qui se ferme d'une main. 18 cm.",
        'de': 'Kleine Süßwasserperlen auf Golddraht, mit Knebelverschluss. Fünf Millimeter Perlen auf 14-Karat-Golddraht, mit einem Knebel, den man mit einer Hand schließt. 18 cm.',
        'it': "Piccole perle d'acqua dolce su filo d'oro, con chiusura a T. Perle da cinque millimetri su filo in oro 14 carati, con una chiusura che si allaccia con una mano. 18 cm."}, 'a freshwater pearl bracelet with a gold toggle clasp', attributes=dict(material='Gold plated', stone='Pearl', color='White')),
    P('J-CORD-BRACELET', {'en': 'Silk cord bracelet', 'fr': 'Bracelet cordon de soie', 'de': 'Seidenkordel-Armband', 'it': 'Bracciale in cordoncino di seta'}, ['bracelets', 'gifts'], 55, {'en': 'A {value} silk cord with a single gold bead, adjustable. A slider knot adjusts it to any wrist. The bead is 14 karat gold.',
        'fr': "Un cordon de soie {value} avec une seule perle d'or, réglable. Un nœud coulissant l'ajuste à tous les poignets. La perle est en or 14 carats.",
        'de': 'Eine Seidenkordel in {value} mit einer einzigen Goldperle, verstellbar. Ein Schiebeknoten passt sie an jedes Handgelenk an. Die Perle ist 14-Karat-Gold.',
        'it': "Un cordoncino di seta {value} con una sola perlina d'oro, regolabile. Un nodo scorsoio lo adatta a ogni polso. La perlina è in oro 14 carati."}, 'a {value} silk cord bracelet with a single gold bead', axis='color', values=['Red', 'Blue Dark', 'Green'], picture_per_value=True, attributes=dict(material='Gold plated', stone='None')),
    P('J-BANGLE', {'en': 'Round bangle', 'fr': 'Jonc rond', 'de': 'Runder Armreif', 'it': 'Bracciale tondo'}, ['bracelets'], 210, {'en': 'A solid 3 mm round bangle in recycled gold. Solid 14 karat recycled gold, 65 mm inside. It slides over the hand.',
        'fr': 'Un jonc rond plein de 3 mm en or recyclé. Or recyclé 14 carats plein, 65 mm de diamètre intérieur. Il passe par la main.',
        'de': 'Ein massiver runder 3-mm-Armreif aus recyceltem Gold. Massives recyceltes 14-Karat-Gold, 65 mm Innendurchmesser. Er gleitet über die Hand.',
        'it': 'Un bracciale tondo pieno da 3 mm in oro riciclato. Oro riciclato 14 carati pieno, 65 mm di diametro interno. Passa dalla mano.'}, 'a thin solid gold round bangle', attributes=dict(material='14k gold', stone='None', color='Yellow')),
    P('J-ID-BRACELET', {'en': 'ID bracelet', 'fr': 'Gourmette', 'de': 'Identitätsarmband', 'it': 'Bracciale con targhetta'}, ['bracelets'], 160, {'en': 'A curb chain with a plain plate for engraving, in silver. A 4 mm curb chain with a 30 mm plate, in sterling silver. Engraving is free and takes three days.',
        'fr': 'Une chaîne gourmette avec une plaque lisse à graver, en argent. Une chaîne gourmette de 4 mm avec une plaque de 30 mm, en argent massif. La gravure est offerte et prend trois jours.',
        'de': 'Eine Panzerkette mit glatter Platte zum Gravieren, in Silber. Eine 4-mm-Panzerkette mit 30-mm-Platte, aus Sterlingsilber. Die Gravur ist kostenlos und dauert drei Tage.',
        'it': "Una catena grumetta con targhetta liscia da incidere, in argento. Catena grumetta da 4 mm con targhetta da 30 mm, in argento sterling. L'incisione è gratuita e richiede tre giorni."}, 'a sterling silver curb chain ID bracelet with a plain plate', attributes=dict(material='Sterling silver', stone='None', color='Silver')),
    P('J-SOLITAIRE', {'en': 'Classic solitaire', 'fr': 'Solitaire classique', 'de': 'Klassischer Solitär', 'it': 'Solitario classico'}, ['engagement'], 1900, {'en': 'A 0.5 carat round diamond in a six-claw setting on a slim gold band. A round brilliant diamond, G colour, VS clarity, with a certificate. Made in 14 or 18 karat gold, in your size.',
        'fr': "Un diamant rond de 0,5 carat serti six griffes sur un anneau d'or fin. Un diamant taille brillant, couleur G, pureté VS, avec un certificat. En or 14 ou 18 carats, à votre taille.",
        'de': 'Ein runder 0,5-Karat-Diamant in Sechskrappenfassung auf einem schmalen Goldring. Ein Diamant im Brillantschliff, Farbe G, Reinheit VS, mit Zertifikat. In 14- oder 18-Karat-Gold, in deiner Größe.',
        'it': 'Un diamante tondo da 0,5 carati in montatura a sei griffe su una fedina sottile di oro. Diamante taglio brillante, colore G, purezza VS, con certificato. In oro 14 o 18 carati, nella tua misura.'}, 'a classic round diamond solitaire ring in gold', axis='size', values=RING, attributes=dict(material='14k gold', stone='Diamond', color='Yellow')),
    P('J-HALO', {'en': 'Halo ring', 'fr': 'Bague halo', 'de': 'Halo-Ring', 'it': 'Anello con contorno'}, ['engagement'], 2400, {'en': 'A 0.4 carat centre stone with a halo of small diamonds. The halo makes the centre stone look larger without adding height. 14 or 18 karat gold, in your size.',
        'fr': "Une pierre centrale de 0,4 carat entourée d'un halo de petits diamants. Le halo fait paraître la pierre centrale plus grande sans ajouter de hauteur. Or 14 ou 18 carats, à votre taille.",
        'de': 'Ein 0,4-Karat-Mittelstein mit einem Kranz kleiner Diamanten. Der Kranz lässt den Mittelstein größer wirken, ohne aufzubauen. 14- oder 18-Karat-Gold, in deiner Größe.',
        'it': 'Una pietra centrale da 0,4 carati con un contorno di piccoli diamanti. Il contorno fa sembrare più grande la pietra centrale senza alzarla. Oro 14 o 18 carati, nella tua misura.'}, 'a diamond halo engagement ring in white gold', axis='size', values=RING, attributes=dict(material='14k gold', stone='Diamond', color='Silver')),
    P('J-SAPPHIRE-SOL', {'en': 'Sapphire solitaire', 'fr': 'Solitaire saphir', 'de': 'Saphir-Solitär', 'it': 'Solitario con zaffiro'}, ['engagement'], 1500, {'en': 'An oval blue sapphire in a bezel on a rose gold band. A 7 by 5 mm oval sapphire in a bezel that protects the stone. 14 karat rose gold, in your size.',
        'fr': "Un saphir bleu ovale serti clos sur un anneau d'or rose. Un saphir ovale de 7 sur 5 mm dans un serti clos qui protège la pierre. Or rose 14 carats, à votre taille.",
        'de': 'Ein ovaler blauer Saphir in Zargenfassung auf einem Roségoldring. Ein 7 mal 5 mm ovaler Saphir in einer Zarge, die den Stein schützt. 14-Karat-Roségold, in deiner Größe.',
        'it': 'Uno zaffiro blu ovale in castone su una fedina di oro rosa. Zaffiro ovale da 7 per 5 mm in un castone che protegge la pietra. Oro rosa 14 carati, nella tua misura.'}, 'an oval blue sapphire ring in a rose gold bezel', axis='size', values=RING, attributes=dict(material='Rose gold', stone='Sapphire', color='Pink')),
    P('J-VINTAGE', {'en': 'Vintage cluster', 'fr': 'Bague marguerite ancienne', 'de': 'Vintage-Blütenring', 'it': 'Anello margherita vintage'}, ['engagement'], 2100, {'en': 'A daisy cluster of seven small diamonds in a vintage setting. Seven small diamonds in a milgrain setting, about 0.35 carat in total. 14 karat gold, in your size.',
        'fr': 'Une marguerite de sept petits diamants dans une monture ancienne. Sept petits diamants sertis grain perlé, environ 0,35 carat au total. Or 14 carats, à votre taille.',
        'de': 'Eine Blüte aus sieben kleinen Diamanten in einer Vintage-Fassung. Sieben kleine Diamanten in Milgrain-Fassung, zusammen etwa 0,35 Karat. 14-Karat-Gold, in deiner Größe.',
        'it': 'Una margherita di sette piccoli diamanti in una montatura vintage. Sette piccoli diamanti in montatura millegrani, circa 0,35 carati in tutto. Oro 14 carati, nella tua misura.'}, 'a vintage style diamond daisy cluster ring in gold', axis='size', values=RING, attributes=dict(material='14k gold', stone='Diamond', color='Yellow')),
    P('J-WEDDING-BAND', {'en': 'Court wedding band', 'fr': 'Alliance profil confort', 'de': 'Trauring mit Komfortprofil', 'it': 'Fede a profilo comodo'}, ['engagement', 'rings'], 380, {'en': 'A 2.5 mm court-profile band in recycled gold. Rounded inside and out, so it sits easily on the finger. 14 or 18 karat gold, in your size.',
        'fr': 'Une alliance de 2,5 mm à profil confort en or recyclé. Arrondie dedans comme dehors, elle se porte sans gêne. Or 14 ou 18 carats, à votre taille.',
        'de': 'Ein 2,5-mm-Ring mit Komfortprofil aus recyceltem Gold. Innen wie außen gerundet, deshalb sitzt er angenehm am Finger. 14- oder 18-Karat-Gold, in deiner Größe.',
        'it': 'Una fede da 2,5 mm a profilo comodo in oro riciclato. Arrotondata dentro e fuori, quindi sta bene al dito. Oro 14 o 18 carati, nella tua misura.'}, 'a plain polished gold court wedding band', axis='size', values=RING, attributes=dict(material='14k gold', stone='None', color='Yellow')),
    P('J-ETERNITY', {'en': 'Half eternity ring', 'fr': 'Alliance demi-tour', 'de': 'Memoire-Ring, halb', 'it': 'Anello eternity a metà'}, ['engagement'], 980, {'en': 'Seven diamonds set half way round a slim band. Seven round diamonds, about 0.25 carat in total, set in 14 karat gold. It stacks against a solitaire.',
        'fr': "Sept diamants sertis sur la moitié d'un anneau fin. Sept diamants ronds, environ 0,25 carat au total, sertis en or 14 carats. Il s'empile contre un solitaire.",
        'de': 'Sieben Diamanten auf der halben Runde eines schmalen Rings. Sieben runde Diamanten, zusammen etwa 0,25 Karat, in 14-Karat-Gold gefasst. Er stapelt sich an einen Solitär.',
        'it': 'Sette diamanti montati su metà di una fedina sottile. Sette diamanti tondi, circa 0,25 carati in tutto, montati in oro 14 carati. Si abbina a un solitario.'}, 'a slim gold half eternity ring set with small diamonds', axis='size', values=RING, attributes=dict(material='14k gold', stone='Diamond', color='Yellow')),
    P('J-PEARL-SET', {'en': 'Pearl gift set', 'fr': 'Coffret perles', 'de': 'Perlen-Geschenkset', 'it': 'Set regalo di perle'}, ['gifts'], 190, {'en': 'The pearl studs and the pearl pendant, boxed together. The studs and the pendant in one linen box, with a card. Cheaper than the two bought separately.',
        'fr': 'Les puces perle et le pendentif perle, réunis en coffret. Les puces et le pendentif dans une boîte en lin, avec une carte. Moins cher que les deux achetés séparément.',
        'de': 'Die Perlenstecker und der Perlenanhänger, zusammen verpackt. Stecker und Anhänger in einer Leinenschachtel, mit Karte. Günstiger als beide einzeln.',
        'it': 'I punti luce con perla e il pendente con perla, insieme in cofanetto. I punti luce e il pendente in una scatola di lino, con un biglietto. Costa meno dei due comprati separati.'}, 'pearl stud earrings and a pearl pendant necklace in a linen gift box', grouped=['J-PEARL-STUD', 'J-PEARL-PENDANT'], attributes=dict(material='Gold plated', stone='Pearl', color='White')),
    P('J-STACK-SET', {'en': 'Stacking set', 'fr': 'Ensemble à empiler', 'de': 'Stapel-Set', 'it': 'Set di anelli da abbinare'}, ['gifts', 'rings'], 300, {'en': 'The thin band, the hammered band and the twist ring in one size. Three rings that were designed to sit together. Cheaper than the three bought separately.',
        'fr': "L'anneau fin, l'anneau martelé et la bague torsadée dans une seule taille. Trois bagues dessinées pour aller ensemble. Moins cher que les trois achetées séparément.",
        'de': 'Der schmale Ring, der gehämmerte Ring und der Zwirbelring in einer Größe. Drei Ringe, die füreinander entworfen wurden. Günstiger als die drei einzeln.',
        'it': 'La fedina sottile, la fedina martellata e l anello attorcigliato in una sola misura. Tre anelli disegnati per stare insieme. Costa meno dei tre comprati separati.'}, 'three stacked rings in gold, silver and rose gold on white', grouped=['J-BAND-THIN-52', 'J-BAND-HAMMER-52', 'J-TWIST-RING-52'], attributes=dict(material='14k gold', stone='None', color='Yellow')),
    P('J-RING-BOX', {'en': 'Linen ring box', 'fr': 'Écrin en lin', 'de': 'Ringschachtel aus Leinen', 'it': 'Scatola per anello in lino'}, ['gifts'], 18, {'en': 'A small linen box with a velvet slot, for the ring you already own. Linen outside, velvet inside, 5 cm square. Made for a proposal or a bedside.',
        'fr': 'Un petit écrin en lin avec une fente en velours, pour la bague que vous avez déjà. Lin dehors, velours dedans, 5 cm de côté. Fait pour une demande ou une table de nuit.',
        'de': 'Eine kleine Leinenschachtel mit Samtschlitz, für den Ring, den du schon hast. Leinen außen, Samt innen, 5 cm im Quadrat. Gemacht für einen Antrag oder den Nachttisch.',
        'it': 'Una piccola scatola di lino con fessura in velluto, per l anello che hai già. Lino fuori, velluto dentro, 5 cm di lato. Fatta per una proposta o per il comodino.'}, 'a small natural linen ring box open with a velvet slot', attributes=dict(material='', stone='None', color='Oatmeal')),
    P('J-POLISH-CLOTH', {'en': 'Polishing cloth', 'fr': 'Chiffon de polissage', 'de': 'Poliertuch', 'it': 'Panno per lucidare'}, ['gifts'], 8, {'en': 'A two-layer cloth that brings silver and gold back in a minute. One layer cleans and one layer shines. It works for years without washing.',
        'fr': "Un chiffon à deux couches qui ramène l'argent et l'or en une minute. Une couche nettoie, l'autre fait briller. Il sert des années sans lavage.",
        'de': 'Ein zweilagiges Tuch, das Silber und Gold in einer Minute zurückbringt. Eine Lage reinigt, eine Lage poliert. Es hält Jahre, ohne gewaschen zu werden.',
        'it': 'Un panno a due strati che riporta argento e oro in un minuto. Uno strato pulisce e uno lucida. Dura anni senza lavarlo.'}, 'a folded grey jewelry polishing cloth', attributes=dict(material='', stone='None', color='Grey')),
    P('J-JEWELRY-DISH', {'en': 'Ceramic ring dish', 'fr': 'Vide-poche en céramique', 'de': 'Keramik-Ringschale', 'it': 'Piattino per anelli in ceramica'}, ['gifts'], 22, {'en': 'A small hand-thrown dish for the bedside. A 9 cm stoneware dish with a matte glaze. A safe place for rings at night.',
        'fr': "Un petit vide-poche tourné à la main, pour la table de nuit. Un plat de grès de 9 cm à l'émail mat. Un endroit sûr pour les bagues la nuit.",
        'de': 'Eine kleine handgedrehte Schale für den Nachttisch. Eine 9-cm-Steinzeugschale mit matter Glasur. Ein sicherer Platz für Ringe in der Nacht.',
        'it': 'Un piccolo piattino tornito a mano per il comodino. Un piattino in gres da 9 cm con smalto opaco. Un posto sicuro per gli anelli di notte.'}, 'a small white ceramic ring dish with a gold rim', attributes=dict(material='', stone='None', color='White')),
    P('J-GIFT-CARD', {'en': 'Aurelie gift card', 'fr': 'Carte cadeau Aurelie', 'de': 'Aurelie Geschenkkarte', 'it': 'Carta regalo Aurelie'}, ['gifts'], 100, {'en': 'A gift card in a linen envelope, for a piece they choose. A paper card in a linen envelope, posted the same day. Any amount, valid for a year.',
        'fr': "Une carte cadeau dans une enveloppe de lin, pour une pièce qu'ils choisiront. Une carte en papier dans une enveloppe de lin, postée le jour même. N'importe quel montant, valable un an.",
        'de': 'Eine Geschenkkarte in einem Leinenumschlag, für ein Stück nach eigener Wahl. Eine Papierkarte in einem Leinenumschlag, am selben Tag verschickt. Jeder Betrag, ein Jahr gültig.',
        'it': 'Una carta regalo in una busta di lino, per un pezzo che sceglieranno loro. Una carta di carta in una busta di lino, spedita in giornata. Qualsiasi importo, valida un anno.'}, 'a cream gift card in a linen envelope with a gold seal', type='virtual', attributes=dict(material='', stone='None', color='')),
]
POSTS = [
    ('How to find your ring size', '<p>Wrap a strip of paper around the base of the finger, mark where it meets, and measure the length in millimetres. That is your size on our chart. Measure in the evening, when fingers are largest, and never in the cold.</p><p>If you are between sizes, go up. We resize for free within a year anyway.</p>', 'A hand measuring a finger with a strip of paper next to a ruler on marble.'),
    ('Why recycled gold', '<p>Gold does not wear out. Every gram we cast was once something else: a chain, a coin, a ring that no longer fit. Refined, it is chemically identical to new gold and needs no mine.</p><p>The price is the same. The story is better.</p>', 'Gold grain and small gold ingots on a dark workbench under a lamp.'),
    ('Caring for pearls', '<p>Pearls are soft. Put them on last, after perfume and hairspray, and take them off first. Wipe them with a soft cloth and let them breathe outside the box now and then.</p><p>Restring a strand every few years if you wear it often. We do it in a week.</p>', 'A strand of pearls on a soft cloth beside a small glass bottle of perfume on marble.'),
]
GALLERY = [('A woman in a black dress fastening a fine gold necklace, soft window light', 'necklaces'), ('A close-up of a hand with a thin gold ring resting on dark velvet', 'rings'), ('A tall shot of a jeweller at a bench with a loupe, tools and a scrap of leather', 'engagement'), ('Pearl and gold earrings arranged on a marble tray beside a linen ribbon', 'earrings'), ('Stacked gold bracelets on a wrist resting on a cafe table with an espresso', 'bracelets')]
BRANDS = [('Aurelie', 'ATELIER'), ('Ora', 'FINE GOLD'), ('Lune', 'PEARLS'), ('Selene', 'SILVER'), ('Maren', 'STONES'), ('Vesper', 'BRIDAL'), ('Halcyon', 'GOLDSMITHS'), ('Petra', 'GEMS'), ('Odile', 'PARIS'), ('Cassia', 'CHAINS')]
GALLERY_TITLE = 'Worn every day'
