CODE = 'kids'; ROOT = {'en': 'Kids', 'fr': 'Enfants', 'de': 'Kinder', 'it': 'Bambini'}; STORE_NAME = 'Little Lark'; ATTRIBUTE_SET = 'Kids'; WEIGHT = 0.5
ATTRIBUTE_COLUMNS = ['age_range', 'size', 'color', 'material']
ATTRIBUTES = [
    dict(code='age_range', label='Age', input='select', scope='global', filterable=1, filterable_in_search=1, visible_on_front=1, used_in_product_listing=1, sets='Kids', group='General', sort_order=50),
]
OPTIONS = {'age_range': ['0 to 1', '1 to 3', '3 to 5', '5 to 8', '8 and up'], 'size': ['62', '68', '74', '80', '86', '92', '98', '104', '110', '116', '122', '128']}
ROOT_DESCRIPTION = {'en': 'Toys, clothes and things for small rooms, chosen to last more than one child.',
                    'fr': "Jouets, vêtements et objets pour petites chambres, choisis pour durer plus d'un enfant.",
                    'de': 'Spielzeug, Kleidung und Dinge für kleine Zimmer, gewählt für mehr als ein Kind.',
                    'it': 'Giochi, vestiti e oggetti per stanze piccole, scelti per durare più di un bambino.'}
META_DESCRIPTION = 'Little Lark: wooden toys, organic cotton clothes, books, nursery furniture and outdoor gear for children from birth to eight.'
PRODUCT_STYLE = 'Studio product photograph of a single childrens product on a plain white seamless background, bright soft light, cheerful colours, no people, no text, no lettering, no logos, no watermark, centered with margin around it.'
SCENE_STYLE = 'Warm editorial photograph of a childrens room or garden, pale wood, soft pastel textiles, morning light, no faces visible, no readable text, no lettering, no logos, no watermark.'
SCENES = {
    'hero-main': 'A bright playroom with a wooden play kitchen, a pile of soft toys and a striped rug, a small child seen from behind.',
    'hero-side': 'A close up of a wooden stacking toy with rainbow rings on a pale pink blanket.',
    'editorial': 'A toymaker sanding a wooden toy car at a bench full of small painted parts.',
    'about': 'A small shop with wooden toys on low shelves and a rocking horse in the window.',
}
CATEGORIES = [
    dict(path='toys', name={'en': 'Toys', 'fr': 'Jouets', 'de': 'Spielzeug', 'it': 'Giochi'}, description='Wooden and soft toys, from rattles to construction sets.', landing_title='Toys that get handed down', landing_text='Beech, maple and organic cotton. Toys that survive a second child and a third.', scene='Wooden toys, a stacking tower, a train and a felt rabbit on a pale wooden floor.'),
    dict(path='clothing', name={'en': 'Clothing', 'fr': 'Vêtements', 'de': 'Kleidung', 'it': 'Abbigliamento'}, description='Organic cotton basics in sizes 62 to 128.', landing_title='Soft, washable, again', landing_text='Organic cotton that survives the wash, with room to grow and snaps where it matters.', scene='Small folded organic cotton clothes in pastel colours on a wooden shelf.'),
    dict(path='books', name={'en': 'Books', 'fr': 'Livres', 'de': 'Bücher', 'it': 'Libri'}, description='Board books, picture books and first readers.', landing_title='Read it again', landing_text='Books that stand up to being read a hundred times and chewed twice.', scene='A low shelf of picture books with a small chair and a soft toy.'),
    dict(path='nursery', name={'en': 'Nursery', 'fr': 'Chambre de bébé', 'de': 'Kinderzimmer', 'it': 'Cameretta'}, description='Cots, changing tables and storage in solid wood.', landing_title='A room that grows', landing_text='Cots that become beds, changing tables that become desks, and storage that stays.', scene='A calm nursery with a wooden cot, a mobile and a rocking chair in soft light.'),
    dict(path='outdoor', name={'en': 'Outdoor', 'fr': 'Plein air', 'de': 'Draußen', 'it': "All'aperto"}, description='Balance bikes, scooters and rain gear.', landing_title='Outside, in any weather', landing_text='Balance bikes, scooters, wellies and the rain suit that makes puddles a plan.', scene='A small wooden balance bike and yellow wellies by a garden gate after rain.'),
    dict(path='gifts', name={'en': 'Gifts', 'fr': 'Cadeaux', 'de': 'Geschenke', 'it': 'Regali'}, description='Boxed sets for new babies and birthdays.', landing_title='Ready to give', landing_text='Newborn boxes, birthday sets and the toys grandparents ask about.', scene='A wrapped gift box with a wooden rattle and a small knitted toy beside it.'),
]
HERO = dict(badge='New arrivals', title='Made to be handed down', text='Wooden toys, organic cotton and furniture that grows. Nothing here is for one season.')
FEATURES = [('truck', 'Free delivery over 40', 'Two to three days'), ('shield-check', 'Safety tested', 'Every toy, every batch'), ('arrow-back-up', 'Easy returns', 'Thirty days, unworn'), ('gift', 'Gift wrap', 'Free, with a card')]
STORY = dict(title='Toys that last three children', text1='Little Lark began when two parents could not find a toy that outlived a birthday. We found a toymaker in the hills, and then a mill for the cotton.', text2='Everything here is tested for safety, and then tested by our own children, which is harder.')
PROMO = dict(badge='Newborn', title='The newborn box', text='A rattle, a muslin set, a bodysuit and a board book, in a box that becomes a keepsake.', path='gifts', button='See the boxes', list_title='Gift boxes')
TESTIMONIALS = [('The wooden train has survived two boys and a dog. Still perfect.', 'Elena R.', 'Utrecht'), ('The rain suit means we go out every day now. Puddles are the plan.', 'Marcus T.', 'Leeds'), ('Bodysuits that did not shrink or twist. Rare.', 'Priya S.', 'Toronto')]
NEWSLETTER = dict(title='Small news', text='A note every month: new toys, sizes back in stock, and things we learned from our own kids.')
ABOUT = dict(title='Two parents and a toymaker', paragraphs=['Little Lark started at a kitchen table with a broken plastic toy and a question: why does nothing last?', 'We found a toymaker who works in beech and maple, and a mill that weaves organic cotton. Everything since has come from people we have met.', 'Every toy is safety tested, then tested by our own children. The second test is harder.'])
REVIEWS = [
    ({'en': 'Beautifully made', 'fr': 'Magnifiquement fait', 'de': 'Wunderschön gemacht', 'it': 'Fatto benissimo'}, {'en': 'Smooth wood, no splinters, non-toxic paint. Loved by a two year old.',
                          'fr': 'Bois lisse, aucune écharde, peinture sans toxique. Adoré par un enfant de deux ans.',
                          'de': 'Glattes Holz, keine Splitter, ungiftige Farbe. Von einem Zweijährigen geliebt.',
                          'it': 'Legno liscio, nessuna scheggia, vernice atossica. Amato da un bimbo di due anni.'}, 5),
    ({'en': 'Good, a bit small', 'fr': 'Bien, un peu petit', 'de': 'Gut, etwas klein', 'it': "Buono, un po' stretto"}, {'en': 'Lovely quality but sizes run small. Go up one.',
                           'fr': 'Belle qualité mais les tailles sont petites. Prenez une taille au-dessus.',
                           'de': 'Schöne Qualität, aber die Größen fallen klein aus. Eine Nummer größer nehmen.',
                           'it': 'Bella qualità ma le taglie vestono strette. Prendi una taglia in più.'}, 4),
    ({'en': 'Survived everything', 'fr': 'Il a tout survécu', 'de': 'Hat alles überstanden', 'it': 'Ha resistito a tutto'}, {'en': 'Washed fifty times, still soft and the colour has held.',
                             'fr': 'Lavé cinquante fois, toujours doux et la couleur a tenu.',
                             'de': 'Fünfzigmal gewaschen, immer noch weich und die Farbe hält.',
                             'it': 'Lavato cinquanta volte, ancora morbido e il colore ha tenuto.'}, 5),
    ({'en': 'Perfect present', 'fr': 'Un cadeau parfait', 'de': 'Perfektes Präsent', 'it': 'Un regalo perfetto'}, {'en': 'Wrapped, carded and delivered in two days.',
                         'fr': 'Emballé, avec une carte, livré en deux jours.',
                         'de': 'Verpackt, mit Karte, in zwei Tagen geliefert.',
                         'it': 'Confezionato, con biglietto, consegnato in due giorni.'}, 5),
    ({'en': 'Chewed and fine', 'fr': 'Mâchouillé et intact', 'de': 'Bekaut und heil', 'it': 'Masticato e intatto'}, {'en': 'Teething baby, three months of chewing, still no chips.',
                         'fr': 'Bébé qui fait ses dents, trois mois de mâchouillage, aucun éclat.',
                         'de': 'Zahnendes Baby, drei Monate Kauen, noch keine Absplitterung.',
                         'it': 'Bimbo che mette i denti, tre mesi di morsi, ancora nessuna scheggiatura.'}, 5),
    ({'en': 'Poppers instead of buttons', 'fr': 'Des pressions plutôt que des boutons', 'de': 'Druckknöpfe statt Knöpfe', 'it': 'Bottoni a pressione invece dei bottoni'}, {'en': 'Night changes are faster. Small thing, huge difference.',
                                    'fr': 'Les changes de nuit sont plus rapides. Un détail, une énorme différence.',
                                    'de': 'Das Wickeln in der Nacht geht schneller. Kleinigkeit, riesiger Unterschied.',
                                    'it': 'I cambi notturni sono più rapidi. Piccola cosa, enorme differenza.'}, 5),
    ({'en': 'Nap time favourite', 'fr': 'Le préféré de la sieste', 'de': 'Der Liebling zur Schlafenszeit', 'it': 'Il preferito del riposino'}, {'en': 'Will not sleep without the rabbit. We bought a spare.',
                            'fr': 'Il ne dort pas sans le lapin. Nous en avons acheté un deuxième.',
                            'de': 'Ohne den Hasen schläft er nicht. Wir haben einen Ersatz gekauft.',
                            'it': 'Non dorme senza il coniglio. Ne abbiamo comprato uno di scorta.'}, 5),
    ({'en': 'Wheels fell off', 'fr': 'Les roues sont tombées', 'de': 'Die Räder fielen ab', 'it': 'Le ruote si sono staccate'}, {'en': 'One wheel came loose after a week. Glued and fine, but still.',
                         'fr': "Une roue s'est détachée après une semaine. Recollée et c'est bon, mais quand même.",
                         'de': 'Ein Rad löste sich nach einer Woche. Geklebt und gut, aber trotzdem.',
                         'it': 'Una ruota si è staccata dopo una settimana. Incollata e va bene, ma comunque.'}, 3),
    ({'en': 'Grew with her', 'fr': 'Il a grandi avec elle', 'de': 'Ist mitgewachsen', 'it': 'È cresciuto con lei'}, {'en': 'Adjustable straps meant it fit from three months to a year.',
                       'fr': "Les bretelles réglables lui ont permis d'aller de trois mois à un an.",
                       'de': 'Verstellbare Gurte, also passte es von drei Monaten bis zu einem Jahr.',
                       'it': 'Le bretelle regolabili gli hanno fatto andare bene da tre mesi a un anno.'}, 5),
    ({'en': 'Colours are soft', 'fr': 'Des couleurs douces', 'de': 'Die Farben sind sanft', 'it': 'I colori sono tenui'}, {'en': 'Muted tones that do not shout. Matches the nursery.',
                          'fr': 'Des tons discrets qui ne crient pas. Assortis à la chambre.',
                          'de': 'Gedeckte Töne, die nicht schreien. Passt zum Kinderzimmer.',
                          'it': 'Toni smorzati che non urlano. Si abbinano alla cameretta.'}, 5),
    ({'en': 'Puzzle is a hit', 'fr': 'Le puzzle a du succès', 'de': 'Das Puzzle kommt an', 'it': 'Il puzzle è un successo'}, {'en': 'Ten pieces, thick wood, and the pictures make sense.',
                         'fr': 'Dix pièces, bois épais, et les images ont du sens.',
                         'de': 'Zehn Teile, dickes Holz, und die Bilder ergeben Sinn.',
                         'it': 'Dieci pezzi, legno spesso, e le figure hanno senso.'}, 5),
    ({'en': 'Zip is tricky', 'fr': 'La fermeture est difficile', 'de': 'Der Reißverschluss ist knifflig', 'it': 'La cerniera è difficile'}, {'en': 'Great coat but a stiff zip for small hands.',
                       'fr': 'Très beau manteau mais une fermeture dure pour de petites mains.',
                       'de': 'Toller Mantel, aber ein strammer Reißverschluss für kleine Hände.',
                       'it': 'Bel cappotto ma una cerniera dura per mani piccole.'}, 4),
    ({'en': 'Wooden blocks clack nicely', 'fr': 'Les cubes en bois font un joli bruit', 'de': 'Die Holzklötze klackern schön', 'it': 'I cubi di legno fanno un bel rumore'}, {'en': 'The sound is half the fun apparently.',
                                    'fr': 'Le bruit fait la moitié du plaisir, apparemment.',
                                    'de': 'Der Klang ist offenbar der halbe Spaß.',
                                    'it': 'Il suono è metà del divertimento, a quanto pare.'}, 5),
    ({'en': 'Hand-me-down ready', 'fr': 'Prêt pour le suivant', 'de': 'Bereit zum Weitergeben', 'it': 'Pronto per il fratellino'}, {'en': 'Second child wearing it now and it still looks new.',
                            'fr': "Le deuxième enfant le porte maintenant et il a l'air neuf.",
                            'de': 'Das zweite Kind trägt es jetzt und es sieht noch neu aus.',
                            'it': 'Ora lo indossa il secondo figlio e sembra ancora nuovo.'}, 5),
    ({'en': 'Instructions were clear', 'fr': 'La notice était claire', 'de': 'Die Anleitung war klar', 'it': 'Le istruzioni erano chiare'}, {'en': 'Built the kitchen in twenty minutes with a toddler helping.',
                                 'fr': "J'ai monté la cuisine en vingt minutes avec un petit qui aidait.",
                                 'de': 'Die Küche in zwanzig Minuten aufgebaut, mit einem Kleinkind als Helfer.',
                                 'it': 'Ho montato la cucina in venti minuti con un bimbo che aiutava.'}, 5),
    ({'en': 'Too warm for spring', 'fr': 'Trop chaud pour le printemps', 'de': 'Zu warm für den Frühling', 'it': 'Troppo caldo per la primavera'}, {'en': 'Beautiful knit but heavy. A winter piece.',
                             'fr': "Belle maille mais lourde. Une pièce d'hiver.",
                             'de': 'Schöner Strick, aber schwer. Ein Winterstück.',
                             'it': 'Bella maglia ma pesante. Un capo invernale.'}, 4),
    ({'en': 'Bath toy has no holes', 'fr': "Le jouet de bain n'a pas de trous", 'de': 'Das Badespielzeug hat keine Löcher', 'it': 'Il gioco da bagno non ha buchi'}, {'en': 'No mould inside. Someone thought about this.',
                               'fr': "Aucune moisissure à l'intérieur. Quelqu'un y a pensé.",
                               'de': 'Kein Schimmel innen. Da hat jemand mitgedacht.',
                               'it': 'Niente muffa dentro. Qualcuno ci ha pensato.'}, 5),
    ({'en': 'Print faded a bit', 'fr': "L'imprimé a un peu passé", 'de': 'Der Druck ist etwas verblasst', 'it': "La stampa è un po' sbiadita"}, {'en': 'Still soft, but the print lost some colour after many washes.',
                           'fr': "Toujours doux, mais l'imprimé a perdu de la couleur après de nombreux lavages.",
                           'de': 'Immer noch weich, aber der Druck hat nach vielen Wäschen Farbe verloren.',
                           'it': 'Ancora morbido, ma la stampa ha perso colore dopo molti lavaggi.'}, 3),
    ({'en': 'Stacks and knocks down', 'fr': 'On empile et on renverse', 'de': 'Stapeln und umwerfen', 'it': 'Impila e butta giù'}, {'en': 'Thirty times a day. Never gets old.',
                                'fr': "Trente fois par jour. On ne s'en lasse pas.",
                                'de': 'Dreißigmal am Tag. Wird nie langweilig.',
                                'it': 'Trenta volte al giorno. Non stanca mai.'}, 5),
    ({'en': 'Sizing chart was right', 'fr': 'Le guide des tailles était juste', 'de': 'Die Größentabelle stimmte', 'it': 'La tabella taglie era giusta'}, {'en': 'Measured, ordered, fit. Thank you for the chart.',
                                'fr': 'Mesuré, commandé, à la bonne taille. Merci pour le guide.',
                                'de': 'Gemessen, bestellt, es passt. Danke für die Tabelle.',
                                'it': 'Misurato, ordinato, calzato. Grazie per la tabella.'}, 5),
    ({'en': 'Muslin is huge', 'fr': 'Le lange est immense', 'de': 'Das Mulltuch ist riesig', 'it': 'La mussola è enorme'}, {'en': 'Big enough to swaddle and later a picnic blanket.',
                        'fr': 'Assez grand pour emmailloter et plus tard servir de nappe de pique-nique.',
                        'de': 'Groß genug zum Pucken und später als Picknickdecke.',
                        'it': 'Abbastanza grande per fasciare e poi come telo da picnic.'}, 5),
    ({'en': 'Grandparents approved', 'fr': 'Approuvé par les grands-parents', 'de': 'Von den Großeltern gebilligt', 'it': 'Approvato dai nonni'}, {'en': 'They said it looks like the toys they had. High praise.',
                               'fr': "Ils ont dit que cela ressemble aux jouets qu'ils avaient. Un beau compliment.",
                               'de': 'Sie sagten, es sehe aus wie ihr eigenes Spielzeug von damals. Großes Lob.',
                               'it': 'Hanno detto che sembra i giochi che avevano loro. Gran complimento.'}, 5),
    ({'en': 'Bib catches everything', 'fr': 'Le bavoir attrape tout', 'de': 'Das Lätzchen fängt alles auf', 'it': 'Il bavaglino prende tutto'}, {'en': 'Deep pocket, wipes clean, no more laundry after lunch.',
                                'fr': "Poche profonde, il s'essuie, plus de lessive après le déjeuner.",
                                'de': 'Tiefe Tasche, abwischbar, keine Wäsche mehr nach dem Mittagessen.',
                                'it': 'Tasca profonda, si pulisce, niente più bucato dopo pranzo.'}, 5),
    ({'en': 'Bell is loud', 'fr': 'La clochette est forte', 'de': 'Die Glocke ist laut', 'it': 'Il campanello è forte'}, {'en': 'Lovely rattle, but the bell is louder than I expected.',
                      'fr': 'Joli hochet, mais la clochette est plus forte que prévu.',
                      'de': 'Schöne Rassel, aber die Glocke ist lauter als erwartet.',
                      'it': 'Bel sonaglio, ma il campanello è più forte del previsto.'}, 4),
]
def P(sku, name, cats, price, desc, prompt, **kw):
    d = dict(sku=sku, name=name, categories=cats, price=price, description=desc, prompt=prompt); d.update(kw); return d
BABY = ['62', '68', '74', '80']
TODDLER = ['86', '92', '98', '104']
KID = ['110', '116', '122', '128']
PRODUCTS = [
    P('K-STACKER', 'Rainbow stacker', ['toys', 'gifts'], 28, 'Seven beech rings on a peg, painted with water-based colour. The rings are large enough for small hands and the peg is rounded. From twelve months.', 'a wooden rainbow ring stacking toy', attributes=dict(age_range='1 to 3', material='Oak', color='Red', size='')),
    P('K-TRAIN', 'Wooden train set', ['toys'], 65, 'A 30-piece beech track with a three-car train and a bridge. The track fits the pieces of other wooden sets. From three years.', 'a wooden train set with curved tracks and a small engine', attributes=dict(age_range='3 to 5', material='Oak', color='Brown', size='')),
    P('K-BLOCKS', 'Building blocks, 50 pieces', ['toys'], 45, 'Fifty maple blocks in a cotton bag. Cubes, arches, triangles and planks, sanded smooth and left unpainted. From eighteen months.', 'a pile of natural wooden building blocks', attributes=dict(age_range='1 to 3', material='Oak', color='Oatmeal', size='')),
    P('K-RABBIT', 'Felt rabbit', ['toys', 'gifts'], 24, 'A hand-sewn wool felt rabbit, 25 cm, with a linen dress. Filled with wool, so it is soft and light. Hand wash and it keeps its shape.', 'a small {value} felt rabbit soft toy', axis='color', values=['Grey', 'Pink', 'Oatmeal'], picture_per_value=True, attributes=dict(age_range='0 to 1', material='Wool', size='')),
    P('K-PLAY-KITCHEN', 'Play kitchen', ['toys', 'nursery'], 180, 'A birch play kitchen with a working tap sound and a chalkboard. Solid birch with two hobs, an oven door and a shelf for pans. Assembly takes twenty minutes.', 'a small wooden childrens play kitchen', attributes=dict(age_range='3 to 5', material='Oak', color='White', size='')),
    P('K-PUZZLE', 'Animal puzzle', ['toys'], 18, 'A nine-piece chunky wooden puzzle of farm animals. Thick pieces with a knob for small fingers. From eighteen months.', 'a chunky wooden puzzle with painted farm animals', attributes=dict(age_range='1 to 3', material='Oak', color='Green', size='')),
    P('K-RATTLE', 'Beech rattle', ['toys', 'gifts'], 12, 'A ring rattle in oiled beech with a bell inside. Oiled beech with no paint and a bell that cannot come out. From birth.', 'a wooden ring rattle with small beads', attributes=dict(age_range='0 to 1', material='Oak', color='Oatmeal', size='')),
    P('K-DOLL', 'Cotton doll', ['toys'], 34, 'A 35 cm soft doll in organic cotton with a removable dress. Washable at thirty degrees, hair and all. The dress comes off and goes back on.', 'a soft cotton doll with yarn hair and a striped dress', attributes=dict(age_range='1 to 3', material='Cotton', color='Pink', size='')),
    P('K-CAR-SET', 'Wooden cars, set of 3', ['toys'], 22, 'Three small cars in maple with rubber wheels. Small enough for a pocket, quiet enough for a wooden floor. From eighteen months.', 'three small painted wooden toy cars', attributes=dict(age_range='1 to 3', material='Oak', color='Blue', size='')),
    P('K-MARBLE-RUN', 'Marble run', ['toys'], 55, 'A 40-piece wooden marble run with glass marbles. The pieces stack in any order, so every run is different. From four years.', 'a wooden marble run tower with glass marbles', attributes=dict(age_range='5 to 8', material='Oak', color='Oatmeal', size='')),
    P('K-CRAFT-KIT', 'Craft box', ['toys'], 26, 'Paper, wool, glue and thirty ideas. Enough material for thirty afternoons, with the ideas on cards. From four years.', 'an open craft box with coloured paper, wool and scissors', attributes=dict(age_range='5 to 8', material='Cotton', color='Yellow', size='')),
    P('K-BOARD-GAME', 'Forest board game', ['toys'], 30, 'A cooperative game for ages five and up, twenty minutes a round. Players work together to get the animals home before nightfall. Two to four players.', 'a colourful illustrated board game box with wooden pieces', attributes=dict(age_range='5 to 8', material='Oak', color='Green', size='')),
    P('K-BODYSUIT', 'Bodysuits, 3 pack', ['clothing'], 28, 'Three long-sleeve bodysuits in organic cotton with envelope necks. Poppers at the crotch, an envelope neck for easy changes. From newborn to twenty-four months.', 'three folded {value} baby bodysuits', axis='color', values=['White', 'Oatmeal', 'Pink'], picture_per_value=True, attributes=dict(age_range='0 to 1', material='Cotton', size='')),
    P('K-SLEEPSUIT', 'Sleepsuit', ['clothing'], 22, 'A footed sleepsuit with a two-way zip. The zip runs from the foot, so a night change does not wake the top half. From newborn to two years.', 'a folded striped baby sleepsuit', axis='size', values=BABY, attributes=dict(age_range='0 to 1', material='Cotton', color='Blue Light')),
    P('K-LEGGINGS', 'Leggings, 2 pack', ['clothing'], 20, 'Two pairs of soft leggings with a wide waistband. Soft organic cotton with a little stretch and no labels inside. From six months to six years.', 'two folded pairs of {value} childrens leggings', axis='color', values=['Grey', 'Green', 'Salmon'], picture_per_value=True, attributes=dict(age_range='1 to 3', material='Cotton', size='')),
    P('K-TEE', 'Striped tee', ['clothing'], 15, 'A breton stripe tee in organic cotton. A boat neck that goes over the head without a fight. From six months to eight years.', 'a folded {value} and white striped childrens t-shirt', axis='color', values=['Blue', 'Red', 'Green'], picture_per_value=True, attributes=dict(age_range='3 to 5', material='Cotton', size='')),
    P('K-DUNGAREES', 'Cord dungarees', ['clothing'], 38, 'Corduroy dungarees with adjustable straps and knee patches. Poppers at the legs for the first year, buttons on the straps later. From six months to five years.', 'a pair of {value} corduroy childrens dungarees laid flat', axis='color', values=['Brown', 'Green', 'Blue Dark'], picture_per_value=True, attributes=dict(age_range='1 to 3', material='Cotton', size='')),
    P('K-CARDIGAN', 'Knit cardigan', ['clothing'], 34, 'A merino cardigan with wooden buttons. Soft merino that washes at thirty degrees. From newborn to six years.', 'a small {value} knitted childrens cardigan laid flat', axis='color', values=['Oatmeal', 'Green', 'Pink'], picture_per_value=True, attributes=dict(age_range='1 to 3', material='Wool', size='')),
    P('K-DRESS', 'Cotton dress', ['clothing'], 30, 'A pinafore dress in printed organic cotton. A pinafore that layers over a tee in winter and stands alone in summer. From one to eight years.', 'a childrens pinafore dress with a small floral print laid flat', axis='size', values=TODDLER, attributes=dict(age_range='3 to 5', material='Cotton', color='Yellow')),
    P('K-HOODIE', 'Hoodie', ['clothing'], 32, 'A brushed cotton hoodie with a kangaroo pocket. Brushed inside, with a hood that stays up. From two to ten years.', 'a {value} childrens hoodie laid flat', axis='color', values=['Grey', 'Blue Dark', 'Orange'], picture_per_value=True, attributes=dict(age_range='5 to 8', material='Cotton', size='')),
    P('K-JEANS', 'Soft jeans', ['clothing'], 28, 'Stretch denim with an elastic waist and no scratchy seams. Stretchy enough to climb in, soft enough to sleep in. From two to ten years.', 'a pair of childrens soft blue jeans laid flat', axis='size', values=KID, attributes=dict(age_range='5 to 8', material='Denim', color='Blue Jean')),
    P('K-SOCKS', 'Socks, 5 pack', ['clothing'], 14, 'Five pairs in soft cotton with a grip sole. A grip sole for wooden floors and a cuff that stays up. From six months to six years.', 'five pairs of small colourful childrens socks', axis='size', values=['19', '23', '27', '31'], attributes=dict(age_range='1 to 3', material='Cotton', color='Blue')),
    P('K-HAT', 'Sun hat', ['clothing', 'outdoor'], 16, 'A wide-brim cotton sun hat with a chin strap. The brim shades the neck and the strap keeps the wind from taking it. From six months to six years.', 'a {value} childrens wide brim sun hat', axis='color', values=['Oatmeal', 'Blue', 'Yellow'], picture_per_value=True, attributes=dict(age_range='1 to 3', material='Cotton', size='')),
    P('K-BOARD-BOOK', 'Board book set', ['books', 'gifts'], 24, 'Four board books about colours, animals, food and bedtime. Thick pages, rounded corners and colours that hold up to chewing. From six months.', 'four small colourful board books fanned out', attributes=dict(age_range='0 to 1', material='', color='Yellow', size='')),
    P('K-PICTURE-BOOK', 'The Lark Who Lost Her Song', ['books'], 14, 'A picture book about a bird, a storm and the neighbour who helped. Thirty-two pages with a picture on every spread. From three years.', 'a picture book with an illustrated cover of a small bird on a branch', attributes=dict(age_range='3 to 5', material='', color='Blue Light', size='')),
    P('K-BEDTIME-BOOK', 'One Hundred Goodnights', ['books'], 14, 'A hundred one-line goodnights, one page each. One line per page, so the reading stops when the eyes close. From one year.', 'a picture book with an illustrated cover of a moon over rooftops', attributes=dict(age_range='1 to 3', material='', color='Blue Dark', size='')),
    P('K-FIRST-READER', 'Otto and the Big Puddle', ['books'], 9, 'A first reader with short words and long puddles. Short chapters, big type and a joke on every page. From five years.', 'a slim childrens book with an illustrated cover of a boy in wellies', attributes=dict(age_range='5 to 8', material='', color='Yellow', size='')),
    P('K-ATLAS', 'My First Atlas', ['books'], 22, 'A large illustrated atlas with animals on every page. Every continent on a double spread, with the animals that live there. From four years.', 'a large illustrated childrens atlas with a colourful map cover', attributes=dict(age_range='5 to 8', material='', color='Green', size='')),
    P('K-COT', 'Convertible cot', ['nursery'], 390, 'A beech cot that becomes a toddler bed, with three mattress heights. Solid beech with a mattress base at three heights. It converts with the parts in the box.', 'a wooden convertible baby cot', attributes=dict(age_range='0 to 1', material='Oak', color='Oatmeal', size='')),
    P('K-CHANGING-TABLE', 'Changing table', ['nursery'], 290, 'A changing table with two shelves that becomes a desk. The top lifts off and it becomes a desk when the nappies are done. Solid birch.', 'a wooden changing table with two shelves', attributes=dict(age_range='0 to 1', material='Oak', color='White', size='')),
    P('K-ROCKER', 'Rocking chair', ['nursery'], 340, 'A nursing chair in boucle on ash rockers. Deep seat, high arms and a quiet rock. The boucle cover is removable.', 'an oatmeal boucle rocking chair on wooden rockers', attributes=dict(age_range='0 to 1', material='Wool', color='Oatmeal', size='')),
    P('K-MOBILE', 'Felt mobile', ['nursery', 'gifts'], 36, 'Clouds, a moon and three birds in wool felt. Wool felt shapes on a wooden arm that clips to a cot. It turns in a draught.', 'a felt baby mobile with clouds, a moon and small birds', attributes=dict(age_range='0 to 1', material='Wool', color='White', size='')),
    P('K-SHELF', 'Picture book shelf', ['nursery', 'books'], 90, 'A front-facing shelf so covers show. Three shallow shelves show the covers, so a child can choose. Fixings for the wall are included.', 'a low wooden front facing bookshelf for children', attributes=dict(age_range='1 to 3', material='Oak', color='Oatmeal', size='')),
    P('K-STORAGE', 'Toy storage boxes, set of 3', ['nursery'], 48, 'Three felt boxes with wooden handles. Felt boxes that fold flat and stand firm. Each one holds a season of toys.', 'three grey felt storage boxes with wooden handles', attributes=dict(age_range='1 to 3', material='Wool', color='Grey', size='')),
    P('K-NIGHT-LIGHT', 'Rabbit night light', ['nursery'], 32, 'A silicone rabbit that glows warm and dims with a tap. Tap once for warm light, twice for dim, and it turns itself off after an hour. Charges by USB-C.', 'a small white silicone rabbit night light glowing softly', attributes=dict(age_range='0 to 1', material='Rubber', color='White', size='')),
    P('K-MUSLINS', 'Muslin squares, 3 pack', ['nursery', 'gifts'], 22, 'Three large organic muslins, for everything. Large squares of double-layer organic cotton, 120 by 120 cm. Swaddle, burp cloth, sun shade.', 'three folded {value} organic muslin squares', axis='color', values=['White', 'Oatmeal', 'Green'], picture_per_value=True, attributes=dict(age_range='0 to 1', material='Cotton', size='')),
    P('K-BALANCE-BIKE', 'Balance bike', ['outdoor'], 120, 'A birch balance bike with a padded seat and 12 inch tyres. Air tyres, a low frame and a seat that rises with the child. From two years.', 'a small {value} wooden balance bike', axis='color', values=['Red', 'Green', 'Blue'], picture_per_value=True, attributes=dict(age_range='1 to 3', material='Oak', size='')),
    P('K-SCOOTER', 'Three-wheel scooter', ['outdoor'], 85, 'A lean-to-steer scooter with a light-up deck. Lean to steer, so it is easy to learn. The deck lights up when it rolls. From three years.', 'a small {value} three wheel childrens scooter', axis='color', values=['Blue', 'Pink', 'Green'], picture_per_value=True, attributes=dict(age_range='3 to 5', material='Nylon', size='')),
    P('K-RAIN-SUIT', 'Rain suit', ['outdoor', 'clothing'], 45, 'A one-piece rain suit with taped seams and welded feet loops. Waterproof to 10 000 mm with taped seams and elastic cuffs. From one to six years.', 'a {value} childrens one piece rain suit laid flat', axis='color', values=['Yellow', 'Blue Dark'], picture_per_value=True, attributes=dict(age_range='1 to 3', material='Recycled polyester', size='')),
    P('K-WELLIES', 'Wellies', ['outdoor'], 28, 'Natural rubber wellies with a pull loop. Natural rubber with a cotton lining and a loop for pulling. Sizes from 20 to 34.', 'a pair of {value} childrens rubber wellington boots', axis='color', values=['Yellow', 'Green', 'Red'], picture_per_value=True, attributes=dict(age_range='1 to 3', material='Rubber', size='')),
    P('K-HELMET', 'Kids helmet', ['outdoor'], 40, 'A light helmet with a dial fit and a rear light. Adjust the dial and the helmet fits for two years of growing. From two years.', 'a {value} childrens bike helmet', axis='color', values=['Blue', 'Pink', 'Green'], picture_per_value=True, attributes=dict(age_range='3 to 5', material='Recycled polyester', size='')),
    P('K-SAND-SET', 'Sand play set', ['outdoor'], 18, 'A bucket, a spade, a rake and two moulds in recycled plastic. Thick recycled plastic that survives a summer. The mould shapes are a fish and a star.', 'a colourful childrens sand bucket and spade set', attributes=dict(age_range='1 to 3', material='Recycled polyester', color='Yellow', size='')),
    P('K-KITE', 'Bird kite', ['outdoor'], 22, 'A single-line kite shaped like a lark, easy to launch. A single line and a tail, ready to fly from the bag. From four years.', 'a colourful bird shaped kite', attributes=dict(age_range='5 to 8', material='Nylon', color='Orange', size='')),
    P('K-NEWBORN-BOX', 'Newborn box', ['gifts'], 70, 'A rattle, three muslins, a bodysuit pack and the board books, boxed. The four things every new baby needs, in a box with a card. Wrapped on request.', 'an open gift box with a wooden rattle, muslins, bodysuits and board books', grouped=['K-RATTLE', 'K-MUSLINS-WHITE', 'K-BODYSUIT-WHITE', 'K-BOARD-BOOK'], attributes=dict(age_range='0 to 1', material='', color='', size='')),
    P('K-BIRTHDAY-BOX', 'Birthday box, age 3', ['gifts'], 95, 'A puzzle, the car set, a picture book and a sun hat. Four presents for a third birthday, chosen to be played with together. Wrapped on request.', 'an open gift box with a wooden puzzle, toy cars, a picture book and a sun hat', grouped=['K-PUZZLE', 'K-CAR-SET', 'K-PICTURE-BOOK', 'K-HAT-OATMEAL'], attributes=dict(age_range='3 to 5', material='', color='', size='')),
    P('K-GIFT-CARD', 'Little Lark gift card', ['gifts'], 30, 'A gift card by email. Delivered by email within the hour, with a message of your own. Valid for a year in the store.', 'a pale yellow gift card with a small bird illustration', type='virtual', attributes=dict(age_range='', material='', color='', size='')),
]
POSTS = [
    ('Toys by age, without the noise', '<p>Under one: things to hold, shake and chew. One to three: things to stack, push and pour. Three to five: things to pretend with. Five and up: things to build and break.</p><p>Fewer, better, and out of sight in rotation. A toy that comes back after a month is new again.</p>', 'A low shelf with a few wooden toys arranged with space between them in a bright room.'),
    ('How to size a child', '<p>Our sizes are heights in centimetres. Measure against a wall, add four for growing room, and pick the nearest size up. Trousers with an adjustable waist buy you a season.</p><p>Wash cold, dry flat, and they will fit the next child too.</p>', 'A child measured against a wall with pencil marks, seen from behind.'),
    ('Puddles are the plan', '<p>A rain suit, wellies and a warm layer underneath turn a wet day into the best day. Twenty minutes outside beats an hour of television, for everyone.</p><p>Hang the suit to dry, rinse the boots, and go again tomorrow.</p>', 'Yellow wellies jumping in a puddle on a garden path, low angle.'),
]
GALLERY = [('A child stacking wooden blocks on a rug in a sunlit playroom, seen from behind', 'toys'), ('A row of small linen clothes hanging on a wooden rail', 'clothing'), ('A tall shot of a nursery with a wooden crib, a mobile and a soft rug, morning light', 'nursery'), ('A picnic blanket in a garden with a kite, a ball and a basket of strawberries', 'outdoor'), ('A stack of picture books and a felt rabbit on a low wooden shelf', 'books')]
BRANDS = [('Little Lark', 'PLAY'), ('Pip & Pod', 'WOODEN TOYS'), ('Cloudling', 'SLEEP'), ('Wren', 'KNITS'), ('Puddle', 'OUTDOOR'), ('Fable', 'BOOKS'), ('Mimi', 'NURSERY'), ('Sprout', 'ORGANIC'), ('Tumble', 'ACTIVE'), ('Acorn', 'GIFTS')]
GALLERY_TITLE = 'Small days'
