CODE = 'kids'; ROOT = {'en': 'Kids', 'fr': 'Enfants', 'de': 'Kinder', 'it': 'Bambini'}; STORE_NAME = 'Little Lark'; ATTRIBUTE_SET = 'Kids'; WEIGHT = 0.5
ATTRIBUTE_COLUMNS = ['age_range', 'size', 'color', 'material']
ATTRIBUTES = [
    dict(code='age_range', label='Age', input='select', scope='global', filterable=1, filterable_in_search=1, visible_on_front=1, used_in_product_listing=1, sets='Kids', group='General', sort_order=50),
]
OPTIONS = {'age_range': ['0 to 1', '1 to 3', '3 to 5', '5 to 8', '8 and up'], 'size': ['62', '68', '74', '80', '86', '92', '98', '104', '110', '116', '122', '128']}
ROOT_DESCRIPTION = {'en': 'Toys, clothes and things for small rooms, chosen to last more than one child.',
                    'fr': "Jouets, vêtements et objets pour petites chambres, choisis pour durer plus d'un enfant.",
                    'de': 'Spielzeug, Kleidung und Dinge für kleine Zimmer, gewählt für mehr als ein Kind.',
                    'it': 'Giochi, vestiti e oggetti per stanze piccole, scelti per durare più di un bambino.'}
META_DESCRIPTION = 'Little Lark: wooden toys, organic cotton clothes, books, nursery furniture and outdoor gear for children from birth to eight.'
PRODUCT_STYLE = 'Studio product photograph of a single childrens product on a plain white seamless background, bright soft light, cheerful colours, no people, no text, no lettering, no logos, no watermark, centered with margin around it.'
SCENE_STYLE = 'Warm editorial photograph of a childrens room or garden, pale wood, soft pastel textiles, morning light, no faces visible, no readable text, no lettering, no logos, no watermark.'
SCENES = {
    'hero-main': 'A bright playroom with a wooden play kitchen, a pile of soft toys and a striped rug, a small child seen from behind.',
    'hero-side': 'A close up of a wooden stacking toy with rainbow rings on a pale pink blanket.',
    'editorial': 'A toymaker sanding a wooden toy car at a bench full of small painted parts.',
    'about': 'A small shop with wooden toys on low shelves and a rocking horse in the window.',
}
CATEGORIES = [
    dict(path='toys', name={'en': 'Toys', 'fr': 'Jouets', 'de': 'Spielzeug', 'it': 'Giochi'}, description='Wooden and soft toys, from rattles to construction sets.', landing_title='Toys that get handed down', landing_text='Beech, maple and organic cotton. Toys that survive a second child and a third.', scene='Wooden toys, a stacking tower, a train and a felt rabbit on a pale wooden floor.'),
    dict(path='clothing', name={'en': 'Clothing', 'fr': 'Vêtements', 'de': 'Kleidung', 'it': 'Abbigliamento'}, description='Organic cotton basics in sizes 62 to 128.', landing_title='Soft, washable, again', landing_text='Organic cotton that survives the wash, with room to grow and snaps where it matters.', scene='Small folded organic cotton clothes in pastel colours on a wooden shelf.'),
    dict(path='books', name={'en': 'Books', 'fr': 'Livres', 'de': 'Bücher', 'it': 'Libri'}, description='Board books, picture books and first readers.', landing_title='Read it again', landing_text='Books that stand up to being read a hundred times and chewed twice.', scene='A low shelf of picture books with a small chair and a soft toy.'),
    dict(path='nursery', name={'en': 'Nursery', 'fr': 'Chambre de bébé', 'de': 'Kinderzimmer', 'it': 'Cameretta'}, description='Cots, changing tables and storage in solid wood.', landing_title='A room that grows', landing_text='Cots that become beds, changing tables that become desks, and storage that stays.', scene='A calm nursery with a wooden cot, a mobile and a rocking chair in soft light.'),
    dict(path='outdoor', name={'en': 'Outdoor', 'fr': 'Plein air', 'de': 'Draußen', 'it': "All'aperto"}, description='Balance bikes, scooters and rain gear.', landing_title='Outside, in any weather', landing_text='Balance bikes, scooters, wellies and the rain suit that makes puddles a plan.', scene='A small wooden balance bike and yellow wellies by a garden gate after rain.'),
    dict(path='gifts', name={'en': 'Gifts', 'fr': 'Cadeaux', 'de': 'Geschenke', 'it': 'Regali'}, description='Boxed sets for new babies and birthdays.', landing_title='Ready to give', landing_text='Newborn boxes, birthday sets and the toys grandparents ask about.', scene='A wrapped gift box with a wooden rattle and a small knitted toy beside it.'),
]
HERO = dict(badge='New arrivals', title='Made to be handed down', text='Wooden toys, organic cotton and furniture that grows. Nothing here is for one season.')
FEATURES = [('truck', 'Free delivery over 40', 'Two to three days'), ('shield-check', 'Safety tested', 'Every toy, every batch'), ('arrow-back-up', 'Easy returns', 'Thirty days, unworn'), ('gift', 'Gift wrap', 'Free, with a card')]
STORY = dict(title='Toys that last three children', text1='Little Lark began when two parents could not find a toy that outlived a birthday. We found a toymaker in the hills, and then a mill for the cotton.', text2='Everything here is tested for safety, and then tested by our own children, which is harder.')
PROMO = dict(badge='Newborn', title='The newborn box', text='A rattle, a muslin set, a bodysuit and a board book, in a box that becomes a keepsake.', path='gifts', button='See the boxes', list_title='Gift boxes')
TESTIMONIALS = [('The wooden train has survived two boys and a dog. Still perfect.', 'Elena R.', 'Utrecht'), ('The rain suit means we go out every day now. Puddles are the plan.', 'Marcus T.', 'Leeds'), ('Bodysuits that did not shrink or twist. Rare.', 'Priya S.', 'Toronto')]
NEWSLETTER = dict(title='Small news', text='A note every month: new toys, sizes back in stock, and things we learned from our own kids.')
ABOUT = dict(title='Two parents and a toymaker', paragraphs=['Little Lark started at a kitchen table with a broken plastic toy and a question: why does nothing last?', 'We found a toymaker who works in beech and maple, and a mill that weaves organic cotton. Everything since has come from people we have met.', 'Every toy is safety tested, then tested by our own children. The second test is harder.'])
REVIEWS = [
    ({'en': 'Beautifully made', 'fr': 'Magnifiquement fait', 'de': 'Wunderschön gemacht', 'it': 'Fatto benissimo'}, {'en': 'Smooth wood, no splinters, non-toxic paint. Loved by a two year old.',
                          'fr': 'Bois lisse, aucune écharde, peinture sans toxique. Adoré par un enfant de deux ans.',
                          'de': 'Glattes Holz, keine Splitter, ungiftige Farbe. Von einem Zweijährigen geliebt.',
                          'it': 'Legno liscio, nessuna scheggia, vernice atossica. Amato da un bimbo di due anni.'}, 5),
    ({'en': 'Good, a bit small', 'fr': 'Bien, un peu petit', 'de': 'Gut, etwas klein', 'it': "Buono, un po' stretto"}, {'en': 'Lovely quality but sizes run small. Go up one.',
                           'fr': 'Belle qualité mais les tailles sont petites. Prenez une taille au-dessus.',
                           'de': 'Schöne Qualität, aber die Größen fallen klein aus. Eine Nummer größer nehmen.',
                           'it': 'Bella qualità ma le taglie vestono strette. Prendi una taglia in più.'}, 4),
    ({'en': 'Survived everything', 'fr': 'Il a tout survécu', 'de': 'Hat alles überstanden', 'it': 'Ha resistito a tutto'}, {'en': 'Washed fifty times, still soft and the colour has held.',
                             'fr': 'Lavé cinquante fois, toujours doux et la couleur a tenu.',
                             'de': 'Fünfzigmal gewaschen, immer noch weich und die Farbe hält.',
                             'it': 'Lavato cinquanta volte, ancora morbido e il colore ha tenuto.'}, 5),
    ({'en': 'Perfect present', 'fr': 'Un cadeau parfait', 'de': 'Perfektes Präsent', 'it': 'Un regalo perfetto'}, {'en': 'Wrapped, carded and delivered in two days.',
                         'fr': 'Emballé, avec une carte, livré en deux jours.',
                         'de': 'Verpackt, mit Karte, in zwei Tagen geliefert.',
                         'it': 'Confezionato, con biglietto, consegnato in due giorni.'}, 5),
    ({'en': 'Chewed and fine', 'fr': 'Mâchouillé et intact', 'de': 'Bekaut und heil', 'it': 'Masticato e intatto'}, {'en': 'Teething baby, three months of chewing, still no chips.',
                         'fr': 'Bébé qui fait ses dents, trois mois de mâchouillage, aucun éclat.',
                         'de': 'Zahnendes Baby, drei Monate Kauen, noch keine Absplitterung.',
                         'it': 'Bimbo che mette i denti, tre mesi di morsi, ancora nessuna scheggiatura.'}, 5),
    ({'en': 'Poppers instead of buttons', 'fr': 'Des pressions plutôt que des boutons', 'de': 'Druckknöpfe statt Knöpfe', 'it': 'Bottoni a pressione invece dei bottoni'}, {'en': 'Night changes are faster. Small thing, huge difference.',
                                    'fr': 'Les changes de nuit sont plus rapides. Un détail, une énorme différence.',
                                    'de': 'Das Wickeln in der Nacht geht schneller. Kleinigkeit, riesiger Unterschied.',
                                    'it': 'I cambi notturni sono più rapidi. Piccola cosa, enorme differenza.'}, 5),
    ({'en': 'Nap time favourite', 'fr': 'Le préféré de la sieste', 'de': 'Der Liebling zur Schlafenszeit', 'it': 'Il preferito del riposino'}, {'en': 'Will not sleep without the rabbit. We bought a spare.',
                            'fr': 'Il ne dort pas sans le lapin. Nous en avons acheté un deuxième.',
                            'de': 'Ohne den Hasen schläft er nicht. Wir haben einen Ersatz gekauft.',
                            'it': 'Non dorme senza il coniglio. Ne abbiamo comprato uno di scorta.'}, 5),
    ({'en': 'Wheels fell off', 'fr': 'Les roues sont tombées', 'de': 'Die Räder fielen ab', 'it': 'Le ruote si sono staccate'}, {'en': 'One wheel came loose after a week. Glued and fine, but still.',
                         'fr': "Une roue s'est détachée après une semaine. Recollée et c'est bon, mais quand même.",
                         'de': 'Ein Rad löste sich nach einer Woche. Geklebt und gut, aber trotzdem.',
                         'it': 'Una ruota si è staccata dopo una settimana. Incollata e va bene, ma comunque.'}, 3),
    ({'en': 'Grew with her', 'fr': 'Il a grandi avec elle', 'de': 'Ist mitgewachsen', 'it': 'È cresciuto con lei'}, {'en': 'Adjustable straps meant it fit from three months to a year.',
                       'fr': "Les bretelles réglables lui ont permis d'aller de trois mois à un an.",
                       'de': 'Verstellbare Gurte, also passte es von drei Monaten bis zu einem Jahr.',
                       'it': 'Le bretelle regolabili gli hanno fatto andare bene da tre mesi a un anno.'}, 5),
    ({'en': 'Colours are soft', 'fr': 'Des couleurs douces', 'de': 'Die Farben sind sanft', 'it': 'I colori sono tenui'}, {'en': 'Muted tones that do not shout. Matches the nursery.',
                          'fr': 'Des tons discrets qui ne crient pas. Assortis à la chambre.',
                          'de': 'Gedeckte Töne, die nicht schreien. Passt zum Kinderzimmer.',
                          'it': 'Toni smorzati che non urlano. Si abbinano alla cameretta.'}, 5),
    ({'en': 'Puzzle is a hit', 'fr': 'Le puzzle a du succès', 'de': 'Das Puzzle kommt an', 'it': 'Il puzzle è un successo'}, {'en': 'Ten pieces, thick wood, and the pictures make sense.',
                         'fr': 'Dix pièces, bois épais, et les images ont du sens.',
                         'de': 'Zehn Teile, dickes Holz, und die Bilder ergeben Sinn.',
                         'it': 'Dieci pezzi, legno spesso, e le figure hanno senso.'}, 5),
    ({'en': 'Zip is tricky', 'fr': 'La fermeture est difficile', 'de': 'Der Reißverschluss ist knifflig', 'it': 'La cerniera è difficile'}, {'en': 'Great coat but a stiff zip for small hands.',
                       'fr': 'Très beau manteau mais une fermeture dure pour de petites mains.',
                       'de': 'Toller Mantel, aber ein strammer Reißverschluss für kleine Hände.',
                       'it': 'Bel cappotto ma una cerniera dura per mani piccole.'}, 4),
    ({'en': 'Wooden blocks clack nicely', 'fr': 'Les cubes en bois font un joli bruit', 'de': 'Die Holzklötze klackern schön', 'it': 'I cubi di legno fanno un bel rumore'}, {'en': 'The sound is half the fun apparently.',
                                    'fr': 'Le bruit fait la moitié du plaisir, apparemment.',
                                    'de': 'Der Klang ist offenbar der halbe Spaß.',
                                    'it': 'Il suono è metà del divertimento, a quanto pare.'}, 5),
    ({'en': 'Hand-me-down ready', 'fr': 'Prêt pour le suivant', 'de': 'Bereit zum Weitergeben', 'it': 'Pronto per il fratellino'}, {'en': 'Second child wearing it now and it still looks new.',
                            'fr': "Le deuxième enfant le porte maintenant et il a l'air neuf.",
                            'de': 'Das zweite Kind trägt es jetzt und es sieht noch neu aus.',
                            'it': 'Ora lo indossa il secondo figlio e sembra ancora nuovo.'}, 5),
    ({'en': 'Instructions were clear', 'fr': 'La notice était claire', 'de': 'Die Anleitung war klar', 'it': 'Le istruzioni erano chiare'}, {'en': 'Built the kitchen in twenty minutes with a toddler helping.',
                                 'fr': "J'ai monté la cuisine en vingt minutes avec un petit qui aidait.",
                                 'de': 'Die Küche in zwanzig Minuten aufgebaut, mit einem Kleinkind als Helfer.',
                                 'it': 'Ho montato la cucina in venti minuti con un bimbo che aiutava.'}, 5),
    ({'en': 'Too warm for spring', 'fr': 'Trop chaud pour le printemps', 'de': 'Zu warm für den Frühling', 'it': 'Troppo caldo per la primavera'}, {'en': 'Beautiful knit but heavy. A winter piece.',
                             'fr': "Belle maille mais lourde. Une pièce d'hiver.",
                             'de': 'Schöner Strick, aber schwer. Ein Winterstück.',
                             'it': 'Bella maglia ma pesante. Un capo invernale.'}, 4),
    ({'en': 'Bath toy has no holes', 'fr': "Le jouet de bain n'a pas de trous", 'de': 'Das Badespielzeug hat keine Löcher', 'it': 'Il gioco da bagno non ha buchi'}, {'en': 'No mould inside. Someone thought about this.',
                               'fr': "Aucune moisissure à l'intérieur. Quelqu'un y a pensé.",
                               'de': 'Kein Schimmel innen. Da hat jemand mitgedacht.',
                               'it': 'Niente muffa dentro. Qualcuno ci ha pensato.'}, 5),
    ({'en': 'Print faded a bit', 'fr': "L'imprimé a un peu passé", 'de': 'Der Druck ist etwas verblasst', 'it': "La stampa è un po' sbiadita"}, {'en': 'Still soft, but the print lost some colour after many washes.',
                           'fr': "Toujours doux, mais l'imprimé a perdu de la couleur après de nombreux lavages.",
                           'de': 'Immer noch weich, aber der Druck hat nach vielen Wäschen Farbe verloren.',
                           'it': 'Ancora morbido, ma la stampa ha perso colore dopo molti lavaggi.'}, 3),
    ({'en': 'Stacks and knocks down', 'fr': 'On empile et on renverse', 'de': 'Stapeln und umwerfen', 'it': 'Impila e butta giù'}, {'en': 'Thirty times a day. Never gets old.',
                                'fr': "Trente fois par jour. On ne s'en lasse pas.",
                                'de': 'Dreißigmal am Tag. Wird nie langweilig.',
                                'it': 'Trenta volte al giorno. Non stanca mai.'}, 5),
    ({'en': 'Sizing chart was right', 'fr': 'Le guide des tailles était juste', 'de': 'Die Größentabelle stimmte', 'it': 'La tabella taglie era giusta'}, {'en': 'Measured, ordered, fit. Thank you for the chart.',
                                'fr': 'Mesuré, commandé, à la bonne taille. Merci pour le guide.',
                                'de': 'Gemessen, bestellt, es passt. Danke für die Tabelle.',
                                'it': 'Misurato, ordinato, calzato. Grazie per la tabella.'}, 5),
    ({'en': 'Muslin is huge', 'fr': 'Le lange est immense', 'de': 'Das Mulltuch ist riesig', 'it': 'La mussola è enorme'}, {'en': 'Big enough to swaddle and later a picnic blanket.',
                        'fr': 'Assez grand pour emmailloter et plus tard servir de nappe de pique-nique.',
                        'de': 'Groß genug zum Pucken und später als Picknickdecke.',
                        'it': 'Abbastanza grande per fasciare e poi come telo da picnic.'}, 5),
    ({'en': 'Grandparents approved', 'fr': 'Approuvé par les grands-parents', 'de': 'Von den Großeltern gebilligt', 'it': 'Approvato dai nonni'}, {'en': 'They said it looks like the toys they had. High praise.',
                               'fr': "Ils ont dit que cela ressemble aux jouets qu'ils avaient. Un beau compliment.",
                               'de': 'Sie sagten, es sehe aus wie ihr eigenes Spielzeug von damals. Großes Lob.',
                               'it': 'Hanno detto che sembra i giochi che avevano loro. Gran complimento.'}, 5),
    ({'en': 'Bib catches everything', 'fr': 'Le bavoir attrape tout', 'de': 'Das Lätzchen fängt alles auf', 'it': 'Il bavaglino prende tutto'}, {'en': 'Deep pocket, wipes clean, no more laundry after lunch.',
                                'fr': "Poche profonde, il s'essuie, plus de lessive après le déjeuner.",
                                'de': 'Tiefe Tasche, abwischbar, keine Wäsche mehr nach dem Mittagessen.',
                                'it': 'Tasca profonda, si pulisce, niente più bucato dopo pranzo.'}, 5),
    ({'en': 'Bell is loud', 'fr': 'La clochette est forte', 'de': 'Die Glocke ist laut', 'it': 'Il campanello è forte'}, {'en': 'Lovely rattle, but the bell is louder than I expected.',
                      'fr': 'Joli hochet, mais la clochette est plus forte que prévu.',
                      'de': 'Schöne Rassel, aber die Glocke ist lauter als erwartet.',
                      'it': 'Bel sonaglio, ma il campanello è più forte del previsto.'}, 4),
]
def P(sku, name, cats, price, desc, prompt, **kw):
    d = dict(sku=sku, name=name, categories=cats, price=price, description=desc, prompt=prompt); d.update(kw); return d
BABY = ['62', '68', '74', '80']
TODDLER = ['86', '92', '98', '104']
KID = ['110', '116', '122', '128']
PRODUCTS = [
    P('K-STACKER', {'en': 'Rainbow stacker', 'fr': 'Empileur arc-en-ciel', 'de': 'Regenbogen-Stapelturm', 'it': 'Impilabile arcobaleno'}, ['toys', 'gifts'], 28, {'en': 'Seven beech rings on a peg, painted with water-based colour. The rings are large enough for small hands and the peg is rounded. From twelve months.',
        'fr': "Sept anneaux de hêtre sur une tige, peints à l'eau. Les anneaux sont assez grands pour de petites mains et la tige est arrondie. Dès douze mois.",
        'de': 'Sieben Buchenringe auf einem Stab, mit Farbe auf Wasserbasis lackiert. Die Ringe sind groß genug für kleine Hände, der Stab ist abgerundet. Ab zwölf Monaten.',
        'it': "Sette anelli di faggio su un perno, dipinti con colori a base d'acqua. Gli anelli sono grandi abbastanza per le mani piccole e il perno è arrotondato. Da dodici mesi."}, 'a wooden rainbow ring stacking toy', attributes=dict(age_range='1 to 3', material='Oak', color='Red', size='')),
    P('K-TRAIN', {'en': 'Wooden train set', 'fr': 'Circuit de train en bois', 'de': 'Holzeisenbahn-Set', 'it': 'Trenino in legno'}, ['toys'], 65, {'en': 'A 30-piece beech track with a three-car train and a bridge. The track fits the pieces of other wooden sets. From three years.',
        'fr': "Un circuit de 30 pièces en hêtre avec un train de trois wagons et un pont. Le circuit s'assemble avec les pièces des autres jeux en bois. Dès trois ans.",
        'de': 'Eine 30-teilige Buchenholzbahn mit einem Zug aus drei Wagen und einer Brücke. Die Schienen passen zu den Teilen anderer Holzbahnen. Ab drei Jahren.',
        'it': 'Un circuito di 30 pezzi in faggio con un treno a tre vagoni e un ponte. I binari si incastrano con i pezzi degli altri set in legno. Da tre anni.'}, 'a wooden train set with curved tracks and a small engine', attributes=dict(age_range='3 to 5', material='Oak', color='Brown', size='')),
    P('K-BLOCKS', {'en': 'Building blocks, 50 pieces', 'fr': 'Cubes de construction, 50 pièces', 'de': 'Bauklötze, 50 Teile', 'it': 'Costruzioni, 50 pezzi'}, ['toys'], 45, {'en': 'Fifty maple blocks in a cotton bag. Cubes, arches, triangles and planks, sanded smooth and left unpainted. From eighteen months.',
        'fr': 'Cinquante cubes en érable dans un sac en coton. Cubes, arches, triangles et planches, poncés lisses et laissés bruts. Dès dix-huit mois.',
        'de': 'Fünfzig Ahornklötze in einem Baumwollbeutel. Würfel, Bögen, Dreiecke und Bretter, glatt geschliffen und unlackiert. Ab achtzehn Monaten.',
        'it': 'Cinquanta blocchi in acero in un sacchetto di cotone. Cubi, archi, triangoli e tavolette, levigati e lasciati grezzi. Da diciotto mesi.'}, 'a pile of natural wooden building blocks', attributes=dict(age_range='1 to 3', material='Oak', color='Oatmeal', size='')),
    P('K-RABBIT', {'en': 'Felt rabbit', 'fr': 'Lapin en feutre', 'de': 'Filzhase', 'it': 'Coniglio in feltro'}, ['toys', 'gifts'], 24, {'en': 'A hand-sewn wool felt rabbit, 25 cm, with a linen dress. Filled with wool, so it is soft and light. Hand wash and it keeps its shape.',
        'fr': 'Un lapin en feutre de laine cousu à la main, 25 cm, avec une robe en lin. Rembourré de laine, il est doux et léger. Lavage à la main et il garde sa forme.',
        'de': 'Ein von Hand genähter Hase aus Wollfilz, 25 cm, mit einem Leinenkleid. Mit Wolle gefüllt, deshalb weich und leicht. Handwäsche, und er behält seine Form.',
        'it': 'Un coniglio in feltro di lana cucito a mano, 25 cm, con un vestitino di lino. Imbottito di lana, quindi morbido e leggero. Si lava a mano e tiene la forma.'}, 'a small {value} felt rabbit soft toy', axis='color', values=['Grey', 'Pink', 'Oatmeal'], picture_per_value=True, attributes=dict(age_range='0 to 1', material='Wool', size='')),
    P('K-PLAY-KITCHEN', {'en': 'Play kitchen', 'fr': 'Cuisine pour enfant', 'de': 'Kinderküche', 'it': 'Cucina giocattolo'}, ['toys', 'nursery'], 180, {'en': 'A birch play kitchen with a working tap sound and a chalkboard. Solid birch with two hobs, an oven door and a shelf for pans. Assembly takes twenty minutes.',
        'fr': "Une cuisine en bouleau avec un robinet qui fait le bruit de l'eau et une ardoise. Bouleau massif avec deux feux, une porte de four et une étagère à casseroles. Le montage prend vingt minutes.",
        'de': 'Eine Kinderküche aus Birke mit Wasserhahn-Geräusch und einer Tafel. Massive Birke mit zwei Kochstellen, einer Ofentür und einem Regal für Töpfe. Der Aufbau dauert zwanzig Minuten.',
        'it': "Una cucina in betulla con un rubinetto che fa il rumore dell'acqua e una lavagna. Betulla massello con due fuochi, uno sportello del forno e un ripiano per le pentole. Il montaggio richiede venti minuti."}, 'a small wooden childrens play kitchen', attributes=dict(age_range='3 to 5', material='Oak', color='White', size='')),
    P('K-PUZZLE', {'en': 'Animal puzzle', 'fr': 'Puzzle des animaux', 'de': 'Tierpuzzle', 'it': 'Puzzle degli animali'}, ['toys'], 18, {'en': 'A nine-piece chunky wooden puzzle of farm animals. Thick pieces with a knob for small fingers. From eighteen months.',
        'fr': 'Un puzzle en bois épais de neuf pièces, avec les animaux de la ferme. Des pièces épaisses avec un bouton pour les petits doigts. Dès dix-huit mois.',
        'de': 'Ein neunteiliges dickes Holzpuzzle mit Bauernhoftieren. Dicke Teile mit einem Knopf für kleine Finger. Ab achtzehn Monaten.',
        'it': 'Un puzzle in legno spesso da nove pezzi, con gli animali della fattoria. Pezzi spessi con un pomello per le dita piccole. Da diciotto mesi.'}, 'a chunky wooden puzzle with painted farm animals', attributes=dict(age_range='1 to 3', material='Oak', color='Green', size='')),
    P('K-RATTLE', {'en': 'Beech rattle', 'fr': 'Hochet en hêtre', 'de': 'Rassel aus Buche', 'it': 'Sonaglio in faggio'}, ['toys', 'gifts'], 12, {'en': 'A ring rattle in oiled beech with a bell inside. Oiled beech with no paint and a bell that cannot come out. From birth.',
        'fr': "Un hochet anneau en hêtre huilé avec un grelot à l'intérieur. Hêtre huilé sans peinture et un grelot qui ne peut pas sortir. Dès la naissance.",
        'de': 'Eine Ringrassel aus geölter Buche mit einem Glöckchen darin. Geölte Buche ohne Lack und ein Glöckchen, das nicht herauskann. Ab der Geburt.',
        'it': 'Un sonaglio ad anello in faggio oliato con un campanellino dentro. Faggio oliato senza vernice e un campanellino che non può uscire. Dalla nascita.'}, 'a wooden ring rattle with small beads', attributes=dict(age_range='0 to 1', material='Oak', color='Oatmeal', size='')),
    P('K-DOLL', {'en': 'Cotton doll', 'fr': 'Poupée en coton', 'de': 'Stoffpuppe aus Baumwolle', 'it': 'Bambola di cotone'}, ['toys'], 34, {'en': 'A 35 cm soft doll in organic cotton with a removable dress. Washable at thirty degrees, hair and all. The dress comes off and goes back on.',
        'fr': "Une poupée souple de 35 cm en coton biologique, avec une robe amovible. Lavable à trente degrés, cheveux compris. La robe s'enlève et se remet.",
        'de': 'Eine weiche 35-cm-Puppe aus Bio-Baumwolle mit abnehmbarem Kleid. Waschbar bei dreißig Grad, samt Haaren. Das Kleid geht ab und wieder an.',
        'it': 'Una bambola morbida da 35 cm in cotone biologico, con vestito sfilabile. Lavabile a trenta gradi, capelli compresi. Il vestito si toglie e si rimette.'}, 'a soft cotton doll with yarn hair and a striped dress', attributes=dict(age_range='1 to 3', material='Cotton', color='Pink', size='')),
    P('K-CAR-SET', {'en': 'Wooden cars, set of 3', 'fr': 'Voitures en bois, lot de 3', 'de': 'Holzautos, 3er-Set', 'it': 'Macchinine di legno, set da 3'}, ['toys'], 22, {'en': 'Three small cars in maple with rubber wheels. Small enough for a pocket, quiet enough for a wooden floor. From eighteen months.',
        'fr': 'Trois petites voitures en érable avec des roues en caoutchouc. Assez petites pour une poche, assez silencieuses pour un parquet. Dès dix-huit mois.',
        'de': 'Drei kleine Autos aus Ahorn mit Gummirädern. Klein genug für die Tasche, leise genug für den Holzboden. Ab achtzehn Monaten.',
        'it': 'Tre macchinine in acero con ruote di gomma. Piccole abbastanza per una tasca, silenziose abbastanza per un pavimento di legno. Da diciotto mesi.'}, 'three small painted wooden toy cars', attributes=dict(age_range='1 to 3', material='Oak', color='Blue', size='')),
    P('K-MARBLE-RUN', {'en': 'Marble run', 'fr': 'Circuit à billes', 'de': 'Murmelbahn', 'it': 'Pista per biglie'}, ['toys'], 55, {'en': 'A 40-piece wooden marble run with glass marbles. The pieces stack in any order, so every run is different. From four years.',
        'fr': "Un circuit à billes en bois de 40 pièces avec des billes en verre. Les pièces s'empilent dans n'importe quel ordre, chaque parcours est donc différent. Dès quatre ans.",
        'de': 'Eine 40-teilige Murmelbahn aus Holz mit Glasmurmeln. Die Teile lassen sich in jeder Reihenfolge stapeln, deshalb ist jede Bahn anders. Ab vier Jahren.',
        'it': 'Una pista per biglie in legno da 40 pezzi con biglie di vetro. I pezzi si impilano in qualsiasi ordine, quindi ogni percorso è diverso. Da quattro anni.'}, 'a wooden marble run tower with glass marbles', attributes=dict(age_range='5 to 8', material='Oak', color='Oatmeal', size='')),
    P('K-CRAFT-KIT', {'en': 'Craft box', 'fr': 'Boîte de bricolage', 'de': 'Bastelkiste', 'it': 'Scatola dei lavoretti'}, ['toys'], 26, {'en': 'Paper, wool, glue and thirty ideas. Enough material for thirty afternoons, with the ideas on cards. From four years.',
        'fr': 'Du papier, de la laine, de la colle et trente idées. De quoi occuper trente après-midis, avec les idées sur des cartes. Dès quatre ans.',
        'de': 'Papier, Wolle, Kleber und dreißig Ideen. Material für dreißig Nachmittage, die Ideen auf Karten. Ab vier Jahren.',
        'it': 'Carta, lana, colla e trenta idee. Materiale per trenta pomeriggi, con le idee su delle schede. Da quattro anni.'}, 'an open craft box with coloured paper, wool and scissors', attributes=dict(age_range='5 to 8', material='Cotton', color='Yellow', size='')),
    P('K-BOARD-GAME', {'en': 'Forest board game', 'fr': 'Jeu de plateau de la forêt', 'de': 'Waldbrettspiel', 'it': 'Gioco da tavolo del bosco'}, ['toys'], 30, {'en': 'A cooperative game for ages five and up, twenty minutes a round. Players work together to get the animals home before nightfall. Two to four players.',
        'fr': "Un jeu coopératif à partir de cinq ans, vingt minutes la partie. Les joueurs s'entraident pour ramener les animaux avant la nuit. De deux à quatre joueurs.",
        'de': 'Ein kooperatives Spiel ab fünf Jahren, zwanzig Minuten pro Runde. Die Spieler bringen gemeinsam die Tiere heim, bevor es dunkel wird. Zwei bis vier Spieler.',
        'it': 'Un gioco cooperativo dai cinque anni, venti minuti a partita. I giocatori collaborano per riportare a casa gli animali prima del buio. Da due a quattro giocatori.'}, 'a colourful illustrated board game box with wooden pieces', attributes=dict(age_range='5 to 8', material='Oak', color='Green', size='')),
    P('K-BODYSUIT', {'en': 'Bodysuits, 3 pack', 'fr': 'Bodys, lot de 3', 'de': 'Bodys, 3er-Pack', 'it': 'Body, confezione da 3'}, ['clothing'], 28, {'en': 'Three long-sleeve bodysuits in organic cotton with envelope necks. Poppers at the crotch, an envelope neck for easy changes. From newborn to twenty-four months.',
        'fr': "Trois bodys à manches longues en coton biologique, avec encolure cache-cœur. Pressions à l'entrejambe et encolure cache-cœur pour changer vite. De la naissance à vingt-quatre mois.",
        'de': 'Drei langärmelige Bodys aus Bio-Baumwolle mit Amerikanischem Ausschnitt. Druckknöpfe im Schritt, der Ausschnitt macht das Umziehen leicht. Von neugeboren bis vierundzwanzig Monate.',
        'it': 'Tre body a maniche lunghe in cotone biologico, con scollo incrociato. Bottoncini sul cavallo e scollo incrociato per cambiarli in fretta. Dalla nascita ai ventiquattro mesi.'}, 'three folded {value} baby bodysuits', axis='color', values=['White', 'Oatmeal', 'Pink'], picture_per_value=True, attributes=dict(age_range='0 to 1', material='Cotton', size='')),
    P('K-SLEEPSUIT', {'en': 'Sleepsuit', 'fr': 'Pyjama une pièce', 'de': 'Schlafanzug mit Füßen', 'it': 'Tutina della notte'}, ['clothing'], 22, {'en': 'A footed sleepsuit with a two-way zip. The zip runs from the foot, so a night change does not wake the top half. From newborn to two years.',
        'fr': 'Un pyjama avec pieds et une fermeture à deux curseurs. La fermeture part du pied, un change de nuit ne réveille donc pas le haut. De la naissance à deux ans.',
        'de': 'Ein Schlafanzug mit Füßen und einem Zwei-Wege-Reißverschluss. Der Reißverschluss beginnt am Fuß, ein nächtliches Wickeln weckt die obere Hälfte also nicht. Von neugeboren bis zwei Jahre.',
        'it': 'Una tutina con i piedini e una zip a due cursori. La zip parte dal piede, quindi un cambio di notte non sveglia la metà di sopra. Dalla nascita ai due anni.'}, 'a folded striped baby sleepsuit', axis='size', values=BABY, attributes=dict(age_range='0 to 1', material='Cotton', color='Blue Light')),
    P('K-LEGGINGS', {'en': 'Leggings, 2 pack', 'fr': 'Leggings, lot de 2', 'de': 'Leggings, 2er-Pack', 'it': 'Leggings, confezione da 2'}, ['clothing'], 20, {'en': 'Two pairs of soft leggings with a wide waistband. Soft organic cotton with a little stretch and no labels inside. From six months to six years.',
        'fr': "Deux leggings tout doux avec une large ceinture. Coton biologique doux, un peu élastique, sans étiquette à l'intérieur. De six mois à six ans.",
        'de': 'Zwei weiche Leggings mit breitem Bund. Weiche Bio-Baumwolle mit etwas Stretch und ohne Etiketten innen. Von sechs Monaten bis sechs Jahre.',
        'it': "Due leggings morbidissimi con fascia larga in vita. Cotone biologico morbido, un po' elastico, senza etichette dentro. Dai sei mesi ai sei anni."}, 'two folded pairs of {value} childrens leggings', axis='color', values=['Grey', 'Green', 'Salmon'], picture_per_value=True, attributes=dict(age_range='1 to 3', material='Cotton', size='')),
    P('K-TEE', {'en': 'Striped tee', 'fr': 'T-shirt marinière', 'de': 'Ringelshirt', 'it': 'Maglia a righe'}, ['clothing'], 15, {'en': 'A breton stripe tee in organic cotton. A boat neck that goes over the head without a fight. From six months to eight years.',
        'fr': 'Un t-shirt marinière en coton biologique. Une encolure bateau qui passe la tête sans bagarre. De six mois à huit ans.',
        'de': 'Ein Ringelshirt aus Bio-Baumwolle. Ein U-Boot-Ausschnitt, der ohne Kampf über den Kopf geht. Von sechs Monaten bis acht Jahre.',
        'it': 'Una maglia a righe in cotone biologico. Scollo a barca che passa dalla testa senza litigare. Dai sei mesi agli otto anni.'}, 'a folded {value} and white striped childrens t-shirt', axis='color', values=['Blue', 'Red', 'Green'], picture_per_value=True, attributes=dict(age_range='3 to 5', material='Cotton', size='')),
    P('K-DUNGAREES', {'en': 'Cord dungarees', 'fr': 'Salopette en velours côtelé', 'de': 'Cordhose mit Latz', 'it': 'Salopette in velluto a coste'}, ['clothing'], 38, {'en': 'Corduroy dungarees with adjustable straps and knee patches. Poppers at the legs for the first year, buttons on the straps later. From six months to five years.',
        'fr': 'Une salopette en velours côtelé avec des bretelles réglables et des renforts aux genoux. Pressions aux jambes la première année, boutons aux bretelles ensuite. De six mois à cinq ans.',
        'de': 'Eine Latzhose aus Cord mit verstellbaren Trägern und Knieflicken. Im ersten Jahr Druckknöpfe an den Beinen, später Knöpfe an den Trägern. Von sechs Monaten bis fünf Jahre.',
        'it': 'Una salopette in velluto a coste con bretelle regolabili e rinforzi sulle ginocchia. Bottoncini sulle gambe il primo anno, poi bottoni sulle bretelle. Dai sei mesi ai cinque anni.'}, 'a pair of {value} corduroy childrens dungarees laid flat', axis='color', values=['Brown', 'Green', 'Blue Dark'], picture_per_value=True, attributes=dict(age_range='1 to 3', material='Cotton', size='')),
    P('K-CARDIGAN', {'en': 'Knit cardigan', 'fr': 'Gilet en maille', 'de': 'Strickjacke', 'it': 'Cardigan di maglia'}, ['clothing'], 34, {'en': 'A merino cardigan with wooden buttons. Soft merino that washes at thirty degrees. From newborn to six years.',
        'fr': 'Un gilet en mérinos avec des boutons en bois. Un mérinos doux qui se lave à trente degrés. De la naissance à six ans.',
        'de': 'Eine Strickjacke aus Merino mit Holzknöpfen. Weiches Merino, das bei dreißig Grad wäscht. Von neugeboren bis sechs Jahre.',
        'it': 'Un cardigan in merino con bottoni di legno. Merino morbido che si lava a trenta gradi. Dalla nascita ai sei anni.'}, 'a small {value} knitted childrens cardigan laid flat', axis='color', values=['Oatmeal', 'Green', 'Pink'], picture_per_value=True, attributes=dict(age_range='1 to 3', material='Wool', size='')),
    P('K-DRESS', {'en': 'Cotton dress', 'fr': 'Robe en coton', 'de': 'Baumwollkleid', 'it': 'Vestito di cotone'}, ['clothing'], 30, {'en': 'A pinafore dress in printed organic cotton. A pinafore that layers over a tee in winter and stands alone in summer. From one to eight years.',
        'fr': "Une robe chasuble en coton biologique imprimé. Une chasuble qui se porte sur un t-shirt l'hiver et toute seule l'été. De un à huit ans.",
        'de': 'Ein Trägerkleid aus bedruckter Bio-Baumwolle. Im Winter über einem Shirt, im Sommer allein. Von einem bis acht Jahre.',
        'it': "Un vestito scamiciato in cotone biologico stampato. D'inverno sopra una maglietta, d'estate da solo. Da uno a otto anni."}, 'a childrens pinafore dress with a small floral print laid flat', axis='size', values=TODDLER, attributes=dict(age_range='3 to 5', material='Cotton', color='Yellow')),
    P('K-HOODIE', {'en': 'Hoodie', 'fr': 'Sweat à capuche', 'de': 'Kapuzenpulli', 'it': 'Felpa con cappuccio'}, ['clothing'], 32, {'en': 'A brushed cotton hoodie with a kangaroo pocket. Brushed inside, with a hood that stays up. From two to ten years.',
        'fr': "Un sweat à capuche en coton gratté avec une poche kangourou. Gratté à l'intérieur, avec une capuche qui tient. De deux à dix ans.",
        'de': 'Ein Kapuzenpulli aus angerauter Baumwolle mit Känguru-Tasche. Innen angeraut, mit einer Kapuze, die oben bleibt. Von zwei bis zehn Jahre.',
        'it': 'Una felpa con cappuccio in cotone garzato con tasca a marsupio. Garzata dentro, con un cappuccio che sta su. Dai due ai dieci anni.'}, 'a {value} childrens hoodie laid flat', axis='color', values=['Grey', 'Blue Dark', 'Orange'], picture_per_value=True, attributes=dict(age_range='5 to 8', material='Cotton', size='')),
    P('K-JEANS', {'en': 'Soft jeans', 'fr': 'Jean tout doux', 'de': 'Weiche Jeans', 'it': 'Jeans morbidi'}, ['clothing'], 28, {'en': 'Stretch denim with an elastic waist and no scratchy seams. Stretchy enough to climb in, soft enough to sleep in. From two to ten years.',
        'fr': 'Un denim extensible avec une taille élastique et aucune couture qui gratte. Assez élastique pour grimper, assez doux pour dormir. De deux à dix ans.',
        'de': 'Stretchdenim mit Gummibund und ohne kratzende Nähte. Dehnbar genug zum Klettern, weich genug zum Schlafen. Von zwei bis zehn Jahre.',
        'it': 'Denim elasticizzato con vita elastica e nessuna cucitura che gratta. Elastici quanto basta per arrampicarsi, morbidi quanto basta per dormirci. Dai due ai dieci anni.'}, 'a pair of childrens soft blue jeans laid flat', axis='size', values=KID, attributes=dict(age_range='5 to 8', material='Denim', color='Blue Jean')),
    P('K-SOCKS', {'en': 'Socks, 5 pack', 'fr': 'Chaussettes, lot de 5', 'de': 'Socken, 5er-Pack', 'it': 'Calze, confezione da 5'}, ['clothing'], 14, {'en': 'Five pairs in soft cotton with a grip sole. A grip sole for wooden floors and a cuff that stays up. From six months to six years.',
        'fr': 'Cinq paires en coton doux avec une semelle antidérapante. Une semelle antidérapante pour les parquets et un bord qui ne tombe pas. De six mois à six ans.',
        'de': 'Fünf Paar aus weicher Baumwolle mit rutschfester Sohle. Rutschfeste Sohle für Holzböden und ein Bund, der oben bleibt. Von sechs Monaten bis sechs Jahre.',
        'it': 'Cinque paia in cotone morbido con suola antiscivolo. Suola antiscivolo per i pavimenti di legno e bordo che non scende. Dai sei mesi ai sei anni.'}, 'five pairs of small colourful childrens socks', axis='size', values=['19', '23', '27', '31'], attributes=dict(age_range='1 to 3', material='Cotton', color='Blue')),
    P('K-HAT', {'en': 'Sun hat', 'fr': 'Chapeau de soleil', 'de': 'Sonnenhut', 'it': 'Cappello da sole'}, ['clothing', 'outdoor'], 16, {'en': 'A wide-brim cotton sun hat with a chin strap. The brim shades the neck and the strap keeps the wind from taking it. From six months to six years.',
        'fr': "Un chapeau de soleil en coton à large bord, avec une jugulaire. Le bord protège la nuque et la jugulaire empêche le vent de l'emporter. De six mois à six ans.",
        'de': 'Ein Sonnenhut aus Baumwolle mit breiter Krempe und Kinnband. Die Krempe beschattet den Nacken, das Band hält ihn im Wind. Von sechs Monaten bis sechs Jahre.',
        'it': 'Un cappello da sole in cotone a tesa larga, con laccetto sotto il mento. La tesa fa ombra sul collo e il laccetto non lo fa volare via. Dai sei mesi ai sei anni.'}, 'a {value} childrens wide brim sun hat', axis='color', values=['Oatmeal', 'Blue', 'Yellow'], picture_per_value=True, attributes=dict(age_range='1 to 3', material='Cotton', size='')),
    P('K-BOARD-BOOK', {'en': 'Board book set', 'fr': 'Coffret de livres cartonnés', 'de': 'Pappbilderbuch-Set', 'it': 'Set di libri cartonati'}, ['books', 'gifts'], 24, {'en': 'Four board books about colours, animals, food and bedtime. Thick pages, rounded corners and colours that hold up to chewing. From six months.',
        'fr': 'Quatre livres cartonnés sur les couleurs, les animaux, la nourriture et le coucher. Des pages épaisses, des coins arrondis et des couleurs qui résistent aux dents. Dès six mois.',
        'de': 'Vier Pappbilderbücher über Farben, Tiere, Essen und das Zubettgehen. Dicke Seiten, runde Ecken und Farben, die das Kauen aushalten. Ab sechs Monaten.',
        'it': 'Quattro libri cartonati su colori, animali, cibo e nanna. Pagine spesse, angoli arrotondati e colori che reggono i morsi. Da sei mesi.'}, 'four small colourful board books fanned out', attributes=dict(age_range='0 to 1', material='', color='Yellow', size='')),
    P('K-PICTURE-BOOK', {'en': 'The Lark Who Lost Her Song', 'fr': "L'alouette qui avait perdu son chant", 'de': 'Die Lerche, die ihr Lied verlor', 'it': "L'allodola che perse il suo canto"}, ['books'], 14, {'en': 'A picture book about a bird, a storm and the neighbour who helped. Thirty-two pages with a picture on every spread. From three years.',
        'fr': 'Un album sur un oiseau, une tempête et le voisin qui a aidé. Trente-deux pages avec une image sur chaque double page. Dès trois ans.',
        'de': 'Ein Bilderbuch über einen Vogel, einen Sturm und den Nachbarn, der geholfen hat. Zweiunddreißig Seiten mit einem Bild auf jeder Doppelseite. Ab drei Jahren.',
        'it': "Un albo illustrato su un uccello, una tempesta e il vicino che lo ha aiutato. Trentadue pagine con un'illustrazione su ogni doppia pagina. Da tre anni."}, 'a picture book with an illustrated cover of a small bird on a branch', attributes=dict(age_range='3 to 5', material='', color='Blue Light', size='')),
    P('K-BEDTIME-BOOK', {'en': 'One Hundred Goodnights', 'fr': 'Cent bonnes nuits', 'de': 'Hundert gute Nächte', 'it': 'Cento buonanotte'}, ['books'], 14, {'en': 'A hundred one-line goodnights, one page each. One line per page, so the reading stops when the eyes close. From one year.',
        'fr': "Cent bonnes nuits d'une ligne, une par page. Une ligne par page, la lecture s'arrête donc quand les yeux se ferment. Dès un an.",
        'de': 'Hundert Gutenachtsätze, einer pro Seite. Eine Zeile pro Seite, das Lesen hört also auf, wenn die Augen zufallen. Ab einem Jahr.',
        'it': 'Cento buonanotte di una riga, una per pagina. Una riga per pagina, così la lettura finisce quando gli occhi si chiudono. Da un anno.'}, 'a picture book with an illustrated cover of a moon over rooftops', attributes=dict(age_range='1 to 3', material='', color='Blue Dark', size='')),
    P('K-FIRST-READER', {'en': 'Otto and the Big Puddle', 'fr': 'Otto et la grande flaque', 'de': 'Otto und die große Pfütze', 'it': 'Otto e la grande pozzanghera'}, ['books'], 9, {'en': 'A first reader with short words and long puddles. Short chapters, big type and a joke on every page. From five years.',
        'fr': 'Un premier roman avec des mots courts et de longues flaques. Des chapitres courts, de grosses lettres et une blague à chaque page. Dès cinq ans.',
        'de': 'Ein erstes Lesebuch mit kurzen Wörtern und langen Pfützen. Kurze Kapitel, große Schrift und auf jeder Seite ein Witz. Ab fünf Jahren.',
        'it': 'Un primo libro da leggere da soli, con parole corte e pozzanghere lunghe. Capitoli brevi, caratteri grandi e una battuta a ogni pagina. Da cinque anni.'}, 'a slim childrens book with an illustrated cover of a boy in wellies', attributes=dict(age_range='5 to 8', material='', color='Yellow', size='')),
    P('K-ATLAS', {'en': 'My First Atlas', 'fr': 'Mon premier atlas', 'de': 'Mein erster Atlas', 'it': 'Il mio primo atlante'}, ['books'], 22, {'en': 'A large illustrated atlas with animals on every page. Every continent on a double spread, with the animals that live there. From four years.',
        'fr': 'Un grand atlas illustré avec des animaux à chaque page. Chaque continent sur une double page, avec les animaux qui y vivent. Dès quatre ans.',
        'de': 'Ein großer illustrierter Atlas mit Tieren auf jeder Seite. Jeder Kontinent auf einer Doppelseite, mit den Tieren, die dort leben. Ab vier Jahren.',
        'it': 'Un grande atlante illustrato con animali su ogni pagina. Ogni continente su una doppia pagina, con gli animali che ci vivono. Da quattro anni.'}, 'a large illustrated childrens atlas with a colourful map cover', attributes=dict(age_range='5 to 8', material='', color='Green', size='')),
    P('K-COT', {'en': 'Convertible cot', 'fr': 'Lit à barreaux évolutif', 'de': 'Mitwachsendes Gitterbett', 'it': 'Lettino trasformabile'}, ['nursery'], 390, {'en': 'A beech cot that becomes a toddler bed, with three mattress heights. Solid beech with a mattress base at three heights. It converts with the parts in the box.',
        'fr': "Un lit en hêtre qui devient un lit d'enfant, avec trois hauteurs de sommier. Hêtre massif et un sommier à trois hauteurs. Il se transforme avec les pièces de la boîte.",
        'de': 'Ein Gitterbett aus Buche, das zum Kinderbett wird, mit drei Höhen für den Lattenrost. Massive Buche mit einem Boden in drei Höhen. Der Umbau gelingt mit den Teilen im Karton.',
        'it': 'Un lettino in faggio che diventa un letto per i più grandi, con tre altezze della rete. Faggio massello e rete a tre altezze. Si trasforma con i pezzi che trovi nella scatola.'}, 'a wooden convertible baby cot', attributes=dict(age_range='0 to 1', material='Oak', color='Oatmeal', size='')),
    P('K-CHANGING-TABLE', {'en': 'Changing table', 'fr': 'Table à langer', 'de': 'Wickeltisch', 'it': 'Fasciatoio'}, ['nursery'], 290, {'en': 'A changing table with two shelves that becomes a desk. The top lifts off and it becomes a desk when the nappies are done. Solid birch.',
        'fr': "Une table à langer à deux étagères qui devient un bureau. Le plateau s'enlève et le meuble devient un bureau quand les couches sont finies. Bouleau massif.",
        'de': 'Ein Wickeltisch mit zwei Böden, der zum Schreibtisch wird. Der Aufsatz kommt ab, und wenn die Windelzeit vorbei ist, bleibt ein Schreibtisch. Massive Birke.',
        'it': 'Un fasciatoio con due ripiani che diventa una scrivania. Il piano si sfila e, finiti i pannolini, resta una scrivania. Betulla massello.'}, 'a wooden changing table with two shelves', attributes=dict(age_range='0 to 1', material='Oak', color='White', size='')),
    P('K-ROCKER', {'en': 'Rocking chair', 'fr': 'Fauteuil à bascule', 'de': 'Schaukelstuhl', 'it': 'Poltrona a dondolo'}, ['nursery'], 340, {'en': 'A nursing chair in boucle on ash rockers. Deep seat, high arms and a quiet rock. The boucle cover is removable.',
        'fr': "Un fauteuil d'allaitement en bouclette sur des patins en frêne. Assise profonde, accoudoirs hauts et une bascule silencieuse. La housse en bouclette s'enlève.",
        'de': 'Ein Stillsessel aus Bouclé auf Kufen aus Esche. Tiefe Sitzfläche, hohe Armlehnen und ein leises Schaukeln. Der Bouclé-Bezug ist abnehmbar.',
        'it': "Una poltrona per l'allattamento in bouclé su pattini di frassino. Seduta profonda, braccioli alti e un dondolio silenzioso. La fodera in bouclé si sfila."}, 'an oatmeal boucle rocking chair on wooden rockers', attributes=dict(age_range='0 to 1', material='Wool', color='Oatmeal', size='')),
    P('K-MOBILE', {'en': 'Felt mobile', 'fr': 'Mobile en feutre', 'de': 'Filzmobile', 'it': 'Giostrina in feltro'}, ['nursery', 'gifts'], 36, {'en': 'Clouds, a moon and three birds in wool felt. Wool felt shapes on a wooden arm that clips to a cot. It turns in a draught.',
        'fr': "Des nuages, une lune et trois oiseaux en feutre de laine. Des formes en feutre de laine sur un bras en bois qui se fixe au lit. Il tourne au moindre courant d'air.",
        'de': 'Wolken, ein Mond und drei Vögel aus Wollfilz. Filzformen an einem Holzarm, der ans Bett geklemmt wird. Es dreht sich im Luftzug.',
        'it': 'Nuvole, una luna e tre uccellini in feltro di lana. Forme di feltro su un braccio di legno che si aggancia al lettino. Gira al minimo spiffero.'}, 'a felt baby mobile with clouds, a moon and small birds', attributes=dict(age_range='0 to 1', material='Wool', color='White', size='')),
    P('K-SHELF', {'en': 'Picture book shelf', 'fr': 'Étagère à albums', 'de': 'Bilderbuchregal', 'it': 'Libreria frontale'}, ['nursery', 'books'], 90, {'en': 'A front-facing shelf so covers show. Three shallow shelves show the covers, so a child can choose. Fixings for the wall are included.',
        'fr': "Une étagère de face pour que les couvertures se voient. Trois tablettes peu profondes montrent les couvertures, l'enfant choisit donc tout seul. Les fixations murales sont fournies.",
        'de': 'Ein Regal, das die Umschläge nach vorn zeigt. Drei flache Böden zeigen die Cover, damit ein Kind selbst wählen kann. Die Wandbefestigung liegt bei.',
        'it': 'Una libreria frontale che mostra le copertine. Tre ripiani bassi tengono i libri di faccia, così il bambino sceglie da sé. I fissaggi a muro sono inclusi.'}, 'a low wooden front facing bookshelf for children', attributes=dict(age_range='1 to 3', material='Oak', color='Oatmeal', size='')),
    P('K-STORAGE', {'en': 'Toy storage boxes, set of 3', 'fr': 'Bacs à jouets, lot de 3', 'de': 'Spielzeugboxen, 3er-Set', 'it': 'Contenitori per giochi, set da 3'}, ['nursery'], 48, {'en': 'Three felt boxes with wooden handles. Felt boxes that fold flat and stand firm. Each one holds a season of toys.',
        'fr': 'Trois bacs en feutre avec des poignées en bois. Des bacs en feutre qui se plient à plat et tiennent debout. Chacun avale une saison de jouets.',
        'de': 'Drei Filzboxen mit Holzgriffen. Filzboxen, die sich flach falten und trotzdem stehen. Jede fasst eine Saison Spielzeug.',
        'it': 'Tre contenitori in feltro con manici di legno. Contenitori che si ripiegano piatti e stanno in piedi. Ognuno tiene una stagione di giochi.'}, 'three grey felt storage boxes with wooden handles', attributes=dict(age_range='1 to 3', material='Wool', color='Grey', size='')),
    P('K-NIGHT-LIGHT', {'en': 'Rabbit night light', 'fr': 'Veilleuse lapin', 'de': 'Nachtlicht Hase', 'it': 'Lucina notturna coniglio'}, ['nursery'], 32, {'en': 'A silicone rabbit that glows warm and dims with a tap. Tap once for warm light, twice for dim, and it turns itself off after an hour. Charges by USB-C.',
        'fr': "Un lapin en silicone qui éclaire chaud et se tamise d'une tape. Une tape pour la lumière chaude, deux pour la veilleuse, et il s'éteint tout seul au bout d'une heure. Se recharge en USB-C.",
        'de': 'Ein Hase aus Silikon, der warm leuchtet und sich mit einem Klopfen dimmt. Einmal klopfen für warmes Licht, zweimal zum Dimmen, nach einer Stunde geht er von selbst aus. Lädt über USB-C.',
        'it': "Un coniglio di silicone che fa luce calda e si abbassa con un colpetto. Un colpetto per la luce calda, due per la luce bassa, e dopo un'ora si spegne da solo. Si ricarica in USB-C."}, 'a small white silicone rabbit night light glowing softly', attributes=dict(age_range='0 to 1', material='Rubber', color='White', size='')),
    P('K-MUSLINS', {'en': 'Muslin squares, 3 pack', 'fr': 'Langes en mousseline, lot de 3', 'de': 'Mulltücher, 3er-Pack', 'it': 'Teli in mussola, confezione da 3'}, ['nursery', 'gifts'], 22, {'en': 'Three large organic muslins, for everything. Large squares of double-layer organic cotton, 120 by 120 cm. Swaddle, burp cloth, sun shade.',
        'fr': "Trois grands langes en mousseline biologique, bons à tout. De grands carrés de coton biologique double épaisseur, 120 sur 120 cm. Emmailloter, essuyer, faire de l'ombre.",
        'de': 'Drei große Mulltücher aus Bio-Baumwolle, für alles. Große Tücher aus doppellagiger Bio-Baumwolle, 120 mal 120 cm. Pucken, aufstoßen, Schatten spenden.',
        'it': 'Tre grandi teli in mussola biologica, buoni per tutto. Grandi quadrati di cotone biologico a doppio strato, 120 per 120 cm. Per fasciare, per il rutto, per fare ombra.'}, 'three folded {value} organic muslin squares', axis='color', values=['White', 'Oatmeal', 'Green'], picture_per_value=True, attributes=dict(age_range='0 to 1', material='Cotton', size='')),
    P('K-BALANCE-BIKE', {'en': 'Balance bike', 'fr': 'Draisienne', 'de': 'Laufrad', 'it': 'Bicicletta senza pedali'}, ['outdoor'], 120, {'en': 'A birch balance bike with a padded seat and 12 inch tyres. Air tyres, a low frame and a seat that rises with the child. From two years.',
        'fr': "Une draisienne en bouleau avec une selle rembourrée et des pneus de 12 pouces. Pneus à air, cadre bas et une selle qui monte avec l'enfant. Dès deux ans.",
        'de': 'Ein Laufrad aus Birke mit gepolstertem Sattel und 12-Zoll-Reifen. Luftreifen, ein tiefer Rahmen und ein Sattel, der mit dem Kind wächst. Ab zwei Jahren.',
        'it': 'Una bici senza pedali in betulla con sella imbottita e gomme da 12 pollici. Gomme ad aria, telaio basso e sella che sale insieme al bambino. Da due anni.'}, 'a small {value} wooden balance bike', axis='color', values=['Red', 'Green', 'Blue'], picture_per_value=True, attributes=dict(age_range='1 to 3', material='Oak', size='')),
    P('K-SCOOTER', {'en': 'Three-wheel scooter', 'fr': 'Trottinette trois roues', 'de': 'Dreirad-Roller', 'it': 'Monopattino a tre ruote'}, ['outdoor'], 85, {'en': 'A lean-to-steer scooter with a light-up deck. Lean to steer, so it is easy to learn. The deck lights up when it rolls. From three years.',
        'fr': "Une trottinette qui tourne en penchant, avec un plateau lumineux. On penche pour tourner, c'est donc facile à apprendre. Le plateau s'allume quand elle roule. Dès trois ans.",
        'de': 'Ein Roller, der durch Gewichtsverlagerung lenkt, mit leuchtendem Trittbrett. Lenken durch Neigen, deshalb schnell gelernt. Das Trittbrett leuchtet beim Rollen. Ab drei Jahren.',
        'it': 'Un monopattino che sterza inclinandosi, con pedana luminosa. Si sterza inclinandosi, quindi si impara subito. La pedana si illumina quando rotola. Da tre anni.'}, 'a small {value} three wheel childrens scooter', axis='color', values=['Blue', 'Pink', 'Green'], picture_per_value=True, attributes=dict(age_range='3 to 5', material='Nylon', size='')),
    P('K-RAIN-SUIT', {'en': 'Rain suit', 'fr': 'Combinaison de pluie', 'de': 'Regenanzug', 'it': 'Tuta antipioggia'}, ['outdoor', 'clothing'], 45, {'en': 'A one-piece rain suit with taped seams and welded feet loops. Waterproof to 10 000 mm with taped seams and elastic cuffs. From one to six years.',
        'fr': 'Une combinaison de pluie une pièce, coutures étanchéifiées et passants de pied soudés. Imperméable à 10 000 mm, coutures étanchéifiées et poignets élastiques. De un à six ans.',
        'de': 'Ein einteiliger Regenanzug mit verschweißten Nähten und angeschweißten Fußschlaufen. Wasserdicht bis 10 000 mm, verschweißte Nähte und elastische Bündchen. Von einem bis sechs Jahre.',
        'it': 'Una tuta antipioggia intera, con cuciture nastrate e staffe per i piedi saldate. Impermeabile a 10 000 mm, cuciture nastrate e polsini elastici. Da uno a sei anni.'}, 'a {value} childrens one piece rain suit laid flat', axis='color', values=['Yellow', 'Blue Dark'], picture_per_value=True, attributes=dict(age_range='1 to 3', material='Recycled polyester', size='')),
    P('K-WELLIES', {'en': 'Wellies', 'fr': 'Bottes de pluie', 'de': 'Gummistiefel', 'it': 'Stivali di gomma'}, ['outdoor'], 28, {'en': 'Natural rubber wellies with a pull loop. Natural rubber with a cotton lining and a loop for pulling. Sizes from 20 to 34.',
        'fr': 'Des bottes en caoutchouc naturel avec une boucle pour tirer. Caoutchouc naturel, doublure en coton et une boucle pour les enfiler. Du 20 au 34.',
        'de': 'Gummistiefel aus Naturkautschuk mit einer Schlaufe zum Anziehen. Naturkautschuk mit Baumwollfutter und einer Schlaufe zum Ziehen. Größen 20 bis 34.',
        'it': 'Stivali in caucciù naturale con un passante per infilarli. Caucciù naturale, fodera di cotone e un passante per tirarli su. Dal 20 al 34.'}, 'a pair of {value} childrens rubber wellington boots', axis='color', values=['Yellow', 'Green', 'Red'], picture_per_value=True, attributes=dict(age_range='1 to 3', material='Rubber', size='')),
    P('K-HELMET', {'en': 'Kids helmet', 'fr': 'Casque enfant', 'de': 'Kinderhelm', 'it': 'Casco per bambini'}, ['outdoor'], 40, {'en': 'A light helmet with a dial fit and a rear light. Adjust the dial and the helmet fits for two years of growing. From two years.',
        'fr': 'Un casque léger avec un réglage à molette et un feu arrière. On tourne la molette et le casque suit deux ans de croissance. Dès deux ans.',
        'de': 'Ein leichter Helm mit Drehrad und Rücklicht. Am Rad drehen, und der Helm passt zwei Jahre lang mit. Ab zwei Jahren.',
        'it': 'Un casco leggero con regolazione a rotella e luce posteriore. Giri la rotella e il casco segue due anni di crescita. Da due anni.'}, 'a {value} childrens bike helmet', axis='color', values=['Blue', 'Pink', 'Green'], picture_per_value=True, attributes=dict(age_range='3 to 5', material='Recycled polyester', size='')),
    P('K-SAND-SET', {'en': 'Sand play set', 'fr': 'Set de jeux de sable', 'de': 'Sandspielzeug-Set', 'it': 'Set per la sabbia'}, ['outdoor'], 18, {'en': 'A bucket, a spade, a rake and two moulds in recycled plastic. Thick recycled plastic that survives a summer. The mould shapes are a fish and a star.',
        'fr': 'Un seau, une pelle, un râteau et deux moules en plastique recyclé. Du plastique recyclé épais qui survit à un été. Les moules sont un poisson et une étoile.',
        'de': 'Ein Eimer, eine Schaufel, ein Rechen und zwei Förmchen aus recyceltem Kunststoff. Dicker recycelter Kunststoff, der einen Sommer übersteht. Die Förmchen sind ein Fisch und ein Stern.',
        'it': "Un secchiello, una paletta, un rastrello e due formine in plastica riciclata. Plastica riciclata spessa che sopravvive a un'estate. Le formine sono un pesce e una stella."}, 'a colourful childrens sand bucket and spade set', attributes=dict(age_range='1 to 3', material='Recycled polyester', color='Yellow', size='')),
    P('K-KITE', {'en': 'Bird kite', 'fr': 'Cerf-volant oiseau', 'de': 'Vogeldrachen', 'it': 'Aquilone a forma di uccello'}, ['outdoor'], 22, {'en': 'A single-line kite shaped like a lark, easy to launch. A single line and a tail, ready to fly from the bag. From four years.',
        'fr': "Un cerf-volant à une ligne en forme d'alouette, facile à lancer. Une seule ligne et une queue, prêt à voler dès la sortie du sac. Dès quatre ans.",
        'de': 'Ein Einleinerdrachen in Form einer Lerche, leicht zu starten. Eine Leine und ein Schwanz, aus dem Beutel heraus flugbereit. Ab vier Jahren.',
        'it': 'Un aquilone a un filo a forma di allodola, facile da far partire. Un filo solo e una coda, pronto a volare appena esce dalla sacca. Da quattro anni.'}, 'a colourful bird shaped kite', attributes=dict(age_range='5 to 8', material='Nylon', color='Orange', size='')),
    P('K-NEWBORN-BOX', {'en': 'Newborn box', 'fr': 'Coffret naissance', 'de': 'Box für Neugeborene', 'it': 'Cofanetto nascita'}, ['gifts'], 70, {'en': 'A rattle, three muslins, a bodysuit pack and the board books, boxed. The four things every new baby needs, in a box with a card. Wrapped on request.',
        'fr': 'Un hochet, trois langes, un lot de bodys et les livres cartonnés, en coffret. Les quatre choses dont un bébé a besoin, dans une boîte avec une carte. Emballage cadeau sur demande.',
        'de': 'Eine Rassel, drei Mulltücher, ein Body-Set und die Pappbilderbücher, verpackt. Die vier Dinge, die ein neues Baby braucht, in einer Schachtel mit Karte. Auf Wunsch als Geschenk verpackt.',
        'it': 'Un sonaglio, tre teli in mussola, una confezione di body e i libri cartonati, in cofanetto. Le quattro cose che servono a un neonato, in una scatola con un biglietto. Su richiesta lo incartiamo.'}, 'an open gift box with a wooden rattle, muslins, bodysuits and board books', grouped=['K-RATTLE', 'K-MUSLINS-WHITE', 'K-BODYSUIT-WHITE', 'K-BOARD-BOOK'], attributes=dict(age_range='0 to 1', material='', color='', size='')),
    P('K-BIRTHDAY-BOX', {'en': 'Birthday box, age 3', 'fr': 'Coffret anniversaire, 3 ans', 'de': 'Geburtstagsbox, 3 Jahre', 'it': 'Cofanetto compleanno, 3 anni'}, ['gifts'], 95, {'en': 'A puzzle, the car set, a picture book and a sun hat. Four presents for a third birthday, chosen to be played with together. Wrapped on request.',
        'fr': 'Un puzzle, les voitures, un album et un chapeau de soleil. Quatre cadeaux pour un troisième anniversaire, choisis pour jouer ensemble. Emballage cadeau sur demande.',
        'de': 'Ein Puzzle, das Autoset, ein Bilderbuch und ein Sonnenhut. Vier Geschenke zum dritten Geburtstag, zum gemeinsamen Spielen ausgesucht. Auf Wunsch als Geschenk verpackt.',
        'it': 'Un puzzle, il set di macchinine, un albo illustrato e un cappello da sole. Quattro regali per il terzo compleanno, scelti per giocarci insieme. Su richiesta lo incartiamo.'}, 'an open gift box with a wooden puzzle, toy cars, a picture book and a sun hat', grouped=['K-PUZZLE', 'K-CAR-SET', 'K-PICTURE-BOOK', 'K-HAT-OATMEAL'], attributes=dict(age_range='3 to 5', material='', color='', size='')),
    P('K-GIFT-CARD', {'en': 'Little Lark gift card', 'fr': 'Carte cadeau Little Lark', 'de': 'Little Lark Geschenkkarte', 'it': 'Carta regalo Little Lark'}, ['gifts'], 30, {'en': 'A gift card by email. Delivered by email within the hour, with a message of your own. Valid for a year in the store.',
        'fr': "Une carte cadeau par email. Envoyée par email dans l'heure, avec votre message. Valable un an dans la boutique.",
        'de': 'Eine Geschenkkarte per E-Mail. Innerhalb einer Stunde per E-Mail zugestellt, mit einer eigenen Nachricht. Ein Jahr im Shop gültig.',
        'it': "Una carta regalo via email. Consegnata via email entro un'ora, con un messaggio tuo. Valida un anno nel negozio."}, 'a pale yellow gift card with a small bird illustration', type='virtual', attributes=dict(age_range='', material='', color='', size='')),
]
POSTS = [
    ('Toys by age, without the noise', '<p>Under one: things to hold, shake and chew. One to three: things to stack, push and pour. Three to five: things to pretend with. Five and up: things to build and break.</p><p>Fewer, better, and out of sight in rotation. A toy that comes back after a month is new again.</p>', 'A low shelf with a few wooden toys arranged with space between them in a bright room.'),
    ('How to size a child', '<p>Our sizes are heights in centimetres. Measure against a wall, add four for growing room, and pick the nearest size up. Trousers with an adjustable waist buy you a season.</p><p>Wash cold, dry flat, and they will fit the next child too.</p>', 'A child measured against a wall with pencil marks, seen from behind.'),
    ('Puddles are the plan', '<p>A rain suit, wellies and a warm layer underneath turn a wet day into the best day. Twenty minutes outside beats an hour of television, for everyone.</p><p>Hang the suit to dry, rinse the boots, and go again tomorrow.</p>', 'Yellow wellies jumping in a puddle on a garden path, low angle.'),
]
GALLERY = [('A child stacking wooden blocks on a rug in a sunlit playroom, seen from behind', 'toys'), ('A row of small linen clothes hanging on a wooden rail', 'clothing'), ('A tall shot of a nursery with a wooden crib, a mobile and a soft rug, morning light', 'nursery'), ('A picnic blanket in a garden with a kite, a ball and a basket of strawberries', 'outdoor'), ('A stack of picture books and a felt rabbit on a low wooden shelf', 'books')]
BRANDS = [('Little Lark', 'PLAY'), ('Pip & Pod', 'WOODEN TOYS'), ('Cloudling', 'SLEEP'), ('Wren', 'KNITS'), ('Puddle', 'OUTDOOR'), ('Fable', 'BOOKS'), ('Mimi', 'NURSERY'), ('Sprout', 'ORGANIC'), ('Tumble', 'ACTIVE'), ('Acorn', 'GIFTS')]
GALLERY_TITLE = 'Small days'
