CODE = 'sports'; ROOT = {'en': 'Sports', 'fr': 'Sport', 'de': 'Sport', 'it': 'Sport'}; STORE_NAME = 'Stride'; ATTRIBUTE_SET = 'Sports'; WEIGHT = 0.8
ATTRIBUTE_COLUMNS = ['sport', 'size', 'color', 'material']
ATTRIBUTES = [
    dict(code='sport', label='Sport', input='multiselect', scope='global', filterable=1, filterable_in_search=1, visible_on_front=1, used_in_product_listing=1, sets='Sports', group='General', sort_order=50),
]
OPTIONS = {'sport': ['Running', 'Cycling', 'Gym', 'Yoga', 'Hiking', 'Swimming']}
ROOT_DESCRIPTION = {'en': 'Gear for running, cycling, the gym and the trail, tested by people who train.',
                    'fr': "De l'équipement pour la course, le vélo, la salle et le sentier, testé par ceux qui s'entraînent.",
                    'de': 'Ausrüstung für Laufen, Radfahren, Studio und Trail, getestet von Menschen, die trainieren.',
                    'it': 'Attrezzatura per la corsa, la bici, la palestra e il sentiero, provata da chi si allena.'}
META_DESCRIPTION = 'Stride: running shoes, cycling kit, gym gear, yoga mats and hiking equipment, tested on the road and the trail.'
PRODUCT_STYLE = 'Studio product photograph of a single sports product on a plain white seamless background, crisp even light, no people, no text, no lettering, no logos, no watermark, centered with margin around it.'
SCENE_STYLE = 'Energetic editorial sports photograph, dawn light, wet asphalt or mountain trail, motion, no readable text, no lettering, no logos, no watermark.'
SCENES = {
    'hero-main': 'A runner in a bright jacket on a wet coastal road at dawn, seen from behind, motion blur in the legs.',
    'hero-side': 'A close up of running shoes on a wet running track with water droplets, low angle.',
    'editorial': 'A group of cyclists climbing a mountain pass in the early morning, seen from the side.',
    'about': 'A small sports shop with a treadmill for gait analysis and shelves of running shoes.',
}
CATEGORIES = [
    dict(path='running', name={'en': 'Running', 'fr': 'Course', 'de': 'Laufen', 'it': 'Corsa'}, description='Shoes, jackets and shorts for road and trail.', landing_title='Every road, every weather', landing_text='Road shoes, trail shoes and layers that breathe. We fit shoes on a treadmill in the shop and by video online.', scene='A pair of trail running shoes on a rocky mountain path with a view over a valley at sunrise.'),
    dict(path='cycling', name={'en': 'Cycling', 'fr': 'Vélo', 'de': 'Radfahren', 'it': 'Ciclismo'}, description='Jerseys, bibs, helmets and the small things.', landing_title='Comfort at kilometre eighty', landing_text='Bib shorts with a chamois that lasts, jerseys with pockets you can reach, and helmets that pass every test.', scene='A road bike leaning against a stone wall on a mountain road, helmet on the bars.'),
    dict(path='gym', name={'en': 'Gym & Training', 'fr': 'Salle et entraînement', 'de': 'Studio und Training', 'it': 'Palestra e allenamento'}, description='Weights, bands and the kit for a home corner.', landing_title='A gym in a corner', landing_text='Kettlebells, bands, a bench and a mat. Enough for most people, most of the time.', scene='A kettlebell, a pair of dumbbells and a rolled mat on a wooden floor by a window.'),
    dict(path='yoga', name={'en': 'Yoga & Recovery', 'fr': 'Yoga et récupération', 'de': 'Yoga und Regeneration', 'it': 'Yoga e recupero'}, description='Mats, blocks, rollers and balls.', landing_title='Slow down', landing_text='Natural rubber mats, cork blocks and the recovery tools physios actually use.', scene='A rolled cork yoga mat and two cork blocks on a wooden floor in a bright studio.'),
    dict(path='hiking', name={'en': 'Hiking', 'fr': 'Randonnée', 'de': 'Wandern', 'it': 'Escursionismo'}, description='Boots, packs and layers for a long day out.', landing_title='Further, drier, lighter', landing_text='Boots that are broken in on day one, packs under a kilo and layers that pack small.', scene='A hiker with a small backpack on a ridge path above the clouds at sunrise.'),
    dict(path='swimming', name={'en': 'Swimming', 'fr': 'Natation', 'de': 'Schwimmen', 'it': 'Nuoto'}, description='Goggles, suits and towels for pool and open water.', landing_title='Pool and open water', landing_text='Goggles that do not leak, suits that last a season of chlorine, and towels that dry in a bag.', scene='Swimming goggles and a folded towel on the edge of an outdoor pool at dawn.'),
]
HERO = dict(badge='New season', title='Gear that keeps up', text='Tested on our own runs, rides and climbs. If it fails us, it is not here.')
FEATURES = [('truck', 'Free delivery over 50', 'Next day on weekdays'), ('run', 'Shoe fitting', 'In store or by video'), ('arrow-back-up', '30-day trial', 'Run in them, return them'), ('shield-check', 'Two-year warranty', 'On every product')]
STORY = dict(title='We train in what we sell', text1='Stride is run by four people who race: two runners, a cyclist and a swimmer. Every product goes through at least a month of our own training before it is listed.', text2='If something fails, we say so on the product page. If it fails you, send it back.')
PROMO = dict(badge='Trail season', title='The trail kit', text='Shoes, a pack and a shell, chosen for a first mountain race.', path='running', button='See trail running', list_title='For the trail')
TESTIMONIALS = [('The video shoe fitting was better than the shop I used to go to. No injuries this year.', 'Elena R.', 'Oslo'), ('Bib shorts that survived a summer of riding. First pair that has.', 'Marcus T.', 'Leeds'), ('The cork mat has not slipped once in a hot class.', 'Priya S.', 'Toronto')]
NEWSLETTER = dict(title='Training notes', text='A short email every two weeks: what we tested, a session plan, and new arrivals.')
ABOUT = dict(title='Four people who race', paragraphs=['Stride started when two runners could not find a shop that fitted shoes properly. They bought a treadmill, a camera and a small lease.', 'A cyclist and a swimmer joined. Every product in the shop goes through a month of our own training first, and the notes are on the product page.', 'The treadmill is still there. Come and run on it, or send us a video and we fit you online.'])
REVIEWS = [
    ({'en': 'Fits as described', 'fr': 'Conforme à la description', 'de': 'Passt wie beschrieben', 'it': 'Veste come descritto'}, {'en': 'The fitting notes were accurate. No blisters on a 30 km run.',
                           'fr': 'Les conseils de taille étaient justes. Aucune ampoule sur 30 km.',
                           'de': 'Die Größenhinweise stimmten. Keine Blasen auf 30 km.',
                           'it': 'Le note sulla vestibilità erano giuste. Nessuna vescica su 30 km.'}, 5),
    ({'en': 'Good, sizing runs small', 'fr': 'Bien, taille petit', 'de': 'Gut, fällt klein aus', 'it': 'Buono, veste stretto'}, {'en': 'Quality is great. Go half a size up.',
                                 'fr': 'La qualité est excellente. Prenez une demi-taille au-dessus.',
                                 'de': 'Die Qualität ist super. Eine halbe Nummer größer nehmen.',
                                 'it': 'La qualità è ottima. Prendi mezza taglia in più.'}, 4),
    ({'en': 'Survived a season', 'fr': 'Il a passé la saison', 'de': 'Hat eine Saison überstanden', 'it': 'Ha superato una stagione'}, {'en': 'Rain, mud, a hundred washes. Still going.',
                           'fr': 'Pluie, boue, cent lavages. Toujours là.',
                           'de': 'Regen, Schlamm, hundert Wäschen. Läuft immer noch.',
                           'it': 'Pioggia, fango, cento lavaggi. Ancora qui.'}, 5),
    ({'en': 'Returned, no questions', 'fr': 'Retourné sans discussion', 'de': 'Zurückgegeben, ohne Fragen', 'it': 'Reso senza domande'}, {'en': 'Did not suit my stride. Return was easy and fast.',
                                'fr': 'Cela ne convenait pas à ma foulée. Le retour a été simple et rapide.',
                                'de': 'Passte nicht zu meinem Laufstil. Die Rückgabe war einfach und schnell.',
                                'it': 'Non andava con la mia falcata. Il reso è stato facile e veloce.'}, 4),
    ({'en': 'Grip in the wet', 'fr': "De l'accroche sur le mouillé", 'de': 'Grip bei Nässe', 'it': 'Aderenza sul bagnato'}, {'en': 'Ran a rainy trail and never slipped.',
                         'fr': "J'ai couru un sentier sous la pluie sans jamais glisser.",
                         'de': 'Bin einen nassen Trail gelaufen und nie gerutscht.',
                         'it': 'Ho corso un sentiero sotto la pioggia senza mai scivolare.'}, 5),
    ({'en': 'Bottle does not leak', 'fr': 'La gourde ne fuit pas', 'de': 'Die Flasche läuft nicht aus', 'it': 'La borraccia non perde'}, {'en': 'Upside down in the bag all day. Dry bag.',
                              'fr': "À l'envers dans le sac toute la journée. Sac sec.",
                              'de': 'Den ganzen Tag kopfüber in der Tasche. Trockene Tasche.',
                              'it': 'A testa in giù nella borsa tutto il giorno. Borsa asciutta.'}, 5),
    ({'en': 'Light and warm', 'fr': 'Léger et chaud', 'de': 'Leicht und warm', 'it': 'Leggera e calda'}, {'en': 'Packs into its own pocket and still cuts the wind.',
                        'fr': 'Elle se range dans sa propre poche et coupe encore le vent.',
                        'de': 'Lässt sich in die eigene Tasche packen und hält trotzdem den Wind ab.',
                        'it': 'Si ripiega nella sua tasca e taglia comunque il vento.'}, 5),
    ({'en': 'Seams rubbed', 'fr': 'Les coutures ont frotté', 'de': 'Die Nähte haben gescheuert', 'it': 'Le cuciture hanno sfregato'}, {'en': 'Great shorts but a seam rubbed on long rides. Fine under 40 km.',
                      'fr': 'Très bon cuissard mais une couture a frotté sur les longues sorties. Parfait sous 40 km.',
                      'de': 'Tolle Hose, aber eine Naht hat bei langen Fahrten gescheuert. Unter 40 km gut.',
                      'it': 'Ottimi pantaloncini ma una cucitura ha sfregato nelle uscite lunghe. Sotto i 40 km vanno bene.'}, 3),
    ({'en': 'Mat stays put', 'fr': 'Le tapis ne glisse pas', 'de': 'Die Matte bleibt liegen', 'it': 'Il tappetino non scivola'}, {'en': 'No sliding on a wooden floor, even in a sweaty class.',
                       'fr': 'Aucun glissement sur un parquet, même pendant un cours transpirant.',
                       'de': 'Kein Rutschen auf Holzboden, auch nicht in einer verschwitzten Stunde.',
                       'it': 'Non scivola sul parquet, nemmeno in una lezione sudata.'}, 5),
    ({'en': 'Zips froze', 'fr': 'Les fermetures ont gelé', 'de': 'Die Reißverschlüsse froren ein', 'it': 'Le cerniere si sono bloccate'}, {'en': 'Fine jacket, but the zip pulls are small with gloves on.',
                    'fr': 'Bonne veste, mais les tirettes sont petites avec des gants.',
                    'de': 'Gute Jacke, aber die Zipper sind mit Handschuhen zu klein.',
                    'it': 'Bella giacca, ma i cursori sono piccoli con i guanti.'}, 4),
    ({'en': 'Race day shoe', 'fr': 'La chaussure des jours de course', 'de': 'Der Wettkampfschuh', 'it': 'La scarpa da gara'}, {'en': 'Saved it for the marathon. Personal best.',
                       'fr': "Je l'ai gardée pour le marathon. Record personnel.",
                       'de': 'Für den Marathon aufgehoben. Persönliche Bestzeit.',
                       'it': "L'ho tenuta per la maratona. Record personale."}, 5),
    ({'en': 'Straps dig in', 'fr': 'Les bretelles rentrent', 'de': 'Die Gurte schneiden ein', 'it': 'Gli spallacci segnano'}, {'en': 'Backpack carries well when full, straps dig when empty.',
                       'fr': 'Le sac porte bien quand il est plein, les bretelles rentrent quand il est vide.',
                       'de': 'Der Rucksack trägt sich voll gut, leer schneiden die Gurte ein.',
                       'it': 'Lo zaino porta bene quando è pieno, gli spallacci segnano quando è vuoto.'}, 3),
    ({'en': 'Socks that stay up', 'fr': 'Des chaussettes qui tiennent', 'de': 'Socken, die halten', 'it': 'Calze che stanno su'}, {'en': 'Finally. No slipping into the shoe at km ten.',
                            'fr': 'Enfin. Elles ne glissent plus dans la chaussure au dixième kilomètre.',
                            'de': 'Endlich. Kein Rutschen in den Schuh bei Kilometer zehn.',
                            'it': 'Finalmente. Non scivolano nella scarpa al decimo chilometro.'}, 5),
    ({'en': 'Heavier than listed', 'fr': "Plus lourd qu'annoncé", 'de': 'Schwerer als angegeben', 'it': 'Più pesante di quanto indicato'}, {'en': 'Good bag, but 200 g over the stated weight on my scale.',
                             'fr': 'Bon sac, mais 200 g de plus que le poids annoncé sur ma balance.',
                             'de': 'Gute Tasche, aber 200 g über dem angegebenen Gewicht auf meiner Waage.',
                             'it': 'Buona borsa, ma 200 g oltre il peso dichiarato sulla mia bilancia.'}, 3),
    ({'en': 'Bright enough for night', 'fr': 'Assez visible la nuit', 'de': 'Hell genug für die Nacht', 'it': 'Abbastanza visibile di notte'}, {'en': 'The reflective panels light up like a sign.',
                                 'fr': "Les bandes réfléchissantes s'allument comme un panneau.",
                                 'de': 'Die Reflexstreifen leuchten wie ein Schild.',
                                 'it': 'Le bande riflettenti si accendono come un cartello.'}, 5),
    ({'en': 'Wore through at the toe', 'fr': 'Usé au bout', 'de': 'An der Zehe durchgelaufen', 'it': 'Consumata sulla punta'}, {'en': 'Six hundred kilometres, which is fair. Buying again.',
                                 'fr': "Six cents kilomètres, c'est honnête. Je rachète.",
                                 'de': 'Sechshundert Kilometer, das ist fair. Ich kaufe wieder.',
                                 'it': 'Seicento chilometri, che è onesto. La ricompro.'}, 4),
    ({'en': 'Great for cold mornings', 'fr': 'Parfait pour les matins froids', 'de': 'Super für kalte Morgen', 'it': 'Ottimo per le mattine fredde'}, {'en': 'Thermal layer under a shell and I was warm at zero degrees.',
                                 'fr': "Une couche thermique sous une coupe-vent et j'avais chaud à zéro degré.",
                                 'de': 'Thermoschicht unter einer Hülle und mir war bei null Grad warm.',
                                 'it': 'Strato termico sotto un guscio e stavo al caldo a zero gradi.'}, 5),
    ({'en': 'Ball holds pressure', 'fr': 'Le ballon garde la pression', 'de': 'Der Ball hält den Druck', 'it': 'Il pallone tiene la pressione'}, {'en': 'Pumped it in March, still firm in May.',
                             'fr': 'Gonflé en mars, encore ferme en mai.',
                             'de': 'Im März aufgepumpt, im Mai noch prall.',
                             'it': 'Gonfiato a marzo, ancora duro a maggio.'}, 5),
    ({'en': 'Laces too long', 'fr': 'Lacets trop longs', 'de': 'Schnürsenkel zu lang', 'it': 'Lacci troppo lunghi'}, {'en': 'Double knot needed. Otherwise a great shoe.',
                        'fr': 'Il faut un double nœud. Sinon une très bonne chaussure.',
                        'de': 'Doppelter Knoten nötig. Sonst ein toller Schuh.',
                        'it': 'Serve un doppio nodo. Per il resto una gran scarpa.'}, 4),
    ({'en': 'Kids team loves them', 'fr': "L'équipe des enfants les adore", 'de': 'Die Kindermannschaft liebt sie', 'it': 'La squadra dei bambini le adora'}, {'en': 'Ordered twelve. All fit, all survived the season.',
                              'fr': "J'en ai commandé douze. Toutes à la bonne taille, toutes ont passé la saison.",
                              'de': 'Zwölf bestellt. Alle passten, alle haben die Saison überstanden.',
                              'it': 'Ne ho ordinate dodici. Tutte giuste, tutte hanno superato la stagione.'}, 5),
    ({'en': 'Watch strap is comfy', 'fr': 'Le bracelet est confortable', 'de': 'Das Armband ist bequem', 'it': 'Il cinturino è comodo'}, {'en': 'Soft silicone, no sweat rash, easy to swap.',
                              'fr': 'Silicone souple, aucune irritation, facile à changer.',
                              'de': 'Weiches Silikon, kein Schweißausschlag, leicht zu wechseln.',
                              'it': 'Silicone morbido, nessuna irritazione, facile da cambiare.'}, 5),
    ({'en': 'Pockets in the right place', 'fr': 'Des poches bien placées', 'de': 'Taschen an der richtigen Stelle', 'it': 'Tasche al posto giusto'}, {'en': 'Phone, key, gel. Nothing bounces.',
                                    'fr': 'Téléphone, clé, gel. Rien ne bouge.',
                                    'de': 'Handy, Schlüssel, Gel. Nichts hüpft.',
                                    'it': 'Telefono, chiave, gel. Niente rimbalza.'}, 5),
    ({'en': 'Faded after a summer', 'fr': 'Délavé après un été', 'de': 'Nach einem Sommer verblasst', 'it': "Sbiadito dopo un'estate"}, {'en': 'Colour went from navy to blue. Still works.',
                              'fr': 'La couleur est passée du marine au bleu. Cela fonctionne encore.',
                              'de': 'Die Farbe ging von Marine zu Blau. Funktioniert trotzdem.',
                              'it': 'Il colore è passato dal blu navy al blu. Funziona ancora.'}, 3),
    ({'en': 'Delivered before the race', 'fr': 'Livré avant la course', 'de': 'Vor dem Rennen geliefert', 'it': 'Consegnato prima della gara'}, {'en': 'Ordered Tuesday, raced Saturday. Thank you.',
                                   'fr': 'Commandé mardi, couru samedi. Merci.',
                                   'de': 'Dienstag bestellt, Samstag gelaufen. Danke.',
                                   'it': 'Ordinato martedì, gara sabato. Grazie.'}, 5),
]
def P(sku, name, cats, price, desc, prompt, **kw):
    d = dict(sku=sku, name=name, categories=cats, price=price, description=desc, prompt=prompt); d.update(kw); return d
SHOE = ['38', '39', '40', '41', '42', '43', '44', '45']
CLOTH = ['XS', 'S', 'M', 'L', 'XL']
PRODUCTS = [
    P('S-ROAD-SHOE', {'en': 'Road running shoe', 'fr': 'Chaussure de running sur route', 'de': 'Laufschuh für die Straße', 'it': 'Scarpa da running su strada'}, ['running'], 140, {'en': 'A daily trainer with a 32 mm stack, a nylon plate and a wide toe box. Soft enough for easy days, quick enough for tempo. Expect 700 km before the foam gives up.',
        'fr': "Une chaussure d'entraînement quotidien avec 32 mm de semelle, une plaque nylon et un avant-pied large. Assez souple pour les jours faciles, assez vive pour le tempo. Comptez 700 km avant que la mousse ne rende les armes.",
        'de': 'Ein Trainingsschuh für jeden Tag, mit 32 mm Sprengkissen, Nylonplatte und breiter Zehenbox. Weich genug für ruhige Tage, schnell genug für Tempoläufe. Rechne mit 700 km, bevor der Schaum aufgibt.',
        'it': 'Una scarpa da allenamento quotidiano con 32 mm di intersuola, piastra in nylon e avampiede largo. Morbida per i giorni facili, reattiva per il medio. Conta 700 km prima che la schiuma si arrenda.'}, 'a {value} road running shoe seen from the side', axis='color', values=['Blue', 'Black', 'Orange'], picture_per_value=True, attributes=dict(sport='Running', material='Recycled polyester', size='')),
    P('S-TRAIL-SHOE', {'en': 'Trail running shoe', 'fr': 'Chaussure de trail', 'de': 'Trailschuh', 'it': 'Scarpa da trail'}, ['running', 'hiking'], 155, {'en': 'Five millimetre lugs, a rock plate and a gaiter attachment. Grip in mud, protection on rocks, and a fit that stays put on descents. Drains fast after a river.',
        'fr': "Des crampons de cinq millimètres, une plaque de protection et un accroche-guêtre. De l'accroche dans la boue, de la protection sur les cailloux et un maintien qui ne bouge pas en descente. Elle sèche vite après un gué.",
        'de': 'Fünf Millimeter Stollen, eine Steinschutzplatte und eine Gamaschenöse. Grip im Schlamm, Schutz auf Steinen und ein Sitz, der bergab nicht wandert. Nach einer Furt läuft das Wasser schnell wieder heraus.',
        'it': "Tacchetti da cinque millimetri, piastra antiroccia e attacco per la ghetta. Tiene nel fango, protegge sulle pietre e non balla in discesa. Dopo un guado l'acqua esce in fretta."}, 'a {value} trail running shoe with deep lugs seen from the side', axis='color', values=['Green', 'Black'], picture_per_value=True, attributes=dict(sport='Running|Hiking', material='Recycled polyester', size='')),
    P('S-RACE-SHOE', {'en': 'Race day shoe', 'fr': 'La chaussure des jours de course', 'de': 'Der Wettkampfschuh', 'it': 'La scarpa da gara'}, ['running'], 220, {'en': 'A carbon plate, a light foam and no compromise. For race day only. Four millimetre drop, 200 g in a size 42, and a plate that gives back what you put in. Save it for the start line.',
        'fr': "Une plaque carbone, une mousse légère et aucun compromis. Pour les jours de course, rien d'autre. Quatre millimètres de drop, 200 g en 42, et une plaque qui rend ce que vous lui donnez. Gardez-la pour la ligne de départ.",
        'de': 'Eine Carbonplatte, ein leichter Schaum und kein Kompromiss. Nur für den Wettkampftag. Vier Millimeter Sprengung, 200 g in Größe 42, und eine Platte, die zurückgibt, was du hineinsteckst. Heb ihn für die Startlinie auf.',
        'it': 'Una piastra in carbonio, una schiuma leggera e nessun compromesso. Solo per il giorno della gara. Quattro millimetri di drop, 200 g nel numero 42, e una piastra che restituisce quello che le dai. Tienila per la linea di partenza.'}, 'a bright yellow lightweight racing shoe with a carbon plate', axis='size', values=SHOE, attributes=dict(sport='Running', material='Recycled polyester', color='Yellow')),
    P('S-RUN-JACKET', {'en': 'Running shell', 'fr': 'Coupe-vent de running', 'de': 'Laufjacke', 'it': 'Giacca da running'}, ['running'], 130, {'en': 'A 90 g waterproof shell that packs into its own pocket. Taped seams and a hood that stays up in wind. It packs to the size of a fist.',
        'fr': "Une veste imperméable de 90 g qui se range dans sa propre poche. Coutures étanchéifiées et capuche qui tient dans le vent. Elle se plie à la taille d'un poing.",
        'de': 'Eine 90 g leichte wasserdichte Jacke, die in ihre eigene Tasche passt. Verschweißte Nähte und eine Kapuze, die im Wind oben bleibt. Zusammengelegt so groß wie eine Faust.',
        'it': 'Una giacca impermeabile da 90 g che si ripiega nella sua tasca. Cuciture nastrate e cappuccio che tiene anche con il vento. Ripiegata sta in un pugno.'}, 'a lightweight {value} running rain jacket laid flat', axis='color', values=['Yellow', 'Black', 'Blue'], picture_per_value=True, attributes=dict(sport='Running|Cycling', material='Recycled polyester', size='')),
    P('S-RUN-SHORT', {'en': 'Split shorts', 'fr': 'Short fendu', 'de': 'Split-Shorts', 'it': 'Pantaloncini con spacco'}, ['running'], 45, {'en': 'Five-inch split shorts with a brief liner and a zip pocket. The split lets the leg move, the liner stops the chafe. The pocket holds a phone.',
        'fr': 'Un short fendu de cinq pouces avec slip intégré et poche zippée. La fente laisse la jambe libre, le slip évite les frottements. La poche avale un téléphone.',
        'de': 'Fünf-Zoll-Split-Shorts mit Innenslip und Reißverschlusstasche. Der Schlitz lässt das Bein laufen, der Slip verhindert das Scheuern. In die Tasche passt ein Telefon.',
        'it': 'Pantaloncini con spacco da cinque pollici, con slip interno e tasca con zip. Lo spacco lascia libera la gamba, lo slip evita gli sfregamenti. Nella tasca ci sta il telefono.'}, 'a pair of {value} split running shorts laid flat', axis='color', values=['Black', 'Blue Dark', 'Green'], picture_per_value=True, attributes=dict(sport='Running', material='Recycled polyester', size='')),
    P('S-RUN-TEE', {'en': 'Running tee', 'fr': 'T-shirt de running', 'de': 'Lauf-Shirt', 'it': 'Maglia da running'}, ['running', 'gym'], 40, {'en': 'A recycled polyester tee with flat seams and a reflective hit. It dries in an hour and never smells of yesterday. Cut close without clinging.',
        'fr': "Un t-shirt en polyester recyclé, coutures plates et touche réfléchissante. Il sèche en une heure et ne garde jamais l'odeur de la veille. Une coupe près du corps, sans coller.",
        'de': 'Ein Shirt aus recyceltem Polyester mit flachen Nähten und einem Reflexstreifen. Es trocknet in einer Stunde und riecht nie nach gestern. Schmal geschnitten, ohne zu kleben.',
        'it': "Una maglia in poliestere riciclato con cuciture piatte e un dettaglio riflettente. Asciuga in un'ora e non sa mai di ieri. Vestibilità aderente senza appiccicarsi."}, 'a {value} technical running t-shirt laid flat', axis='color', values=['White', 'Black', 'Orange'], picture_per_value=True, attributes=dict(sport='Running|Gym', material='Recycled polyester', size='')),
    P('S-RUN-SOCKS', {'en': 'Running socks, 3 pack', 'fr': 'Chaussettes de running, lot de 3', 'de': 'Laufsocken, 3er-Pack', 'it': 'Calze da running, confezione da 3'}, ['running'], 24, {'en': 'Merino blend, cushioned heel, no seam at the toe. Merino keeps feet cool in summer and warm in winter. Three pairs in one colour.',
        'fr': "Mélange mérinos, talon rembourré, sans couture aux orteils. Le mérinos garde le pied frais l'été et chaud l'hiver. Trois paires dans une seule couleur.",
        'de': 'Merinomischung, gepolsterte Ferse, keine Naht an den Zehen. Merino hält den Fuß im Sommer kühl und im Winter warm. Drei Paar in einer Farbe.',
        'it': "Misto merino, tallone imbottito, senza cuciture sulle dita. Il merino tiene il piede fresco d'estate e caldo d'inverno. Tre paia in un solo colore."}, 'three pairs of grey and white running socks', axis='size', values=['36', '39', '42', '45'], attributes=dict(sport='Running|Hiking', material='Wool', color='Grey')),
    P('S-HEADLAMP', {'en': 'Running headlamp', 'fr': 'Lampe frontale de course', 'de': 'Stirnlampe zum Laufen', 'it': 'Lampada frontale da corsa'}, ['running', 'hiking'], 60, {'en': 'A 400 lumen headlamp with a rechargeable battery and a red rear light. Enough light for a trail at speed, with a red light behind for the road. Charges by USB-C.',
        'fr': 'Une frontale de 400 lumens avec batterie rechargeable et feu rouge arrière. De quoi éclairer un sentier à bonne allure, avec un feu rouge derrière pour la route. Se recharge en USB-C.',
        'de': 'Eine 400-Lumen-Stirnlampe mit Akku und rotem Rücklicht. Genug Licht für einen Trail im Tempo, hinten ein rotes Licht für die Straße. Lädt über USB-C.',
        'it': 'Una frontale da 400 lumen con batteria ricaricabile e luce rossa posteriore. Luce che basta per un sentiero a ritmo, e dietro una luce rossa per la strada. Si ricarica in USB-C.'}, 'a small black rechargeable headlamp', attributes=dict(sport='Running|Hiking', material='Nylon', color='Black', size='One size')),
    P('S-WATCH-STRAP', {'en': 'Running belt', 'fr': 'Ceinture de running', 'de': 'Laufgürtel', 'it': 'Cintura da running'}, ['running'], 25, {'en': 'A stretch belt that holds a phone and a gel without bouncing. Two pockets that stretch and a buckle that stays flat. It fits most phones.',
        'fr': "Une ceinture extensible qui porte un téléphone et un gel sans rebondir. Deux poches qui s'écartent et une boucle qui reste plate. Elle accepte la plupart des téléphones.",
        'de': 'Ein elastischer Gürtel, der Telefon und Gel trägt, ohne zu hüpfen. Zwei dehnbare Taschen und eine Schnalle, die flach bleibt. Die meisten Telefone passen hinein.',
        'it': 'Una cintura elastica che porta telefono e gel senza rimbalzare. Due tasche che si allargano e una fibbia che resta piatta. Ci sta quasi ogni telefono.'}, 'a black stretch running belt', attributes=dict(sport='Running', material='Nylon', color='Black', size='One size')),
    P('S-JERSEY', {'en': 'Cycling jersey', 'fr': 'Maillot de vélo', 'de': 'Radtrikot', 'it': 'Maglia da ciclismo'}, ['cycling'], 95, {'en': 'A race-fit jersey with three pockets and a full zip. Long in the back, short in the front, with a silicone gripper at the hem. The pockets hold a day of food.',
        'fr': 'Un maillot coupe course avec trois poches et une fermeture intégrale. Long dans le dos, court devant, avec une bande silicone à la taille. Les poches portent une journée de ravitaillement.',
        'de': 'Ein Trikot im Renn-Schnitt mit drei Taschen und durchgehendem Reißverschluss. Hinten lang, vorn kurz, mit Silikonband am Saum. In die Taschen passt die Verpflegung für einen Tag.',
        'it': 'Una maglia dal taglio race con tre tasche e zip intera. Lunga dietro, corta davanti, con elastico siliconato in vita. Nelle tasche ci sta il cibo di una giornata.'}, 'a {value} short sleeve cycling jersey laid flat', axis='color', values=['Blue Dark', 'Red', 'White'], picture_per_value=True, attributes=dict(sport='Cycling', material='Recycled polyester', size='')),
    P('S-BIB-SHORT', {'en': 'Bib shorts', 'fr': 'Cuissard à bretelles', 'de': 'Trägerhose', 'it': 'Salopette da ciclismo'}, ['cycling'], 140, {'en': 'A chamois that lasts six hours and straps that do not dig. The chamois is dense where you sit and thin where you do not. The leg grippers do not squeeze.',
        'fr': "Une peau de chamois qui tient six heures et des bretelles qui ne scient pas. Le fond est dense là où l'on s'appuie et fin ailleurs. Les bandes de jambe ne serrent pas.",
        'de': 'Ein Sitzpolster, das sechs Stunden hält, und Träger, die nicht einschneiden. Das Polster ist dicht, wo du sitzt, und dünn, wo nicht. Die Beinabschlüsse schnüren nicht ein.',
        'it': 'Un fondello che regge sei ore e bretelle che non segnano. Il fondello è denso dove appoggi e sottile dove non serve. Gli elastici alle gambe non stringono.'}, 'a pair of black cycling bib shorts laid flat', axis='size', values=CLOTH, attributes=dict(sport='Cycling', material='Recycled polyester', color='Black')),
    P('S-HELMET', {'en': 'Road helmet', 'fr': 'Casque route', 'de': 'Rennradhelm', 'it': 'Casco da strada'}, ['cycling'], 160, {'en': 'A ventilated road helmet with rotational protection, 280 g. Twenty vents, a dial fit and a rear light mount. It passes every current standard.',
        'fr': 'Un casque route ventilé avec protection rotationnelle, 280 g. Vingt aérations, un réglage à molette et un support de feu arrière. Il passe toutes les normes en vigueur.',
        'de': 'Ein belüfteter Rennradhelm mit Rotationsschutz, 280 g. Zwanzig Öffnungen, ein Drehrad und eine Halterung für das Rücklicht. Er erfüllt alle geltenden Normen.',
        'it': "Un casco da strada ventilato con protezione rotazionale, 280 g. Venti prese d'aria, regolazione a rotella e attacco per la luce posteriore. Supera tutte le norme in vigore."}, 'a {value} road cycling helmet seen from the side', axis='color', values=['White', 'Black', 'Red'], picture_per_value=True, attributes=dict(sport='Cycling', material='Recycled polyester', size='')),
    P('S-GILET', {'en': 'Wind gilet', 'fr': 'Gilet coupe-vent', 'de': 'Windweste', 'it': 'Gilet antivento'}, ['cycling'], 70, {'en': 'A packable gilet for the descent. A windproof front, a mesh back, and a pocket it packs into. It weighs 60 g.',
        'fr': 'Un gilet compressible pour la descente. Un devant coupe-vent, un dos en filet, et une poche dans laquelle il se range. Il pèse 60 g.',
        'de': 'Eine packbare Weste für die Abfahrt. Vorn winddicht, hinten Mesh, und eine Tasche, in der sie verschwindet. Sie wiegt 60 g.',
        'it': 'Un gilet comprimibile per la discesa. Davanti antivento, dietro in rete, e una tasca in cui si infila. Pesa 60 g.'}, 'a {value} lightweight cycling gilet laid flat', axis='color', values=['Yellow', 'Black'], picture_per_value=True, attributes=dict(sport='Cycling|Running', material='Recycled polyester', size='')),
    P('S-GLOVES', {'en': 'Cycling mitts', 'fr': 'Gants courts de vélo', 'de': 'Kurzfingerhandschuhe', 'it': 'Guanti corti da ciclismo'}, ['cycling'], 30, {'en': 'Gel-padded mitts with a terry thumb. Gel where the bars press and terry on the thumb for a runny nose. Velcro at the wrist.',
        'fr': "Des gants courts rembourrés de gel avec un pouce en éponge. Du gel là où le cintre appuie et de l'éponge sur le pouce pour le nez qui coule. Velcro au poignet.",
        'de': 'Kurzfingerhandschuhe mit Gelpolster und Frotteedaumen. Gel dort, wo der Lenker drückt, und Frottee am Daumen für die laufende Nase. Klettverschluss am Handgelenk.',
        'it': 'Guanti corti con imbottitura in gel e pollice in spugna. Gel dove preme il manubrio e spugna sul pollice per il naso che cola. Velcro al polso.'}, 'a pair of black fingerless cycling gloves', axis='size', values=['S', 'M', 'L'], attributes=dict(sport='Cycling', material='Nylon', color='Black')),
    P('S-BOTTLE', {'en': 'Insulated bottle', 'fr': 'Bouteille isotherme', 'de': 'Isolierflasche', 'it': 'Borraccia termica'}, ['cycling', 'gym'], 18, {'en': 'A 650 ml insulated bottle that keeps water cold for three hours. Double-walled steel that fits a bike cage. The lid opens with one hand.',
        'fr': "Une bouteille isotherme de 650 ml qui garde l'eau fraîche trois heures. De l'acier à double paroi qui entre dans un porte-bidon. Le bouchon s'ouvre d'une main.",
        'de': 'Eine 650-ml-Isolierflasche, die Wasser drei Stunden kalt hält. Doppelwandiger Stahl, der in den Flaschenhalter passt. Der Deckel öffnet mit einer Hand.',
        'it': "Una borraccia termica da 650 ml che tiene l'acqua fresca per tre ore. Acciaio a doppia parete che entra nel portaborraccia. Il tappo si apre con una mano."}, 'a {value} insulated cycling water bottle', axis='color', values=['Black', 'White', 'Blue'], picture_per_value=True, attributes=dict(sport='Cycling|Gym|Running', material='Recycled polyester', size='One size')),
    P('S-BIKE-LIGHT', {'en': 'Bike light set', 'fr': 'Jeu de feux de vélo', 'de': 'Fahrradlicht-Set', 'it': 'Set luci per bicicletta'}, ['cycling'], 55, {'en': 'A 600 lumen front and a 50 lumen rear, USB-C. The front light runs three hours on full, the rear light ten. Both mount without tools.',
        'fr': "Un feu avant de 600 lumens et un arrière de 50, en USB-C. Le feu avant tient trois heures à pleine puissance, l'arrière dix. Les deux se montent sans outil.",
        'de': 'Ein 600-Lumen-Frontlicht und ein 50-Lumen-Rücklicht, USB-C. Das Frontlicht hält auf voller Stufe drei Stunden, das Rücklicht zehn. Beide montieren sich ohne Werkzeug.',
        'it': "Una luce anteriore da 600 lumen e una posteriore da 50, in USB-C. L'anteriore dura tre ore al massimo, la posteriore dieci. Si montano senza attrezzi."}, 'a pair of small black bike lights, front and rear', attributes=dict(sport='Cycling', material='Nylon', color='Black', size='One size')),
    P('S-PUMP', {'en': 'Mini pump', 'fr': 'Mini pompe', 'de': 'Minipumpe', 'it': 'Micropompa'}, ['cycling'], 28, {'en': 'A 100 psi mini pump with a hose and a frame mount. The hose saves the valve and the frame mount saves the pocket. It reaches 100 psi in a minute.',
        'fr': 'Une mini pompe 100 psi avec flexible et support de cadre. Le flexible épargne la valve et le support épargne la poche. Elle atteint 100 psi en une minute.',
        'de': 'Eine Minipumpe mit 100 psi, Schlauch und Rahmenhalter. Der Schlauch schont das Ventil, der Halter die Tasche. Sie erreicht 100 psi in einer Minute.',
        'it': "Una micropompa da 100 psi con tubetto e attacco al telaio. Il tubetto salva la valvola e l'attacco salva la tasca. Arriva a 100 psi in un minuto."}, 'a small aluminium bicycle mini pump', attributes=dict(sport='Cycling', material='Stainless steel', color='Silver', size='One size')),
    P('S-KETTLEBELL', {'en': 'Cast iron kettlebell', 'fr': 'Kettlebell en fonte', 'de': 'Kettlebell aus Gusseisen', 'it': 'Kettlebell in ghisa'}, ['gym'], 45, {'en': 'A powder-coated kettlebell with a smooth handle. Cast in one piece, so nothing loosens. Available from 8 to 32 kg.',
        'fr': 'Une kettlebell époxy avec une poignée lisse. Coulée en une seule pièce, rien ne se desserre. De 8 à 32 kg.',
        'de': 'Eine pulverbeschichtete Kettlebell mit glattem Griff. Aus einem Stück gegossen, da lockert sich nichts. Von 8 bis 32 kg.',
        'it': 'Un kettlebell verniciato a polvere con maniglia liscia. Fuso in un pezzo solo, quindi non si allenta niente. Da 8 a 32 kg.'}, 'a black cast iron kettlebell', axis='size', values=['8', '12', '16', '20', '24'], attributes=dict(sport='Gym', material='Stainless steel', color='Black')),
    P('S-DUMBBELLS', {'en': 'Adjustable dumbbells', 'fr': 'Haltères réglables', 'de': 'Verstellbare Kurzhanteln', 'it': 'Manubri regolabili'}, ['gym'], 290, {'en': 'A pair that goes from 2 to 24 kg with a dial. Turn the dial and the plates lock in. A whole rack in the space of one pair.',
        'fr': "Une paire qui va de 2 à 24 kg avec une molette. On tourne la molette et les disques se verrouillent. Tout un rack dans la place d'une paire.",
        'de': 'Ein Paar, das per Drehrad von 2 auf 24 kg geht. Rad drehen, und die Scheiben rasten ein. Ein ganzer Ständer auf dem Platz eines Paares.',
        'it': 'Una coppia che va da 2 a 24 kg con una rotella. Giri la rotella e i dischi si agganciano. Una rastrelliera intera nello spazio di una coppia.'}, 'a pair of adjustable dumbbells on a stand', attributes=dict(sport='Gym', material='Stainless steel', color='Black', size='One size')),
    P('S-BANDS', {'en': 'Resistance bands, set of 5', 'fr': 'Bandes élastiques, lot de 5', 'de': 'Widerstandsbänder, 5er-Set', 'it': 'Elastici, set da 5'}, ['gym', 'yoga'], 30, {'en': 'Five latex bands from light to heavy, with a door anchor. Five tensions from 5 to 50 kg, with handles and a door anchor. They roll into the pouch.',
        'fr': 'Cinq bandes en latex, de légère à forte, avec une ancre de porte. Cinq tensions de 5 à 50 kg, avec poignées et ancre de porte. Elles se roulent dans la pochette.',
        'de': 'Fünf Latexbänder von leicht bis schwer, mit Türanker. Fünf Stärken von 5 bis 50 kg, mit Griffen und Türanker. Sie rollen sich in den Beutel.',
        'it': 'Cinque elastici in lattice, da leggero a duro, con ancoraggio per la porta. Cinque tensioni da 5 a 50 kg, con maniglie e ancoraggio. Si arrotolano nella custodia.'}, 'five colourful resistance bands laid in a fan', attributes=dict(sport='Gym|Yoga', material='Rubber', color='Green', size='One size')),
    P('S-BENCH', {'en': 'Folding bench', 'fr': 'Banc pliant', 'de': 'Klappbank', 'it': 'Panca pieghevole'}, ['gym'], 180, {'en': 'A flat-to-incline bench that folds under a bed. Seven positions from flat to upright, rated for 300 kg. It folds in seconds.',
        'fr': 'Un banc plat-incliné qui se plie sous un lit. Sept positions du plat à la verticale, prévu pour 300 kg. Il se plie en quelques secondes.',
        'de': 'Eine Bank von flach bis schräg, die unter ein Bett passt. Sieben Positionen von flach bis aufrecht, für 300 kg zugelassen. Sie klappt in Sekunden zusammen.',
        'it': 'Una panca da piana a inclinata che si ripiega sotto il letto. Sette posizioni, dalla piana alla verticale, portata 300 kg. Si chiude in pochi secondi.'}, 'a black folding weight bench', attributes=dict(sport='Gym', material='Stainless steel', color='Black', size='One size')),
    P('S-JUMP-ROPE', {'en': 'Speed rope', 'fr': 'Corde à sauter de vitesse', 'de': 'Speed Rope', 'it': 'Corda da salto veloce'}, ['gym'], 22, {'en': 'A steel cable rope with ball bearings and a screw-lock length. The cable spins fast and the handles stay cool. Cut it to length once and lock it.',
        'fr': 'Une corde en câble acier avec roulements à billes et longueur verrouillable. Le câble tourne vite et les poignées restent fraîches. On la coupe à la bonne longueur une fois pour toutes.',
        'de': 'Ein Springseil aus Stahlkabel mit Kugellagern und schraubbarer Längenarretierung. Das Kabel dreht schnell, die Griffe bleiben kühl. Einmal auf Länge kürzen und feststellen.',
        'it': "Una corda in cavo d'acciaio con cuscinetti a sfera e blocco a vite per la lunghezza. Il cavo gira veloce e le maniglie restano fresche. La tagli su misura una volta sola."}, 'a black speed jump rope coiled with steel handles', attributes=dict(sport='Gym', material='Stainless steel', color='Black', size='One size')),
    P('S-GYM-BAG', {'en': 'Gym duffel', 'fr': 'Sac de sport', 'de': 'Sporttasche', 'it': 'Borsone da palestra'}, ['gym', 'swimming'], 65, {'en': 'A 35 litre duffel with a shoe pocket and a wet pocket. Shoes in one end, wet kit in the other, and a padded strap. It fits a locker.',
        'fr': "Un sac de 35 litres avec un compartiment chaussures et une poche humide. Les chaussures d'un côté, les affaires mouillées de l'autre, et une bandoulière rembourrée. Il entre dans un casier.",
        'de': 'Eine 35-Liter-Tasche mit Schuhfach und Nassfach. Schuhe an einem Ende, nasse Sachen am anderen, dazu ein gepolsterter Gurt. Sie passt in einen Spind.',
        'it': "Un borsone da 35 litri con scomparto per le scarpe e tasca per il bagnato. Scarpe da una parte, roba bagnata dall'altra, e tracolla imbottita. Entra in un armadietto."}, 'a {value} gym duffel bag', axis='color', values=['Black', 'Green'], picture_per_value=True, attributes=dict(sport='Gym|Swimming', material='Nylon', size='One size')),
    P('S-TRAINING-TEE', {'en': 'Training tee', 'fr': "T-shirt d'entraînement", 'de': 'Trainingsshirt', 'it': 'Maglia da allenamento'}, ['gym'], 35, {'en': 'A boxy cotton blend tee for the gym. Heavy enough to hold its shape, light enough to train in. Washes without shrinking.',
        'fr': "Un t-shirt ample en coton mélangé pour la salle. Assez épais pour tenir sa forme, assez léger pour s'entraîner. Il ne rétrécit pas au lavage.",
        'de': 'Ein kastiges Shirt aus Baumwollmischung für das Studio. Schwer genug, um die Form zu halten, leicht genug zum Trainieren. Es läuft beim Waschen nicht ein.',
        'it': 'Una maglia dal taglio squadrato in misto cotone per la palestra. Pesante quanto basta per tenere la forma, leggera quanto basta per allenarsi. In lavatrice non si restringe.'}, 'a {value} boxy training t-shirt laid flat', axis='color', values=['Black', 'Grey', 'White'], picture_per_value=True, attributes=dict(sport='Gym', material='Cotton', size='')),
    P('S-YOGA-MAT', {'en': 'Cork yoga mat', 'fr': 'Tapis de yoga en liège', 'de': 'Yogamatte aus Kork', 'it': 'Tappetino da yoga in sughero'}, ['yoga'], 85, {'en': 'A 4 mm natural rubber mat with a cork top that grips more when wet. The cork top is naturally antibacterial and grips better as you sweat. It rolls with a cotton strap.',
        'fr': 'Un tapis en caoutchouc naturel de 4 mm avec une surface en liège qui accroche davantage quand elle est humide. Le liège est naturellement antibactérien et accroche mieux à mesure que vous transpirez. Il se roule avec une sangle en coton.',
        'de': 'Eine 4 mm dicke Matte aus Naturkautschuk mit Korkoberfläche, die feucht mehr Halt gibt. Kork ist von Natur aus antibakteriell und greift besser, je mehr du schwitzt. Sie rollt sich mit einem Baumwollgurt zusammen.',
        'it': 'Un tappetino in caucciù naturale da 4 mm con superficie in sughero che tiene di più quando è umida. Il sughero è antibatterico per natura e fa più presa man mano che sudi. Si arrotola con una cinghia di cotone.'}, 'a rolled cork yoga mat with a natural rubber base', attributes=dict(sport='Yoga', material='Rubber', color='Tan', size='One size')),
    P('S-RUBBER-MAT', {'en': 'Rubber yoga mat', 'fr': 'Tapis de yoga en caoutchouc', 'de': 'Yogamatte aus Kautschuk', 'it': 'Tappetino da yoga in caucciù'}, ['yoga', 'gym'], 70, {'en': 'A 5 mm natural rubber mat, 183 cm long. Grippy on both sides, cushioned enough for knees. It weighs 2.5 kg.',
        'fr': 'Un tapis en caoutchouc naturel de 5 mm, long de 183 cm. Antidérapant des deux côtés, assez épais pour les genoux. Il pèse 2,5 kg.',
        'de': 'Eine 5 mm dicke Matte aus Naturkautschuk, 183 cm lang. Auf beiden Seiten rutschfest, gepolstert genug für die Knie. Sie wiegt 2,5 kg.',
        'it': 'Un tappetino in caucciù naturale da 5 mm, lungo 183 cm. Antiscivolo su entrambi i lati, imbottito quanto basta per le ginocchia. Pesa 2,5 kg.'}, 'a rolled {value} natural rubber yoga mat', axis='color', values=['Green', 'Charcoal', 'Purple'], picture_per_value=True, attributes=dict(sport='Yoga|Gym', material='Rubber', size='One size')),
    P('S-BLOCKS', {'en': 'Cork blocks, pair', 'fr': 'Briques en liège, la paire', 'de': 'Korkblöcke, Paar', 'it': 'Mattoncini in sughero, coppia'}, ['yoga'], 28, {'en': 'Two cork blocks with rounded edges. Light, firm and warm to the touch. They wipe clean.',
        'fr': "Deux briques en liège aux arêtes arrondies. Légères, fermes et chaudes au toucher. Elles se nettoient d'un coup de chiffon.",
        'de': 'Zwei Korkblöcke mit abgerundeten Kanten. Leicht, fest und warm in der Hand. Sie wischen sich sauber.',
        'it': 'Due mattoncini in sughero con gli spigoli arrotondati. Leggeri, solidi e caldi al tatto. Si puliscono con un panno.'}, 'two cork yoga blocks', attributes=dict(sport='Yoga', material='Bamboo', color='Tan', size='One size')),
    P('S-STRAP', {'en': 'Yoga strap', 'fr': 'Sangle de yoga', 'de': 'Yogagurt', 'it': 'Cinghia da yoga'}, ['yoga'], 12, {'en': 'A 2.5 m cotton strap with a metal buckle. A long strap for deep stretches and a buckle that holds. It washes with the towels.',
        'fr': 'Une sangle en coton de 2,5 m avec une boucle métallique. Une sangle longue pour les étirements profonds et une boucle qui tient. Elle se lave avec les serviettes.',
        'de': 'Ein 2,5 m langer Baumwollgurt mit Metallschnalle. Ein langer Gurt für tiefe Dehnungen und eine Schnalle, die hält. Er wäscht mit den Handtüchern.',
        'it': 'Una cinghia di cotone da 2,5 m con fibbia di metallo. Lunga per gli allungamenti profondi, con una fibbia che tiene. Si lava insieme agli asciugamani.'}, 'a rolled cotton yoga strap with a metal buckle', attributes=dict(sport='Yoga', material='Cotton', color='Oatmeal', size='One size')),
    P('S-ROLLER', {'en': 'Foam roller', 'fr': 'Rouleau en mousse', 'de': 'Faszienrolle', 'it': 'Rullo in schiuma'}, ['yoga', 'running'], 35, {'en': 'A 33 cm medium density roller. Firm enough for legs, forgiving enough for backs. It does not lose its shape.',
        'fr': 'Un rouleau de 33 cm, densité moyenne. Assez ferme pour les jambes, assez doux pour le dos. Il ne se déforme pas.',
        'de': 'Eine 33 cm lange Rolle mit mittlerer Dichte. Fest genug für die Beine, nachgiebig genug für den Rücken. Sie verliert ihre Form nicht.',
        'it': 'Un rullo da 33 cm a densità media. Abbastanza duro per le gambe, abbastanza gentile per la schiena. Non perde la forma.'}, 'a black textured foam roller', attributes=dict(sport='Yoga|Running|Cycling', material='Rubber', color='Black', size='One size')),
    P('S-MASSAGE-BALL', {'en': 'Massage ball set', 'fr': 'Set de balles de massage', 'de': 'Massageball-Set', 'it': 'Set di palline per il massaggio'}, ['yoga'], 18, {'en': 'A lacrosse ball and a peanut, for feet and backs. The ball reaches the small muscles and the peanut sits either side of the spine. Both fit a pocket.',
        'fr': "Une balle de crosse et une cacahuète, pour les pieds et le dos. La balle atteint les petits muscles et la cacahuète se place de part et d'autre de la colonne. Les deux tiennent dans une poche.",
        'de': 'Ein Lacrosseball und eine Erdnuss, für Füße und Rücken. Der Ball erreicht die kleinen Muskeln, die Erdnuss liegt links und rechts der Wirbelsäule. Beide passen in die Tasche.',
        'it': 'Una pallina da lacrosse e una a doppia sfera, per i piedi e la schiena. La pallina arriva ai muscoli piccoli e la doppia sfera si mette ai lati della colonna. Stanno tutte e due in tasca.'}, 'a black massage ball and a peanut shaped massage ball', attributes=dict(sport='Yoga|Running', material='Rubber', color='Black', size='One size')),
    P('S-HIKING-BOOT', {'en': 'Hiking boot', 'fr': 'Chaussure de randonnée montante', 'de': 'Wanderstiefel', 'it': 'Scarpone da trekking'}, ['hiking'], 190, {'en': 'A waterproof leather boot with a stiff sole and no break-in. Full-grain leather, a waterproof lining and a sole that grips wet rock. Comfortable from the first walk.',
        'fr': 'Une chaussure en cuir imperméable, semelle rigide, sans rodage. Cuir pleine fleur, doublure imperméable et une semelle qui accroche sur la roche mouillée. Confortable dès la première sortie.',
        'de': 'Ein wasserdichter Lederstiefel mit steifer Sohle, ohne Einlaufzeit. Vollnarbenleder, wasserdichtes Futter und eine Sohle, die auf nassem Fels greift. Vom ersten Weg an bequem.',
        'it': 'Uno scarpone in pelle impermeabile, suola rigida, che non ha bisogno di rodaggio. Pelle pieno fiore, fodera impermeabile e suola che tiene sulla roccia bagnata. Comodo dalla prima camminata.'}, 'a {value} leather hiking boot seen from the side', axis='color', values=['Brown', 'Charcoal'], picture_per_value=True, attributes=dict(sport='Hiking', material='Leather', size='')),
    P('S-HIKING-SHOE', {'en': 'Hiking shoe', 'fr': 'Chaussure de randonnée basse', 'de': 'Wanderschuh', 'it': 'Scarpa da trekking'}, ['hiking'], 140, {'en': 'A low waterproof shoe for fast days. Light, waterproof and grippy, for long days at speed. It dries overnight.',
        'fr': 'Une chaussure basse imperméable pour les journées rapides. Légère, imperméable et accrocheuse, pour les longues journées à bonne allure. Elle sèche pendant la nuit.',
        'de': 'Ein niedriger wasserdichter Schuh für schnelle Tage. Leicht, wasserdicht und griffig, für lange Tage im Tempo. Über Nacht ist er trocken.',
        'it': 'Una scarpa bassa impermeabile per le giornate veloci. Leggera, impermeabile e con presa, per giornate lunghe a passo svelto. Asciuga nella notte.'}, 'a grey and green low hiking shoe', axis='size', values=SHOE, attributes=dict(sport='Hiking', material='Recycled polyester', color='Grey')),
    P('S-DAYPACK', {'en': 'Daypack 25', 'fr': 'Sac à dos 25 litres', 'de': 'Tagesrucksack 25', 'it': 'Zaino da giornata 25'}, ['hiking'], 110, {'en': 'A 25 litre pack at 780 g, with a rain cover and a hydration sleeve. Enough room for a day in the hills, with a hip belt that carries the weight. The rain cover lives in its own pocket.',
        'fr': "Un sac de 25 litres pour 780 g, avec housse de pluie et poche à poche d'eau. De quoi tenir une journée en montagne, avec une ceinture qui porte le poids. La housse de pluie a sa propre poche.",
        'de': 'Ein 25-Liter-Rucksack mit 780 g, mit Regenhülle und Trinkblasenfach. Genug Platz für einen Tag in den Bergen, mit einem Hüftgurt, der das Gewicht trägt. Die Regenhülle hat ihre eigene Tasche.',
        'it': "Uno zaino da 25 litri per 780 g, con copertura antipioggia e tasca per la sacca d'acqua. Spazio per una giornata in montagna, con cintura che scarica il peso. La copertura ha la sua tasca."}, 'a {value} 25 litre hiking daypack', axis='color', values=['Green', 'Blue Dark', 'Orange'], picture_per_value=True, attributes=dict(sport='Hiking', material='Nylon', size='One size')),
    P('S-SHELL', {'en': 'Three-layer shell', 'fr': 'Veste trois couches', 'de': 'Dreilagenjacke', 'it': 'Giacca a tre strati'}, ['hiking', 'cycling'], 260, {'en': 'A 20 000 mm waterproof shell with pit zips and a helmet hood. The kind of jacket you buy once. Pit zips for the climb, a hood that fits a helmet, and a lifetime repair promise.',
        'fr': "Une veste imperméable 20 000 mm avec aérations sous les bras et capuche à casque. Le genre de veste qu'on achète une fois. Des aérations pour la montée, une capuche qui passe sur un casque, et une promesse de réparation à vie.",
        'de': 'Eine wasserdichte Jacke mit 20 000 mm, Unterarmbelüftung und helmtauglicher Kapuze. Die Sorte Jacke, die man einmal kauft. Belüftung für den Aufstieg, eine Kapuze über den Helm und ein Reparaturversprechen auf Lebenszeit.',
        'it': 'Una giacca impermeabile da 20 000 mm con aperture sotto le ascelle e cappuccio da casco. Il tipo di giacca che compri una volta sola. Aperture per la salita, cappuccio che passa sul casco e riparazione promessa per sempre.'}, 'a {value} hooded waterproof shell jacket laid flat', axis='color', values=['Blue', 'Red', 'Black'], picture_per_value=True, attributes=dict(sport='Hiking|Cycling', material='Recycled polyester', size='')),
    P('S-FLEECE', {'en': 'Grid fleece', 'fr': 'Polaire grid', 'de': 'Grid-Fleece', 'it': 'Pile a nido'}, ['hiking', 'running'], 90, {'en': 'A light grid fleece that breathes on the climb. The grid traps warmth and lets sweat through. It layers under the shell without bulk.',
        'fr': 'Une polaire grid légère qui respire à la montée. Le quadrillage garde la chaleur et laisse passer la transpiration. Elle se glisse sous la veste sans épaisseur.',
        'de': 'Ein leichtes Grid-Fleece, das im Aufstieg atmet. Das Gitter hält die Wärme und lässt den Schweiß durch. Es liegt unter der Jacke, ohne aufzutragen.',
        'it': 'Un pile leggero a nido che respira in salita. La trama a nido trattiene il calore e lascia passare il sudore. Sotto la giacca non fa volume.'}, 'a {value} grid fleece pullover laid flat', axis='color', values=['Green', 'Grey', 'Blue Dark'], picture_per_value=True, attributes=dict(sport='Hiking|Running', material='Recycled polyester', size='')),
    P('S-POLES', {'en': 'Carbon poles', 'fr': 'Bâtons en carbone', 'de': 'Carbonstöcke', 'it': 'Bastoncini in carbonio'}, ['hiking'], 120, {'en': 'Folding carbon poles at 180 g each, with cork grips. They fold into three and fit a pack. The cork grips shape to the hand.',
        'fr': 'Des bâtons pliants en carbone de 180 g pièce, avec des poignées en liège. Ils se plient en trois et entrent dans le sac. Le liège prend la forme de la main.',
        'de': 'Faltbare Carbonstöcke mit 180 g pro Stück, mit Korkgriffen. Sie falten sich dreiteilig und passen in den Rucksack. Der Kork nimmt die Form der Hand an.',
        'it': "Bastoncini pieghevoli in carbonio da 180 g l'uno, con impugnature in sughero. Si piegano in tre e stanno nello zaino. Il sughero prende la forma della mano."}, 'a pair of folding carbon trekking poles with cork grips', attributes=dict(sport='Hiking|Running', material='Nylon', color='Black', size='One size')),
    P('S-HIKE-SOCKS', {'en': 'Hiking socks, 2 pack', 'fr': 'Chaussettes de randonnée, lot de 2', 'de': 'Wandersocken, 2er-Pack', 'it': 'Calze da trekking, confezione da 2'}, ['hiking'], 26, {'en': 'Merino socks with a cushioned sole. Merino with a cushioned sole and a snug arch. No blisters on a three-day walk.',
        'fr': 'Des chaussettes en mérinos à semelle rembourrée. Du mérinos, une semelle rembourrée et un maintien serré à la voûte. Aucune ampoule sur trois jours de marche.',
        'de': 'Merinosocken mit gepolsterter Sohle. Merino mit gepolsterter Sohle und festem Sitz am Fußgewölbe. Keine Blasen auf einer Dreitagestour.',
        'it': "Calze in merino con pianta imbottita. Merino, pianta imbottita e sostegno deciso sull'arco. Tre giorni di cammino senza una vescica."}, 'two pairs of grey merino hiking socks', axis='size', values=['36', '39', '42', '45'], attributes=dict(sport='Hiking', material='Wool', color='Grey')),
    P('S-GOGGLES', {'en': 'Swim goggles', 'fr': 'Lunettes de natation', 'de': 'Schwimmbrille', 'it': 'Occhialini da nuoto'}, ['swimming'], 32, {'en': 'Low-profile goggles with a curved lens and five nose bridges. The curved lens gives a wide view and the five bridges give a real fit. Anti-fog inside.',
        'fr': "Des lunettes profil bas avec un verre incurvé et cinq ponts de nez. Le verre incurvé ouvre le champ et les cinq ponts donnent un vrai réglage. Traitement antibuée à l'intérieur.",
        'de': 'Eine flach gebaute Brille mit gebogener Scheibe und fünf Nasenstegen. Die gebogene Scheibe gibt ein weites Blickfeld, die fünf Stege eine echte Passform. Innen mit Antibeschlag.',
        'it': "Occhialini a profilo basso con lente curva e cinque ponti nasali. La lente curva allarga il campo visivo e i cinque ponti danno una vestibilità vera. Antiappannamento all'interno."}, 'a pair of {value} swimming goggles', axis='color', values=['Black', 'Blue', 'Silver'], picture_per_value=True, attributes=dict(sport='Swimming', material='Rubber', size='One size')),
    P('S-SWIMSUIT', {'en': 'Training swimsuit', 'fr': "Maillot d'entraînement", 'de': 'Trainingsbadeanzug', 'it': 'Costume da allenamento'}, ['swimming'], 55, {'en': 'A chlorine-proof one-piece with a medium back. Chlorine-proof fabric that keeps its shape for a year of mornings. The medium back gives free shoulders.',
        'fr': 'Un une-pièce résistant au chlore, dos moyen. Un tissu résistant au chlore qui garde sa forme pendant un an de séances. Le dos moyen laisse les épaules libres.',
        'de': 'Ein chlorbeständiger Badeanzug mit mittlerem Rücken. Chlorfestes Gewebe, das ein Jahr Morgentraining übersteht. Der mittlere Rücken lässt die Schultern frei.',
        'it': 'Un costume intero resistente al cloro, con schiena media. Tessuto resistente al cloro che tiene la forma per un anno di vasche. La schiena media lascia libere le spalle.'}, 'a {value} one piece training swimsuit laid flat', axis='color', values=['Black', 'Blue Dark'], picture_per_value=True, attributes=dict(sport='Swimming', material='Recycled polyester', size='')),
    P('S-JAMMERS', {'en': 'Training jammers', 'fr': "Jammer d'entraînement", 'de': 'Trainings-Jammer', 'it': 'Jammer da allenamento'}, ['swimming'], 45, {'en': 'Knee-length jammers that last a season of chlorine. A drawstring waist and a fabric that lasts. Quick to dry.',
        'fr': 'Un jammer longueur genou qui tient une saison de chlore. Une taille à cordon et un tissu qui dure. Il sèche vite.',
        'de': 'Ein knielanger Jammer, der eine Saison Chlor übersteht. Ein Bund mit Kordel und ein Gewebe, das hält. Er trocknet schnell.',
        'it': 'Un jammer al ginocchio che regge una stagione di cloro. Vita con coulisse e tessuto che dura. Asciuga in fretta.'}, 'a pair of black swimming jammers laid flat', axis='size', values=CLOTH, attributes=dict(sport='Swimming', material='Recycled polyester', color='Black')),
    P('S-SWIM-CAP', {'en': 'Silicone cap', 'fr': 'Bonnet en silicone', 'de': 'Silikonbadekappe', 'it': 'Cuffia in silicone'}, ['swimming'], 10, {'en': 'A soft silicone cap that does not pull. Soft silicone that goes on without pulling hair. One size.',
        'fr': 'Un bonnet en silicone souple qui ne tire pas. Un silicone souple qui se met sans arracher les cheveux. Taille unique.',
        'de': 'Eine weiche Silikonkappe, die nicht zieht. Weiches Silikon, das ohne Haareziehen aufgeht. Eine Größe.',
        'it': 'Una cuffia in silicone morbido che non tira. Silicone morbido che si infila senza strappare i capelli. Taglia unica.'}, 'a {value} silicone swim cap', axis='color', values=['Black', 'Blue', 'Pink'], picture_per_value=True, attributes=dict(sport='Swimming', material='Rubber', size='One size')),
    P('S-TOWEL', {'en': 'Microfibre towel', 'fr': 'Serviette microfibre', 'de': 'Mikrofaserhandtuch', 'it': 'Asciugamano in microfibra'}, ['swimming', 'hiking'], 22, {'en': 'A large towel that dries in an hour and packs to a fist. Large enough to wrap, small enough for a pocket. It dries in an hour on a rail.',
        'fr': "Une grande serviette qui sèche en une heure et se plie en un poing. Assez grande pour s'enrouler, assez petite pour une poche. Elle sèche en une heure sur un fil.",
        'de': 'Ein großes Handtuch, das in einer Stunde trocknet und faustgroß zusammengeht. Groß genug zum Einwickeln, klein genug für die Tasche. Auf der Stange trocknet es in einer Stunde.',
        'it': "Un asciugamano grande che asciuga in un'ora e si ripiega in un pugno. Grande abbastanza per avvolgersi, piccolo abbastanza per la tasca. Sullo stendino asciuga in un'ora."}, 'a folded {value} microfibre towel', axis='color', values=['Blue', 'Grey'], picture_per_value=True, attributes=dict(sport='Swimming|Hiking', material='Recycled polyester', size='One size')),
    P('S-TOW-FLOAT', {'en': 'Open water tow float', 'fr': 'Bouée de nage en eau libre', 'de': 'Schwimmboje für offenes Wasser', 'it': 'Boa da nuoto in acque libere'}, ['swimming'], 30, {'en': 'A bright float with a dry pocket, for open water. Bright orange so boats see you, with a dry pocket for keys and a phone. It clips to a waist belt.',
        'fr': "Une bouée bien visible avec une poche étanche, pour l'eau libre. Orange vif pour que les bateaux vous voient, avec une poche étanche pour les clés et le téléphone. Elle se clipse à une ceinture.",
        'de': 'Eine gut sichtbare Boje mit Trockenfach, für offenes Wasser. Leuchtend orange, damit Boote dich sehen, mit einem Trockenfach für Schlüssel und Telefon. Sie klickt an einen Hüftgurt.',
        'it': 'Una boa ben visibile con tasca stagna, per le acque libere. Arancione acceso perché le barche ti vedano, con tasca stagna per chiavi e telefono. Si aggancia alla cintura.'}, 'a bright orange inflatable swim tow float', attributes=dict(sport='Swimming', material='Nylon', color='Orange', size='One size')),
    P('S-HOME-GYM', {'en': 'Home gym kit', 'fr': 'Kit de salle à la maison', 'de': 'Homegym-Set', 'it': 'Kit palestra in casa'}, ['gym'], 330, {'en': 'A kettlebell, bands, a rope and a mat. Everything for a full session in a small room. Cheaper than the four bought apart.',
        'fr': 'Une kettlebell, des élastiques, une corde et un tapis. De quoi faire une séance complète dans une petite pièce. Moins cher que les quatre achetés séparément.',
        'de': 'Eine Kettlebell, Bänder, ein Seil und eine Matte. Alles für eine ganze Einheit in einem kleinen Raum. Günstiger als die vier einzeln.',
        'it': 'Un kettlebell, gli elastici, una corda e un tappetino. Tutto per una sessione intera in una stanza piccola. Costa meno dei quattro comprati separati.'}, 'a kettlebell, resistance bands, a jump rope and a rolled mat arranged together', grouped=['S-KETTLEBELL-16', 'S-BANDS', 'S-JUMP-ROPE', 'S-RUBBER-MAT-CHARCOAL'], attributes=dict(sport='Gym', material='', color='Black', size='One size')),
    P('S-RECOVERY-KIT', {'en': 'Recovery kit', 'fr': 'Kit de récupération', 'de': 'Regenerations-Set', 'it': 'Kit per il recupero'}, ['yoga', 'running'], 60, {'en': 'A roller, a ball set and a strap. The three tools our physio uses, in one bag. Ten minutes after each run.',
        'fr': 'Un rouleau, un set de balles et une sangle. Les trois outils que notre kiné utilise, dans un sac. Dix minutes après chaque sortie.',
        'de': 'Eine Rolle, ein Ballset und ein Gurt. Die drei Werkzeuge, die unser Physio nimmt, in einer Tasche. Zehn Minuten nach jedem Lauf.',
        'it': 'Un rullo, un set di palline e una cinghia. I tre attrezzi che usa il nostro fisioterapista, in una sola borsa. Dieci minuti dopo ogni uscita.'}, 'a foam roller, two massage balls and a strap arranged together', grouped=['S-ROLLER', 'S-MASSAGE-BALL', 'S-STRAP'], attributes=dict(sport='Yoga|Running', material='Rubber', color='Black', size='One size')),
    P('S-GIFT-CARD', {'en': 'Stride gift card', 'fr': 'Carte cadeau Stride', 'de': 'Stride Geschenkkarte', 'it': 'Carta regalo Stride'}, ['gym'], 50, {'en': 'A gift card by email. Delivered by email within the hour, with a message of your own. Valid for a year in the store.',
        'fr': "Une carte cadeau par email. Envoyée par email dans l'heure, avec votre message. Valable un an dans la boutique.",
        'de': 'Eine Geschenkkarte per E-Mail. Innerhalb einer Stunde per E-Mail zugestellt, mit einer eigenen Nachricht. Ein Jahr im Shop gültig.',
        'it': "Una carta regalo via email. Consegnata via email entro un'ora, con un messaggio tuo. Valida un anno nel negozio."}, 'a green gift card with a white stripe', type='virtual', attributes=dict(sport='', material='', color='', size='')),
]
POSTS = [
    ('How we fit shoes by video', '<p>Film thirty seconds from behind on a treadmill or a flat path, shoes off. Send it with your current shoe size and the distance you run each week. We reply with two options and why.</p><p>Run in them for thirty days. If they are wrong, send them back.</p>', 'A runner filmed from behind on a treadmill in a small shop with shoes on shelves.'),
    ('The first mountain race', '<p>Start with shoes that grip on wet rock, a pack that holds a litre and a shell, and poles if the climb is long. Eat every forty minutes from the start, not when you are hungry.</p><p>Walk the steep bits. Everyone does.</p>', 'Trail runners climbing a steep rocky path in the mountains with poles.'),
    ('A week of training, one room', '<p>A kettlebell, a set of bands and a mat cover most of a strength week: swings, presses, rows, carries, and a long stretch on Sunday.</p><p>Twenty minutes, three times a week, beats a gym membership you skip.</p>', 'A small home gym corner with a kettlebell, bands and a mat by a window.'),
]
GALLERY = [('A runner on a wet city street at dawn, mid stride, motion blur in the background', 'running'), ('Close-up of cycling shoes clipped into pedals on a mountain road', 'cycling'), ('A tall shot of a climber on a rocky ridge at sunrise with a small backpack', 'hiking'), ('A person holding a yoga pose on a wooden deck by a lake in soft morning light', 'yoga'), ('A swimmer pushing off the wall of an outdoor pool, water splashing in sunlight', 'swimming')]
BRANDS = [('Stride', 'ORIGINALS'), ('Ridgeline', 'OUTDOOR'), ('Velo', 'CYCLING'), ('Cadence', 'RUNNING'), ('Ferro', 'STRENGTH'), ('Tidal', 'SWIM'), ('Ashram', 'YOGA'), ('Summit', 'PACKS'), ('Kinetic', 'APPAREL'), ('Northface Peak', 'LAYERS')]
GALLERY_TITLE = 'Out before sunrise'
