CODE = 'sports'; ROOT = {'en': 'Sports', 'fr': 'Sport', 'de': 'Sport', 'it': 'Sport'}; STORE_NAME = 'Stride'; ATTRIBUTE_SET = 'Sports'; WEIGHT = 0.8
ATTRIBUTE_COLUMNS = ['sport', 'size', 'color', 'material']
ATTRIBUTES = [
    dict(code='sport', label='Sport', input='multiselect', scope='global', filterable=1, filterable_in_search=1, visible_on_front=1, used_in_product_listing=1, sets='Sports', group='General', sort_order=50),
]
OPTIONS = {'sport': ['Running', 'Cycling', 'Gym', 'Yoga', 'Hiking', 'Swimming']}
ROOT_DESCRIPTION = {'en': 'Gear for running, cycling, the gym and the trail, tested by people who train.',
                    'fr': "De l'équipement pour la course, le vélo, la salle et le sentier, testé par ceux qui s'entraînent.",
                    'de': 'Ausrüstung für Laufen, Radfahren, Studio und Trail, getestet von Menschen, die trainieren.',
                    'it': 'Attrezzatura per la corsa, la bici, la palestra e il sentiero, provata da chi si allena.'}
META_DESCRIPTION = 'Stride: running shoes, cycling kit, gym gear, yoga mats and hiking equipment, tested on the road and the trail.'
PRODUCT_STYLE = 'Studio product photograph of a single sports product on a plain white seamless background, crisp even light, no people, no text, no lettering, no logos, no watermark, centered with margin around it.'
SCENE_STYLE = 'Energetic editorial sports photograph, dawn light, wet asphalt or mountain trail, motion, no readable text, no lettering, no logos, no watermark.'
SCENES = {
    'hero-main': 'A runner in a bright jacket on a wet coastal road at dawn, seen from behind, motion blur in the legs.',
    'hero-side': 'A close up of running shoes on a wet running track with water droplets, low angle.',
    'editorial': 'A group of cyclists climbing a mountain pass in the early morning, seen from the side.',
    'about': 'A small sports shop with a treadmill for gait analysis and shelves of running shoes.',
}
CATEGORIES = [
    dict(path='running', name={'en': 'Running', 'fr': 'Course', 'de': 'Laufen', 'it': 'Corsa'}, description='Shoes, jackets and shorts for road and trail.', landing_title='Every road, every weather', landing_text='Road shoes, trail shoes and layers that breathe. We fit shoes on a treadmill in the shop and by video online.', scene='A pair of trail running shoes on a rocky mountain path with a view over a valley at sunrise.'),
    dict(path='cycling', name={'en': 'Cycling', 'fr': 'Vélo', 'de': 'Radfahren', 'it': 'Ciclismo'}, description='Jerseys, bibs, helmets and the small things.', landing_title='Comfort at kilometre eighty', landing_text='Bib shorts with a chamois that lasts, jerseys with pockets you can reach, and helmets that pass every test.', scene='A road bike leaning against a stone wall on a mountain road, helmet on the bars.'),
    dict(path='gym', name={'en': 'Gym & Training', 'fr': 'Salle et entraînement', 'de': 'Studio und Training', 'it': 'Palestra e allenamento'}, description='Weights, bands and the kit for a home corner.', landing_title='A gym in a corner', landing_text='Kettlebells, bands, a bench and a mat. Enough for most people, most of the time.', scene='A kettlebell, a pair of dumbbells and a rolled mat on a wooden floor by a window.'),
    dict(path='yoga', name={'en': 'Yoga & Recovery', 'fr': 'Yoga et récupération', 'de': 'Yoga und Regeneration', 'it': 'Yoga e recupero'}, description='Mats, blocks, rollers and balls.', landing_title='Slow down', landing_text='Natural rubber mats, cork blocks and the recovery tools physios actually use.', scene='A rolled cork yoga mat and two cork blocks on a wooden floor in a bright studio.'),
    dict(path='hiking', name={'en': 'Hiking', 'fr': 'Randonnée', 'de': 'Wandern', 'it': 'Escursionismo'}, description='Boots, packs and layers for a long day out.', landing_title='Further, drier, lighter', landing_text='Boots that are broken in on day one, packs under a kilo and layers that pack small.', scene='A hiker with a small backpack on a ridge path above the clouds at sunrise.'),
    dict(path='swimming', name={'en': 'Swimming', 'fr': 'Natation', 'de': 'Schwimmen', 'it': 'Nuoto'}, description='Goggles, suits and towels for pool and open water.', landing_title='Pool and open water', landing_text='Goggles that do not leak, suits that last a season of chlorine, and towels that dry in a bag.', scene='Swimming goggles and a folded towel on the edge of an outdoor pool at dawn.'),
]
HERO = dict(badge='New season', title='Gear that keeps up', text='Tested on our own runs, rides and climbs. If it fails us, it is not here.')
FEATURES = [('truck', 'Free delivery over 50', 'Next day on weekdays'), ('run', 'Shoe fitting', 'In store or by video'), ('arrow-back-up', '30-day trial', 'Run in them, return them'), ('shield-check', 'Two-year warranty', 'On every product')]
STORY = dict(title='We train in what we sell', text1='Stride is run by four people who race: two runners, a cyclist and a swimmer. Every product goes through at least a month of our own training before it is listed.', text2='If something fails, we say so on the product page. If it fails you, send it back.')
PROMO = dict(badge='Trail season', title='The trail kit', text='Shoes, a pack and a shell, chosen for a first mountain race.', path='running', button='See trail running', list_title='For the trail')
TESTIMONIALS = [('The video shoe fitting was better than the shop I used to go to. No injuries this year.', 'Elena R.', 'Oslo'), ('Bib shorts that survived a summer of riding. First pair that has.', 'Marcus T.', 'Leeds'), ('The cork mat has not slipped once in a hot class.', 'Priya S.', 'Toronto')]
NEWSLETTER = dict(title='Training notes', text='A short email every two weeks: what we tested, a session plan, and new arrivals.')
ABOUT = dict(title='Four people who race', paragraphs=['Stride started when two runners could not find a shop that fitted shoes properly. They bought a treadmill, a camera and a small lease.', 'A cyclist and a swimmer joined. Every product in the shop goes through a month of our own training first, and the notes are on the product page.', 'The treadmill is still there. Come and run on it, or send us a video and we fit you online.'])
REVIEWS = [
    ({'en': 'Fits as described', 'fr': 'Conforme à la description', 'de': 'Passt wie beschrieben', 'it': 'Veste come descritto'}, {'en': 'The fitting notes were accurate. No blisters on a 30 km run.',
                           'fr': 'Les conseils de taille étaient justes. Aucune ampoule sur 30 km.',
                           'de': 'Die Größenhinweise stimmten. Keine Blasen auf 30 km.',
                           'it': 'Le note sulla vestibilità erano giuste. Nessuna vescica su 30 km.'}, 5),
    ({'en': 'Good, sizing runs small', 'fr': 'Bien, taille petit', 'de': 'Gut, fällt klein aus', 'it': 'Buono, veste stretto'}, {'en': 'Quality is great. Go half a size up.',
                                 'fr': 'La qualité est excellente. Prenez une demi-taille au-dessus.',
                                 'de': 'Die Qualität ist super. Eine halbe Nummer größer nehmen.',
                                 'it': 'La qualità è ottima. Prendi mezza taglia in più.'}, 4),
    ({'en': 'Survived a season', 'fr': 'Il a passé la saison', 'de': 'Hat eine Saison überstanden', 'it': 'Ha superato una stagione'}, {'en': 'Rain, mud, a hundred washes. Still going.',
                           'fr': 'Pluie, boue, cent lavages. Toujours là.',
                           'de': 'Regen, Schlamm, hundert Wäschen. Läuft immer noch.',
                           'it': 'Pioggia, fango, cento lavaggi. Ancora qui.'}, 5),
    ({'en': 'Returned, no questions', 'fr': 'Retourné sans discussion', 'de': 'Zurückgegeben, ohne Fragen', 'it': 'Reso senza domande'}, {'en': 'Did not suit my stride. Return was easy and fast.',
                                'fr': 'Cela ne convenait pas à ma foulée. Le retour a été simple et rapide.',
                                'de': 'Passte nicht zu meinem Laufstil. Die Rückgabe war einfach und schnell.',
                                'it': 'Non andava con la mia falcata. Il reso è stato facile e veloce.'}, 4),
    ({'en': 'Grip in the wet', 'fr': "De l'accroche sur le mouillé", 'de': 'Grip bei Nässe', 'it': 'Aderenza sul bagnato'}, {'en': 'Ran a rainy trail and never slipped.',
                         'fr': "J'ai couru un sentier sous la pluie sans jamais glisser.",
                         'de': 'Bin einen nassen Trail gelaufen und nie gerutscht.',
                         'it': 'Ho corso un sentiero sotto la pioggia senza mai scivolare.'}, 5),
    ({'en': 'Bottle does not leak', 'fr': 'La gourde ne fuit pas', 'de': 'Die Flasche läuft nicht aus', 'it': 'La borraccia non perde'}, {'en': 'Upside down in the bag all day. Dry bag.',
                              'fr': "À l'envers dans le sac toute la journée. Sac sec.",
                              'de': 'Den ganzen Tag kopfüber in der Tasche. Trockene Tasche.',
                              'it': 'A testa in giù nella borsa tutto il giorno. Borsa asciutta.'}, 5),
    ({'en': 'Light and warm', 'fr': 'Léger et chaud', 'de': 'Leicht und warm', 'it': 'Leggera e calda'}, {'en': 'Packs into its own pocket and still cuts the wind.',
                        'fr': 'Elle se range dans sa propre poche et coupe encore le vent.',
                        'de': 'Lässt sich in die eigene Tasche packen und hält trotzdem den Wind ab.',
                        'it': 'Si ripiega nella sua tasca e taglia comunque il vento.'}, 5),
    ({'en': 'Seams rubbed', 'fr': 'Les coutures ont frotté', 'de': 'Die Nähte haben gescheuert', 'it': 'Le cuciture hanno sfregato'}, {'en': 'Great shorts but a seam rubbed on long rides. Fine under 40 km.',
                      'fr': 'Très bon cuissard mais une couture a frotté sur les longues sorties. Parfait sous 40 km.',
                      'de': 'Tolle Hose, aber eine Naht hat bei langen Fahrten gescheuert. Unter 40 km gut.',
                      'it': 'Ottimi pantaloncini ma una cucitura ha sfregato nelle uscite lunghe. Sotto i 40 km vanno bene.'}, 3),
    ({'en': 'Mat stays put', 'fr': 'Le tapis ne glisse pas', 'de': 'Die Matte bleibt liegen', 'it': 'Il tappetino non scivola'}, {'en': 'No sliding on a wooden floor, even in a sweaty class.',
                       'fr': 'Aucun glissement sur un parquet, même pendant un cours transpirant.',
                       'de': 'Kein Rutschen auf Holzboden, auch nicht in einer verschwitzten Stunde.',
                       'it': 'Non scivola sul parquet, nemmeno in una lezione sudata.'}, 5),
    ({'en': 'Zips froze', 'fr': 'Les fermetures ont gelé', 'de': 'Die Reißverschlüsse froren ein', 'it': 'Le cerniere si sono bloccate'}, {'en': 'Fine jacket, but the zip pulls are small with gloves on.',
                    'fr': 'Bonne veste, mais les tirettes sont petites avec des gants.',
                    'de': 'Gute Jacke, aber die Zipper sind mit Handschuhen zu klein.',
                    'it': 'Bella giacca, ma i cursori sono piccoli con i guanti.'}, 4),
    ({'en': 'Race day shoe', 'fr': 'La chaussure des jours de course', 'de': 'Der Wettkampfschuh', 'it': 'La scarpa da gara'}, {'en': 'Saved it for the marathon. Personal best.',
                       'fr': "Je l'ai gardée pour le marathon. Record personnel.",
                       'de': 'Für den Marathon aufgehoben. Persönliche Bestzeit.',
                       'it': "L'ho tenuta per la maratona. Record personale."}, 5),
    ({'en': 'Straps dig in', 'fr': 'Les bretelles rentrent', 'de': 'Die Gurte schneiden ein', 'it': 'Gli spallacci segnano'}, {'en': 'Backpack carries well when full, straps dig when empty.',
                       'fr': 'Le sac porte bien quand il est plein, les bretelles rentrent quand il est vide.',
                       'de': 'Der Rucksack trägt sich voll gut, leer schneiden die Gurte ein.',
                       'it': 'Lo zaino porta bene quando è pieno, gli spallacci segnano quando è vuoto.'}, 3),
    ({'en': 'Socks that stay up', 'fr': 'Des chaussettes qui tiennent', 'de': 'Socken, die halten', 'it': 'Calze che stanno su'}, {'en': 'Finally. No slipping into the shoe at km ten.',
                            'fr': 'Enfin. Elles ne glissent plus dans la chaussure au dixième kilomètre.',
                            'de': 'Endlich. Kein Rutschen in den Schuh bei Kilometer zehn.',
                            'it': 'Finalmente. Non scivolano nella scarpa al decimo chilometro.'}, 5),
    ({'en': 'Heavier than listed', 'fr': "Plus lourd qu'annoncé", 'de': 'Schwerer als angegeben', 'it': 'Più pesante di quanto indicato'}, {'en': 'Good bag, but 200 g over the stated weight on my scale.',
                             'fr': 'Bon sac, mais 200 g de plus que le poids annoncé sur ma balance.',
                             'de': 'Gute Tasche, aber 200 g über dem angegebenen Gewicht auf meiner Waage.',
                             'it': 'Buona borsa, ma 200 g oltre il peso dichiarato sulla mia bilancia.'}, 3),
    ({'en': 'Bright enough for night', 'fr': 'Assez visible la nuit', 'de': 'Hell genug für die Nacht', 'it': 'Abbastanza visibile di notte'}, {'en': 'The reflective panels light up like a sign.',
                                 'fr': "Les bandes réfléchissantes s'allument comme un panneau.",
                                 'de': 'Die Reflexstreifen leuchten wie ein Schild.',
                                 'it': 'Le bande riflettenti si accendono come un cartello.'}, 5),
    ({'en': 'Wore through at the toe', 'fr': 'Usé au bout', 'de': 'An der Zehe durchgelaufen', 'it': 'Consumata sulla punta'}, {'en': 'Six hundred kilometres, which is fair. Buying again.',
                                 'fr': "Six cents kilomètres, c'est honnête. Je rachète.",
                                 'de': 'Sechshundert Kilometer, das ist fair. Ich kaufe wieder.',
                                 'it': 'Seicento chilometri, che è onesto. La ricompro.'}, 4),
    ({'en': 'Great for cold mornings', 'fr': 'Parfait pour les matins froids', 'de': 'Super für kalte Morgen', 'it': 'Ottimo per le mattine fredde'}, {'en': 'Thermal layer under a shell and I was warm at zero degrees.',
                                 'fr': "Une couche thermique sous une coupe-vent et j'avais chaud à zéro degré.",
                                 'de': 'Thermoschicht unter einer Hülle und mir war bei null Grad warm.',
                                 'it': 'Strato termico sotto un guscio e stavo al caldo a zero gradi.'}, 5),
    ({'en': 'Ball holds pressure', 'fr': 'Le ballon garde la pression', 'de': 'Der Ball hält den Druck', 'it': 'Il pallone tiene la pressione'}, {'en': 'Pumped it in March, still firm in May.',
                             'fr': 'Gonflé en mars, encore ferme en mai.',
                             'de': 'Im März aufgepumpt, im Mai noch prall.',
                             'it': 'Gonfiato a marzo, ancora duro a maggio.'}, 5),
    ({'en': 'Laces too long', 'fr': 'Lacets trop longs', 'de': 'Schnürsenkel zu lang', 'it': 'Lacci troppo lunghi'}, {'en': 'Double knot needed. Otherwise a great shoe.',
                        'fr': 'Il faut un double nœud. Sinon une très bonne chaussure.',
                        'de': 'Doppelter Knoten nötig. Sonst ein toller Schuh.',
                        'it': 'Serve un doppio nodo. Per il resto una gran scarpa.'}, 4),
    ({'en': 'Kids team loves them', 'fr': "L'équipe des enfants les adore", 'de': 'Die Kindermannschaft liebt sie', 'it': 'La squadra dei bambini le adora'}, {'en': 'Ordered twelve. All fit, all survived the season.',
                              'fr': "J'en ai commandé douze. Toutes à la bonne taille, toutes ont passé la saison.",
                              'de': 'Zwölf bestellt. Alle passten, alle haben die Saison überstanden.',
                              'it': 'Ne ho ordinate dodici. Tutte giuste, tutte hanno superato la stagione.'}, 5),
    ({'en': 'Watch strap is comfy', 'fr': 'Le bracelet est confortable', 'de': 'Das Armband ist bequem', 'it': 'Il cinturino è comodo'}, {'en': 'Soft silicone, no sweat rash, easy to swap.',
                              'fr': 'Silicone souple, aucune irritation, facile à changer.',
                              'de': 'Weiches Silikon, kein Schweißausschlag, leicht zu wechseln.',
                              'it': 'Silicone morbido, nessuna irritazione, facile da cambiare.'}, 5),
    ({'en': 'Pockets in the right place', 'fr': 'Des poches bien placées', 'de': 'Taschen an der richtigen Stelle', 'it': 'Tasche al posto giusto'}, {'en': 'Phone, key, gel. Nothing bounces.',
                                    'fr': 'Téléphone, clé, gel. Rien ne bouge.',
                                    'de': 'Handy, Schlüssel, Gel. Nichts hüpft.',
                                    'it': 'Telefono, chiave, gel. Niente rimbalza.'}, 5),
    ({'en': 'Faded after a summer', 'fr': 'Délavé après un été', 'de': 'Nach einem Sommer verblasst', 'it': "Sbiadito dopo un'estate"}, {'en': 'Colour went from navy to blue. Still works.',
                              'fr': 'La couleur est passée du marine au bleu. Cela fonctionne encore.',
                              'de': 'Die Farbe ging von Marine zu Blau. Funktioniert trotzdem.',
                              'it': 'Il colore è passato dal blu navy al blu. Funziona ancora.'}, 3),
    ({'en': 'Delivered before the race', 'fr': 'Livré avant la course', 'de': 'Vor dem Rennen geliefert', 'it': 'Consegnato prima della gara'}, {'en': 'Ordered Tuesday, raced Saturday. Thank you.',
                                   'fr': 'Commandé mardi, couru samedi. Merci.',
                                   'de': 'Dienstag bestellt, Samstag gelaufen. Danke.',
                                   'it': 'Ordinato martedì, gara sabato. Grazie.'}, 5),
]
def P(sku, name, cats, price, desc, prompt, **kw):
    d = dict(sku=sku, name=name, categories=cats, price=price, description=desc, prompt=prompt); d.update(kw); return d
SHOE = ['38', '39', '40', '41', '42', '43', '44', '45']
CLOTH = ['XS', 'S', 'M', 'L', 'XL']
PRODUCTS = [
    P('S-ROAD-SHOE', 'Road running shoe', ['running'], 140, 'A daily trainer with a 32 mm stack, a nylon plate and a wide toe box. Soft enough for easy days, quick enough for tempo. Expect 700 km before the foam gives up.', 'a {value} road running shoe seen from the side', axis='color', values=['Blue', 'Black', 'Orange'], picture_per_value=True, attributes=dict(sport='Running', material='Recycled polyester', size='')),
    P('S-TRAIL-SHOE', 'Trail running shoe', ['running', 'hiking'], 155, 'Five millimetre lugs, a rock plate and a gaiter attachment. Grip in mud, protection on rocks, and a fit that stays put on descents. Drains fast after a river.', 'a {value} trail running shoe with deep lugs seen from the side', axis='color', values=['Green', 'Black'], picture_per_value=True, attributes=dict(sport='Running|Hiking', material='Recycled polyester', size='')),
    P('S-RACE-SHOE', {'en': 'Race day shoe', 'fr': 'La chaussure des jours de course', 'de': 'Der Wettkampfschuh', 'it': 'La scarpa da gara'}, ['running'], 220, 'A carbon plate, a light foam and no compromise. For race day only. Four millimetre drop, 200 g in a size 42, and a plate that gives back what you put in. Save it for the start line.', 'a bright yellow lightweight racing shoe with a carbon plate', axis='size', values=SHOE, attributes=dict(sport='Running', material='Recycled polyester', color='Yellow')),
    P('S-RUN-JACKET', 'Running shell', ['running'], 130, 'A 90 g waterproof shell that packs into its own pocket. Taped seams and a hood that stays up in wind. It packs to the size of a fist.', 'a lightweight {value} running rain jacket laid flat', axis='color', values=['Yellow', 'Black', 'Blue'], picture_per_value=True, attributes=dict(sport='Running|Cycling', material='Recycled polyester', size='')),
    P('S-RUN-SHORT', 'Split shorts', ['running'], 45, 'Five-inch split shorts with a brief liner and a zip pocket. The split lets the leg move, the liner stops the chafe. The pocket holds a phone.', 'a pair of {value} split running shorts laid flat', axis='color', values=['Black', 'Blue Dark', 'Green'], picture_per_value=True, attributes=dict(sport='Running', material='Recycled polyester', size='')),
    P('S-RUN-TEE', 'Running tee', ['running', 'gym'], 40, 'A recycled polyester tee with flat seams and a reflective hit. It dries in an hour and never smells of yesterday. Cut close without clinging.', 'a {value} technical running t-shirt laid flat', axis='color', values=['White', 'Black', 'Orange'], picture_per_value=True, attributes=dict(sport='Running|Gym', material='Recycled polyester', size='')),
    P('S-RUN-SOCKS', 'Running socks, 3 pack', ['running'], 24, 'Merino blend, cushioned heel, no seam at the toe. Merino keeps feet cool in summer and warm in winter. Three pairs in one colour.', 'three pairs of grey and white running socks', axis='size', values=['36', '39', '42', '45'], attributes=dict(sport='Running|Hiking', material='Wool', color='Grey')),
    P('S-HEADLAMP', 'Running headlamp', ['running', 'hiking'], 60, 'A 400 lumen headlamp with a rechargeable battery and a red rear light. Enough light for a trail at speed, with a red light behind for the road. Charges by USB-C.', 'a small black rechargeable headlamp', attributes=dict(sport='Running|Hiking', material='Nylon', color='Black', size='One size')),
    P('S-WATCH-STRAP', 'Running belt', ['running'], 25, 'A stretch belt that holds a phone and a gel without bouncing. Two pockets that stretch and a buckle that stays flat. It fits most phones.', 'a black stretch running belt', attributes=dict(sport='Running', material='Nylon', color='Black', size='One size')),
    P('S-JERSEY', 'Cycling jersey', ['cycling'], 95, 'A race-fit jersey with three pockets and a full zip. Long in the back, short in the front, with a silicone gripper at the hem. The pockets hold a day of food.', 'a {value} short sleeve cycling jersey laid flat', axis='color', values=['Blue Dark', 'Red', 'White'], picture_per_value=True, attributes=dict(sport='Cycling', material='Recycled polyester', size='')),
    P('S-BIB-SHORT', 'Bib shorts', ['cycling'], 140, 'A chamois that lasts six hours and straps that do not dig. The chamois is dense where you sit and thin where you do not. The leg grippers do not squeeze.', 'a pair of black cycling bib shorts laid flat', axis='size', values=CLOTH, attributes=dict(sport='Cycling', material='Recycled polyester', color='Black')),
    P('S-HELMET', 'Road helmet', ['cycling'], 160, 'A ventilated road helmet with rotational protection, 280 g. Twenty vents, a dial fit and a rear light mount. It passes every current standard.', 'a {value} road cycling helmet seen from the side', axis='color', values=['White', 'Black', 'Red'], picture_per_value=True, attributes=dict(sport='Cycling', material='Recycled polyester', size='')),
    P('S-GILET', 'Wind gilet', ['cycling'], 70, 'A packable gilet for the descent. A windproof front, a mesh back, and a pocket it packs into. It weighs 60 g.', 'a {value} lightweight cycling gilet laid flat', axis='color', values=['Yellow', 'Black'], picture_per_value=True, attributes=dict(sport='Cycling|Running', material='Recycled polyester', size='')),
    P('S-GLOVES', 'Cycling mitts', ['cycling'], 30, 'Gel-padded mitts with a terry thumb. Gel where the bars press and terry on the thumb for a runny nose. Velcro at the wrist.', 'a pair of black fingerless cycling gloves', axis='size', values=['S', 'M', 'L'], attributes=dict(sport='Cycling', material='Nylon', color='Black')),
    P('S-BOTTLE', 'Insulated bottle', ['cycling', 'gym'], 18, 'A 650 ml insulated bottle that keeps water cold for three hours. Double-walled steel that fits a bike cage. The lid opens with one hand.', 'a {value} insulated cycling water bottle', axis='color', values=['Black', 'White', 'Blue'], picture_per_value=True, attributes=dict(sport='Cycling|Gym|Running', material='Recycled polyester', size='One size')),
    P('S-BIKE-LIGHT', 'Bike light set', ['cycling'], 55, 'A 600 lumen front and a 50 lumen rear, USB-C. The front light runs three hours on full, the rear light ten. Both mount without tools.', 'a pair of small black bike lights, front and rear', attributes=dict(sport='Cycling', material='Nylon', color='Black', size='One size')),
    P('S-PUMP', 'Mini pump', ['cycling'], 28, 'A 100 psi mini pump with a hose and a frame mount. The hose saves the valve and the frame mount saves the pocket. It reaches 100 psi in a minute.', 'a small aluminium bicycle mini pump', attributes=dict(sport='Cycling', material='Stainless steel', color='Silver', size='One size')),
    P('S-KETTLEBELL', 'Cast iron kettlebell', ['gym'], 45, 'A powder-coated kettlebell with a smooth handle. Cast in one piece, so nothing loosens. Available from 8 to 32 kg.', 'a black cast iron kettlebell', axis='size', values=['8', '12', '16', '20', '24'], attributes=dict(sport='Gym', material='Stainless steel', color='Black')),
    P('S-DUMBBELLS', 'Adjustable dumbbells', ['gym'], 290, 'A pair that goes from 2 to 24 kg with a dial. Turn the dial and the plates lock in. A whole rack in the space of one pair.', 'a pair of adjustable dumbbells on a stand', attributes=dict(sport='Gym', material='Stainless steel', color='Black', size='One size')),
    P('S-BANDS', 'Resistance bands, set of 5', ['gym', 'yoga'], 30, 'Five latex bands from light to heavy, with a door anchor. Five tensions from 5 to 50 kg, with handles and a door anchor. They roll into the pouch.', 'five colourful resistance bands laid in a fan', attributes=dict(sport='Gym|Yoga', material='Rubber', color='Green', size='One size')),
    P('S-BENCH', 'Folding bench', ['gym'], 180, 'A flat-to-incline bench that folds under a bed. Seven positions from flat to upright, rated for 300 kg. It folds in seconds.', 'a black folding weight bench', attributes=dict(sport='Gym', material='Stainless steel', color='Black', size='One size')),
    P('S-JUMP-ROPE', 'Speed rope', ['gym'], 22, 'A steel cable rope with ball bearings and a screw-lock length. The cable spins fast and the handles stay cool. Cut it to length once and lock it.', 'a black speed jump rope coiled with steel handles', attributes=dict(sport='Gym', material='Stainless steel', color='Black', size='One size')),
    P('S-GYM-BAG', 'Gym duffel', ['gym', 'swimming'], 65, 'A 35 litre duffel with a shoe pocket and a wet pocket. Shoes in one end, wet kit in the other, and a padded strap. It fits a locker.', 'a {value} gym duffel bag', axis='color', values=['Black', 'Green'], picture_per_value=True, attributes=dict(sport='Gym|Swimming', material='Nylon', size='One size')),
    P('S-TRAINING-TEE', 'Training tee', ['gym'], 35, 'A boxy cotton blend tee for the gym. Heavy enough to hold its shape, light enough to train in. Washes without shrinking.', 'a {value} boxy training t-shirt laid flat', axis='color', values=['Black', 'Grey', 'White'], picture_per_value=True, attributes=dict(sport='Gym', material='Cotton', size='')),
    P('S-YOGA-MAT', 'Cork yoga mat', ['yoga'], 85, 'A 4 mm natural rubber mat with a cork top that grips more when wet. The cork top is naturally antibacterial and grips better as you sweat. It rolls with a cotton strap.', 'a rolled cork yoga mat with a natural rubber base', attributes=dict(sport='Yoga', material='Rubber', color='Tan', size='One size')),
    P('S-RUBBER-MAT', 'Rubber yoga mat', ['yoga', 'gym'], 70, 'A 5 mm natural rubber mat, 183 cm long. Grippy on both sides, cushioned enough for knees. It weighs 2.5 kg.', 'a rolled {value} natural rubber yoga mat', axis='color', values=['Green', 'Charcoal', 'Purple'], picture_per_value=True, attributes=dict(sport='Yoga|Gym', material='Rubber', size='One size')),
    P('S-BLOCKS', 'Cork blocks, pair', ['yoga'], 28, 'Two cork blocks with rounded edges. Light, firm and warm to the touch. They wipe clean.', 'two cork yoga blocks', attributes=dict(sport='Yoga', material='Bamboo', color='Tan', size='One size')),
    P('S-STRAP', 'Yoga strap', ['yoga'], 12, 'A 2.5 m cotton strap with a metal buckle. A long strap for deep stretches and a buckle that holds. It washes with the towels.', 'a rolled cotton yoga strap with a metal buckle', attributes=dict(sport='Yoga', material='Cotton', color='Oatmeal', size='One size')),
    P('S-ROLLER', 'Foam roller', ['yoga', 'running'], 35, 'A 33 cm medium density roller. Firm enough for legs, forgiving enough for backs. It does not lose its shape.', 'a black textured foam roller', attributes=dict(sport='Yoga|Running|Cycling', material='Rubber', color='Black', size='One size')),
    P('S-MASSAGE-BALL', 'Massage ball set', ['yoga'], 18, 'A lacrosse ball and a peanut, for feet and backs. The ball reaches the small muscles and the peanut sits either side of the spine. Both fit a pocket.', 'a black massage ball and a peanut shaped massage ball', attributes=dict(sport='Yoga|Running', material='Rubber', color='Black', size='One size')),
    P('S-HIKING-BOOT', 'Hiking boot', ['hiking'], 190, 'A waterproof leather boot with a stiff sole and no break-in. Full-grain leather, a waterproof lining and a sole that grips wet rock. Comfortable from the first walk.', 'a {value} leather hiking boot seen from the side', axis='color', values=['Brown', 'Charcoal'], picture_per_value=True, attributes=dict(sport='Hiking', material='Leather', size='')),
    P('S-HIKING-SHOE', 'Hiking shoe', ['hiking'], 140, 'A low waterproof shoe for fast days. Light, waterproof and grippy, for long days at speed. It dries overnight.', 'a grey and green low hiking shoe', axis='size', values=SHOE, attributes=dict(sport='Hiking', material='Recycled polyester', color='Grey')),
    P('S-DAYPACK', 'Daypack 25', ['hiking'], 110, 'A 25 litre pack at 780 g, with a rain cover and a hydration sleeve. Enough room for a day in the hills, with a hip belt that carries the weight. The rain cover lives in its own pocket.', 'a {value} 25 litre hiking daypack', axis='color', values=['Green', 'Blue Dark', 'Orange'], picture_per_value=True, attributes=dict(sport='Hiking', material='Nylon', size='One size')),
    P('S-SHELL', 'Three-layer shell', ['hiking', 'cycling'], 260, 'A 20 000 mm waterproof shell with pit zips and a helmet hood. The kind of jacket you buy once. Pit zips for the climb, a hood that fits a helmet, and a lifetime repair promise.', 'a {value} hooded waterproof shell jacket laid flat', axis='color', values=['Blue', 'Red', 'Black'], picture_per_value=True, attributes=dict(sport='Hiking|Cycling', material='Recycled polyester', size='')),
    P('S-FLEECE', 'Grid fleece', ['hiking', 'running'], 90, 'A light grid fleece that breathes on the climb. The grid traps warmth and lets sweat through. It layers under the shell without bulk.', 'a {value} grid fleece pullover laid flat', axis='color', values=['Green', 'Grey', 'Blue Dark'], picture_per_value=True, attributes=dict(sport='Hiking|Running', material='Recycled polyester', size='')),
    P('S-POLES', 'Carbon poles', ['hiking'], 120, 'Folding carbon poles at 180 g each, with cork grips. They fold into three and fit a pack. The cork grips shape to the hand.', 'a pair of folding carbon trekking poles with cork grips', attributes=dict(sport='Hiking|Running', material='Nylon', color='Black', size='One size')),
    P('S-HIKE-SOCKS', 'Hiking socks, 2 pack', ['hiking'], 26, 'Merino socks with a cushioned sole. Merino with a cushioned sole and a snug arch. No blisters on a three-day walk.', 'two pairs of grey merino hiking socks', axis='size', values=['36', '39', '42', '45'], attributes=dict(sport='Hiking', material='Wool', color='Grey')),
    P('S-GOGGLES', 'Swim goggles', ['swimming'], 32, 'Low-profile goggles with a curved lens and five nose bridges. The curved lens gives a wide view and the five bridges give a real fit. Anti-fog inside.', 'a pair of {value} swimming goggles', axis='color', values=['Black', 'Blue', 'Silver'], picture_per_value=True, attributes=dict(sport='Swimming', material='Rubber', size='One size')),
    P('S-SWIMSUIT', 'Training swimsuit', ['swimming'], 55, 'A chlorine-proof one-piece with a medium back. Chlorine-proof fabric that keeps its shape for a year of mornings. The medium back gives free shoulders.', 'a {value} one piece training swimsuit laid flat', axis='color', values=['Black', 'Blue Dark'], picture_per_value=True, attributes=dict(sport='Swimming', material='Recycled polyester', size='')),
    P('S-JAMMERS', 'Training jammers', ['swimming'], 45, 'Knee-length jammers that last a season of chlorine. A drawstring waist and a fabric that lasts. Quick to dry.', 'a pair of black swimming jammers laid flat', axis='size', values=CLOTH, attributes=dict(sport='Swimming', material='Recycled polyester', color='Black')),
    P('S-SWIM-CAP', 'Silicone cap', ['swimming'], 10, 'A soft silicone cap that does not pull. Soft silicone that goes on without pulling hair. One size.', 'a {value} silicone swim cap', axis='color', values=['Black', 'Blue', 'Pink'], picture_per_value=True, attributes=dict(sport='Swimming', material='Rubber', size='One size')),
    P('S-TOWEL', 'Microfibre towel', ['swimming', 'hiking'], 22, 'A large towel that dries in an hour and packs to a fist. Large enough to wrap, small enough for a pocket. It dries in an hour on a rail.', 'a folded {value} microfibre towel', axis='color', values=['Blue', 'Grey'], picture_per_value=True, attributes=dict(sport='Swimming|Hiking', material='Recycled polyester', size='One size')),
    P('S-TOW-FLOAT', 'Open water tow float', ['swimming'], 30, 'A bright float with a dry pocket, for open water. Bright orange so boats see you, with a dry pocket for keys and a phone. It clips to a waist belt.', 'a bright orange inflatable swim tow float', attributes=dict(sport='Swimming', material='Nylon', color='Orange', size='One size')),
    P('S-HOME-GYM', 'Home gym kit', ['gym'], 330, 'A kettlebell, bands, a rope and a mat. Everything for a full session in a small room. Cheaper than the four bought apart.', 'a kettlebell, resistance bands, a jump rope and a rolled mat arranged together', grouped=['S-KETTLEBELL-16', 'S-BANDS', 'S-JUMP-ROPE', 'S-RUBBER-MAT-CHARCOAL'], attributes=dict(sport='Gym', material='', color='Black', size='One size')),
    P('S-RECOVERY-KIT', 'Recovery kit', ['yoga', 'running'], 60, 'A roller, a ball set and a strap. The three tools our physio uses, in one bag. Ten minutes after each run.', 'a foam roller, two massage balls and a strap arranged together', grouped=['S-ROLLER', 'S-MASSAGE-BALL', 'S-STRAP'], attributes=dict(sport='Yoga|Running', material='Rubber', color='Black', size='One size')),
    P('S-GIFT-CARD', 'Stride gift card', ['gym'], 50, 'A gift card by email. Delivered by email within the hour, with a message of your own. Valid for a year in the store.', 'a green gift card with a white stripe', type='virtual', attributes=dict(sport='', material='', color='', size='')),
]
POSTS = [
    ('How we fit shoes by video', '<p>Film thirty seconds from behind on a treadmill or a flat path, shoes off. Send it with your current shoe size and the distance you run each week. We reply with two options and why.</p><p>Run in them for thirty days. If they are wrong, send them back.</p>', 'A runner filmed from behind on a treadmill in a small shop with shoes on shelves.'),
    ('The first mountain race', '<p>Start with shoes that grip on wet rock, a pack that holds a litre and a shell, and poles if the climb is long. Eat every forty minutes from the start, not when you are hungry.</p><p>Walk the steep bits. Everyone does.</p>', 'Trail runners climbing a steep rocky path in the mountains with poles.'),
    ('A week of training, one room', '<p>A kettlebell, a set of bands and a mat cover most of a strength week: swings, presses, rows, carries, and a long stretch on Sunday.</p><p>Twenty minutes, three times a week, beats a gym membership you skip.</p>', 'A small home gym corner with a kettlebell, bands and a mat by a window.'),
]
GALLERY = [('A runner on a wet city street at dawn, mid stride, motion blur in the background', 'running'), ('Close-up of cycling shoes clipped into pedals on a mountain road', 'cycling'), ('A tall shot of a climber on a rocky ridge at sunrise with a small backpack', 'hiking'), ('A person holding a yoga pose on a wooden deck by a lake in soft morning light', 'yoga'), ('A swimmer pushing off the wall of an outdoor pool, water splashing in sunlight', 'swimming')]
BRANDS = [('Stride', 'ORIGINALS'), ('Ridgeline', 'OUTDOOR'), ('Velo', 'CYCLING'), ('Cadence', 'RUNNING'), ('Ferro', 'STRENGTH'), ('Tidal', 'SWIM'), ('Ashram', 'YOGA'), ('Summit', 'PACKS'), ('Kinetic', 'APPAREL'), ('Northface Peak', 'LAYERS')]
GALLERY_TITLE = 'Out before sunrise'
