CODE = 'sports'; ROOT = 'Sports'; STORE_NAME = 'Stride'; ATTRIBUTE_SET = 'Sports'; WEIGHT = 0.8
ATTRIBUTE_COLUMNS = ['sport', 'size', 'color', 'material']
ATTRIBUTES = [
    dict(code='sport', label='Sport', input='multiselect', scope='global', filterable=1, filterable_in_search=1, visible_on_front=1, used_in_product_listing=1, sets='Sports', group='General', sort_order=50),
]
OPTIONS = {'sport': ['Running', 'Cycling', 'Gym', 'Yoga', 'Hiking', 'Swimming']}
ROOT_DESCRIPTION = 'Gear for running, cycling, the gym and the trail, tested by people who train.'
META_DESCRIPTION = 'Stride: running shoes, cycling kit, gym gear, yoga mats and hiking equipment, tested on the road and the trail.'
PRODUCT_STYLE = 'Studio product photograph of a single sports product on a plain white seamless background, crisp even light, no people, no text, no lettering, no logos, no watermark, centered with margin around it.'
SCENE_STYLE = 'Energetic editorial sports photograph, dawn light, wet asphalt or mountain trail, motion, no readable text, no lettering, no logos, no watermark.'
SCENES = {
    'hero-main': 'A runner in a bright jacket on a wet coastal road at dawn, seen from behind, motion blur in the legs.',
    'hero-side': 'A close up of running shoes on a wet running track with water droplets, low angle.',
    'editorial': 'A group of cyclists climbing a mountain pass in the early morning, seen from the side.',
    'about': 'A small sports shop with a treadmill for gait analysis and shelves of running shoes.',
}
CATEGORIES = [
    dict(path='running', name='Running', description='Shoes, jackets and shorts for road and trail.', landing_title='Every road, every weather', landing_text='Road shoes, trail shoes and layers that breathe. We fit shoes on a treadmill in the shop and by video online.', scene='A pair of trail running shoes on a rocky mountain path with a view over a valley at sunrise.'),
    dict(path='cycling', name='Cycling', description='Jerseys, bibs, helmets and the small things.', landing_title='Comfort at kilometre eighty', landing_text='Bib shorts with a chamois that lasts, jerseys with pockets you can reach, and helmets that pass every test.', scene='A road bike leaning against a stone wall on a mountain road, helmet on the bars.'),
    dict(path='gym', name='Gym & Training', description='Weights, bands and the kit for a home corner.', landing_title='A gym in a corner', landing_text='Kettlebells, bands, a bench and a mat. Enough for most people, most of the time.', scene='A kettlebell, a pair of dumbbells and a rolled mat on a wooden floor by a window.'),
    dict(path='yoga', name='Yoga & Recovery', description='Mats, blocks, rollers and balls.', landing_title='Slow down', landing_text='Natural rubber mats, cork blocks and the recovery tools physios actually use.', scene='A rolled cork yoga mat and two cork blocks on a wooden floor in a bright studio.'),
    dict(path='hiking', name='Hiking', description='Boots, packs and layers for a long day out.', landing_title='Further, drier, lighter', landing_text='Boots that are broken in on day one, packs under a kilo and layers that pack small.', scene='A hiker with a small backpack on a ridge path above the clouds at sunrise.'),
    dict(path='swimming', name='Swimming', description='Goggles, suits and towels for pool and open water.', landing_title='Pool and open water', landing_text='Goggles that do not leak, suits that last a season of chlorine, and towels that dry in a bag.', scene='Swimming goggles and a folded towel on the edge of an outdoor pool at dawn.'),
]
HERO = dict(badge='New season', title='Gear that keeps up', text='Tested on our own runs, rides and climbs. If it fails us, it is not here.')
FEATURES = [('truck', 'Free delivery over 50', 'Next day on weekdays'), ('run', 'Shoe fitting', 'In store or by video'), ('arrow-back-up', '30-day trial', 'Run in them, return them'), ('shield-check', 'Two-year warranty', 'On every product')]
STORY = dict(title='We train in what we sell', text1='Stride is run by four people who race: two runners, a cyclist and a swimmer. Every product goes through at least a month of our own training before it is listed.', text2='If something fails, we say so on the product page. If it fails you, send it back.')
PROMO = dict(badge='Trail season', title='The trail kit', text='Shoes, a pack and a shell, chosen for a first mountain race.', path='running', button='See trail running', list_title='For the trail')
TESTIMONIALS = [('The video shoe fitting was better than the shop I used to go to. No injuries this year.', 'Elena R.', 'Oslo'), ('Bib shorts that survived a summer of riding. First pair that has.', 'Marcus T.', 'Leeds'), ('The cork mat has not slipped once in a hot class.', 'Priya S.', 'Toronto')]
NEWSLETTER = dict(title='Training notes', text='A short email every two weeks: what we tested, a session plan, and new arrivals.')
ABOUT = dict(title='Four people who race', paragraphs=['Stride started when two runners could not find a shop that fitted shoes properly. They bought a treadmill, a camera and a small lease.', 'A cyclist and a swimmer joined. Every product in the shop goes through a month of our own training first, and the notes are on the product page.', 'The treadmill is still there. Come and run on it, or send us a video and we fit you online.'])
REVIEWS = [('Fits as described', 'The fitting notes were accurate. No blisters on a 30 km run.', 5, 4, 4), ('Good, sizing runs small', 'Quality is great. Go half a size up.', 4, 4, 3), ('Survived a season', 'Rain, mud, a hundred washes. Still going.', 5, 5, 5), ('Returned, no questions', 'Did not suit my stride. Return was easy and fast.', 4, 5, 4)]
def P(sku, name, cats, price, desc, prompt, **kw):
    d = dict(sku=sku, name=name, categories=cats, price=price, description=desc, prompt=prompt); d.update(kw); return d
SHOE = ['38', '39', '40', '41', '42', '43', '44', '45']
CLOTH = ['XS', 'S', 'M', 'L', 'XL']
PRODUCTS = [
    P('S-ROAD-SHOE', 'Road running shoe', ['running'], 140, 'A daily trainer with a 32 mm stack, a nylon plate and a wide toe box.', 'a {value} road running shoe seen from the side', axis='color', values=['Blue', 'Black', 'Orange'], picture_per_value=True, attributes=dict(sport='Running', material='Recycled polyester', size='')),
    P('S-TRAIL-SHOE', 'Trail running shoe', ['running', 'hiking'], 155, 'Five millimetre lugs, a rock plate and a gaiter attachment.', 'a {value} trail running shoe with deep lugs seen from the side', axis='color', values=['Green', 'Black'], picture_per_value=True, attributes=dict(sport='Running|Hiking', material='Recycled polyester', size='')),
    P('S-RACE-SHOE', 'Race day shoe', ['running'], 220, 'A carbon plate, a light foam and no compromise. For race day only.', 'a bright yellow lightweight racing shoe with a carbon plate', axis='size', values=SHOE, attributes=dict(sport='Running', material='Recycled polyester', color='Yellow')),
    P('S-RUN-JACKET', 'Running shell', ['running'], 130, 'A 90 g waterproof shell that packs into its own pocket.', 'a lightweight {value} running rain jacket laid flat', axis='color', values=['Yellow', 'Black', 'Blue'], picture_per_value=True, attributes=dict(sport='Running|Cycling', material='Recycled polyester', size='')),
    P('S-RUN-SHORT', 'Split shorts', ['running'], 45, 'Five-inch split shorts with a brief liner and a zip pocket.', 'a pair of {value} split running shorts laid flat', axis='color', values=['Black', 'Blue Dark', 'Green'], picture_per_value=True, attributes=dict(sport='Running', material='Recycled polyester', size='')),
    P('S-RUN-TEE', 'Running tee', ['running', 'gym'], 40, 'A recycled polyester tee with flat seams and a reflective hit.', 'a {value} technical running t-shirt laid flat', axis='color', values=['White', 'Black', 'Orange'], picture_per_value=True, attributes=dict(sport='Running|Gym', material='Recycled polyester', size='')),
    P('S-RUN-SOCKS', 'Running socks, 3 pack', ['running'], 24, 'Merino blend, cushioned heel, no seam at the toe.', 'three pairs of grey and white running socks', axis='size', values=['36', '39', '42', '45'], attributes=dict(sport='Running|Hiking', material='Wool', color='Grey')),
    P('S-HEADLAMP', 'Running headlamp', ['running', 'hiking'], 60, 'A 400 lumen headlamp with a rechargeable battery and a red rear light.', 'a small black rechargeable headlamp', attributes=dict(sport='Running|Hiking', material='Nylon', color='Black', size='One size')),
    P('S-WATCH-STRAP', 'Running belt', ['running'], 25, 'A stretch belt that holds a phone and a gel without bouncing.', 'a black stretch running belt', attributes=dict(sport='Running', material='Nylon', color='Black', size='One size')),
    P('S-JERSEY', 'Cycling jersey', ['cycling'], 95, 'A race-fit jersey with three pockets and a full zip.', 'a {value} short sleeve cycling jersey laid flat', axis='color', values=['Blue Dark', 'Red', 'White'], picture_per_value=True, attributes=dict(sport='Cycling', material='Recycled polyester', size='')),
    P('S-BIB-SHORT', 'Bib shorts', ['cycling'], 140, 'A chamois that lasts six hours and straps that do not dig.', 'a pair of black cycling bib shorts laid flat', axis='size', values=CLOTH, attributes=dict(sport='Cycling', material='Recycled polyester', color='Black')),
    P('S-HELMET', 'Road helmet', ['cycling'], 160, 'A ventilated road helmet with rotational protection, 280 g.', 'a {value} road cycling helmet seen from the side', axis='color', values=['White', 'Black', 'Red'], picture_per_value=True, attributes=dict(sport='Cycling', material='Recycled polyester', size='')),
    P('S-GILET', 'Wind gilet', ['cycling'], 70, 'A packable gilet for the descent.', 'a {value} lightweight cycling gilet laid flat', axis='color', values=['Yellow', 'Black'], picture_per_value=True, attributes=dict(sport='Cycling|Running', material='Recycled polyester', size='')),
    P('S-GLOVES', 'Cycling mitts', ['cycling'], 30, 'Gel-padded mitts with a terry thumb.', 'a pair of black fingerless cycling gloves', axis='size', values=['S', 'M', 'L'], attributes=dict(sport='Cycling', material='Nylon', color='Black')),
    P('S-BOTTLE', 'Insulated bottle', ['cycling', 'gym'], 18, 'A 650 ml insulated bottle that keeps water cold for three hours.', 'a {value} insulated cycling water bottle', axis='color', values=['Black', 'White', 'Blue'], picture_per_value=True, attributes=dict(sport='Cycling|Gym|Running', material='Recycled polyester', size='One size')),
    P('S-BIKE-LIGHT', 'Bike light set', ['cycling'], 55, 'A 600 lumen front and a 50 lumen rear, USB-C.', 'a pair of small black bike lights, front and rear', attributes=dict(sport='Cycling', material='Nylon', color='Black', size='One size')),
    P('S-PUMP', 'Mini pump', ['cycling'], 28, 'A 100 psi mini pump with a hose and a frame mount.', 'a small aluminium bicycle mini pump', attributes=dict(sport='Cycling', material='Stainless steel', color='Silver', size='One size')),
    P('S-KETTLEBELL', 'Cast iron kettlebell', ['gym'], 45, 'A powder-coated kettlebell with a smooth handle.', 'a black cast iron kettlebell', axis='size', values=['8', '12', '16', '20', '24'], attributes=dict(sport='Gym', material='Stainless steel', color='Black')),
    P('S-DUMBBELLS', 'Adjustable dumbbells', ['gym'], 290, 'A pair that goes from 2 to 24 kg with a dial.', 'a pair of adjustable dumbbells on a stand', attributes=dict(sport='Gym', material='Stainless steel', color='Black', size='One size')),
    P('S-BANDS', 'Resistance bands, set of 5', ['gym', 'yoga'], 30, 'Five latex bands from light to heavy, with a door anchor.', 'five colourful resistance bands laid in a fan', attributes=dict(sport='Gym|Yoga', material='Rubber', color='Green', size='One size')),
    P('S-BENCH', 'Folding bench', ['gym'], 180, 'A flat-to-incline bench that folds under a bed.', 'a black folding weight bench', attributes=dict(sport='Gym', material='Stainless steel', color='Black', size='One size')),
    P('S-JUMP-ROPE', 'Speed rope', ['gym'], 22, 'A steel cable rope with ball bearings and a screw-lock length.', 'a black speed jump rope coiled with steel handles', attributes=dict(sport='Gym', material='Stainless steel', color='Black', size='One size')),
    P('S-GYM-BAG', 'Gym duffel', ['gym', 'swimming'], 65, 'A 35 litre duffel with a shoe pocket and a wet pocket.', 'a {value} gym duffel bag', axis='color', values=['Black', 'Green'], picture_per_value=True, attributes=dict(sport='Gym|Swimming', material='Nylon', size='One size')),
    P('S-TRAINING-TEE', 'Training tee', ['gym'], 35, 'A boxy cotton blend tee for the gym.', 'a {value} boxy training t-shirt laid flat', axis='color', values=['Black', 'Grey', 'White'], picture_per_value=True, attributes=dict(sport='Gym', material='Cotton', size='')),
    P('S-YOGA-MAT', 'Cork yoga mat', ['yoga'], 85, 'A 4 mm natural rubber mat with a cork top that grips more when wet.', 'a rolled cork yoga mat with a natural rubber base', attributes=dict(sport='Yoga', material='Rubber', color='Tan', size='One size')),
    P('S-RUBBER-MAT', 'Rubber yoga mat', ['yoga', 'gym'], 70, 'A 5 mm natural rubber mat, 183 cm long.', 'a rolled {value} natural rubber yoga mat', axis='color', values=['Green', 'Charcoal', 'Purple'], picture_per_value=True, attributes=dict(sport='Yoga|Gym', material='Rubber', size='One size')),
    P('S-BLOCKS', 'Cork blocks, pair', ['yoga'], 28, 'Two cork blocks with rounded edges.', 'two cork yoga blocks', attributes=dict(sport='Yoga', material='Bamboo', color='Tan', size='One size')),
    P('S-STRAP', 'Yoga strap', ['yoga'], 12, 'A 2.5 m cotton strap with a metal buckle.', 'a rolled cotton yoga strap with a metal buckle', attributes=dict(sport='Yoga', material='Cotton', color='Oatmeal', size='One size')),
    P('S-ROLLER', 'Foam roller', ['yoga', 'running'], 35, 'A 33 cm medium density roller.', 'a black textured foam roller', attributes=dict(sport='Yoga|Running|Cycling', material='Rubber', color='Black', size='One size')),
    P('S-MASSAGE-BALL', 'Massage ball set', ['yoga'], 18, 'A lacrosse ball and a peanut, for feet and backs.', 'a black massage ball and a peanut shaped massage ball', attributes=dict(sport='Yoga|Running', material='Rubber', color='Black', size='One size')),
    P('S-HIKING-BOOT', 'Hiking boot', ['hiking'], 190, 'A waterproof leather boot with a stiff sole and no break-in.', 'a {value} leather hiking boot seen from the side', axis='color', values=['Brown', 'Charcoal'], picture_per_value=True, attributes=dict(sport='Hiking', material='Leather', size='')),
    P('S-HIKING-SHOE', 'Hiking shoe', ['hiking'], 140, 'A low waterproof shoe for fast days.', 'a grey and green low hiking shoe', axis='size', values=SHOE, attributes=dict(sport='Hiking', material='Recycled polyester', color='Grey')),
    P('S-DAYPACK', 'Daypack 25', ['hiking'], 110, 'A 25 litre pack at 780 g, with a rain cover and a hydration sleeve.', 'a {value} 25 litre hiking daypack', axis='color', values=['Green', 'Blue Dark', 'Orange'], picture_per_value=True, attributes=dict(sport='Hiking', material='Nylon', size='One size')),
    P('S-SHELL', 'Three-layer shell', ['hiking', 'cycling'], 260, 'A 20 000 mm waterproof shell with pit zips and a helmet hood.', 'a {value} hooded waterproof shell jacket laid flat', axis='color', values=['Blue', 'Red', 'Black'], picture_per_value=True, attributes=dict(sport='Hiking|Cycling', material='Recycled polyester', size='')),
    P('S-FLEECE', 'Grid fleece', ['hiking', 'running'], 90, 'A light grid fleece that breathes on the climb.', 'a {value} grid fleece pullover laid flat', axis='color', values=['Green', 'Grey', 'Blue Dark'], picture_per_value=True, attributes=dict(sport='Hiking|Running', material='Recycled polyester', size='')),
    P('S-POLES', 'Carbon poles', ['hiking'], 120, 'Folding carbon poles at 180 g each, with cork grips.', 'a pair of folding carbon trekking poles with cork grips', attributes=dict(sport='Hiking|Running', material='Nylon', color='Black', size='One size')),
    P('S-HIKE-SOCKS', 'Hiking socks, 2 pack', ['hiking'], 26, 'Merino socks with a cushioned sole.', 'two pairs of grey merino hiking socks', axis='size', values=['36', '39', '42', '45'], attributes=dict(sport='Hiking', material='Wool', color='Grey')),
    P('S-GOGGLES', 'Swim goggles', ['swimming'], 32, 'Low-profile goggles with a curved lens and five nose bridges.', 'a pair of {value} swimming goggles', axis='color', values=['Black', 'Blue', 'Silver'], picture_per_value=True, attributes=dict(sport='Swimming', material='Rubber', size='One size')),
    P('S-SWIMSUIT', 'Training swimsuit', ['swimming'], 55, 'A chlorine-proof one-piece with a medium back.', 'a {value} one piece training swimsuit laid flat', axis='color', values=['Black', 'Blue Dark'], picture_per_value=True, attributes=dict(sport='Swimming', material='Recycled polyester', size='')),
    P('S-JAMMERS', 'Training jammers', ['swimming'], 45, 'Knee-length jammers that last a season of chlorine.', 'a pair of black swimming jammers laid flat', axis='size', values=CLOTH, attributes=dict(sport='Swimming', material='Recycled polyester', color='Black')),
    P('S-SWIM-CAP', 'Silicone cap', ['swimming'], 10, 'A soft silicone cap that does not pull.', 'a {value} silicone swim cap', axis='color', values=['Black', 'Blue', 'Pink'], picture_per_value=True, attributes=dict(sport='Swimming', material='Rubber', size='One size')),
    P('S-TOWEL', 'Microfibre towel', ['swimming', 'hiking'], 22, 'A large towel that dries in an hour and packs to a fist.', 'a folded {value} microfibre towel', axis='color', values=['Blue', 'Grey'], picture_per_value=True, attributes=dict(sport='Swimming|Hiking', material='Recycled polyester', size='One size')),
    P('S-TOW-FLOAT', 'Open water tow float', ['swimming'], 30, 'A bright float with a dry pocket, for open water.', 'a bright orange inflatable swim tow float', attributes=dict(sport='Swimming', material='Nylon', color='Orange', size='One size')),
    P('S-HOME-GYM', 'Home gym kit', ['gym'], 330, 'A kettlebell, bands, a rope and a mat.', 'a kettlebell, resistance bands, a jump rope and a rolled mat arranged together', grouped=['S-KETTLEBELL-16', 'S-BANDS', 'S-JUMP-ROPE', 'S-RUBBER-MAT-CHARCOAL'], attributes=dict(sport='Gym', material='', color='Black', size='One size')),
    P('S-RECOVERY-KIT', 'Recovery kit', ['yoga', 'running'], 60, 'A roller, a ball set and a strap.', 'a foam roller, two massage balls and a strap arranged together', grouped=['S-ROLLER', 'S-MASSAGE-BALL', 'S-STRAP'], attributes=dict(sport='Yoga|Running', material='Rubber', color='Black', size='One size')),
    P('S-GIFT-CARD', 'Stride gift card', ['gym'], 50, 'A gift card by email.', 'a green gift card with a white stripe', type='virtual', attributes=dict(sport='', material='', color='', size='')),
]
POSTS = [
    ('How we fit shoes by video', '<p>Film thirty seconds from behind on a treadmill or a flat path, shoes off. Send it with your current shoe size and the distance you run each week. We reply with two options and why.</p><p>Run in them for thirty days. If they are wrong, send them back.</p>', 'A runner filmed from behind on a treadmill in a small shop with shoes on shelves.'),
    ('The first mountain race', '<p>Start with shoes that grip on wet rock, a pack that holds a litre and a shell, and poles if the climb is long. Eat every forty minutes from the start, not when you are hungry.</p><p>Walk the steep bits. Everyone does.</p>', 'Trail runners climbing a steep rocky path in the mountains with poles.'),
    ('A week of training, one room', '<p>A kettlebell, a set of bands and a mat cover most of a strength week: swings, presses, rows, carries, and a long stretch on Sunday.</p><p>Twenty minutes, three times a week, beats a gym membership you skip.</p>', 'A small home gym corner with a kettlebell, bands and a mat by a window.'),
]
